/* GENERATED by tools/penpot-to-code/to-react-native.mjs from the Penpot
 * board "01B Screen 01B-C". Do not edit: regenerate with
 * `pnpm design:rn`. Its text is the board's sample copy — a design
 * reference, not a screen.
 */
import React from "react";
import { StyleSheet, View, Text } from "react-native";
import Svg, { SvgXml, Defs, Rect, Stop, LinearGradient, RadialGradient } from "react-native-svg";

export const size = { width: 376, height: 859 } as const;

const SVG_0 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"376\" height=\"85.3\" viewBox=\"3626 2535.7 376 85.3\" fill=\"none\"><path d=\"M3626.0,2581.625L3675.439453125,2551.0L3711.868408203125,2570.6875L3761.30810546875,2535.6875L3815.95166015625,2568.5L3867.9931640625,2544.4375L3917.4326171875,2572.875L3966.8720703125,2548.8125L4002.0,2568.5L4002.0,2621.0L3626.0,2621.0Z\" fill=\"#dbefe9\"/></svg>";
const SVG_1 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"376\" height=\"59.1\" viewBox=\"3626 2561.9 376 59.1\" fill=\"none\"><path d=\"M3626.0,2596.9375L3683.24560546875,2570.6875L3732.68505859375,2590.375L3789.9306640625,2561.9375L3847.17626953125,2586.0L3901.81982421875,2566.3125L3953.861328125,2590.375L4002.0,2575.0625L4002.0,2621.0L3626.0,2621.0Z\" fill=\"#c6e5dd\"/></svg>";
const SVG_2 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"18.6\" height=\"5.4\" viewBox=\"3931.9 1783.8 18.6 5.4\" fill=\"none\"><path d=\"M3933.28857421875,1787.857177734375C3937.615234375,1784.2857666015625,3944.82666015625,1784.2857666015625,3949.15380859375,1787.857177734375\" fill=\"none\" stroke=\"#0f3244\" stroke-width=\"1.7\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_3 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"11.9\" height=\"4.4\" viewBox=\"3935.3 1788.9 11.9 4.4\" fill=\"none\"><path d=\"M3936.60546875,1792.0C3939.34619140625,1789.7142333984375,3943.09619140625,1789.7142333984375,3945.83642578125,1792.0\" fill=\"none\" stroke=\"#0f3244\" stroke-width=\"1.7\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_4 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"10.5\" height=\"17.9\" viewBox=\"3654.8 1821.1 10.5 17.9\" fill=\"none\"><path d=\"M3663.75,1822.6666259765625L3656.41650390625,1830.0L3663.75,1837.3333740234375\" fill=\"none\" stroke=\"#0f3244\" stroke-width=\"2.2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_5 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"27.2\" height=\"34.5\" viewBox=\"3799.9 1889.2 27.2 34.5\" fill=\"none\"><path d=\"M3813.5,1889.245849609375C3805.9794921875,1889.245849609375,3799.88330078125,1895.0587158203125,3799.88330078125,1902.2291259765625C3799.88330078125,1911.9666748046875,3813.5,1923.754150390625,3813.5,1923.754150390625C3813.5,1923.754150390625,3827.11669921875,1911.9666748046875,3827.11669921875,1902.2291259765625C3827.11669921875,1898.7857666015625,3825.68212890625,1895.4835205078125,3823.12841796875,1893.048583984375C3820.57470703125,1890.61376953125,3817.111328125,1889.245849609375,3813.5,1889.245849609375ZM3813.5,1906.8416748046875C3810.828125,1906.8416748046875,3808.66259765625,1904.776611328125,3808.66259765625,1902.2291259765625C3808.66259765625,1899.681640625,3810.828125,1897.61669921875,3813.5,1897.61669921875C3816.17138671875,1897.61669921875,3818.33740234375,1899.681640625,3818.33740234375,1902.2291259765625C3818.33740234375,1904.776611328125,3816.17138671875,1906.8416748046875,3813.5,1906.8416748046875Z\" fill=\"#e5484d\"/></svg>";
const SVG_6 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"16.7\" height=\"16.7\" viewBox=\"3669.7 2177.7 16.7 16.7\" fill=\"none\"><path d=\"M3678.0,2177.666748046875C3673.3974609375,2177.666748046875,3669.66650390625,2181.397705078125,3669.66650390625,2186.0C3669.66650390625,2190.602294921875,3673.3974609375,2194.333251953125,3678.0,2194.333251953125C3682.602294921875,2194.333251953125,3686.333251953125,2190.602294921875,3686.333251953125,2186.0C3686.333251953125,2181.397705078125,3682.602294921875,2177.666748046875,3678.0,2177.666748046875ZM3678.91650390625,2190.333251953125L3677.083251953125,2190.333251953125L3677.083251953125,2184.833251953125L3678.91650390625,2184.833251953125L3678.91650390625,2190.333251953125ZM3678.91650390625,2183.333251953125L3677.083251953125,2183.333251953125L3677.083251953125,2181.5L3678.91650390625,2181.5L3678.91650390625,2183.333251953125Z\" fill=\"#5e7a88\"/></svg>";
const SVG_7 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"14.9\" height=\"15.4\" viewBox=\"3723.9 2289.8 14.9 15.4\" fill=\"none\"><path d=\"M3736.97509765625,2298.375C3737.05224609375,2297.794189453125,3737.05224609375,2297.205810546875,3736.97509765625,2296.625L3738.8125,2295.22509765625L3737.0625,2292.16259765625L3734.875,2293.03759765625C3734.4189453125,2292.683349609375,3733.9189453125,2292.38916015625,3733.3876953125,2292.16259765625L3733.125,2289.800048828125L3729.625,2289.800048828125L3729.362548828125,2292.16259765625C3728.83740234375,2292.38134765625,3728.3125,2292.6875,3727.875,2293.03759765625L3725.6875,2292.16259765625L3723.9375,2295.22509765625L3725.77490234375,2296.625C3725.69775390625,2297.205810546875,3725.69775390625,2297.794189453125,3725.77490234375,2298.375L3723.9375,2299.77490234375L3725.6875,2302.83740234375L3727.875,2301.96240234375C3728.3125,2302.3125,3728.83740234375,2302.61865234375,3729.362548828125,2302.83740234375L3729.625,2305.199951171875L3733.125,2305.199951171875L3733.3876953125,2302.83740234375C3733.91259765625,2302.61865234375,3734.4375,2302.3125,3734.875,2301.96240234375L3737.0625,2302.83740234375L3738.8125,2299.77490234375L3736.97509765625,2298.375ZM3731.375,2300.300048828125C3729.82861328125,2300.300048828125,3728.574951171875,2299.04638671875,3728.574951171875,2297.5C3728.574951171875,2295.95361328125,3729.82861328125,2294.699951171875,3731.375,2294.699951171875C3732.92138671875,2294.699951171875,3734.17529296875,2295.95361328125,3734.17529296875,2297.5C3734.17529296875,2299.04638671875,3732.92138671875,2300.300048828125,3731.375,2300.300048828125Z\" fill=\"#ffffff\"/></svg>";
const SVG_8 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"12.9\" height=\"15.7\" viewBox=\"3733 2353.2 12.9 15.7\" fill=\"none\"><path d=\"M3739.5,2356.02490234375L3739.5,2353.22509765625L3735.64990234375,2357.074951171875L3739.5,2360.925048828125L3739.5,2358.125C3741.916015625,2358.125,3743.875,2360.083740234375,3743.875,2362.5C3743.875,2364.916259765625,3741.916015625,2366.875,3739.5,2366.875C3737.083984375,2366.875,3735.125,2364.916259765625,3735.125,2362.5L3733.02490234375,2362.5C3733.02490234375,2366.075927734375,3735.923828125,2368.97509765625,3739.5,2368.97509765625C3743.076171875,2368.97509765625,3745.97509765625,2366.075927734375,3745.97509765625,2362.5C3745.97509765625,2358.924072265625,3743.076171875,2356.02490234375,3739.5,2356.02490234375Z\" fill=\"#0e7a4a\"/></svg>";

export default function Penpot01bScreen01bC() {
  return (
    <View style={{ width: 376, height: 859, backgroundColor: "#FFFFFF", borderRadius: 34, overflow: "hidden", boxShadow: "0px 10px 28px 0px rgba(15,50,68,0.14)" }}>{/* "01B Screen 01B-C" */}
      <View style={{ position: "absolute", left: 0, top: 754, width: 376, height: 105 }} pointerEvents="box-none">{/* "mountains" */}
        <SvgXml xml={SVG_0} width={376} height={85.3} style={{ position: "absolute", left: 0, top: 19.7 }} />
        <SvgXml xml={SVG_1} width={376} height={59.1} style={{ position: "absolute", left: 0, top: 45.9 }} />
      </View>
      <View style={{ position: "absolute", left: 0, top: 0, width: 376, height: 859, backgroundColor: "#FFFFFF", borderRadius: 34 }} />
      <View style={{ position: "absolute", left: 0, top: 611, width: 376, height: 248, borderBottomRightRadius: 34, borderBottomLeftRadius: 34, overflow: "hidden" }}>{/* "mint" */}
        <Svg style={StyleSheet.absoluteFill} width="100%" height="100%"><Defs><LinearGradient id="g01bscreen01bc0" x1="0.5" y1="0" x2="0.5" y2="1"><Stop offset={0} stopColor="#E9F7F0" stopOpacity={0} /><Stop offset={1} stopColor="#DCF1E7" stopOpacity={1} /></LinearGradient></Defs><Rect width="100%" height="100%" fill="url(#g01bscreen01bc0)" /></Svg>
      </View>
      <Text style={{ position: "absolute", left: 24, top: 18, width: 78, textAlign: "left", fontFamily: "PlusJakartaSans_700Bold", fontSize: 14, lineHeight: 16.8, color: "#0F3244" }}>{"9:41"}</Text>
      <View style={{ position: "absolute", left: 277, top: 18, width: 75, height: 20 }} pointerEvents="box-none">{/* "status-icons" */}
        <View style={{ position: "absolute", left: 0, top: 12.9, width: 4.3, height: 7.1, backgroundColor: "#0F3244", borderRadius: 1 }} />
        <View style={{ position: "absolute", left: 6.5, top: 9.3, width: 4.3, height: 10.7, backgroundColor: "#0F3244", borderRadius: 1 }} />
        <View style={{ position: "absolute", left: 13, top: 5.7, width: 4.3, height: 14.3, backgroundColor: "#0F3244", borderRadius: 1 }} />
        <View style={{ position: "absolute", left: 19.5, top: 2.1, width: 4.3, height: 17.9, backgroundColor: "#0F3244", borderRadius: 1 }} />
        <SvgXml xml={SVG_2} width={18.6} height={5.4} style={{ position: "absolute", left: 28.9, top: 3.8 }} />
        <SvgXml xml={SVG_3} width={11.9} height={4.4} style={{ position: "absolute", left: 32.3, top: 8.9 }} />
        <View style={{ position: "absolute", left: 36.2, top: 14.6, width: 4, height: 4, backgroundColor: "#0F3244", borderRadius: 2 }} />
        <View style={{ position: "absolute", left: 53.4, top: 4.3, width: 18.8, height: 11.4, borderRadius: 2.2, borderWidth: 1.1, borderColor: "#0F3244", opacity: 0.9 }} />
        <View style={{ position: "absolute", left: 55.7, top: 6.6, width: 12.7, height: 6.9, backgroundColor: "#0F3244", borderRadius: 1.1 }} />
        <View style={{ position: "absolute", left: 72.8, top: 8, width: 2, height: 4, backgroundColor: "#0F3244", borderRadius: 0.7 }} />
      </View>
      <View style={{ position: "absolute", left: 24, top: 57, width: 22, height: 22 }} pointerEvents="box-none">{/* "back" */}
        <SvgXml xml={SVG_4} width={10.5} height={17.9} style={{ position: "absolute", left: 4.8, top: 2.1 }} />
      </View>
      <View style={{ position: "absolute", left: 122, top: 85, width: 130, height: 130, borderRadius: 65, overflow: "hidden" }}>{/* "disc" */}
        <Svg style={StyleSheet.absoluteFill} width="100%" height="100%"><Defs><RadialGradient id="g01bscreen01bc1" cx="0.5" cy="0.5" rx="0.5" ry="0.5" gradientUnits="objectBoundingBox"><Stop offset={0} stopColor="#F9D5DA" stopOpacity={1} /><Stop offset={0.58} stopColor="#FBE3E7" stopOpacity={1} /><Stop offset={0.93} stopColor="#FFFFFF" stopOpacity={1} /></RadialGradient></Defs><Rect width="100%" height="100%" fill="url(#g01bscreen01bc1)" /></Svg>
      </View>
      <View style={{ position: "absolute", left: 26, top: 96, width: 78, height: 33 }} pointerEvents="box-none">{/* "cloud-l" */}
        <View style={{ position: "absolute", left: 1.1, top: 12.1, width: 37.9, height: 19.8, backgroundColor: "#E9F2F6", borderRadius: 9.9 }} />
        <View style={{ position: "absolute", left: 24, top: 3.3, width: 32.3, height: 25.3, backgroundColor: "#F5FAFC", borderRadius: 12.7 }} />
        <View style={{ position: "absolute", left: 41.2, top: 14.3, width: 33.4, height: 17.6, backgroundColor: "#E9F2F6", borderRadius: 8.8 }} />
      </View>
      <View style={{ position: "absolute", left: 278, top: 111, width: 73, height: 30 }} pointerEvents="box-none">{/* "cloud-r" */}
        <View style={{ position: "absolute", left: 1, top: 11, width: 35.5, height: 18, backgroundColor: "#E9F2F6", borderRadius: 9 }} />
        <View style={{ position: "absolute", left: 22.4, top: 3, width: 30.2, height: 23, backgroundColor: "#F5FAFC", borderRadius: 11.5 }} />
        <View style={{ position: "absolute", left: 38.6, top: 13, width: 31.3, height: 16, backgroundColor: "#E9F2F6", borderRadius: 8 }} />
      </View>
      <View style={{ position: "absolute", left: 166, top: 124, width: 43, height: 41 }} pointerEvents="box-none">{/* "pin" */}
        <SvgXml xml={SVG_5} width={27.2} height={34.5} style={{ position: "absolute", left: 7.9, top: 3.2 }} />
      </View>
      <Text style={{ position: "absolute", left: 0, top: 252, width: 376, textAlign: "center", fontFamily: "PlusJakartaSans_800ExtraBold", fontSize: 22, lineHeight: 28.6, color: "#0F3244" }}>{"Location Access is Off"}</Text>
      <Text style={{ position: "absolute", left: 34, top: 291, width: 308, textAlign: "center", fontFamily: "PlusJakartaSans_400Regular", fontSize: 14, lineHeight: 22.4, color: "#6B8796" }}>{"We couldn't access your location. Some features like nearby customers, route planning and location-based insights may be limited."}</Text>
      <View style={{ position: "absolute", left: 24, top: 397, width: 329, height: 83, backgroundColor: "#F1F7FA", borderRadius: 13, borderWidth: 1, borderColor: "#E3EDF2" }} />
      <View style={{ position: "absolute", left: 42, top: 414, width: 20, height: 20 }} pointerEvents="box-none">{/* "note-ic" */}
        <SvgXml xml={SVG_6} width={16.7} height={16.7} style={{ position: "absolute", left: 1.7, top: 1.7 }} />
      </View>
      <Text style={{ position: "absolute", left: 70, top: 412, width: 247, textAlign: "left", fontFamily: "PlusJakartaSans_700Bold", fontSize: 14, lineHeight: 18.2, color: "#0F3244" }}>{"You can still continue"}</Text>
      <Text style={{ position: "absolute", left: 70, top: 433, width: 263, textAlign: "left", fontFamily: "PlusJakartaSans_400Regular", fontSize: 11, lineHeight: 16, color: "#6B8796" }}>{"You can use the app without location and enable it anytime from settings."}</Text>
      <View style={{ position: "absolute", left: 24, top: 509, width: 329, height: 52, borderRadius: 13, overflow: "hidden", boxShadow: "0px 4px 12px 0px rgba(15,50,68,0.2)" }}>{/* "btn1" */}
        <Svg style={StyleSheet.absoluteFill} width="100%" height="100%"><Defs><LinearGradient id="g01bscreen01bc2" x1="0" y1="0.5" x2="1" y2="0.5"><Stop offset={0} stopColor="#0E7A4A" stopOpacity={1} /><Stop offset={1} stopColor="#1BA560" stopOpacity={1} /></LinearGradient></Defs><Rect width="100%" height="100%" fill="url(#g01bscreen01bc2)" /></Svg>
      </View>
      <View style={{ position: "absolute", left: 94, top: 525, width: 21, height: 21 }} pointerEvents="box-none">{/* "btn1-ic" */}
        <SvgXml xml={SVG_7} width={14.9} height={15.4} style={{ position: "absolute", left: 3.9, top: 2.8 }} />
      </View>
      <Text style={{ position: "absolute", left: 124, top: 525, width: 221, textAlign: "left", fontFamily: "PlusJakartaSans_700Bold", fontSize: 16, lineHeight: 21.6, color: "#FFFFFF" }}>{"Open App Settings"}</Text>
      <View style={{ position: "absolute", left: 24, top: 574, width: 329, height: 52, backgroundColor: "#FFFFFF", borderRadius: 13, borderWidth: 1.4, borderColor: "#17A45E" }} />
      <View style={{ position: "absolute", left: 103, top: 590, width: 21, height: 21 }} pointerEvents="box-none">{/* "btn2-ic" */}
        <SvgXml xml={SVG_8} width={12.9} height={15.7} style={{ position: "absolute", left: 4, top: 1.2 }} />
      </View>
      <Text style={{ position: "absolute", left: 133, top: 590, width: 221, textAlign: "left", fontFamily: "PlusJakartaSans_700Bold", fontSize: 16, lineHeight: 21.6, color: "#0E7A4A" }}>{"Retry Permission"}</Text>
      <View style={{ position: "absolute", left: 24, top: 639, width: 329, height: 49, backgroundColor: "#EFF3F5", borderRadius: 13 }} />
      <Text style={{ position: "absolute", left: 24, top: 654, width: 329, textAlign: "center", fontFamily: "PlusJakartaSans_600SemiBold", fontSize: 16, lineHeight: 21.6, color: "#53707E" }}>{"Continue Without Location"}</Text>
    </View>
  );
}
