/* GENERATED by tools/penpot-to-code/to-react-native.mjs from the Penpot
 * board "01B Screen 01B-INFO". Do not edit: regenerate with
 * `pnpm design:rn`. Its text is the board's sample copy — a design
 * reference, not a screen.
 */
import React from "react";
import { StyleSheet, View, Text } from "react-native";
import Svg, { SvgXml, Defs, Rect, Stop, LinearGradient } from "react-native-svg";

export const size = { width: 376, height: 859 } as const;

const SVG_0 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"376\" height=\"85.3\" viewBox=\"3173 2527.7 376 85.3\" fill=\"none\"><path d=\"M3173.0,2573.625L3222.439453125,2543.0L3258.868408203125,2562.6875L3308.307861328125,2527.6875L3362.951416015625,2560.5L3414.992919921875,2536.4375L3464.432373046875,2564.875L3513.871826171875,2540.8125L3549.0,2560.5L3549.0,2613.0L3173.0,2613.0Z\" fill=\"#dbefe9\"/></svg>";
const SVG_1 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"376\" height=\"59.1\" viewBox=\"3173 2553.9 376 59.1\" fill=\"none\"><path d=\"M3173.0,2588.9375L3230.24560546875,2562.6875L3279.68505859375,2582.375L3336.9306640625,2553.9375L3394.17626953125,2578.0L3448.820068359375,2558.3125L3500.861572265625,2582.375L3549.0,2567.0625L3549.0,2613.0L3173.0,2613.0Z\" fill=\"#c6e5dd\"/></svg>";
const SVG_2 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"18.6\" height=\"5.4\" viewBox=\"3478.9 1775.8 18.6 5.4\" fill=\"none\"><path d=\"M3480.288330078125,1779.857177734375C3484.615234375,1776.2857666015625,3491.826904296875,1776.2857666015625,3496.15380859375,1779.857177734375\" fill=\"none\" stroke=\"#0f3244\" stroke-width=\"1.7\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_3 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"11.9\" height=\"4.4\" viewBox=\"3482.3 1780.9 11.9 4.4\" fill=\"none\"><path d=\"M3483.605712890625,1784.0C3486.345947265625,1781.7142333984375,3490.095947265625,1781.7142333984375,3492.83642578125,1784.0\" fill=\"none\" stroke=\"#0f3244\" stroke-width=\"1.7\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_4 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"10.5\" height=\"17.9\" viewBox=\"3201.8 1813.1 10.5 17.9\" fill=\"none\"><path d=\"M3210.75,1814.6666259765625L3203.41650390625,1822.0L3210.75,1829.3333740234375\" fill=\"none\" stroke=\"#0f3244\" stroke-width=\"2.2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_5 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"23.6\" height=\"18\" viewBox=\"3216.1 1970.5 23.6 18\" fill=\"none\"><path d=\"M3224.5625,1978.375C3226.737060546875,1978.375,3228.5,1976.612060546875,3228.5,1974.4375C3228.5,1972.262939453125,3226.737060546875,1970.5,3224.5625,1970.5C3222.3876953125,1970.5,3220.625,1972.262939453125,3220.625,1974.4375C3220.625,1976.612060546875,3222.3876953125,1978.375,3224.5625,1978.375ZM3232.4375,1978.375C3234.30126953125,1978.375,3235.8125,1976.864013671875,3235.8125,1975.0C3235.8125,1973.135986328125,3234.30126953125,1971.625,3232.4375,1971.625C3230.573486328125,1971.625,3229.0625,1973.135986328125,3229.0625,1975.0C3229.0625,1976.864013671875,3230.573486328125,1978.375,3232.4375,1978.375ZM3224.5625,1980.625C3221.1875,1980.625,3216.125,1982.425048828125,3216.125,1985.6875L3216.125,1988.5L3233.0,1988.5L3233.0,1985.6875C3233.0,1982.425048828125,3227.9375,1980.625,3224.5625,1980.625ZM3232.662353515625,1980.625C3231.64990234375,1980.625,3230.637451171875,1980.737548828125,3229.7373046875,1980.9625244140625C3231.3125,1982.199951171875,3231.875,1983.6624755859375,3231.875,1985.6875L3231.875,1988.5L3239.75,1988.5L3239.75,1985.6875C3239.75,1982.6500244140625,3235.699951171875,1980.625,3232.662353515625,1980.625Z\" fill=\"#17a45e\"/></svg>";
const SVG_6 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"21.6\" height=\"21.6\" viewBox=\"3217.7 2061.7 21.6 21.6\" fill=\"none\"><path d=\"M3239.2998046875,2061.699951171875L3217.699951171875,2070.47509765625L3226.8125,2074.1875L3230.52490234375,2083.300048828125L3239.2998046875,2061.699951171875Z\" fill=\"#17a45e\"/></svg>";
const SVG_7 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"18.9\" height=\"23.1\" viewBox=\"3219 2248 18.9 23.1\" fill=\"none\"><path d=\"M3228.5,2248.02490234375L3219.0498046875,2251.625L3219.0498046875,2258.824951171875C3219.0498046875,2264.449951171875,3223.099853515625,2269.737548828125,3228.5,2271.08740234375C3233.89990234375,2269.737548828125,3237.949951171875,2264.449951171875,3237.949951171875,2258.824951171875L3237.949951171875,2251.625L3228.5,2248.02490234375ZM3227.375,2264.22509765625L3222.9873046875,2259.83740234375L3224.787353515625,2258.03759765625L3227.375,2260.625L3233.33740234375,2254.66259765625L3235.137451171875,2256.46240234375L3227.375,2264.22509765625Z\" fill=\"#17a45e\"/></svg>";

export default function Penpot01bScreen01bInfo() {
  return (
    <View style={{ width: 376, height: 859, backgroundColor: "#FFFFFF", borderRadius: 34, overflow: "hidden", boxShadow: "0px 10px 28px 0px rgba(15,50,68,0.14)" }}>{/* "01B Screen 01B-INFO" */}
      <View style={{ position: "absolute", left: 0, top: 754, width: 376, height: 105 }} pointerEvents="box-none">{/* "mountains" */}
        <SvgXml xml={SVG_0} width={376} height={85.3} style={{ position: "absolute", left: 0, top: 19.7 }} />
        <SvgXml xml={SVG_1} width={376} height={59.1} style={{ position: "absolute", left: 0, top: 45.9 }} />
      </View>
      <View style={{ position: "absolute", left: 0, top: 0, width: 376, height: 859, backgroundColor: "#FFFFFF", borderRadius: 34 }} />
      <View style={{ position: "absolute", left: 0, top: 611, width: 376, height: 248, borderBottomRightRadius: 34, borderBottomLeftRadius: 34, overflow: "hidden" }}>{/* "mint" */}
        <Svg style={StyleSheet.absoluteFill} width="100%" height="100%"><Defs><LinearGradient id="g01bscreen01binfo0" x1="0.5" y1="0" x2="0.5" y2="1"><Stop offset={0} stopColor="#E9F7F0" stopOpacity={0} /><Stop offset={1} stopColor="#DCF1E7" stopOpacity={1} /></LinearGradient></Defs><Rect width="100%" height="100%" fill="url(#g01bscreen01binfo0)" /></Svg>
      </View>
      <Text style={{ position: "absolute", left: 24, top: 18, width: 78, textAlign: "left", fontFamily: "PlusJakartaSans_700Bold", fontSize: 14, lineHeight: 16.8, color: "#0F3244" }}>{"9:41"}</Text>
      <View style={{ position: "absolute", left: 277, top: 18, width: 75, height: 20 }} pointerEvents="box-none">{/* "status-icons" */}
        <View style={{ position: "absolute", left: 0, top: 12.9, width: 4.3, height: 7.1, backgroundColor: "#0F3244", borderRadius: 1 }} />
        <View style={{ position: "absolute", left: 6.5, top: 9.3, width: 4.3, height: 10.7, backgroundColor: "#0F3244", borderRadius: 1 }} />
        <View style={{ position: "absolute", left: 13, top: 5.7, width: 4.3, height: 14.3, backgroundColor: "#0F3244", borderRadius: 1 }} />
        <View style={{ position: "absolute", left: 19.5, top: 2.1, width: 4.3, height: 17.9, backgroundColor: "#0F3244", borderRadius: 1 }} />
        <SvgXml xml={SVG_2} width={18.6} height={5.4} style={{ position: "absolute", left: 28.9, top: 3.8 }} />
        <SvgXml xml={SVG_3} width={11.9} height={4.4} style={{ position: "absolute", left: 32.3, top: 8.9 }} />
        <View style={{ position: "absolute", left: 36.2, top: 14.6, width: 4, height: 4, backgroundColor: "#0F3244", borderRadius: 2 }} />
        <View style={{ position: "absolute", left: 53.4, top: 4.3, width: 18.8, height: 11.4, borderRadius: 2.2, borderWidth: 1.1, borderColor: "#0F3244", opacity: 0.9 }} />
        <View style={{ position: "absolute", left: 55.7, top: 6.6, width: 12.7, height: 6.9, backgroundColor: "#0F3244", borderRadius: 1.1 }} />
        <View style={{ position: "absolute", left: 72.8, top: 8, width: 2, height: 4, backgroundColor: "#0F3244", borderRadius: 0.7 }} />
      </View>
      <View style={{ position: "absolute", left: 24, top: 57, width: 22, height: 22 }} pointerEvents="box-none">{/* "back" */}
        <SvgXml xml={SVG_4} width={10.5} height={17.9} style={{ position: "absolute", left: 4.8, top: 2.1 }} />
      </View>
      <Text style={{ position: "absolute", left: 0, top: 93, width: 376, textAlign: "center", fontFamily: "PlusJakartaSans_800ExtraBold", fontSize: 23, lineHeight: 29.9, color: "#0F3244" }}>{"Why Location Helps"}</Text>
      <Text style={{ position: "absolute", left: 42, top: 132, width: 293, textAlign: "center", fontFamily: "PlusJakartaSans_400Regular", fontSize: 14, lineHeight: 21.7, color: "#6B8796" }}>{"Location turns everyday territory into real opportunities."}</Text>
      <View style={{ position: "absolute", left: 24, top: 192, width: 329, height: 81, backgroundColor: "#F2F9F5", borderRadius: 13 }} />
      <View style={{ position: "absolute", left: 42, top: 212, width: 27, height: 27 }} pointerEvents="box-none">{/* "card-ic-0" */}
        <SvgXml xml={SVG_5} width={23.6} height={18} style={{ position: "absolute", left: 1.1, top: 4.5 }} />
      </View>
      <Text style={{ position: "absolute", left: 84, top: 206, width: 254, textAlign: "left", fontFamily: "PlusJakartaSans_700Bold", fontSize: 14, lineHeight: 18.2, color: "#0F3244" }}>{"Find Nearby Customers"}</Text>
      <Text style={{ position: "absolute", left: 84, top: 226, width: 250, textAlign: "left", fontFamily: "PlusJakartaSans_400Regular", fontSize: 11, lineHeight: 16, color: "#6B8796" }}>{"See customers around you and never miss a potential visit."}</Text>
      <View style={{ position: "absolute", left: 24, top: 286, width: 329, height: 81, backgroundColor: "#F2F9F5", borderRadius: 13 }} />
      <View style={{ position: "absolute", left: 42, top: 305, width: 27, height: 27 }} pointerEvents="box-none">{/* "card-ic-1" */}
        <SvgXml xml={SVG_6} width={21.6} height={21.6} style={{ position: "absolute", left: 2.7, top: 2.7 }} />
      </View>
      <Text style={{ position: "absolute", left: 84, top: 300, width: 254, textAlign: "left", fontFamily: "PlusJakartaSans_700Bold", fontSize: 14, lineHeight: 18.2, color: "#0F3244" }}>{"Plan Your Field Visits"}</Text>
      <Text style={{ position: "absolute", left: 84, top: 319, width: 250, textAlign: "left", fontFamily: "PlusJakartaSans_400Regular", fontSize: 11, lineHeight: 16, color: "#6B8796" }}>{"Get suggested routes, save travel time and cover more customers."}</Text>
      <View style={{ position: "absolute", left: 24, top: 379, width: 329, height: 81, backgroundColor: "#F2F9F5", borderRadius: 13 }} />
      <View style={{ position: "absolute", left: 42, top: 399, width: 27, height: 27 }} pointerEvents="box-none">{/* "card-ic-2" */}
        <View style={{ position: "absolute", left: 3.4, top: 13.5, width: 5.2, height: 10.1, backgroundColor: "#17A45E", borderRadius: 1.3 }} />
        <View style={{ position: "absolute", left: 10.9, top: 7.9, width: 5.2, height: 15.8, backgroundColor: "#17A45E", borderRadius: 1.3 }} />
        <View style={{ position: "absolute", left: 18.5, top: 3.4, width: 5.2, height: 20.3, backgroundColor: "#17A45E", borderRadius: 1.3 }} />
      </View>
      <Text style={{ position: "absolute", left: 84, top: 394, width: 254, textAlign: "left", fontFamily: "PlusJakartaSans_700Bold", fontSize: 14, lineHeight: 18.2, color: "#0F3244" }}>{"Smarter Insights"}</Text>
      <Text style={{ position: "absolute", left: 84, top: 413, width: 250, textAlign: "left", fontFamily: "PlusJakartaSans_400Regular", fontSize: 11, lineHeight: 16, color: "#6B8796" }}>{"Access location-based opportunities and area-wise performance insights."}</Text>
      <View style={{ position: "absolute", left: 24, top: 473, width: 329, height: 81, backgroundColor: "#F2F9F5", borderRadius: 13 }} />
      <View style={{ position: "absolute", left: 42, top: 492, width: 27, height: 27 }} pointerEvents="box-none">{/* "card-ic-3" */}
        <SvgXml xml={SVG_7} width={18.9} height={23.1} style={{ position: "absolute", left: 4, top: 2 }} />
      </View>
      <Text style={{ position: "absolute", left: 84, top: 487, width: 254, textAlign: "left", fontFamily: "PlusJakartaSans_700Bold", fontSize: 14, lineHeight: 18.2, color: "#0F3244" }}>{"Your Privacy Matters"}</Text>
      <Text style={{ position: "absolute", left: 84, top: 507, width: 250, textAlign: "left", fontFamily: "PlusJakartaSans_400Regular", fontSize: 11, lineHeight: 16, color: "#6B8796" }}>{"Your location is used only with your permission and is never shared without your consent."}</Text>
      <View style={{ position: "absolute", left: 24, top: 587, width: 329, height: 52, borderRadius: 13, overflow: "hidden", boxShadow: "0px 4px 12px 0px rgba(15,50,68,0.2)" }}>{/* "cta" */}
        <Svg style={StyleSheet.absoluteFill} width="100%" height="100%"><Defs><LinearGradient id="g01bscreen01binfo1" x1="0" y1="0.5" x2="1" y2="0.5"><Stop offset={0} stopColor="#0E7A4A" stopOpacity={1} /><Stop offset={1} stopColor="#1BA560" stopOpacity={1} /></LinearGradient></Defs><Rect width="100%" height="100%" fill="url(#g01bscreen01binfo1)" /></Svg>
      </View>
      <Text style={{ position: "absolute", left: 24, top: 603, width: 329, textAlign: "center", fontFamily: "PlusJakartaSans_700Bold", fontSize: 17, lineHeight: 23, color: "#FFFFFF" }}>{"Allow Location Access  →"}</Text>
      <View style={{ position: "absolute", left: 24, top: 652, width: 329, height: 49, backgroundColor: "#EFF3F5", borderRadius: 13 }} />
      <Text style={{ position: "absolute", left: 24, top: 667, width: 329, textAlign: "center", fontFamily: "PlusJakartaSans_600SemiBold", fontSize: 17, lineHeight: 23, color: "#53707E" }}>{"Not Now"}</Text>
    </View>
  );
}
