/* GENERATED by tools/penpot-to-code/to-react-native.mjs from the Penpot
 * board "02C.5 Follow-up Detail". Do not edit: regenerate with
 * `pnpm design:rn`. Its text is the board's sample copy — a design
 * reference, not a screen.
 */
import React from "react";
import { StyleSheet, View, Text } from "react-native";
import { SvgXml } from "react-native-svg";

export const size = { width: 376, height: 859 } as const;

const SVG_0 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"18.6\" height=\"5.4\" viewBox=\"2309.9 5822.8 18.6 5.4\" fill=\"none\"><path d=\"M2311.28857421875,5826.85693359375C2315.615478515625,5823.28564453125,2322.826904296875,5823.28564453125,2327.15380859375,5826.85693359375\" fill=\"none\" stroke=\"#0f3244\" stroke-width=\"1.7\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_1 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"11.9\" height=\"4.4\" viewBox=\"2313.3 5827.9 11.9 4.4\" fill=\"none\"><path d=\"M2314.605712890625,5831.0C2317.34619140625,5828.71435546875,2321.09619140625,5828.71435546875,2323.83642578125,5831.0\" fill=\"none\" stroke=\"#0f3244\" stroke-width=\"1.7\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_2 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"12.2\" height=\"21.2\" viewBox=\"2028.3 5852.9 12.2 21.2\" fill=\"none\"><path d=\"M2038.875,5854.5L2029.875,5863.5L2038.875,5872.5\" fill=\"none\" stroke=\"#0f3244\" stroke-width=\"2.2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_3 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"9.5\" height=\"11.7\" viewBox=\"2218.7 5966.2 9.5 11.7\" fill=\"none\"><path d=\"M2220.0,5967.5L2226.75,5972.0L2220.0,5976.5\" fill=\"none\" stroke=\"#17a45e\" stroke-width=\"1.7\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_4 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"17\" height=\"17\" viewBox=\"2058.4 6021.6 17 17\" fill=\"none\"><path d=\"M2061.6875,6023.0625L2064.3125,6023.0625L2065.625,6026.5625L2063.875,6027.875C2064.8525390625,6030.2568359375,2066.743408203125,6032.1474609375,2069.125,6033.125L2070.4375,6031.375L2073.9375,6032.6875L2073.9375,6035.3125C2073.93994140625,6035.80859375,2073.731689453125,6036.2822265625,2073.36474609375,6036.6162109375C2072.99755859375,6036.94970703125,2072.506103515625,6037.1123046875,2072.012451171875,6037.0625C2065.783447265625,6036.1044921875,2060.8955078125,6031.216796875,2059.9375,6024.9873046875C2059.887939453125,6024.49365234375,2060.050048828125,6024.00244140625,2060.3837890625,6023.63525390625C2060.717529296875,6023.26806640625,2061.19140625,6023.06005859375,2061.6875,6023.0625L2061.6875,6023.0625\" fill=\"none\" stroke=\"#0e7a4a\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_5 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"10.9\" height=\"6.1\" viewBox=\"2144.1 6026.8 10.9 6.1\" fill=\"none\"><path d=\"M2145.5625,6028.3125L2153.4375,6028.3125M2145.5625,6031.375L2149.9375,6031.375\" fill=\"none\" stroke=\"#0e7a4a\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_6 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"17.9\" height=\"8.3\" viewBox=\"2223.6 6024.6 17.9 8.3\" fill=\"none\"><path d=\"M2225.0625,6026.125L2232.5,6031.375L2239.9375,6026.125\" fill=\"none\" stroke=\"#0e7a4a\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_7 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"15.3\" height=\"18.9\" viewBox=\"2307.9 6021.4 15.3 18.9\" fill=\"none\"><path d=\"M2315.5,6038.8125C2315.5,6038.8125,2321.625,6033.2998046875,2321.625,6029.0126953125C2321.625,6025.6298828125,2318.8828125,6022.8876953125,2315.5,6022.8876953125C2312.1171875,6022.8876953125,2309.375,6025.6298828125,2309.375,6029.0126953125C2309.375,6033.2998046875,2315.5,6038.8125,2315.5,6038.8125L2315.5,6038.8125\" fill=\"none\" stroke=\"#0e7a4a\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_8 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"5.6\" height=\"8.5\" viewBox=\"2048.5 6128.9 5.6 8.5\" fill=\"none\"><path d=\"M2050.0,6130.375L2050.0,6134.16650390625L2052.60009765625,6135.89990234375\" fill=\"none\" stroke=\"#e5484d\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_9 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"5.5\" height=\"5.2\" viewBox=\"2040.5 6121 5.5 5.2\" fill=\"none\"><path d=\"M2041.9832763671875,6124.63330078125L2044.4749755859375,6122.466796875\" fill=\"none\" stroke=\"#e5484d\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_10 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"5.5\" height=\"5.2\" viewBox=\"2054 6121 5.5 5.2\" fill=\"none\"><path d=\"M2058.0166015625,6124.63330078125L2055.52490234375,6122.466796875\" fill=\"none\" stroke=\"#e5484d\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_11 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"4.7\" height=\"4.7\" viewBox=\"2039.4 6139.6 4.7 4.7\" fill=\"none\"><path d=\"M2042.63330078125,6141.10009765625L2040.9000244140625,6142.83349609375\" fill=\"none\" stroke=\"#e5484d\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_12 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"4.7\" height=\"4.7\" viewBox=\"2055.9 6139.6 4.7 4.7\" fill=\"none\"><path d=\"M2057.36669921875,6141.10009765625L2059.10009765625,6142.83349609375\" fill=\"none\" stroke=\"#e5484d\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_13 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"9.7\" height=\"13\" viewBox=\"2043.2 6493.8 9.7 13\" fill=\"none\"><path d=\"M2044.6666259765625,6505.33349609375L2044.6666259765625,6496.33349609375C2044.6666259765625,6495.78125,2045.1143798828125,6495.33349609375,2045.6666259765625,6495.33349609375L2050.333251953125,6495.33349609375C2050.885498046875,6495.33349609375,2051.333251953125,6495.78125,2051.333251953125,6496.33349609375L2051.333251953125,6505.33349609375\" fill=\"none\" stroke=\"#0e7a4a\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_14 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"7\" height=\"9.7\" viewBox=\"2049.8 6497.2 7 9.7\" fill=\"none\"><path d=\"M2051.333251953125,6498.66650390625L2054.333251953125,6498.66650390625C2054.885498046875,6498.66650390625,2055.333251953125,6499.1142578125,2055.333251953125,6499.66650390625L2055.333251953125,6505.33349609375\" fill=\"none\" stroke=\"#0e7a4a\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_15 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"15.7\" height=\"3\" viewBox=\"2042.2 6503.8 15.7 3\" fill=\"none\"><path d=\"M2043.6666259765625,6505.33349609375L2056.333251953125,6505.33349609375\" fill=\"none\" stroke=\"#0e7a4a\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" transform=\"translate(2050 6505.3) matrix(1,0,0,0.6666666666667709,0,-0.001111111111072982) translate(-2050 -6505.3)\"/></svg>";
const SVG_16 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"10.3\" height=\"6.3\" viewBox=\"2045.2 6496.5 10.3 6.3\" fill=\"none\"><path d=\"M2046.6666259765625,6498.0L2049.333251953125,6498.0M2046.6666259765625,6500.66650390625L2049.333251953125,6500.66650390625M2053.333251953125,6501.33349609375L2054.0,6501.33349609375\" fill=\"none\" stroke=\"#0e7a4a\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_17 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"11.7\" height=\"14.7\" viewBox=\"2337.7 6491.7 11.7 14.7\" fill=\"none\"><path d=\"M2339.0,6493.0L2348.0,6499.0L2339.0,6505.0\" fill=\"none\" stroke=\"#8aa3b0\" stroke-width=\"1.7\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";

export default function Penpot02c5FollowUpDetail() {
  return (
    <View style={{ width: 376, height: 859, backgroundColor: "#F8FBFC", borderRadius: 34, overflow: "hidden" }}>{/* "02C.5 Follow-up Detail" */}
      <Text style={{ position: "absolute", left: 23, top: 18, width: 78, textAlign: "left", fontFamily: "PlusJakartaSans_700Bold", fontSize: 14, lineHeight: 16.8, color: "#0F3244" }}>{"9:41"}</Text>
      <View style={{ position: "absolute", left: 277, top: 18, width: 75, height: 20 }} pointerEvents="box-none">{/* "status-icons" */}
        <View style={{ position: "absolute", left: 0, top: 12.9, width: 4.3, height: 7.1, backgroundColor: "#0F3244", borderRadius: 1 }} />
        <View style={{ position: "absolute", left: 6.5, top: 9.3, width: 4.3, height: 10.7, backgroundColor: "#0F3244", borderRadius: 1 }} />
        <View style={{ position: "absolute", left: 13, top: 5.7, width: 4.3, height: 14.3, backgroundColor: "#0F3244", borderRadius: 1 }} />
        <View style={{ position: "absolute", left: 19.5, top: 2.1, width: 4.3, height: 17.9, backgroundColor: "#0F3244", borderRadius: 1 }} />
        <SvgXml xml={SVG_0} width={18.6} height={5.4} style={{ position: "absolute", left: 28.9, top: 3.8 }} />
        <SvgXml xml={SVG_1} width={11.9} height={4.4} style={{ position: "absolute", left: 32.3, top: 8.9 }} />
        <View style={{ position: "absolute", left: 36.2, top: 14.6, width: 4, height: 4, backgroundColor: "#0F3244", borderRadius: 2 }} />
        <View style={{ position: "absolute", left: 53.4, top: 4.3, width: 18.8, height: 11.4, borderRadius: 2.2, borderWidth: 1.1, borderColor: "#0F3244", opacity: 0.9 }} />
        <View style={{ position: "absolute", left: 55.7, top: 6.6, width: 12.7, height: 6.9, backgroundColor: "#0F3244", borderRadius: 1.1 }} />
        <View style={{ position: "absolute", left: 72.8, top: 8, width: 2, height: 4, backgroundColor: "#0F3244", borderRadius: 0.7 }} />
      </View>
      <View style={{ position: "absolute", left: 18, top: 49, width: 27, height: 27 }} pointerEvents="box-none">{/* "h-left" */}
        <SvgXml xml={SVG_2} width={12.2} height={21.2} style={{ position: "absolute", left: 6.3, top: 2.9 }} />
      </View>
      <View style={{ position: "absolute", left: 330, top: 49, width: 27, height: 27 }} pointerEvents="box-none">{/* "h-right" */}
        <View style={{ position: "absolute", left: 11.6, top: 3.7, width: 3.8, height: 3.8, backgroundColor: "#0F3244", borderRadius: 1.9 }} />
        <View style={{ position: "absolute", left: 11.6, top: 11.6, width: 3.8, height: 3.8, backgroundColor: "#0F3244", borderRadius: 1.9 }} />
        <View style={{ position: "absolute", left: 11.6, top: 19.5, width: 3.8, height: 3.8, backgroundColor: "#0F3244", borderRadius: 1.9 }} />
      </View>
      <Text style={{ position: "absolute", left: 57, top: 50, width: 261, textAlign: "center", fontFamily: "PlusJakartaSans_700Bold", fontSize: 20, lineHeight: 26, color: "#0F3244" }}>{"Follow-up Details"}</Text>
      <View style={{ position: "absolute", left: 18, top: 101, width: 339, height: 185, backgroundColor: "#FFFFFF", borderRadius: 18, borderWidth: 1, borderColor: "#E6EFF3", boxShadow: "0px 3px 12px 0px rgba(15,50,68,0.06)" }} />
      <View style={{ position: "absolute", left: 33, top: 119, width: 57, height: 57, backgroundColor: "#E8F6EE", borderRadius: 28.5 }} />
      <Text style={{ position: "absolute", left: 33, top: 135, width: 57, textAlign: "center", fontFamily: "PlusJakartaSans_800ExtraBold", fontSize: 18, lineHeight: 25.2, letterSpacing: 0.2, color: "#0E7A4A" }}>{"TM"}</Text>
      <Text style={{ position: "absolute", left: 106, top: 118, width: 234, textAlign: "left", fontFamily: "PlusJakartaSans_700Bold", fontSize: 17, lineHeight: 23.8, color: "#0F3244" }}>{"TrendMart"}</Text>
      <Text style={{ position: "absolute", left: 106, top: 143, width: 208, textAlign: "left", fontFamily: "PlusJakartaSans_500Medium", fontSize: 12, lineHeight: 16.8, color: "#6B8796" }}>{"Ravi Kumar"}</Text>
      <Text style={{ position: "absolute", left: 106, top: 163, width: 125, textAlign: "left", fontFamily: "PlusJakartaSans_600SemiBold", fontSize: 12, lineHeight: 16.8, color: "#0E7A4A" }}>{"Customer Details"}</Text>
      <View style={{ position: "absolute", left: 213, top: 165, width: 12, height: 12 }} pointerEvents="box-none">{/* "cd-ch" */}
        <SvgXml xml={SVG_3} width={9.5} height={11.7} style={{ position: "absolute", left: 1.7, top: 0.2 }} />
      </View>
      <View style={{ position: "absolute", left: 31, top: 195, width: 313, height: 1, backgroundColor: "#EEF4F7" }} />
      <View style={{ position: "absolute", left: 40, top: 208, width: 44, height: 44, backgroundColor: "#E8F6EE", borderRadius: 22 }} />
      <View style={{ position: "absolute", left: 52, top: 219, width: 21, height: 21 }} pointerEvents="box-none">{/* "qa-ic" */}
        <SvgXml xml={SVG_4} width={17} height={17} style={{ position: "absolute", left: 2.4, top: 1.6 }} />
      </View>
      <Text style={{ position: "absolute", left: 23, top: 257, width: 78, textAlign: "center", fontFamily: "PlusJakartaSans_600SemiBold", fontSize: 10, lineHeight: 14, color: "#6B8796" }}>{"Call"}</Text>
      <View style={{ position: "absolute", left: 123, top: 208, width: 44, height: 44, backgroundColor: "#E8F6EE", borderRadius: 22 }} />
      <View style={{ position: "absolute", left: 135, top: 219, width: 21, height: 21 }} pointerEvents="box-none">{/* "qa-ic" */}
        <View style={{ position: "absolute", left: 2.6, top: 4.4, width: 15.8, height: 11.4, borderRadius: 2.5, borderWidth: 2, borderColor: "#0E7A4A" }} />
        <SvgXml xml={SVG_5} width={10.9} height={6.1} style={{ position: "absolute", left: 5.1, top: 6.8 }} />
      </View>
      <Text style={{ position: "absolute", left: 106, top: 257, width: 78, textAlign: "center", fontFamily: "PlusJakartaSans_600SemiBold", fontSize: 10, lineHeight: 14, color: "#6B8796" }}>{"Message"}</Text>
      <View style={{ position: "absolute", left: 206, top: 208, width: 44, height: 44, backgroundColor: "#E8F6EE", borderRadius: 22 }} />
      <View style={{ position: "absolute", left: 218, top: 219, width: 21, height: 21 }} pointerEvents="box-none">{/* "qa-ic" */}
        <View style={{ position: "absolute", left: 2.2, top: 4.4, width: 16.6, height: 12.3, borderRadius: 2.5, borderWidth: 2, borderColor: "#0E7A4A" }} />
        <SvgXml xml={SVG_6} width={17.9} height={8.3} style={{ position: "absolute", left: 1.6, top: 4.6 }} />
      </View>
      <Text style={{ position: "absolute", left: 189, top: 257, width: 78, textAlign: "center", fontFamily: "PlusJakartaSans_600SemiBold", fontSize: 10, lineHeight: 14, color: "#6B8796" }}>{"Email"}</Text>
      <View style={{ position: "absolute", left: 290, top: 208, width: 44, height: 44, backgroundColor: "#E8F6EE", borderRadius: 22 }} />
      <View style={{ position: "absolute", left: 301, top: 219, width: 21, height: 21 }} pointerEvents="box-none">{/* "qa-ic" */}
        <SvgXml xml={SVG_7} width={15.3} height={18.9} style={{ position: "absolute", left: 2.9, top: 1.4 }} />
        <View style={{ position: "absolute", left: 8.2, top: 6.5, width: 4.6, height: 4.5, borderRadius: 2.3, borderWidth: 2, borderColor: "#0E7A4A" }} />
      </View>
      <Text style={{ position: "absolute", left: 273, top: 257, width: 78, textAlign: "center", fontFamily: "PlusJakartaSans_600SemiBold", fontSize: 10, lineHeight: 14, color: "#6B8796" }}>{"Location"}</Text>
      <View style={{ position: "absolute", left: 18, top: 296, width: 339, height: 70, backgroundColor: "#FDEDED", borderRadius: 16, borderWidth: 1, borderColor: "#F8DCDC" }} />
      <View style={{ position: "absolute", left: 33, top: 318, width: 26, height: 26 }} pointerEvents="box-none">{/* "od-ic" */}
        <View style={{ position: "absolute", left: 4.9, top: 6.5, width: 16.3, height: 16.3, borderRadius: 8.2, borderWidth: 2, borderColor: "#E5484D" }} />
        <SvgXml xml={SVG_8} width={5.6} height={8.5} style={{ position: "absolute", left: 11.5, top: 9.9 }} />
        <SvgXml xml={SVG_9} width={5.5} height={5.2} style={{ position: "absolute", left: 3.5, top: 2 }} />
        <SvgXml xml={SVG_10} width={5.5} height={5.2} style={{ position: "absolute", left: 17, top: 2 }} />
        <SvgXml xml={SVG_11} width={4.7} height={4.7} style={{ position: "absolute", left: 2.4, top: 20.6 }} />
        <SvgXml xml={SVG_12} width={4.7} height={4.7} style={{ position: "absolute", left: 18.9, top: 20.6 }} />
      </View>
      <Text style={{ position: "absolute", left: 70, top: 306, width: 247, textAlign: "left", fontFamily: "PlusJakartaSans_700Bold", fontSize: 15, lineHeight: 21, color: "#C22B30" }}>{"Overdue by 3 days"}</Text>
      <Text style={{ position: "absolute", left: 70, top: 329, width: 247, textAlign: "left", fontFamily: "PlusJakartaSans_500Medium", fontSize: 12, lineHeight: 16.8, color: "#A86063" }}>{"Due on 12 Sep 2026"}</Text>
      <Text style={{ position: "absolute", left: 18, top: 400, width: 143, textAlign: "left", fontFamily: "PlusJakartaSans_500Medium", fontSize: 13, lineHeight: 18.2, color: "#6B8796" }}>{"Follow-up Title"}</Text>
      <Text style={{ position: "absolute", left: 156, top: 400, width: 202, textAlign: "right", fontFamily: "PlusJakartaSans_600SemiBold", fontSize: 13, lineHeight: 18.2, color: "#0F3244" }}>{"Discuss final proposal"}</Text>
      <Text style={{ position: "absolute", left: 18, top: 448, width: 143, textAlign: "left", fontFamily: "PlusJakartaSans_500Medium", fontSize: 13, lineHeight: 18.2, color: "#6B8796" }}>{"Description"}</Text>
      <Text style={{ position: "absolute", left: 143, top: 448, width: 215, textAlign: "right", fontFamily: "PlusJakartaSans_600SemiBold", fontSize: 13, lineHeight: 18.2, color: "#0F3244" }}>{"Share the revised pricing and get"}</Text>
      <Text style={{ position: "absolute", left: 143, top: 466, width: 215, textAlign: "right", fontFamily: "PlusJakartaSans_600SemiBold", fontSize: 13, lineHeight: 18.2, color: "#0F3244" }}>{"confirmation on the order."}</Text>
      <Text style={{ position: "absolute", left: 18, top: 511, width: 143, textAlign: "left", fontFamily: "PlusJakartaSans_500Medium", fontSize: 13, lineHeight: 18.2, color: "#6B8796" }}>{"Expected Value"}</Text>
      <Text style={{ position: "absolute", left: 156, top: 511, width: 202, textAlign: "right", fontFamily: "PlusJakartaSans_600SemiBold", fontSize: 13, lineHeight: 18.2, color: "#0F3244" }}>{"₹ 5,00,000"}</Text>
      <Text style={{ position: "absolute", left: 18, top: 556, width: 143, textAlign: "left", fontFamily: "PlusJakartaSans_500Medium", fontSize: 13, lineHeight: 18.2, color: "#6B8796" }}>{"Stage"}</Text>
      <View style={{ position: "absolute", left: 248, top: 547, width: 109, height: 26, backgroundColor: "#E8F6EE", borderRadius: 13 }} />
      <Text style={{ position: "absolute", left: 258, top: 551, width: 94, textAlign: "left", fontFamily: "PlusJakartaSans_700Bold", fontSize: 12, lineHeight: 16.8, letterSpacing: 0.1, color: "#0E7A4A" }}>{"Proposal Sent"}</Text>
      <Text style={{ position: "absolute", left: 18, top: 602, width: 143, textAlign: "left", fontFamily: "PlusJakartaSans_500Medium", fontSize: 13, lineHeight: 18.2, color: "#6B8796" }}>{"Priority"}</Text>
      <View style={{ position: "absolute", left: 309, top: 592, width: 48, height: 26, backgroundColor: "#FDEDED", borderRadius: 13 }} />
      <Text style={{ position: "absolute", left: 319, top: 597, width: 33, textAlign: "left", fontFamily: "PlusJakartaSans_700Bold", fontSize: 12, lineHeight: 16.8, letterSpacing: 0.1, color: "#E5484D" }}>{"High"}</Text>
      <Text style={{ position: "absolute", left: 18, top: 647, width: 260, textAlign: "left", fontFamily: "PlusJakartaSans_700Bold", fontSize: 14, lineHeight: 19.6, color: "#0F3244" }}>{"Related Opportunity"}</Text>
      <View style={{ position: "absolute", left: 18, top: 670, width: 339, height: 55, backgroundColor: "#FFFFFF", borderRadius: 16, borderWidth: 1, borderColor: "#E6EFF3", boxShadow: "0px 2px 8px 0px rgba(15,50,68,0.05)" }} />
      <View style={{ position: "absolute", left: 31, top: 683, width: 31, height: 31, backgroundColor: "#E8F6EE", borderRadius: 9 }} />
      <View style={{ position: "absolute", left: 38, top: 691, width: 16, height: 16 }} pointerEvents="box-none">{/* "tile-ic" */}
        <SvgXml xml={SVG_13} width={9.7} height={13} style={{ position: "absolute", left: 1.2, top: 1.8 }} />
        <SvgXml xml={SVG_14} width={7} height={9.7} style={{ position: "absolute", left: 7.8, top: 5.2 }} />
        <SvgXml xml={SVG_15} width={15.7} height={3} style={{ position: "absolute", left: 0.2, top: 11.8 }} />
        <SvgXml xml={SVG_16} width={10.3} height={6.3} style={{ position: "absolute", left: 3.2, top: 4.5 }} />
      </View>
      <Text style={{ position: "absolute", left: 75, top: 690, width: 234, textAlign: "left", fontFamily: "PlusJakartaSans_700Bold", fontSize: 14, lineHeight: 19.6, color: "#0F3244" }}>{"New Outlet Expansion"}</Text>
      <View style={{ position: "absolute", left: 331, top: 690, width: 16, height: 16 }} pointerEvents="box-none">{/* "rel-ch" */}
        <SvgXml xml={SVG_17} width={11.7} height={14.7} style={{ position: "absolute", left: 2.7, top: 0.7 }} />
      </View>
      <View style={{ position: "absolute", left: 18, top: 751, width: 339, height: 57, backgroundColor: "#17A45E", borderRadius: 16, boxShadow: "0px 5px 14px 0px rgba(14,122,74,0.32)" }} />
      <Text style={{ position: "absolute", left: 18, top: 769, width: 339, textAlign: "center", fontFamily: "PlusJakartaSans_700Bold", fontSize: 16, lineHeight: 22.4, color: "#FFFFFF" }}>{"Mark as Completed"}</Text>
    </View>
  );
}
