/* GENERATED by tools/penpot-to-code/to-react-native.mjs from the Penpot
 * board "02D.2 Filter & Sort". Do not edit: regenerate with
 * `pnpm design:rn`. Its text is the board's sample copy — a design
 * reference, not a screen.
 */
import React from "react";
import { StyleSheet, View, Text } from "react-native";
import Svg, { SvgXml, Defs, Rect, Stop, LinearGradient } from "react-native-svg";

export const size = { width: 376, height: 859 } as const;

const SVG_0 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"18.6\" height=\"5.4\" viewBox=\"1073.9 6922.8 18.6 5.4\" fill=\"none\"><path d=\"M1075.2884521484375,6926.85693359375C1079.6153564453125,6923.28564453125,1086.826904296875,6923.28564453125,1091.15380859375,6926.85693359375\" fill=\"none\" stroke=\"#0f3244\" stroke-width=\"1.7\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_1 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"11.9\" height=\"4.4\" viewBox=\"1077.3 6927.9 11.9 4.4\" fill=\"none\"><path d=\"M1078.605712890625,6931.0C1081.34619140625,6928.71435546875,1085.09619140625,6928.71435546875,1087.8365478515625,6931.0\" fill=\"none\" stroke=\"#0f3244\" stroke-width=\"1.7\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_2 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"12.2\" height=\"21.2\" viewBox=\"793.3 6952.9 12.2 21.2\" fill=\"none\"><path d=\"M803.875,6954.5L794.875,6963.5L803.875,6972.5\" fill=\"none\" stroke=\"#0f3244\" stroke-width=\"2.2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_3 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"10.9\" height=\"8.9\" viewBox=\"802 7051.2 10.9 8.9\" fill=\"none\"><path d=\"M803.5999755859375,7055.685546875L806.3857421875,7058.47119140625L811.4000244140625,7052.71435546875\" fill=\"none\" stroke=\"#ffffff\" stroke-width=\"2.1\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_4 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"11.7\" height=\"14.7\" viewBox=\"1106.7 7554.7 11.7 14.7\" fill=\"none\"><path d=\"M1108.0,7556.0L1117.0,7562.0L1108.0,7568.0\" fill=\"none\" stroke=\"#8aa3b0\" stroke-width=\"1.7\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_5 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"17.9\" height=\"16.4\" viewBox=\"811.6 7718.3 17.9 16.4\" fill=\"none\"><path d=\"M820.5,7718.27490234375L811.574951171875,7725.7998046875L814.199951171875,7725.7998046875L814.199951171875,7734.72509765625L819.449951171875,7734.72509765625L819.449951171875,7729.125L821.550048828125,7729.125L821.550048828125,7734.72509765625L826.800048828125,7734.72509765625L826.800048828125,7725.7998046875L829.425048828125,7725.7998046875L820.5,7718.27490234375Z\" fill=\"#17a45e\"/></svg>";
const SVG_6 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"16.6\" height=\"16.6\" viewBox=\"879.2 7718.3 16.6 16.6\" fill=\"none\"><path d=\"M879.1875,7718.27490234375L895.8125,7718.27490234375L895.8125,7720.2001953125L879.1875,7720.2001953125ZM880.675048828125,7721.4248046875L894.324951171875,7721.4248046875L894.324951171875,7729.64990234375C894.324951171875,7730.4716796875,893.6590576171875,7731.1376953125,892.8375244140625,7731.1376953125L882.1624755859375,7731.1376953125C881.3409423828125,7731.1376953125,880.675048828125,7730.4716796875,880.675048828125,7729.64990234375L880.675048828125,7721.4248046875ZM886.625,7732.10009765625L888.375,7732.10009765625L888.375,7734.89990234375L886.625,7734.89990234375Z\" fill=\"#93a9b5\"/></svg>";
const SVG_7 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"18.4\" height=\"14\" viewBox=\"1014.9 7719.5 18.4 14\" fill=\"none\"><path d=\"M1021.4375,7725.625C1023.12890625,7725.625,1024.5,7724.25390625,1024.5,7722.5625C1024.5,7720.87109375,1023.12890625,7719.5,1021.4375,7719.5C1019.74609375,7719.5,1018.375,7720.87109375,1018.375,7722.5625C1018.375,7724.25390625,1019.74609375,7725.625,1021.4375,7725.625ZM1027.5625,7725.625C1029.01220703125,7725.625,1030.1875,7724.44970703125,1030.1875,7723.0C1030.1875,7721.55029296875,1029.01220703125,7720.375,1027.5625,7720.375C1026.11279296875,7720.375,1024.9375,7721.55029296875,1024.9375,7723.0C1024.9375,7724.44970703125,1026.11279296875,7725.625,1027.5625,7725.625ZM1021.4375,7727.375C1018.8125,7727.375,1014.875,7728.77490234375,1014.875,7731.3125L1014.875,7733.5L1028.0,7733.5L1028.0,7731.3125C1028.0,7728.77490234375,1024.0625,7727.375,1021.4375,7727.375ZM1027.737548828125,7727.375C1026.949951171875,7727.375,1026.1624755859375,7727.46240234375,1025.4625244140625,7727.6376953125C1026.6875,7728.60009765625,1027.125,7729.7373046875,1027.125,7731.3125L1027.125,7733.5L1033.25,7733.5L1033.25,7731.3125C1033.25,7728.9501953125,1030.0999755859375,7727.375,1027.737548828125,7727.375Z\" fill=\"#93a9b5\"/></svg>";
const SVG_8 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"3.6\" height=\"18.2\" viewBox=\"954.7 7707.4 3.6 18.2\" fill=\"none\"><path d=\"M956.5,7709.20849609375L956.5,7723.79150390625\" fill=\"none\" stroke=\"#ffffff\" stroke-width=\"2.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_9 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"18.2\" height=\"3.6\" viewBox=\"947.4 7714.7 18.2 3.6\" fill=\"none\"><path d=\"M949.2083740234375,7716.5L963.7916259765625,7716.5\" fill=\"none\" stroke=\"#ffffff\" stroke-width=\"2.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";

export default function Penpot02d2FilterSort() {
  return (
    <View style={{ width: 376, height: 859, backgroundColor: "#F8FBFC", borderRadius: 34, overflow: "hidden" }}>{/* "02D.2 Filter & Sort" */}
      <Text style={{ position: "absolute", left: 24, top: 19, width: 78, textAlign: "left", fontFamily: "PlusJakartaSans_700Bold", fontSize: 14, lineHeight: 16.8, color: "#0F3244" }}>{"9:41"}</Text>
      <View style={{ position: "absolute", left: 277, top: 19, width: 75, height: 20 }} pointerEvents="box-none">{/* "status-icons" */}
        <View style={{ position: "absolute", left: 0, top: 12.9, width: 4.3, height: 7.1, backgroundColor: "#0F3244", borderRadius: 1 }} />
        <View style={{ position: "absolute", left: 6.5, top: 9.3, width: 4.3, height: 10.7, backgroundColor: "#0F3244", borderRadius: 1 }} />
        <View style={{ position: "absolute", left: 13, top: 5.7, width: 4.3, height: 14.3, backgroundColor: "#0F3244", borderRadius: 1 }} />
        <View style={{ position: "absolute", left: 19.5, top: 2.1, width: 4.3, height: 17.9, backgroundColor: "#0F3244", borderRadius: 1 }} />
        <SvgXml xml={SVG_0} width={18.6} height={5.4} style={{ position: "absolute", left: 28.9, top: 3.8 }} />
        <SvgXml xml={SVG_1} width={11.9} height={4.4} style={{ position: "absolute", left: 32.3, top: 8.9 }} />
        <View style={{ position: "absolute", left: 36.2, top: 14.6, width: 4, height: 4, backgroundColor: "#0F3244", borderRadius: 2 }} />
        <View style={{ position: "absolute", left: 53.4, top: 4.3, width: 18.8, height: 11.4, borderRadius: 2.2, borderWidth: 1.1, borderColor: "#0F3244", opacity: 0.9 }} />
        <View style={{ position: "absolute", left: 55.7, top: 6.6, width: 12.7, height: 6.9, backgroundColor: "#0F3244", borderRadius: 1.1 }} />
        <View style={{ position: "absolute", left: 72.8, top: 8, width: 2, height: 4, backgroundColor: "#0F3244", borderRadius: 0.7 }} />
      </View>
      <View style={{ position: "absolute", left: 19, top: 50, width: 27, height: 27 }} pointerEvents="box-none">{/* "h-left" */}
        <SvgXml xml={SVG_2} width={12.2} height={21.2} style={{ position: "absolute", left: 6.3, top: 2.9 }} />
      </View>
      <Text style={{ position: "absolute", left: 58, top: 52, width: 226, textAlign: "center", fontFamily: "PlusJakartaSans_700Bold", fontSize: 18, lineHeight: 25.2, color: "#0F3244" }}>{"Filter Opportunities"}</Text>
      <Text style={{ position: "absolute", left: 289, top: 55, width: 69, textAlign: "right", fontFamily: "PlusJakartaSans_600SemiBold", fontSize: 13, lineHeight: 18.2, color: "#17A45E" }}>{"Clear All"}</Text>
      <Text style={{ position: "absolute", left: 19, top: 115, width: 260, textAlign: "left", fontFamily: "PlusJakartaSans_700Bold", fontSize: 15, lineHeight: 21, color: "#0F3244" }}>{"Probability"}</Text>
      <View style={{ position: "absolute", left: 19, top: 138, width: 339, height: 34, backgroundColor: "#EDF5F8", borderRadius: 10 }} />
      <View style={{ position: "absolute", left: 29, top: 145, width: 21, height: 21, backgroundColor: "#17A45E", borderRadius: 6 }} />
      <View style={{ position: "absolute", left: 33, top: 149, width: 13, height: 13 }} pointerEvents="box-none">{/* "cb-ck" */}
        <SvgXml xml={SVG_3} width={10.9} height={8.9} style={{ position: "absolute", left: 1, top: 2.2 }} />
      </View>
      <Text style={{ position: "absolute", left: 63, top: 147, width: 228, textAlign: "left", fontFamily: "PlusJakartaSans_700Bold", fontSize: 14, lineHeight: 19.6, color: "#0F3244" }}>{"High (70% - 100%)"}</Text>
      <Text style={{ position: "absolute", left: 293, top: 147, width: 52, textAlign: "right", fontFamily: "PlusJakartaSans_600SemiBold", fontSize: 14, lineHeight: 19.6, color: "#6B8796" }}>{"8"}</Text>
      <View style={{ position: "absolute", left: 29, top: 182, width: 21, height: 21, backgroundColor: "#FFFFFF", borderRadius: 6, borderWidth: 1.3, borderColor: "#C9D9E1" }} />
      <Text style={{ position: "absolute", left: 63, top: 185, width: 228, textAlign: "left", fontFamily: "PlusJakartaSans_500Medium", fontSize: 14, lineHeight: 19.6, color: "#0F3244" }}>{"Medium (40% - 69%)"}</Text>
      <Text style={{ position: "absolute", left: 293, top: 185, width: 52, textAlign: "right", fontFamily: "PlusJakartaSans_600SemiBold", fontSize: 14, lineHeight: 19.6, color: "#6B8796" }}>{"3"}</Text>
      <View style={{ position: "absolute", left: 29, top: 220, width: 21, height: 21, backgroundColor: "#FFFFFF", borderRadius: 6, borderWidth: 1.3, borderColor: "#C9D9E1" }} />
      <Text style={{ position: "absolute", left: 63, top: 223, width: 228, textAlign: "left", fontFamily: "PlusJakartaSans_500Medium", fontSize: 14, lineHeight: 19.6, color: "#0F3244" }}>{"Low (1% - 39%)"}</Text>
      <Text style={{ position: "absolute", left: 293, top: 223, width: 52, textAlign: "right", fontFamily: "PlusJakartaSans_600SemiBold", fontSize: 14, lineHeight: 19.6, color: "#6B8796" }}>{"1"}</Text>
      <Text style={{ position: "absolute", left: 19, top: 276, width: 260, textAlign: "left", fontFamily: "PlusJakartaSans_700Bold", fontSize: 15, lineHeight: 21, color: "#0F3244" }}>{"Stage"}</Text>
      <View style={{ position: "absolute", left: 29, top: 309, width: 21, height: 21, backgroundColor: "#FFFFFF", borderRadius: 6, borderWidth: 1.3, borderColor: "#C9D9E1" }} />
      <Text style={{ position: "absolute", left: 63, top: 311, width: 228, textAlign: "left", fontFamily: "PlusJakartaSans_500Medium", fontSize: 14, lineHeight: 19.6, color: "#0F3244" }}>{"Discovery"}</Text>
      <Text style={{ position: "absolute", left: 293, top: 311, width: 52, textAlign: "right", fontFamily: "PlusJakartaSans_600SemiBold", fontSize: 14, lineHeight: 19.6, color: "#6B8796" }}>{"2"}</Text>
      <View style={{ position: "absolute", left: 29, top: 345, width: 21, height: 21, backgroundColor: "#FFFFFF", borderRadius: 6, borderWidth: 1.3, borderColor: "#C9D9E1" }} />
      <Text style={{ position: "absolute", left: 63, top: 348, width: 228, textAlign: "left", fontFamily: "PlusJakartaSans_500Medium", fontSize: 14, lineHeight: 19.6, color: "#0F3244" }}>{"Needs Follow-up"}</Text>
      <Text style={{ position: "absolute", left: 293, top: 348, width: 52, textAlign: "right", fontFamily: "PlusJakartaSans_600SemiBold", fontSize: 14, lineHeight: 19.6, color: "#6B8796" }}>{"3"}</Text>
      <View style={{ position: "absolute", left: 29, top: 381, width: 21, height: 21, backgroundColor: "#FFFFFF", borderRadius: 6, borderWidth: 1.3, borderColor: "#C9D9E1" }} />
      <Text style={{ position: "absolute", left: 63, top: 384, width: 228, textAlign: "left", fontFamily: "PlusJakartaSans_500Medium", fontSize: 14, lineHeight: 19.6, color: "#0F3244" }}>{"Proposal Sent"}</Text>
      <Text style={{ position: "absolute", left: 293, top: 384, width: 52, textAlign: "right", fontFamily: "PlusJakartaSans_600SemiBold", fontSize: 14, lineHeight: 19.6, color: "#6B8796" }}>{"4"}</Text>
      <View style={{ position: "absolute", left: 29, top: 418, width: 21, height: 21, backgroundColor: "#FFFFFF", borderRadius: 6, borderWidth: 1.3, borderColor: "#C9D9E1" }} />
      <Text style={{ position: "absolute", left: 63, top: 420, width: 228, textAlign: "left", fontFamily: "PlusJakartaSans_500Medium", fontSize: 14, lineHeight: 19.6, color: "#0F3244" }}>{"Negotiation"}</Text>
      <Text style={{ position: "absolute", left: 293, top: 420, width: 52, textAlign: "right", fontFamily: "PlusJakartaSans_600SemiBold", fontSize: 14, lineHeight: 19.6, color: "#6B8796" }}>{"2"}</Text>
      <View style={{ position: "absolute", left: 29, top: 454, width: 21, height: 21, backgroundColor: "#FFFFFF", borderRadius: 6, borderWidth: 1.3, borderColor: "#C9D9E1" }} />
      <Text style={{ position: "absolute", left: 63, top: 457, width: 228, textAlign: "left", fontFamily: "PlusJakartaSans_500Medium", fontSize: 14, lineHeight: 19.6, color: "#0F3244" }}>{"Closed Won"}</Text>
      <Text style={{ position: "absolute", left: 293, top: 457, width: 52, textAlign: "right", fontFamily: "PlusJakartaSans_600SemiBold", fontSize: 14, lineHeight: 19.6, color: "#6B8796" }}>{"0"}</Text>
      <Text style={{ position: "absolute", left: 19, top: 510, width: 260, textAlign: "left", fontFamily: "PlusJakartaSans_700Bold", fontSize: 15, lineHeight: 21, color: "#0F3244" }}>{"Expected Closure"}</Text>
      <View style={{ position: "absolute", left: 29, top: 543, width: 21, height: 21, backgroundColor: "#FFFFFF", borderRadius: 6, borderWidth: 1.3, borderColor: "#C9D9E1" }} />
      <Text style={{ position: "absolute", left: 63, top: 545, width: 228, textAlign: "left", fontFamily: "PlusJakartaSans_500Medium", fontSize: 14, lineHeight: 19.6, color: "#0F3244" }}>{"This Month"}</Text>
      <Text style={{ position: "absolute", left: 293, top: 545, width: 52, textAlign: "right", fontFamily: "PlusJakartaSans_600SemiBold", fontSize: 14, lineHeight: 19.6, color: "#6B8796" }}>{"5"}</Text>
      <View style={{ position: "absolute", left: 29, top: 579, width: 21, height: 21, backgroundColor: "#FFFFFF", borderRadius: 6, borderWidth: 1.3, borderColor: "#C9D9E1" }} />
      <Text style={{ position: "absolute", left: 63, top: 582, width: 228, textAlign: "left", fontFamily: "PlusJakartaSans_500Medium", fontSize: 14, lineHeight: 19.6, color: "#0F3244" }}>{"Next Month"}</Text>
      <Text style={{ position: "absolute", left: 293, top: 582, width: 52, textAlign: "right", fontFamily: "PlusJakartaSans_600SemiBold", fontSize: 14, lineHeight: 19.6, color: "#6B8796" }}>{"4"}</Text>
      <View style={{ position: "absolute", left: 29, top: 615, width: 21, height: 21, backgroundColor: "#FFFFFF", borderRadius: 6, borderWidth: 1.3, borderColor: "#C9D9E1" }} />
      <Text style={{ position: "absolute", left: 63, top: 618, width: 228, textAlign: "left", fontFamily: "PlusJakartaSans_500Medium", fontSize: 14, lineHeight: 19.6, color: "#0F3244" }}>{"Next Quarter"}</Text>
      <Text style={{ position: "absolute", left: 293, top: 618, width: 52, textAlign: "right", fontFamily: "PlusJakartaSans_600SemiBold", fontSize: 14, lineHeight: 19.6, color: "#6B8796" }}>{"3"}</Text>
      <View style={{ position: "absolute", left: 29, top: 652, width: 21, height: 21, backgroundColor: "#FFFFFF", borderRadius: 6, borderWidth: 1.3, borderColor: "#C9D9E1" }} />
      <Text style={{ position: "absolute", left: 63, top: 654, width: 228, textAlign: "left", fontFamily: "PlusJakartaSans_500Medium", fontSize: 14, lineHeight: 19.6, color: "#0F3244" }}>{"Custom Range"}</Text>
      <View style={{ position: "absolute", left: 336, top: 654, width: 16, height: 16 }} pointerEvents="box-none">{/* "chk-ch" */}
        <SvgXml xml={SVG_4} width={11.7} height={14.7} style={{ position: "absolute", left: 2.7, top: 0.7 }} />
      </View>
      <View style={{ position: "absolute", left: 19, top: 718, width: 339, height: 55, backgroundColor: "#17A45E", borderRadius: 16, boxShadow: "0px 5px 14px 0px rgba(14,122,74,0.32)" }} />
      <Text style={{ position: "absolute", left: 19, top: 735, width: 339, textAlign: "center", fontFamily: "PlusJakartaSans_700Bold", fontSize: 16, lineHeight: 22.4, color: "#FFFFFF" }}>{"Apply Filters"}</Text>
      <View style={{ position: "absolute", left: 0, top: 807, width: 376, height: 52, backgroundColor: "#FFFFFF", borderBottomRightRadius: 34, borderBottomLeftRadius: 34, boxShadow: "0px -3px 14px 0px rgba(15,50,68,0.08)" }} />
      <View style={{ position: "absolute", left: 42, top: 816, width: 21, height: 21 }} pointerEvents="box-none">{/* "nav-ic-0" */}
        <SvgXml xml={SVG_5} width={17.9} height={16.4} style={{ position: "absolute", left: 1.6, top: 2.3 }} />
      </View>
      <Text style={{ position: "absolute", left: 11, top: 841, width: 83, textAlign: "center", fontFamily: "PlusJakartaSans_700Bold", fontSize: 10, lineHeight: 12.5, color: "#17A45E" }}>{"Home"}</Text>
      <View style={{ position: "absolute", left: 109, top: 816, width: 21, height: 21 }} pointerEvents="box-none">{/* "nav-ic-1" */}
        <SvgXml xml={SVG_6} width={16.6} height={16.6} style={{ position: "absolute", left: 2.2, top: 2.3 }} />
      </View>
      <Text style={{ position: "absolute", left: 78, top: 841, width: 83, textAlign: "center", fontFamily: "PlusJakartaSans_500Medium", fontSize: 10, lineHeight: 12.5, color: "#93A9B5" }}>{"Pipeline"}</Text>
      <View style={{ position: "absolute", left: 246, top: 816, width: 21, height: 21 }} pointerEvents="box-none">{/* "nav-ic-2" */}
        <SvgXml xml={SVG_7} width={18.4} height={14} style={{ position: "absolute", left: 0.9, top: 3.5 }} />
      </View>
      <Text style={{ position: "absolute", left: 215, top: 841, width: 83, textAlign: "center", fontFamily: "PlusJakartaSans_500Medium", fontSize: 10, lineHeight: 12.5, color: "#93A9B5" }}>{"Customers"}</Text>
      <View style={{ position: "absolute", left: 314, top: 816, width: 21, height: 21 }} pointerEvents="box-none">{/* "nav-ic-3" */}
        <View style={{ position: "absolute", left: 2.5, top: 8.7, width: 15.9, height: 3.7 }} pointerEvents="box-none">{/* "svg-g" */}
          <View style={{ position: "absolute", left: 0, top: 0, width: 3.7, height: 3.7, backgroundColor: "#93A9B5", borderRadius: 1.9 }} />
          <View style={{ position: "absolute", left: 6.2, top: 0, width: 3.7, height: 3.7, backgroundColor: "#93A9B5", borderRadius: 1.9 }} />
          <View style={{ position: "absolute", left: 12.3, top: 0, width: 3.7, height: 3.7, backgroundColor: "#93A9B5", borderRadius: 1.9 }} />
        </View>
      </View>
      <Text style={{ position: "absolute", left: 282, top: 841, width: 83, textAlign: "center", fontFamily: "PlusJakartaSans_500Medium", fontSize: 10, lineHeight: 12.5, color: "#93A9B5" }}>{"More"}</Text>
      <View style={{ position: "absolute", left: 161, top: 790, width: 53, height: 53, borderRadius: 26.5, overflow: "hidden", boxShadow: "0px 5px 14px 0px rgba(15,50,68,0.3)" }}>{/* "fab" */}
        <Svg style={StyleSheet.absoluteFill} width="100%" height="100%"><Defs><LinearGradient id="g02d2filtersort0" x1="0" y1="0" x2="1" y2="1"><Stop offset={0} stopColor="#1BA560" stopOpacity={1} /><Stop offset={1} stopColor="#0E7A4A" stopOpacity={1} /></LinearGradient></Defs><Rect width="100%" height="100%" fill="url(#g02d2filtersort0)" /></Svg>
      </View>
      <View style={{ position: "absolute", left: 176, top: 804, width: 25, height: 25 }} pointerEvents="box-none">{/* "fab-plus" */}
        <View style={{ position: "absolute", left: 5.2, top: 5.2, width: 14.6, height: 14.6 }} pointerEvents="box-none">{/* "svg-g" */}
          <SvgXml xml={SVG_8} width={3.6} height={18.2} style={{ position: "absolute", left: 5.5, top: -1.8 }} />
          <SvgXml xml={SVG_9} width={18.2} height={3.6} style={{ position: "absolute", left: -1.8, top: 5.5 }} />
        </View>
      </View>
    </View>
  );
}
