/* GENERATED by tools/penpot-to-code/to-react-native.mjs from the Penpot
 * board "02D.3 Sorted View". Do not edit: regenerate with
 * `pnpm design:rn`. Its text is the board's sample copy — a design
 * reference, not a screen.
 */
import React from "react";
import { StyleSheet, View, Text } from "react-native";
import Svg, { SvgXml, Defs, Rect, Stop, LinearGradient } from "react-native-svg";

export const size = { width: 376, height: 859 } as const;

const SVG_0 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"18.6\" height=\"5.4\" viewBox=\"1485.9 6922.8 18.6 5.4\" fill=\"none\"><path d=\"M1487.2884521484375,6926.85693359375C1491.6153564453125,6923.28564453125,1498.826904296875,6923.28564453125,1503.15380859375,6926.85693359375\" fill=\"none\" stroke=\"#0f3244\" stroke-width=\"1.7\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_1 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"11.9\" height=\"4.4\" viewBox=\"1489.3 6927.9 11.9 4.4\" fill=\"none\"><path d=\"M1490.605712890625,6931.0C1493.34619140625,6928.71435546875,1497.09619140625,6928.71435546875,1499.8365478515625,6931.0\" fill=\"none\" stroke=\"#0f3244\" stroke-width=\"1.7\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_2 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"12.2\" height=\"21.2\" viewBox=\"1205.3 6957.9 12.2 21.2\" fill=\"none\"><path d=\"M1215.875,6959.5L1206.875,6968.5L1215.875,6977.5\" fill=\"none\" stroke=\"#0f3244\" stroke-width=\"2.2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_3 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"13.2\" height=\"10.6\" viewBox=\"1269.4 7026.2 13.2 10.6\" fill=\"none\"><path d=\"M1270.75,7027.5L1276.0,7035.375L1281.25,7027.5\" fill=\"none\" stroke=\"#0e7a4a\" stroke-width=\"1.7\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_4 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"3\" height=\"13\" viewBox=\"1316.2 7025.8 3 13\" fill=\"none\"><path d=\"M1317.6666259765625,7037.33349609375L1317.6666259765625,7027.33349609375\" fill=\"none\" stroke=\"#0f3244\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" transform=\"translate(1317.7 7032.3) matrix(0.6666666666667425,0,0,1.0000000000000355,-0.0011111111115944539,3.7125857943465235e-13) translate(-1317.7 -7032.3)\"/></svg>";
const SVG_5 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"7.7\" height=\"5.3\" viewBox=\"1313.8 7025.8 7.7 5.3\" fill=\"none\"><path d=\"M1315.3333740234375,7029.66650390625L1317.6666259765625,7027.33349609375L1320.0,7029.66650390625\" fill=\"none\" stroke=\"#0f3244\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_6 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"7.7\" height=\"9.7\" viewBox=\"1320.5 7027.2 7.7 9.7\" fill=\"none\"><path d=\"M1322.0,7028.66650390625L1326.6666259765625,7028.66650390625M1322.0,7032.0L1325.6666259765625,7032.0M1322.0,7035.33349609375L1324.6666259765625,7035.33349609375\" fill=\"none\" stroke=\"#0f3244\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_7 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"13.2\" height=\"10.6\" viewBox=\"1515.4 7026.2 13.2 10.6\" fill=\"none\"><path d=\"M1516.75,7027.5L1522.0,7035.375L1527.25,7027.5\" fill=\"none\" stroke=\"#6b8796\" stroke-width=\"1.7\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_8 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"4.9\" height=\"9.5\" viewBox=\"1266.5 7137 4.9 9.5\" fill=\"none\"><path d=\"M1269.0,7137.0C1269.5,7139.0,1267.5,7139.5,1267.5,7141.25C1267.5,7141.89990234375,1267.8499755859375,7142.39990234375,1268.300048828125,7142.7001953125C1267.8499755859375,7142.7998046875,1267.300048828125,7142.4501953125,1267.0,7141.89990234375C1266.699951171875,7142.39990234375,1266.550048828125,7142.9501953125,1266.550048828125,7143.5C1266.550048828125,7145.39990234375,1267.6500244140625,7146.5,1269.0,7146.5C1270.3499755859375,7146.5,1271.449951171875,7145.39990234375,1271.449951171875,7144.0498046875C1271.449951171875,7141.5,1269.0,7140.75,1269.0,7137.0Z\" fill=\"#e5484d\"/></svg>";
const SVG_9 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"11.7\" height=\"14.7\" viewBox=\"1518.7 7115.7 11.7 14.7\" fill=\"none\"><path d=\"M1520.0,7117.0L1529.0,7123.0L1520.0,7129.0\" fill=\"none\" stroke=\"#8aa3b0\" stroke-width=\"1.7\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_10 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"4.9\" height=\"9.5\" viewBox=\"1266.5 7239 4.9 9.5\" fill=\"none\"><path d=\"M1269.0,7239.0C1269.5,7241.0,1267.5,7241.5,1267.5,7243.25C1267.5,7243.89990234375,1267.8499755859375,7244.39990234375,1268.300048828125,7244.7001953125C1267.8499755859375,7244.7998046875,1267.300048828125,7244.4501953125,1267.0,7243.89990234375C1266.699951171875,7244.39990234375,1266.550048828125,7244.9501953125,1266.550048828125,7245.5C1266.550048828125,7247.39990234375,1267.6500244140625,7248.5,1269.0,7248.5C1270.3499755859375,7248.5,1271.449951171875,7247.39990234375,1271.449951171875,7246.0498046875C1271.449951171875,7243.5,1269.0,7242.75,1269.0,7239.0Z\" fill=\"#e5484d\"/></svg>";
const SVG_11 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"11.7\" height=\"14.7\" viewBox=\"1518.7 7216.7 11.7 14.7\" fill=\"none\"><path d=\"M1520.0,7218.0L1529.0,7224.0L1520.0,7230.0\" fill=\"none\" stroke=\"#8aa3b0\" stroke-width=\"1.7\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_12 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"4.9\" height=\"9.5\" viewBox=\"1266.5 7340 4.9 9.5\" fill=\"none\"><path d=\"M1269.0,7340.0C1269.5,7342.0,1267.5,7342.5,1267.5,7344.25C1267.5,7344.89990234375,1267.8499755859375,7345.39990234375,1268.300048828125,7345.7001953125C1267.8499755859375,7345.7998046875,1267.300048828125,7345.4501953125,1267.0,7344.89990234375C1266.699951171875,7345.39990234375,1266.550048828125,7345.9501953125,1266.550048828125,7346.5C1266.550048828125,7348.39990234375,1267.6500244140625,7349.5,1269.0,7349.5C1270.3499755859375,7349.5,1271.449951171875,7348.39990234375,1271.449951171875,7347.0498046875C1271.449951171875,7344.5,1269.0,7343.75,1269.0,7340.0Z\" fill=\"#e5484d\"/></svg>";
const SVG_13 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"11.7\" height=\"14.7\" viewBox=\"1518.7 7318.7 11.7 14.7\" fill=\"none\"><path d=\"M1520.0,7320.0L1529.0,7326.0L1520.0,7332.0\" fill=\"none\" stroke=\"#8aa3b0\" stroke-width=\"1.7\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_14 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"4.9\" height=\"9.5\" viewBox=\"1266.5 7442 4.9 9.5\" fill=\"none\"><path d=\"M1269.0,7442.0C1269.5,7444.0,1267.5,7444.5,1267.5,7446.25C1267.5,7446.89990234375,1267.8499755859375,7447.39990234375,1268.300048828125,7447.7001953125C1267.8499755859375,7447.7998046875,1267.300048828125,7447.4501953125,1267.0,7446.89990234375C1266.699951171875,7447.39990234375,1266.550048828125,7447.9501953125,1266.550048828125,7448.5C1266.550048828125,7450.39990234375,1267.6500244140625,7451.5,1269.0,7451.5C1270.3499755859375,7451.5,1271.449951171875,7450.39990234375,1271.449951171875,7449.0498046875C1271.449951171875,7446.5,1269.0,7445.75,1269.0,7442.0Z\" fill=\"#e5484d\"/></svg>";
const SVG_15 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"11.7\" height=\"14.7\" viewBox=\"1518.7 7419.7 11.7 14.7\" fill=\"none\"><path d=\"M1520.0,7421.0L1529.0,7427.0L1520.0,7433.0\" fill=\"none\" stroke=\"#8aa3b0\" stroke-width=\"1.7\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_16 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"4.9\" height=\"9.5\" viewBox=\"1266.5 7543 4.9 9.5\" fill=\"none\"><path d=\"M1269.0,7543.0C1269.5,7545.0,1267.5,7545.5,1267.5,7547.25C1267.5,7547.89990234375,1267.8499755859375,7548.39990234375,1268.300048828125,7548.7001953125C1267.8499755859375,7548.7998046875,1267.300048828125,7548.4501953125,1267.0,7547.89990234375C1266.699951171875,7548.39990234375,1266.550048828125,7548.9501953125,1266.550048828125,7549.5C1266.550048828125,7551.39990234375,1267.6500244140625,7552.5,1269.0,7552.5C1270.3499755859375,7552.5,1271.449951171875,7551.39990234375,1271.449951171875,7550.0498046875C1271.449951171875,7547.5,1269.0,7546.75,1269.0,7543.0Z\" fill=\"#e5484d\"/></svg>";
const SVG_17 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"11.7\" height=\"14.7\" viewBox=\"1518.7 7521.7 11.7 14.7\" fill=\"none\"><path d=\"M1520.0,7523.0L1529.0,7529.0L1520.0,7535.0\" fill=\"none\" stroke=\"#8aa3b0\" stroke-width=\"1.7\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_18 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"4.9\" height=\"9.5\" viewBox=\"1266.5 7644 4.9 9.5\" fill=\"none\"><path d=\"M1269.0,7644.0C1269.5,7646.0,1267.5,7646.5,1267.5,7648.25C1267.5,7648.89990234375,1267.8499755859375,7649.39990234375,1268.300048828125,7649.7001953125C1267.8499755859375,7649.7998046875,1267.300048828125,7649.4501953125,1267.0,7648.89990234375C1266.699951171875,7649.39990234375,1266.550048828125,7649.9501953125,1266.550048828125,7650.5C1266.550048828125,7652.39990234375,1267.6500244140625,7653.5,1269.0,7653.5C1270.3499755859375,7653.5,1271.449951171875,7652.39990234375,1271.449951171875,7651.0498046875C1271.449951171875,7648.5,1269.0,7647.75,1269.0,7644.0Z\" fill=\"#e5484d\"/></svg>";
const SVG_19 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"11.7\" height=\"14.7\" viewBox=\"1518.7 7622.7 11.7 14.7\" fill=\"none\"><path d=\"M1520.0,7624.0L1529.0,7630.0L1520.0,7636.0\" fill=\"none\" stroke=\"#8aa3b0\" stroke-width=\"1.7\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_20 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"17.9\" height=\"16.4\" viewBox=\"1223.6 7718.3 17.9 16.4\" fill=\"none\"><path d=\"M1232.5,7718.27490234375L1223.574951171875,7725.7998046875L1226.199951171875,7725.7998046875L1226.199951171875,7734.72509765625L1231.449951171875,7734.72509765625L1231.449951171875,7729.125L1233.550048828125,7729.125L1233.550048828125,7734.72509765625L1238.800048828125,7734.72509765625L1238.800048828125,7725.7998046875L1241.425048828125,7725.7998046875L1232.5,7718.27490234375Z\" fill=\"#17a45e\"/></svg>";
const SVG_21 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"16.6\" height=\"16.6\" viewBox=\"1291.2 7718.3 16.6 16.6\" fill=\"none\"><path d=\"M1291.1875,7718.27490234375L1307.8125,7718.27490234375L1307.8125,7720.2001953125L1291.1875,7720.2001953125ZM1292.675048828125,7721.4248046875L1306.324951171875,7721.4248046875L1306.324951171875,7729.64990234375C1306.324951171875,7730.4716796875,1305.6590576171875,7731.1376953125,1304.8375244140625,7731.1376953125L1294.1624755859375,7731.1376953125C1293.3409423828125,7731.1376953125,1292.675048828125,7730.4716796875,1292.675048828125,7729.64990234375L1292.675048828125,7721.4248046875ZM1298.625,7732.10009765625L1300.375,7732.10009765625L1300.375,7734.89990234375L1298.625,7734.89990234375Z\" fill=\"#93a9b5\"/></svg>";
const SVG_22 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"18.4\" height=\"14\" viewBox=\"1426.9 7719.5 18.4 14\" fill=\"none\"><path d=\"M1433.4375,7725.625C1435.12890625,7725.625,1436.5,7724.25390625,1436.5,7722.5625C1436.5,7720.87109375,1435.12890625,7719.5,1433.4375,7719.5C1431.74609375,7719.5,1430.375,7720.87109375,1430.375,7722.5625C1430.375,7724.25390625,1431.74609375,7725.625,1433.4375,7725.625ZM1439.5625,7725.625C1441.01220703125,7725.625,1442.1875,7724.44970703125,1442.1875,7723.0C1442.1875,7721.55029296875,1441.01220703125,7720.375,1439.5625,7720.375C1438.11279296875,7720.375,1436.9375,7721.55029296875,1436.9375,7723.0C1436.9375,7724.44970703125,1438.11279296875,7725.625,1439.5625,7725.625ZM1433.4375,7727.375C1430.8125,7727.375,1426.875,7728.77490234375,1426.875,7731.3125L1426.875,7733.5L1440.0,7733.5L1440.0,7731.3125C1440.0,7728.77490234375,1436.0625,7727.375,1433.4375,7727.375ZM1439.737548828125,7727.375C1438.949951171875,7727.375,1438.1624755859375,7727.46240234375,1437.4625244140625,7727.6376953125C1438.6875,7728.60009765625,1439.125,7729.7373046875,1439.125,7731.3125L1439.125,7733.5L1445.25,7733.5L1445.25,7731.3125C1445.25,7728.9501953125,1442.0999755859375,7727.375,1439.737548828125,7727.375Z\" fill=\"#93a9b5\"/></svg>";
const SVG_23 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"3.6\" height=\"18.2\" viewBox=\"1366.7 7707.4 3.6 18.2\" fill=\"none\"><path d=\"M1368.5,7709.20849609375L1368.5,7723.79150390625\" fill=\"none\" stroke=\"#ffffff\" stroke-width=\"2.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_24 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"18.2\" height=\"3.6\" viewBox=\"1359.4 7714.7 18.2 3.6\" fill=\"none\"><path d=\"M1361.2083740234375,7716.5L1375.7916259765625,7716.5\" fill=\"none\" stroke=\"#ffffff\" stroke-width=\"2.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";

export default function Penpot02d3SortedView() {
  return (
    <View style={{ width: 376, height: 859, backgroundColor: "#F8FBFC", borderRadius: 34, overflow: "hidden" }}>{/* "02D.3 Sorted View" */}
      <Text style={{ position: "absolute", left: 24, top: 19, width: 78, textAlign: "left", fontFamily: "PlusJakartaSans_700Bold", fontSize: 14, lineHeight: 16.8, color: "#0F3244" }}>{"9:41"}</Text>
      <View style={{ position: "absolute", left: 277, top: 19, width: 75, height: 20 }} pointerEvents="box-none">{/* "status-icons" */}
        <View style={{ position: "absolute", left: 0, top: 12.9, width: 4.3, height: 7.1, backgroundColor: "#0F3244", borderRadius: 1 }} />
        <View style={{ position: "absolute", left: 6.5, top: 9.3, width: 4.3, height: 10.7, backgroundColor: "#0F3244", borderRadius: 1 }} />
        <View style={{ position: "absolute", left: 13, top: 5.7, width: 4.3, height: 14.3, backgroundColor: "#0F3244", borderRadius: 1 }} />
        <View style={{ position: "absolute", left: 19.5, top: 2.1, width: 4.3, height: 17.9, backgroundColor: "#0F3244", borderRadius: 1 }} />
        <SvgXml xml={SVG_0} width={18.6} height={5.4} style={{ position: "absolute", left: 28.9, top: 3.8 }} />
        <SvgXml xml={SVG_1} width={11.9} height={4.4} style={{ position: "absolute", left: 32.3, top: 8.9 }} />
        <View style={{ position: "absolute", left: 36.2, top: 14.6, width: 4, height: 4, backgroundColor: "#0F3244", borderRadius: 2 }} />
        <View style={{ position: "absolute", left: 53.4, top: 4.3, width: 18.8, height: 11.4, borderRadius: 2.2, borderWidth: 1.1, borderColor: "#0F3244", opacity: 0.9 }} />
        <View style={{ position: "absolute", left: 55.7, top: 6.6, width: 12.7, height: 6.9, backgroundColor: "#0F3244", borderRadius: 1.1 }} />
        <View style={{ position: "absolute", left: 72.8, top: 8, width: 2, height: 4, backgroundColor: "#0F3244", borderRadius: 0.7 }} />
      </View>
      <View style={{ position: "absolute", left: 19, top: 55, width: 27, height: 27 }} pointerEvents="box-none">{/* "h-left" */}
        <SvgXml xml={SVG_2} width={12.2} height={21.2} style={{ position: "absolute", left: 6.3, top: 2.9 }} />
      </View>
      <Text style={{ position: "absolute", left: 58, top: 56, width: 261, textAlign: "center", fontFamily: "PlusJakartaSans_700Bold", fontSize: 18, lineHeight: 25.2, color: "#0F3244" }}>{"Hot Opportunities"}</Text>
      <Text style={{ position: "absolute", left: 32, top: 78, width: 313, textAlign: "center", fontFamily: "PlusJakartaSans_500Medium", fontSize: 11, lineHeight: 15.4, color: "#6B8796" }}>{"8 high-probability opportunities"}</Text>
      <View style={{ position: "absolute", left: 19, top: 115, width: 94, height: 34, backgroundColor: "#E8F6EE", borderRadius: 17, borderWidth: 1, borderColor: "#D4EDE0" }} />
      <Text style={{ position: "absolute", left: 32, top: 124, width: 52, textAlign: "left", fontFamily: "PlusJakartaSans_700Bold", fontSize: 12, lineHeight: 16.8, color: "#0E7A4A" }}>{"High (8)"}</Text>
      <View style={{ position: "absolute", left: 89, top: 124, width: 14, height: 14 }} pointerEvents="box-none">{/* "dd1-ch" */}
        <SvgXml xml={SVG_3} width={13.2} height={10.6} style={{ position: "absolute", left: 0.4, top: 2.2 }} />
      </View>
      <View style={{ position: "absolute", left: 120, top: 115, width: 238, height: 34, backgroundColor: "#FFFFFF", borderRadius: 17, borderWidth: 1, borderColor: "#E6EFF3" }} />
      <View style={{ position: "absolute", left: 133, top: 124, width: 16, height: 16 }} pointerEvents="box-none">{/* "dd2-ic" */}
        <SvgXml xml={SVG_4} width={3} height={13} style={{ position: "absolute", left: 3.2, top: 1.8 }} />
        <SvgXml xml={SVG_5} width={7.7} height={5.3} style={{ position: "absolute", left: 0.8, top: 1.8 }} />
        <SvgXml xml={SVG_6} width={7.7} height={9.7} style={{ position: "absolute", left: 7.5, top: 3.2 }} />
      </View>
      <Text style={{ position: "absolute", left: 154, top: 125, width: 182, textAlign: "left", fontFamily: "PlusJakartaSans_600SemiBold", fontSize: 12, lineHeight: 16.8, color: "#0F3244" }}>{"Expected Close (Soonest)"}</Text>
      <View style={{ position: "absolute", left: 335, top: 124, width: 14, height: 14 }} pointerEvents="box-none">{/* "dd2-ch" */}
        <SvgXml xml={SVG_7} width={13.2} height={10.6} style={{ position: "absolute", left: 0.4, top: 2.2 }} />
      </View>
      <View style={{ position: "absolute", left: 19, top: 172, width: 339, height: 608, backgroundColor: "#FFFFFF", borderRadius: 18, borderWidth: 1, borderColor: "#E6EFF3", boxShadow: "0px 3px 12px 0px rgba(15,50,68,0.06)" }} />
      <View style={{ position: "absolute", left: 29, top: 189, width: 39, height: 39, backgroundColor: "#E8F6EE", borderRadius: 19.5 }} />
      <Text style={{ position: "absolute", left: 29, top: 200, width: 39, textAlign: "center", fontFamily: "PlusJakartaSans_800ExtraBold", fontSize: 12, lineHeight: 16.8, letterSpacing: 0.2, color: "#0E7A4A" }}>{"UC"}</Text>
      <Text style={{ position: "absolute", left: 76, top: 192, width: 164, textAlign: "left", fontFamily: "PlusJakartaSans_700Bold", fontSize: 14, lineHeight: 19.6, color: "#0F3244" }}>{"Urban Creations"}</Text>
      <Text style={{ position: "absolute", left: 242, top: 192, width: 81, textAlign: "right", fontFamily: "PlusJakartaSans_800ExtraBold", fontSize: 14, lineHeight: 19.6, color: "#0F3244" }}>{"₹ 4.8L"}</Text>
      <Text style={{ position: "absolute", left: 76, top: 211, width: 169, textAlign: "left", fontFamily: "PlusJakartaSans_500Medium", fontSize: 12, lineHeight: 16.8, color: "#6B8796" }}>{"Product Upgrade"}</Text>
      <View style={{ position: "absolute", left: 76, top: 232, width: 55, height: 21, backgroundColor: "#FDECEC", borderRadius: 10 }} />
      <View style={{ position: "absolute", left: 83, top: 236, width: 12, height: 12 }} pointerEvents="box-none">{/* "pill-ic" */}
        <SvgXml xml={SVG_8} width={4.9} height={9.5} style={{ position: "absolute", left: 3.5, top: 1 }} />
      </View>
      <Text style={{ position: "absolute", left: 101, top: 234, width: 25, textAlign: "left", fontFamily: "PlusJakartaSans_700Bold", fontSize: 11, lineHeight: 15.4, letterSpacing: 0.1, color: "#E5484D" }}>{"75%"}</Text>
      <View style={{ position: "absolute", left: 137, top: 232, width: 121, height: 21, backgroundColor: "#EAF2F7", borderRadius: 10 }} />
      <Text style={{ position: "absolute", left: 147, top: 234, width: 105, textAlign: "left", fontFamily: "PlusJakartaSans_700Bold", fontSize: 11, lineHeight: 15.4, letterSpacing: 0.1, color: "#4B7C93" }}>{"Needs Follow-up"}</Text>
      <View style={{ position: "absolute", left: 281, top: 232, width: 60, height: 21, backgroundColor: "#F1F6F8", borderRadius: 10 }} />
      <Text style={{ position: "absolute", left: 292, top: 234, width: 44, textAlign: "left", fontFamily: "PlusJakartaSans_700Bold", fontSize: 11, lineHeight: 15.4, letterSpacing: 0.1, color: "#6B8796" }}>{"18 Sep"}</Text>
      <View style={{ position: "absolute", left: 336, top: 215, width: 16, height: 16 }} pointerEvents="box-none">{/* "ch" */}
        <SvgXml xml={SVG_9} width={11.7} height={14.7} style={{ position: "absolute", left: 2.7, top: 0.7 }} />
      </View>
      <View style={{ position: "absolute", left: 29, top: 273, width: 319, height: 1, backgroundColor: "#EEF4F7" }} />
      <View style={{ position: "absolute", left: 29, top: 290, width: 39, height: 39, backgroundColor: "#E8F6EE", borderRadius: 19.5 }} />
      <Text style={{ position: "absolute", left: 29, top: 301, width: 39, textAlign: "center", fontFamily: "PlusJakartaSans_800ExtraBold", fontSize: 12, lineHeight: 16.8, letterSpacing: 0.2, color: "#0E7A4A" }}>{"TM"}</Text>
      <Text style={{ position: "absolute", left: 76, top: 293, width: 164, textAlign: "left", fontFamily: "PlusJakartaSans_700Bold", fontSize: 14, lineHeight: 19.6, color: "#0F3244" }}>{"TrendMart"}</Text>
      <Text style={{ position: "absolute", left: 242, top: 293, width: 81, textAlign: "right", fontFamily: "PlusJakartaSans_800ExtraBold", fontSize: 14, lineHeight: 19.6, color: "#0F3244" }}>{"₹ 5.0L"}</Text>
      <Text style={{ position: "absolute", left: 76, top: 312, width: 169, textAlign: "left", fontFamily: "PlusJakartaSans_500Medium", fontSize: 12, lineHeight: 16.8, color: "#6B8796" }}>{"New Outlet Expansion"}</Text>
      <View style={{ position: "absolute", left: 76, top: 333, width: 55, height: 21, backgroundColor: "#FDECEC", borderRadius: 10 }} />
      <View style={{ position: "absolute", left: 83, top: 338, width: 12, height: 12 }} pointerEvents="box-none">{/* "pill-ic" */}
        <SvgXml xml={SVG_10} width={4.9} height={9.5} style={{ position: "absolute", left: 3.5, top: 1 }} />
      </View>
      <Text style={{ position: "absolute", left: 101, top: 336, width: 25, textAlign: "left", fontFamily: "PlusJakartaSans_700Bold", fontSize: 11, lineHeight: 15.4, letterSpacing: 0.1, color: "#E5484D" }}>{"90%"}</Text>
      <View style={{ position: "absolute", left: 137, top: 333, width: 108, height: 21, backgroundColor: "#EAF2F7", borderRadius: 10 }} />
      <Text style={{ position: "absolute", left: 147, top: 336, width: 92, textAlign: "left", fontFamily: "PlusJakartaSans_700Bold", fontSize: 11, lineHeight: 15.4, letterSpacing: 0.1, color: "#4B7C93" }}>{"Proposal Sent"}</Text>
      <View style={{ position: "absolute", left: 281, top: 333, width: 60, height: 21, backgroundColor: "#F1F6F8", borderRadius: 10 }} />
      <Text style={{ position: "absolute", left: 292, top: 336, width: 44, textAlign: "left", fontFamily: "PlusJakartaSans_700Bold", fontSize: 11, lineHeight: 15.4, letterSpacing: 0.1, color: "#6B8796" }}>{"20 Sep"}</Text>
      <View style={{ position: "absolute", left: 336, top: 316, width: 16, height: 16 }} pointerEvents="box-none">{/* "ch" */}
        <SvgXml xml={SVG_11} width={11.7} height={14.7} style={{ position: "absolute", left: 2.7, top: 0.7 }} />
      </View>
      <View style={{ position: "absolute", left: 29, top: 375, width: 319, height: 1, backgroundColor: "#EEF4F7" }} />
      <View style={{ position: "absolute", left: 29, top: 392, width: 39, height: 39, backgroundColor: "#E8F6EE", borderRadius: 19.5 }} />
      <Text style={{ position: "absolute", left: 29, top: 403, width: 39, textAlign: "center", fontFamily: "PlusJakartaSans_800ExtraBold", fontSize: 12, lineHeight: 16.8, letterSpacing: 0.2, color: "#0E7A4A" }}>{"GT"}</Text>
      <Text style={{ position: "absolute", left: 76, top: 394, width: 164, textAlign: "left", fontFamily: "PlusJakartaSans_700Bold", fontSize: 14, lineHeight: 19.6, color: "#0F3244" }}>{"Greenfield Traders"}</Text>
      <Text style={{ position: "absolute", left: 242, top: 394, width: 81, textAlign: "right", fontFamily: "PlusJakartaSans_800ExtraBold", fontSize: 14, lineHeight: 19.6, color: "#0F3244" }}>{"₹ 3.6L"}</Text>
      <Text style={{ position: "absolute", left: 76, top: 414, width: 169, textAlign: "left", fontFamily: "PlusJakartaSans_500Medium", fontSize: 12, lineHeight: 16.8, color: "#6B8796" }}>{"New Product Line"}</Text>
      <View style={{ position: "absolute", left: 76, top: 435, width: 55, height: 21, backgroundColor: "#FDECEC", borderRadius: 10 }} />
      <View style={{ position: "absolute", left: 83, top: 439, width: 12, height: 12 }} pointerEvents="box-none">{/* "pill-ic" */}
        <SvgXml xml={SVG_12} width={4.9} height={9.5} style={{ position: "absolute", left: 3.5, top: 1 }} />
      </View>
      <Text style={{ position: "absolute", left: 101, top: 437, width: 25, textAlign: "left", fontFamily: "PlusJakartaSans_700Bold", fontSize: 11, lineHeight: 15.4, letterSpacing: 0.1, color: "#E5484D" }}>{"70%"}</Text>
      <View style={{ position: "absolute", left: 137, top: 435, width: 108, height: 21, backgroundColor: "#EAF2F7", borderRadius: 10 }} />
      <Text style={{ position: "absolute", left: 147, top: 437, width: 92, textAlign: "left", fontFamily: "PlusJakartaSans_700Bold", fontSize: 11, lineHeight: 15.4, letterSpacing: 0.1, color: "#4B7C93" }}>{"Proposal Sent"}</Text>
      <View style={{ position: "absolute", left: 281, top: 435, width: 60, height: 21, backgroundColor: "#F1F6F8", borderRadius: 10 }} />
      <Text style={{ position: "absolute", left: 292, top: 437, width: 44, textAlign: "left", fontFamily: "PlusJakartaSans_700Bold", fontSize: 11, lineHeight: 15.4, letterSpacing: 0.1, color: "#6B8796" }}>{"22 Sep"}</Text>
      <View style={{ position: "absolute", left: 336, top: 418, width: 16, height: 16 }} pointerEvents="box-none">{/* "ch" */}
        <SvgXml xml={SVG_13} width={11.7} height={14.7} style={{ position: "absolute", left: 2.7, top: 0.7 }} />
      </View>
      <View style={{ position: "absolute", left: 29, top: 476, width: 319, height: 1, backgroundColor: "#EEF4F7" }} />
      <View style={{ position: "absolute", left: 29, top: 493, width: 39, height: 39, backgroundColor: "#E8F6EE", borderRadius: 19.5 }} />
      <Text style={{ position: "absolute", left: 29, top: 504, width: 39, textAlign: "center", fontFamily: "PlusJakartaSans_800ExtraBold", fontSize: 12, lineHeight: 16.8, letterSpacing: 0.2, color: "#0E7A4A" }}>{"MR"}</Text>
      <Text style={{ position: "absolute", left: 76, top: 496, width: 164, textAlign: "left", fontFamily: "PlusJakartaSans_700Bold", fontSize: 14, lineHeight: 19.6, color: "#0F3244" }}>{"Metro Retail"}</Text>
      <Text style={{ position: "absolute", left: 242, top: 496, width: 81, textAlign: "right", fontFamily: "PlusJakartaSans_800ExtraBold", fontSize: 14, lineHeight: 19.6, color: "#0F3244" }}>{"₹ 12.5L"}</Text>
      <Text style={{ position: "absolute", left: 76, top: 515, width: 169, textAlign: "left", fontFamily: "PlusJakartaSans_500Medium", fontSize: 12, lineHeight: 16.8, color: "#6B8796" }}>{"Annual Supply Contract"}</Text>
      <View style={{ position: "absolute", left: 76, top: 536, width: 55, height: 21, backgroundColor: "#FDECEC", borderRadius: 10 }} />
      <View style={{ position: "absolute", left: 83, top: 541, width: 12, height: 12 }} pointerEvents="box-none">{/* "pill-ic" */}
        <SvgXml xml={SVG_14} width={4.9} height={9.5} style={{ position: "absolute", left: 3.5, top: 1 }} />
      </View>
      <Text style={{ position: "absolute", left: 101, top: 539, width: 25, textAlign: "left", fontFamily: "PlusJakartaSans_700Bold", fontSize: 11, lineHeight: 15.4, letterSpacing: 0.1, color: "#E5484D" }}>{"80%"}</Text>
      <View style={{ position: "absolute", left: 137, top: 536, width: 94, height: 21, backgroundColor: "#EAF2F7", borderRadius: 10 }} />
      <Text style={{ position: "absolute", left: 147, top: 539, width: 78, textAlign: "left", fontFamily: "PlusJakartaSans_700Bold", fontSize: 11, lineHeight: 15.4, letterSpacing: 0.1, color: "#4B7C93" }}>{"Negotiation"}</Text>
      <View style={{ position: "absolute", left: 281, top: 536, width: 60, height: 21, backgroundColor: "#F1F6F8", borderRadius: 10 }} />
      <Text style={{ position: "absolute", left: 292, top: 539, width: 44, textAlign: "left", fontFamily: "PlusJakartaSans_700Bold", fontSize: 11, lineHeight: 15.4, letterSpacing: 0.1, color: "#6B8796" }}>{"25 Sep"}</Text>
      <View style={{ position: "absolute", left: 336, top: 519, width: 16, height: 16 }} pointerEvents="box-none">{/* "ch" */}
        <SvgXml xml={SVG_15} width={11.7} height={14.7} style={{ position: "absolute", left: 2.7, top: 0.7 }} />
      </View>
      <View style={{ position: "absolute", left: 29, top: 578, width: 319, height: 1, backgroundColor: "#EEF4F7" }} />
      <View style={{ position: "absolute", left: 29, top: 595, width: 39, height: 39, backgroundColor: "#E8F6EE", borderRadius: 19.5 }} />
      <Text style={{ position: "absolute", left: 29, top: 606, width: 39, textAlign: "center", fontFamily: "PlusJakartaSans_800ExtraBold", fontSize: 12, lineHeight: 16.8, letterSpacing: 0.2, color: "#0E7A4A" }}>{"LM"}</Text>
      <Text style={{ position: "absolute", left: 76, top: 597, width: 164, textAlign: "left", fontFamily: "PlusJakartaSans_700Bold", fontSize: 14, lineHeight: 19.6, color: "#0F3244" }}>{"Laxmi Mart"}</Text>
      <Text style={{ position: "absolute", left: 242, top: 597, width: 81, textAlign: "right", fontFamily: "PlusJakartaSans_800ExtraBold", fontSize: 14, lineHeight: 19.6, color: "#0F3244" }}>{"₹ 2.8L"}</Text>
      <Text style={{ position: "absolute", left: 76, top: 617, width: 169, textAlign: "left", fontFamily: "PlusJakartaSans_500Medium", fontSize: 12, lineHeight: 16.8, color: "#6B8796" }}>{"Store Expansion"}</Text>
      <View style={{ position: "absolute", left: 76, top: 637, width: 55, height: 21, backgroundColor: "#FDECEC", borderRadius: 10 }} />
      <View style={{ position: "absolute", left: 83, top: 642, width: 12, height: 12 }} pointerEvents="box-none">{/* "pill-ic" */}
        <SvgXml xml={SVG_16} width={4.9} height={9.5} style={{ position: "absolute", left: 3.5, top: 1 }} />
      </View>
      <Text style={{ position: "absolute", left: 101, top: 640, width: 25, textAlign: "left", fontFamily: "PlusJakartaSans_700Bold", fontSize: 11, lineHeight: 15.4, letterSpacing: 0.1, color: "#E5484D" }}>{"65%"}</Text>
      <View style={{ position: "absolute", left: 137, top: 637, width: 81, height: 21, backgroundColor: "#EAF2F7", borderRadius: 10 }} />
      <Text style={{ position: "absolute", left: 147, top: 640, width: 65, textAlign: "left", fontFamily: "PlusJakartaSans_700Bold", fontSize: 11, lineHeight: 15.4, letterSpacing: 0.1, color: "#4B7C93" }}>{"Discovery"}</Text>
      <View style={{ position: "absolute", left: 281, top: 637, width: 60, height: 21, backgroundColor: "#F1F6F8", borderRadius: 10 }} />
      <Text style={{ position: "absolute", left: 292, top: 640, width: 44, textAlign: "left", fontFamily: "PlusJakartaSans_700Bold", fontSize: 11, lineHeight: 15.4, letterSpacing: 0.1, color: "#6B8796" }}>{"30 Sep"}</Text>
      <View style={{ position: "absolute", left: 336, top: 621, width: 16, height: 16 }} pointerEvents="box-none">{/* "ch" */}
        <SvgXml xml={SVG_17} width={11.7} height={14.7} style={{ position: "absolute", left: 2.7, top: 0.7 }} />
      </View>
      <View style={{ position: "absolute", left: 29, top: 679, width: 319, height: 1, backgroundColor: "#EEF4F7" }} />
      <View style={{ position: "absolute", left: 29, top: 696, width: 39, height: 39, backgroundColor: "#E8F6EE", borderRadius: 19.5 }} />
      <Text style={{ position: "absolute", left: 29, top: 707, width: 39, textAlign: "center", fontFamily: "PlusJakartaSans_800ExtraBold", fontSize: 12, lineHeight: 16.8, letterSpacing: 0.2, color: "#0E7A4A" }}>{"CS"}</Text>
      <Text style={{ position: "absolute", left: 76, top: 699, width: 164, textAlign: "left", fontFamily: "PlusJakartaSans_700Bold", fontSize: 14, lineHeight: 19.6, color: "#0F3244" }}>{"City Super Market"}</Text>
      <Text style={{ position: "absolute", left: 242, top: 699, width: 81, textAlign: "right", fontFamily: "PlusJakartaSans_800ExtraBold", fontSize: 14, lineHeight: 19.6, color: "#0F3244" }}>{"₹ 1.9L"}</Text>
      <Text style={{ position: "absolute", left: 76, top: 718, width: 169, textAlign: "left", fontFamily: "PlusJakartaSans_500Medium", fontSize: 12, lineHeight: 16.8, color: "#6B8796" }}>{"Product Sampling"}</Text>
      <View style={{ position: "absolute", left: 76, top: 739, width: 55, height: 21, backgroundColor: "#FDECEC", borderRadius: 10 }} />
      <View style={{ position: "absolute", left: 83, top: 743, width: 12, height: 12 }} pointerEvents="box-none">{/* "pill-ic" */}
        <SvgXml xml={SVG_18} width={4.9} height={9.5} style={{ position: "absolute", left: 3.5, top: 1 }} />
      </View>
      <Text style={{ position: "absolute", left: 101, top: 741, width: 25, textAlign: "left", fontFamily: "PlusJakartaSans_700Bold", fontSize: 11, lineHeight: 15.4, letterSpacing: 0.1, color: "#E5484D" }}>{"70%"}</Text>
      <View style={{ position: "absolute", left: 137, top: 739, width: 121, height: 21, backgroundColor: "#EAF2F7", borderRadius: 10 }} />
      <Text style={{ position: "absolute", left: 147, top: 741, width: 105, textAlign: "left", fontFamily: "PlusJakartaSans_700Bold", fontSize: 11, lineHeight: 15.4, letterSpacing: 0.1, color: "#4B7C93" }}>{"Needs Follow-up"}</Text>
      <View style={{ position: "absolute", left: 281, top: 739, width: 60, height: 21, backgroundColor: "#F1F6F8", borderRadius: 10 }} />
      <Text style={{ position: "absolute", left: 292, top: 741, width: 44, textAlign: "left", fontFamily: "PlusJakartaSans_700Bold", fontSize: 11, lineHeight: 15.4, letterSpacing: 0.1, color: "#6B8796" }}>{"05 Oct"}</Text>
      <View style={{ position: "absolute", left: 336, top: 722, width: 16, height: 16 }} pointerEvents="box-none">{/* "ch" */}
        <SvgXml xml={SVG_19} width={11.7} height={14.7} style={{ position: "absolute", left: 2.7, top: 0.7 }} />
      </View>
      <View style={{ position: "absolute", left: 0, top: 807, width: 376, height: 52, backgroundColor: "#FFFFFF", borderBottomRightRadius: 34, borderBottomLeftRadius: 34, boxShadow: "0px -3px 14px 0px rgba(15,50,68,0.08)" }} />
      <View style={{ position: "absolute", left: 42, top: 816, width: 21, height: 21 }} pointerEvents="box-none">{/* "nav-ic-0" */}
        <SvgXml xml={SVG_20} width={17.9} height={16.4} style={{ position: "absolute", left: 1.6, top: 2.3 }} />
      </View>
      <Text style={{ position: "absolute", left: 11, top: 841, width: 83, textAlign: "center", fontFamily: "PlusJakartaSans_700Bold", fontSize: 10, lineHeight: 12.5, color: "#17A45E" }}>{"Home"}</Text>
      <View style={{ position: "absolute", left: 109, top: 816, width: 21, height: 21 }} pointerEvents="box-none">{/* "nav-ic-1" */}
        <SvgXml xml={SVG_21} width={16.6} height={16.6} style={{ position: "absolute", left: 2.2, top: 2.3 }} />
      </View>
      <Text style={{ position: "absolute", left: 78, top: 841, width: 83, textAlign: "center", fontFamily: "PlusJakartaSans_500Medium", fontSize: 10, lineHeight: 12.5, color: "#93A9B5" }}>{"Pipeline"}</Text>
      <View style={{ position: "absolute", left: 246, top: 816, width: 21, height: 21 }} pointerEvents="box-none">{/* "nav-ic-2" */}
        <SvgXml xml={SVG_22} width={18.4} height={14} style={{ position: "absolute", left: 0.9, top: 3.5 }} />
      </View>
      <Text style={{ position: "absolute", left: 215, top: 841, width: 83, textAlign: "center", fontFamily: "PlusJakartaSans_500Medium", fontSize: 10, lineHeight: 12.5, color: "#93A9B5" }}>{"Customers"}</Text>
      <View style={{ position: "absolute", left: 314, top: 816, width: 21, height: 21 }} pointerEvents="box-none">{/* "nav-ic-3" */}
        <View style={{ position: "absolute", left: 2.5, top: 8.7, width: 15.9, height: 3.7 }} pointerEvents="box-none">{/* "svg-g" */}
          <View style={{ position: "absolute", left: 0, top: 0, width: 3.7, height: 3.7, backgroundColor: "#93A9B5", borderRadius: 1.9 }} />
          <View style={{ position: "absolute", left: 6.2, top: 0, width: 3.7, height: 3.7, backgroundColor: "#93A9B5", borderRadius: 1.9 }} />
          <View style={{ position: "absolute", left: 12.3, top: 0, width: 3.7, height: 3.7, backgroundColor: "#93A9B5", borderRadius: 1.9 }} />
        </View>
      </View>
      <Text style={{ position: "absolute", left: 282, top: 841, width: 83, textAlign: "center", fontFamily: "PlusJakartaSans_500Medium", fontSize: 10, lineHeight: 12.5, color: "#93A9B5" }}>{"More"}</Text>
      <View style={{ position: "absolute", left: 161, top: 790, width: 53, height: 53, borderRadius: 26.5, overflow: "hidden", boxShadow: "0px 5px 14px 0px rgba(15,50,68,0.3)" }}>{/* "fab" */}
        <Svg style={StyleSheet.absoluteFill} width="100%" height="100%"><Defs><LinearGradient id="g02d3sortedview0" x1="0" y1="0" x2="1" y2="1"><Stop offset={0} stopColor="#1BA560" stopOpacity={1} /><Stop offset={1} stopColor="#0E7A4A" stopOpacity={1} /></LinearGradient></Defs><Rect width="100%" height="100%" fill="url(#g02d3sortedview0)" /></Svg>
      </View>
      <View style={{ position: "absolute", left: 176, top: 804, width: 25, height: 25 }} pointerEvents="box-none">{/* "fab-plus" */}
        <View style={{ position: "absolute", left: 5.2, top: 5.2, width: 14.6, height: 14.6 }} pointerEvents="box-none">{/* "svg-g" */}
          <SvgXml xml={SVG_23} width={3.6} height={18.2} style={{ position: "absolute", left: 5.5, top: -1.8 }} />
          <SvgXml xml={SVG_24} width={18.2} height={3.6} style={{ position: "absolute", left: -1.8, top: 5.5 }} />
        </View>
      </View>
    </View>
  );
}
