/* GENERATED by tools/penpot-to-code/to-react-native.mjs from the Penpot
 * board "02E.4 Back to Home". Do not edit: regenerate with
 * `pnpm design:rn`. Its text is the board's sample copy — a design
 * reference, not a screen.
 */
import React from "react";
import { StyleSheet, View, Text, Image } from "react-native";
import Svg, { SvgXml, Defs, Rect, Stop, LinearGradient } from "react-native-svg";

export const size = { width: 376, height: 859 } as const;

const SVG_0 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"376\" height=\"109.7\" viewBox=\"1592 8236.3 376 109.7\" fill=\"none\"><path d=\"M1592.0,8295.375L1641.439453125,8256.0L1677.8685302734375,8281.3125L1727.3079833984375,8236.3125L1781.9515380859375,8278.5L1833.9930419921875,8247.5625L1883.4324951171875,8284.125L1932.8719482421875,8253.1875L1968.0,8278.5L1968.0,8346.0L1592.0,8346.0Z\" fill=\"#e6f1ec\"/></svg>";
const SVG_1 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"376\" height=\"75.9\" viewBox=\"1592 8270.1 376 75.9\" fill=\"none\"><path d=\"M1592.0,8315.0625L1649.2457275390625,8281.3125L1698.68505859375,8306.625L1755.9307861328125,8270.0625L1813.176513671875,8301.0L1867.820068359375,8275.6875L1919.861572265625,8306.625L1968.0,8286.9375L1968.0,8346.0L1592.0,8346.0Z\" fill=\"#d8e8e1\"/></svg>";
const SVG_2 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"18.6\" height=\"5.4\" viewBox=\"1897.9 8121.8 18.6 5.4\" fill=\"none\"><path d=\"M1899.2884521484375,8125.85693359375C1903.6153564453125,8122.28564453125,1910.826904296875,8122.28564453125,1915.15380859375,8125.85693359375\" fill=\"none\" stroke=\"#0f3244\" stroke-width=\"1.7\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_3 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"11.9\" height=\"4.4\" viewBox=\"1901.3 8126.9 11.9 4.4\" fill=\"none\"><path d=\"M1902.605712890625,8130.0C1905.34619140625,8127.71435546875,1909.09619140625,8127.71435546875,1911.8365478515625,8130.0\" fill=\"none\" stroke=\"#0f3244\" stroke-width=\"1.7\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_4 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"16.1\" height=\"19.2\" viewBox=\"1884.4 8168.9 16.1 19.2\" fill=\"none\"><path d=\"M1892.5,8168.91650390625C1891.6002197265625,8168.91650390625,1890.870849609375,8169.64599609375,1890.870849609375,8170.5458984375L1890.870849609375,8171.12060546875C1887.970458984375,8171.8798828125,1885.9814453125,8174.54541015625,1886.0792236328125,8177.54150390625L1886.0792236328125,8181.56689453125L1884.449951171875,8184.25L1884.449951171875,8185.20849609375L1900.550048828125,8185.20849609375L1900.550048828125,8184.25L1898.9207763671875,8181.56689453125L1898.9207763671875,8177.54150390625C1899.0185546875,8174.54541015625,1897.029541015625,8171.8798828125,1894.129150390625,8171.12060546875L1894.129150390625,8170.5458984375C1894.129150390625,8169.64599609375,1893.3997802734375,8168.91650390625,1892.5,8168.91650390625ZM1892.5,8188.08349609375C1893.8045654296875,8188.08740234375,1894.891357421875,8187.083984375,1894.99169921875,8185.783203125L1890.00830078125,8185.783203125C1890.108642578125,8187.083984375,1891.1954345703125,8188.08740234375,1892.5,8188.08349609375Z\" fill=\"#123e52\"/></svg>";
const SVG_5 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"12\" height=\"13.3\" viewBox=\"1628 8303.3 12 13.3\" fill=\"none\"><path d=\"M1630.6666259765625,8303.3330078125L1630.6666259765625,8304.6669921875L1629.6666259765625,8304.6669921875C1628.7462158203125,8304.6669921875,1628.0,8305.4130859375,1628.0,8306.3330078125L1628.0,8315.3330078125C1628.0,8316.0693359375,1628.596923828125,8316.6669921875,1629.3333740234375,8316.6669921875L1638.6666259765625,8316.6669921875C1639.403076171875,8316.6669921875,1640.0,8316.0693359375,1640.0,8315.3330078125L1640.0,8306.3330078125C1640.0,8305.4130859375,1639.2537841796875,8304.6669921875,1638.3333740234375,8304.6669921875L1637.3333740234375,8304.6669921875L1637.3333740234375,8303.3330078125L1636.0,8303.3330078125L1636.0,8304.6669921875L1632.0,8304.6669921875L1632.0,8303.3330078125L1630.6666259765625,8303.3330078125ZM1638.6666259765625,8308.0L1638.6666259765625,8315.3330078125L1629.3333740234375,8315.3330078125L1629.3333740234375,8308.0L1638.6666259765625,8308.0Z\" fill=\"#5e7a88\"/></svg>";
const SVG_6 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"10.1\" height=\"13.5\" viewBox=\"1859.9 8303.3 10.1 13.5\" fill=\"none\"><path d=\"M1865.0,8303.2666015625C1862.2017822265625,8303.2666015625,1859.933349609375,8305.53515625,1859.933349609375,8308.3330078125C1859.933349609375,8312.1337890625,1865.0,8316.7333984375,1865.0,8316.7333984375C1865.0,8316.7333984375,1870.066650390625,8312.1337890625,1870.066650390625,8308.3330078125C1870.066650390625,8306.9892578125,1869.5328369140625,8305.701171875,1868.5826416015625,8304.7509765625C1867.6324462890625,8303.80078125,1866.34375,8303.2666015625,1865.0,8303.2666015625ZM1865.0,8310.1337890625C1864.005859375,8310.1337890625,1863.199951171875,8309.3271484375,1863.199951171875,8308.3330078125C1863.199951171875,8307.3388671875,1864.005859375,8306.533203125,1865.0,8306.533203125C1865.994140625,8306.533203125,1866.800048828125,8307.3388671875,1866.800048828125,8308.3330078125C1866.800048828125,8309.3271484375,1865.994140625,8310.1337890625,1865.0,8310.1337890625Z\" fill=\"#5e7a88\"/></svg>";
const SVG_7 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"7.2\" height=\"11.7\" viewBox=\"1941.7 8361.2 7.2 11.7\" fill=\"none\"><path d=\"M1943.0,8362.5L1947.5,8367.0L1943.0,8371.5\" fill=\"none\" stroke=\"#0e7a4a\" stroke-width=\"1.7\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_8 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"11.6\" height=\"15.8\" viewBox=\"1642.1 8534.9 11.6 15.8\" fill=\"none\"><path d=\"M1648.75,8542.974609375C1650.972900390625,8542.974609375,1652.7750244140625,8541.1728515625,1652.7750244140625,8538.9501953125C1652.7750244140625,8536.7265625,1650.972900390625,8534.9248046875,1648.75,8534.9248046875C1646.527099609375,8534.9248046875,1644.7249755859375,8536.7265625,1644.7249755859375,8538.9501953125C1644.7249755859375,8541.1728515625,1646.527099609375,8542.974609375,1648.75,8542.974609375ZM1648.75,8544.6376953125C1645.425048828125,8544.6376953125,1642.0999755859375,8546.2998046875,1642.0999755859375,8548.400390625L1642.0999755859375,8550.6748046875L1652.074951171875,8550.6748046875L1652.074951171875,8548.5751953125C1652.074951171875,8547.0,1652.6875,8545.599609375,1653.6500244140625,8544.900390625C1652.0447998046875,8544.5244140625,1650.3861083984375,8544.435546875,1648.75,8544.6376953125Z\" fill=\"#17a45e\"/></svg>";
const SVG_9 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"6.9\" height=\"6.9\" viewBox=\"1653.5 8544 6.9 6.9\" fill=\"none\"><path d=\"M1656.0999755859375,8544.025390625L1657.762451171875,8544.025390625L1657.762451171875,8546.650390625L1660.387451171875,8546.650390625L1660.387451171875,8548.3125L1657.762451171875,8548.3125L1657.762451171875,8550.9375L1656.0999755859375,8550.9375L1656.0999755859375,8548.3125L1653.4749755859375,8548.3125L1653.4749755859375,8546.650390625L1656.0999755859375,8546.650390625Z\" fill=\"#17a45e\"/></svg>";
const SVG_10 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"13.3\" height=\"17.7\" viewBox=\"1728.9 8534.7 13.3 17.7\" fill=\"none\"><path d=\"M1735.5,8534.662109375C1731.8272705078125,8534.662109375,1728.8499755859375,8537.6396484375,1728.8499755859375,8541.3125C1728.8499755859375,8546.2998046875,1735.5,8552.337890625,1735.5,8552.337890625C1735.5,8552.337890625,1742.1500244140625,8546.2998046875,1742.1500244140625,8541.3125C1742.1500244140625,8539.548828125,1741.4493408203125,8537.857421875,1740.2022705078125,8536.6103515625C1738.9552001953125,8535.36328125,1737.263671875,8534.662109375,1735.5,8534.662109375ZM1735.5,8543.6748046875C1734.1951904296875,8543.6748046875,1733.137451171875,8542.6171875,1733.137451171875,8541.3125C1733.137451171875,8540.0078125,1734.1951904296875,8538.9501953125,1735.5,8538.9501953125C1736.8048095703125,8538.9501953125,1737.862548828125,8540.0078125,1737.862548828125,8541.3125C1737.862548828125,8542.6171875,1736.8048095703125,8543.6748046875,1735.5,8543.6748046875Z\" fill=\"#2e7fc2\"/></svg>";
const SVG_11 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"16.4\" height=\"16.4\" viewBox=\"1811.3 8535.3 16.4 16.4\" fill=\"none\"><path d=\"M1811.2750244140625,8535.275390625L1817.4000244140625,8535.275390625L1817.4000244140625,8537.1123046875L1813.112548828125,8537.1123046875L1813.112548828125,8541.400390625L1811.2750244140625,8541.400390625ZM1821.5999755859375,8535.275390625L1827.7249755859375,8535.275390625L1827.7249755859375,8541.400390625L1825.887451171875,8541.400390625L1825.887451171875,8537.1123046875L1821.5999755859375,8537.1123046875ZM1811.2750244140625,8545.599609375L1813.112548828125,8545.599609375L1813.112548828125,8549.8876953125L1817.4000244140625,8549.8876953125L1817.4000244140625,8551.724609375L1811.2750244140625,8551.724609375ZM1825.887451171875,8545.599609375L1827.7249755859375,8545.599609375L1827.7249755859375,8551.724609375L1821.5999755859375,8551.724609375L1821.5999755859375,8549.8876953125L1825.887451171875,8549.8876953125Z\" fill=\"#3b5ea8\"/></svg>";
const SVG_12 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"16.7\" height=\"18\" viewBox=\"1896.1 8535.3 16.7 18\" fill=\"none\"><path d=\"M1896.0999755859375,8535.275390625L1899.074951171875,8535.275390625L1899.7750244140625,8538.25L1912.8125,8538.25L1910.887451171875,8545.599609375L1901.0875244140625,8545.599609375L1900.737548828125,8547.1748046875L1910.887451171875,8547.1748046875L1910.887451171875,8549.0126953125L1898.550048828125,8549.0126953125L1901.0,8538.775390625L1900.125,8537.1123046875L1896.0999755859375,8537.1123046875ZM1901.875,8549.974609375C1900.956787109375,8549.974609375,1900.2125244140625,8550.7197265625,1900.2125244140625,8551.6376953125C1900.2125244140625,8552.5556640625,1900.956787109375,8553.2998046875,1901.875,8553.2998046875C1902.793212890625,8553.2998046875,1903.5374755859375,8552.5556640625,1903.5374755859375,8551.6376953125C1903.5374755859375,8550.7197265625,1902.793212890625,8549.974609375,1901.875,8549.974609375ZM1909.2249755859375,8549.974609375C1908.306884765625,8549.974609375,1907.5625,8550.7197265625,1907.5625,8551.6376953125C1907.5625,8552.5556640625,1908.306884765625,8553.2998046875,1909.2249755859375,8553.2998046875C1910.1431884765625,8553.2998046875,1910.887451171875,8552.5556640625,1910.887451171875,8551.6376953125C1910.887451171875,8550.7197265625,1910.1431884765625,8549.974609375,1909.2249755859375,8549.974609375Z\" fill=\"#17a45e\"/></svg>";
const SVG_13 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"7.2\" height=\"11.7\" viewBox=\"1941.7 8650.2 7.2 11.7\" fill=\"none\"><path d=\"M1943.0,8651.5L1947.5,8656.0L1943.0,8660.5\" fill=\"none\" stroke=\"#0e7a4a\" stroke-width=\"1.7\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_14 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"13.8\" height=\"13.8\" viewBox=\"1918.3 8695.9 13.8 13.8\" fill=\"none\"><path d=\"M1920.949951171875,8695.9501953125L1918.25,8698.650390625C1918.25,8705.099609375,1922.9000244140625,8709.75,1929.3499755859375,8709.75L1932.050048828125,8707.0498046875L1928.5250244140625,8704.724609375L1926.7249755859375,8706.525390625C1924.763916015625,8705.5703125,1923.179443359375,8703.986328125,1922.2249755859375,8702.025390625L1924.0250244140625,8700.224609375L1920.949951171875,8695.9501953125Z\" fill=\"#17a45e\"/></svg>";
const SVG_15 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"11.4\" height=\"15.2\" viewBox=\"1919.3 8755.4 11.4 15.2\" fill=\"none\"><path d=\"M1925.0,8755.4248046875C1921.8519287109375,8755.4248046875,1919.300048828125,8757.9765625,1919.300048828125,8761.125C1919.300048828125,8765.400390625,1925.0,8770.5751953125,1925.0,8770.5751953125C1925.0,8770.5751953125,1930.699951171875,8765.400390625,1930.699951171875,8761.125C1930.699951171875,8759.61328125,1930.0994873046875,8758.1630859375,1929.030517578125,8757.0947265625C1927.9615478515625,8756.025390625,1926.51171875,8755.4248046875,1925.0,8755.4248046875ZM1925.0,8763.150390625C1923.881591796875,8763.150390625,1922.9749755859375,8762.2431640625,1922.9749755859375,8761.125C1922.9749755859375,8760.0068359375,1923.881591796875,8759.099609375,1925.0,8759.099609375C1926.118408203125,8759.099609375,1927.0250244140625,8760.0068359375,1927.0250244140625,8761.125C1927.0250244140625,8762.2431640625,1926.118408203125,8763.150390625,1925.0,8763.150390625Z\" fill=\"#17a45e\"/></svg>";
const SVG_16 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"13.8\" height=\"13.8\" viewBox=\"1918.3 8814.9 13.8 13.8\" fill=\"none\"><path d=\"M1920.949951171875,8814.9501953125L1918.25,8817.650390625C1918.25,8824.099609375,1922.9000244140625,8828.75,1929.3499755859375,8828.75L1932.050048828125,8826.0498046875L1928.5250244140625,8823.724609375L1926.7249755859375,8825.525390625C1924.763916015625,8824.5703125,1923.179443359375,8822.986328125,1922.2249755859375,8821.025390625L1924.0250244140625,8819.224609375L1920.949951171875,8814.9501953125Z\" fill=\"#17a45e\"/></svg>";
const SVG_17 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"17.9\" height=\"16.4\" viewBox=\"1635.6 8918.3 17.9 16.4\" fill=\"none\"><path d=\"M1644.5,8918.275390625L1635.574951171875,8925.7998046875L1638.199951171875,8925.7998046875L1638.199951171875,8934.724609375L1643.449951171875,8934.724609375L1643.449951171875,8929.125L1645.550048828125,8929.125L1645.550048828125,8934.724609375L1650.800048828125,8934.724609375L1650.800048828125,8925.7998046875L1653.425048828125,8925.7998046875L1644.5,8918.275390625Z\" fill=\"#17a45e\"/></svg>";
const SVG_18 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"16.6\" height=\"16.6\" viewBox=\"1703.2 8918.3 16.6 16.6\" fill=\"none\"><path d=\"M1703.1875,8918.275390625L1719.8125,8918.275390625L1719.8125,8920.2001953125L1703.1875,8920.2001953125ZM1704.675048828125,8921.4248046875L1718.324951171875,8921.4248046875L1718.324951171875,8929.650390625C1718.324951171875,8930.4716796875,1717.6590576171875,8931.1376953125,1716.8375244140625,8931.1376953125L1706.1624755859375,8931.1376953125C1705.3409423828125,8931.1376953125,1704.675048828125,8930.4716796875,1704.675048828125,8929.650390625L1704.675048828125,8921.4248046875ZM1710.625,8932.099609375L1712.375,8932.099609375L1712.375,8934.900390625L1710.625,8934.900390625Z\" fill=\"#93a9b5\"/></svg>";
const SVG_19 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"18.4\" height=\"14\" viewBox=\"1838.9 8919.5 18.4 14\" fill=\"none\"><path d=\"M1845.4375,8925.625C1847.12890625,8925.625,1848.5,8924.25390625,1848.5,8922.5625C1848.5,8920.87109375,1847.12890625,8919.5,1845.4375,8919.5C1843.74609375,8919.5,1842.375,8920.87109375,1842.375,8922.5625C1842.375,8924.25390625,1843.74609375,8925.625,1845.4375,8925.625ZM1851.5625,8925.625C1853.01220703125,8925.625,1854.1875,8924.44921875,1854.1875,8923.0C1854.1875,8921.55078125,1853.01220703125,8920.375,1851.5625,8920.375C1850.11279296875,8920.375,1848.9375,8921.55078125,1848.9375,8923.0C1848.9375,8924.44921875,1850.11279296875,8925.625,1851.5625,8925.625ZM1845.4375,8927.375C1842.8125,8927.375,1838.875,8928.775390625,1838.875,8931.3125L1838.875,8933.5L1852.0,8933.5L1852.0,8931.3125C1852.0,8928.775390625,1848.0625,8927.375,1845.4375,8927.375ZM1851.737548828125,8927.375C1850.949951171875,8927.375,1850.1624755859375,8927.462890625,1849.4625244140625,8927.6376953125C1850.6875,8928.599609375,1851.125,8929.7373046875,1851.125,8931.3125L1851.125,8933.5L1857.25,8933.5L1857.25,8931.3125C1857.25,8928.9501953125,1854.0999755859375,8927.375,1851.737548828125,8927.375Z\" fill=\"#93a9b5\"/></svg>";
const SVG_20 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"3.6\" height=\"18.2\" viewBox=\"1778.7 8907.4 3.6 18.2\" fill=\"none\"><path d=\"M1780.5,8909.2080078125L1780.5,8923.7919921875\" fill=\"none\" stroke=\"#ffffff\" stroke-width=\"2.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_21 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"18.2\" height=\"3.6\" viewBox=\"1771.4 8914.7 18.2 3.6\" fill=\"none\"><path d=\"M1773.2083740234375,8916.5L1787.7916259765625,8916.5\" fill=\"none\" stroke=\"#ffffff\" stroke-width=\"2.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";

export default function Penpot02e4BackToHome() {
  return (
    <View style={{ width: 376, height: 859, backgroundColor: "#FFFFFF", borderRadius: 34, overflow: "hidden" }}>{/* "02E.4 Back to Home" */}
      <View style={{ position: "absolute", left: 0, top: 0, width: 376, height: 859, backgroundColor: "#F4F8FA", borderRadius: 34 }} />
      <View style={{ position: "absolute", left: 0, top: 111, width: 376, height: 135 }} pointerEvents="box-none">{/* "hdr-mountains" */}
        <SvgXml xml={SVG_0} width={376} height={109.7} style={{ position: "absolute", left: 0, top: 25.3 }} />
        <SvgXml xml={SVG_1} width={376} height={75.9} style={{ position: "absolute", left: 0, top: 59.1 }} />
      </View>
      <View style={{ position: "absolute", left: 0, top: 179, width: 376, height: 78, overflow: "hidden" }}>{/* "hdr-fade" */}
        <Svg style={StyleSheet.absoluteFill} width="100%" height="100%"><Defs><LinearGradient id="g02e4backtohome0" x1="0.5" y1="0" x2="0.5" y2="1"><Stop offset={0} stopColor="#F4F8FA" stopOpacity={0} /><Stop offset={1} stopColor="#F4F8FA" stopOpacity={1} /></LinearGradient></Defs><Rect width="100%" height="100%" fill="url(#g02e4backtohome0)" /></Svg>
      </View>
      <View style={{ position: "absolute", left: 0, top: 0, width: 376, height: 260, borderTopLeftRadius: 34, borderTopRightRadius: 34, overflow: "hidden" }}>{/* "hdr-wash" */}
        <Svg style={StyleSheet.absoluteFill} width="100%" height="100%"><Defs><LinearGradient id="g02e4backtohome1" x1="0.5" y1="0" x2="0.5" y2="1"><Stop offset={0} stopColor="#FFFFFF" stopOpacity={1} /><Stop offset={1} stopColor="#FFFFFF" stopOpacity={0} /></LinearGradient></Defs><Rect width="100%" height="100%" fill="url(#g02e4backtohome1)" /></Svg>
      </View>
      <Text style={{ position: "absolute", left: 24, top: 18, width: 78, textAlign: "left", fontFamily: "PlusJakartaSans_700Bold", fontSize: 14, lineHeight: 16.8, color: "#0F3244" }}>{"9:41"}</Text>
      <View style={{ position: "absolute", left: 277, top: 18, width: 75, height: 20 }} pointerEvents="box-none">{/* "status-icons" */}
        <View style={{ position: "absolute", left: 0, top: 12.9, width: 4.3, height: 7.1, backgroundColor: "#0F3244", borderRadius: 1 }} />
        <View style={{ position: "absolute", left: 6.5, top: 9.3, width: 4.3, height: 10.7, backgroundColor: "#0F3244", borderRadius: 1 }} />
        <View style={{ position: "absolute", left: 13, top: 5.7, width: 4.3, height: 14.3, backgroundColor: "#0F3244", borderRadius: 1 }} />
        <View style={{ position: "absolute", left: 19.5, top: 2.1, width: 4.3, height: 17.9, backgroundColor: "#0F3244", borderRadius: 1 }} />
        <SvgXml xml={SVG_2} width={18.6} height={5.4} style={{ position: "absolute", left: 28.9, top: 3.8 }} />
        <SvgXml xml={SVG_3} width={11.9} height={4.4} style={{ position: "absolute", left: 32.3, top: 8.9 }} />
        <View style={{ position: "absolute", left: 36.2, top: 14.6, width: 4, height: 4, backgroundColor: "#0F3244", borderRadius: 2 }} />
        <View style={{ position: "absolute", left: 53.4, top: 4.3, width: 18.8, height: 11.4, borderRadius: 2.2, borderWidth: 1.1, borderColor: "#0F3244", opacity: 0.9 }} />
        <View style={{ position: "absolute", left: 55.7, top: 6.6, width: 12.7, height: 6.9, backgroundColor: "#0F3244", borderRadius: 1.1 }} />
        <View style={{ position: "absolute", left: 72.8, top: 8, width: 2, height: 4, backgroundColor: "#0F3244", borderRadius: 0.7 }} />
      </View>
      <Text style={{ position: "absolute", left: 22, top: 118, width: 140, textAlign: "left", fontFamily: "PlusJakartaSans_400Regular", fontSize: 12.5, lineHeight: 16.3, color: "#6B8796" }}>{"Good Morning,"}</Text>
      <Text style={{ position: "absolute", left: 22, top: 134, width: 170, textAlign: "left", fontFamily: "PlusJakartaSans_800ExtraBold", fontSize: 22, lineHeight: 28.6, color: "#0F3244" }}>{"Megala 👋"}</Text>
      <View style={{ position: "absolute", left: 289, top: 67, width: 23, height: 23 }} pointerEvents="box-none">{/* "bell" */}
        <SvgXml xml={SVG_4} width={16.1} height={19.2} style={{ position: "absolute", left: 3.4, top: 1.9 }} />
      </View>
      <View style={{ position: "absolute", left: 328, top: 59, width: 39, height: 39, borderRadius: 19.5, overflow: "hidden" }}>{/* "avatar" */}
        <Image source={require("@/assets/penpot/megala-avatar.jpg")} style={{ position: "absolute", left: 0, top: 0, width: 39, height: 39 }} resizeMode="cover" />
      </View>
      <Text style={{ position: "absolute", left: 194, top: 120, width: 160, textAlign: "right", fontFamily: "PlusJakartaSans_400Regular", fontSize: 14, lineHeight: 20.3, color: "#5E7A88" }}>{"“More conversations."}</Text>
      <Text style={{ position: "absolute", left: 194, top: 141, width: 160, textAlign: "right", fontFamily: "PlusJakartaSans_400Regular", fontSize: 14, lineHeight: 20.3, color: "#5E7A88" }}>{"More opportunities.”"}</Text>
      <View style={{ position: "absolute", left: 22, top: 195, width: 159, height: 33, backgroundColor: "#FFFFFF", borderRadius: 10, borderWidth: 1, borderColor: "#E4EDF1" }} />
      <View style={{ position: "absolute", left: 34, top: 202, width: 16, height: 16 }} pointerEvents="box-none">{/* "pill-date-ic" */}
        <SvgXml xml={SVG_5} width={12} height={13.3} style={{ position: "absolute", left: 2, top: 1.3 }} />
        <View style={{ position: "absolute", left: 4.7, top: 7.6, width: 2, height: 2, backgroundColor: "#5E7A88", borderRadius: 0.7 }} />
        <View style={{ position: "absolute", left: 7.7, top: 7.6, width: 2, height: 2, backgroundColor: "#5E7A88", borderRadius: 0.7 }} />
        <View style={{ position: "absolute", left: 10.7, top: 7.6, width: 2, height: 2, backgroundColor: "#5E7A88", borderRadius: 0.7 }} />
      </View>
      <Text style={{ position: "absolute", left: 56, top: 204, width: 124, textAlign: "left", fontFamily: "PlusJakartaSans_600SemiBold", fontSize: 12, lineHeight: 15.6, color: "#123E52" }}>{"Sun, 14 Sep 2026"}</Text>
      <View style={{ position: "absolute", left: 254, top: 195, width: 100, height: 33, backgroundColor: "#FFFFFF", borderRadius: 10, borderWidth: 1, borderColor: "#E4EDF1" }} />
      <View style={{ position: "absolute", left: 265, top: 202, width: 16, height: 16 }} pointerEvents="box-none">{/* "pill-loc-ic" */}
        <SvgXml xml={SVG_6} width={10.1} height={13.5} style={{ position: "absolute", left: 2.9, top: 1.3 }} />
      </View>
      <Text style={{ position: "absolute", left: 286, top: 204, width: 65, textAlign: "left", fontFamily: "PlusJakartaSans_600SemiBold", fontSize: 12, lineHeight: 15.6, color: "#123E52" }}>{"Chennai"}</Text>
      <Text style={{ position: "absolute", left: 22, top: 257, width: 234, textAlign: "left", fontFamily: "PlusJakartaSans_800ExtraBold", fontSize: 16, lineHeight: 20.8, color: "#0F3244" }}>{"Today's Focus"}</Text>
      <Text style={{ position: "absolute", left: 234, top: 258, width: 109, textAlign: "right", fontFamily: "PlusJakartaSans_600SemiBold", fontSize: 12, lineHeight: 15.6, color: "#0E7A4A" }}>{"View All"}</Text>
      <View style={{ position: "absolute", left: 349, top: 261, width: 8, height: 12 }} pointerEvents="box-none">{/* "vac-Today's Focus" */}
        <SvgXml xml={SVG_7} width={7.2} height={11.7} style={{ position: "absolute", left: 0.7, top: 0.2 }} />
      </View>
      <View style={{ position: "absolute", left: 22, top: 288, width: 103, height: 73, backgroundColor: "#E9F6EF", borderRadius: 13 }} />
      <Text style={{ position: "absolute", left: 22, top: 300, width: 103, textAlign: "center", fontFamily: "PlusJakartaSans_800ExtraBold", fontSize: 26, lineHeight: 32.5, color: "#0F3244" }}>{"5"}</Text>
      <Text style={{ position: "absolute", left: 22, top: 335, width: 103, textAlign: "center", fontFamily: "PlusJakartaSans_500Medium", fontSize: 12, lineHeight: 15.6, color: "#6B8796" }}>{"Follow-ups"}</Text>
      <View style={{ position: "absolute", left: 135, top: 288, width: 103, height: 73, backgroundColor: "#E9F6EF", borderRadius: 13 }} />
      <Text style={{ position: "absolute", left: 135, top: 300, width: 103, textAlign: "center", fontFamily: "PlusJakartaSans_800ExtraBold", fontSize: 26, lineHeight: 32.5, color: "#0F3244" }}>{"3"}</Text>
      <Text style={{ position: "absolute", left: 135, top: 335, width: 103, textAlign: "center", fontFamily: "PlusJakartaSans_500Medium", fontSize: 12, lineHeight: 15.6, color: "#6B8796" }}>{"Site Visits"}</Text>
      <View style={{ position: "absolute", left: 249, top: 288, width: 103, height: 73, backgroundColor: "#EBF1F8", borderRadius: 13 }} />
      <Text style={{ position: "absolute", left: 249, top: 300, width: 103, textAlign: "center", fontFamily: "PlusJakartaSans_800ExtraBold", fontSize: 26, lineHeight: 32.5, color: "#0F3244" }}>{"2"}</Text>
      <Text style={{ position: "absolute", left: 249, top: 335, width: 103, textAlign: "center", fontFamily: "PlusJakartaSans_500Medium", fontSize: 12, lineHeight: 15.6, color: "#6B8796" }}>{"Proposals"}</Text>
      <Text style={{ position: "absolute", left: 22, top: 390, width: 234, textAlign: "left", fontFamily: "PlusJakartaSans_800ExtraBold", fontSize: 16, lineHeight: 20.8, color: "#0F3244" }}>{"Quick Actions"}</Text>
      <View style={{ position: "absolute", left: 37, top: 421, width: 44, height: 44, backgroundColor: "#EDF6F1", borderRadius: 14 }} />
      <View style={{ position: "absolute", left: 48, top: 433, width: 21, height: 21 }} pointerEvents="box-none">{/* "qa-ic-0" */}
        <SvgXml xml={SVG_8} width={11.6} height={15.8} style={{ position: "absolute", left: 2.1, top: 1.9 }} />
        <SvgXml xml={SVG_9} width={6.9} height={6.9} style={{ position: "absolute", left: 13.5, top: 11 }} />
      </View>
      <Text style={{ position: "absolute", left: 18, top: 472, width: 81, textAlign: "center", fontFamily: "PlusJakartaSans_500Medium", fontSize: 11, lineHeight: 14.3, color: "#123E52" }}>{"Add Lead"}</Text>
      <View style={{ position: "absolute", left: 121, top: 421, width: 44, height: 44, backgroundColor: "#EDF6F1", borderRadius: 14 }} />
      <View style={{ position: "absolute", left: 133, top: 433, width: 21, height: 21 }} pointerEvents="box-none">{/* "qa-ic-1" */}
        <SvgXml xml={SVG_10} width={13.3} height={17.7} style={{ position: "absolute", left: 3.9, top: 1.7 }} />
      </View>
      <Text style={{ position: "absolute", left: 103, top: 472, width: 81, textAlign: "center", fontFamily: "PlusJakartaSans_500Medium", fontSize: 11, lineHeight: 14.3, color: "#123E52" }}>{"Log Visit"}</Text>
      <View style={{ position: "absolute", left: 206, top: 421, width: 44, height: 44, backgroundColor: "#EDF6F1", borderRadius: 14 }} />
      <View style={{ position: "absolute", left: 217, top: 433, width: 21, height: 21 }} pointerEvents="box-none">{/* "qa-ic-2" */}
        <View style={{ position: "absolute", left: 2.3, top: 2.3, width: 16.4, height: 16.4 }} pointerEvents="box-none">{/* "svg-g" */}
          <SvgXml xml={SVG_11} width={16.4} height={16.4} style={{ position: "absolute", left: 0, top: 0 }} />
          <View style={{ position: "absolute", left: 3.5, top: 7.3, width: 9.4, height: 1.8, backgroundColor: "#3B5EA8", borderRadius: 1 }} />
        </View>
      </View>
      <Text style={{ position: "absolute", left: 187, top: 472, width: 81, textAlign: "center", fontFamily: "PlusJakartaSans_500Medium", fontSize: 11, lineHeight: 14.3, color: "#123E52" }}>{"Scan Bill"}</Text>
      <View style={{ position: "absolute", left: 290, top: 421, width: 44, height: 44, backgroundColor: "#EDF6F1", borderRadius: 14 }} />
      <View style={{ position: "absolute", left: 302, top: 433, width: 21, height: 21 }} pointerEvents="box-none">{/* "qa-ic-3" */}
        <SvgXml xml={SVG_12} width={16.7} height={18} style={{ position: "absolute", left: 2.1, top: 2.3 }} />
      </View>
      <Text style={{ position: "absolute", left: 272, top: 472, width: 81, textAlign: "center", fontFamily: "PlusJakartaSans_500Medium", fontSize: 11, lineHeight: 14.3, color: "#123E52" }}>{"New Order"}</Text>
      <Text style={{ position: "absolute", left: 22, top: 546, width: 234, textAlign: "left", fontFamily: "PlusJakartaSans_800ExtraBold", fontSize: 16, lineHeight: 20.8, color: "#0F3244" }}>{"Upcoming Follow-ups"}</Text>
      <Text style={{ position: "absolute", left: 234, top: 547, width: 109, textAlign: "right", fontFamily: "PlusJakartaSans_600SemiBold", fontSize: 12, lineHeight: 15.6, color: "#0E7A4A" }}>{"View All"}</Text>
      <View style={{ position: "absolute", left: 349, top: 550, width: 8, height: 12 }} pointerEvents="box-none">{/* "vac-Upcoming Follow-ups" */}
        <SvgXml xml={SVG_13} width={7.2} height={11.7} style={{ position: "absolute", left: 0.7, top: 0.2 }} />
      </View>
      <View style={{ position: "absolute", left: 18, top: 577, width: 339, height: 52, backgroundColor: "#FFFFFF", borderRadius: 13, borderWidth: 1, borderColor: "#EAF0F3" }} />
      <View style={{ position: "absolute", left: 28, top: 600, width: 7, height: 7, backgroundColor: "#E5484D", borderRadius: 3.5 }} />
      <Text style={{ position: "absolute", left: 39, top: 596, width: 70, textAlign: "left", fontFamily: "PlusJakartaSans_600SemiBold", fontSize: 11, lineHeight: 14.3, color: "#E5484D" }}>{"04:00 PM"}</Text>
      <View style={{ position: "absolute", left: 115, top: 586, width: 34, height: 34, backgroundColor: "#FBE9EA", borderRadius: 9 }} />
      <Text style={{ position: "absolute", left: 115, top: 595, width: 34, textAlign: "center", fontFamily: "PlusJakartaSans_800ExtraBold", fontSize: 12, lineHeight: 15.6, color: "#C7343A" }}>{"SC"}</Text>
      <Text style={{ position: "absolute", left: 156, top: 587, width: 159, textAlign: "left", fontFamily: "PlusJakartaSans_700Bold", fontSize: 13, lineHeight: 16.9, color: "#0F3244" }}>{"Southern Auto Works"}</Text>
      <Text style={{ position: "absolute", left: 156, top: 605, width: 159, textAlign: "left", fontFamily: "PlusJakartaSans_400Regular", fontSize: 11, lineHeight: 14.3, color: "#6B8796" }}>{"Call & discuss proposal"}</Text>
      <View style={{ position: "absolute", left: 324, top: 594, width: 18, height: 18 }} pointerEvents="box-none">{/* "row-ic-0" */}
        <SvgXml xml={SVG_14} width={13.8} height={13.8} style={{ position: "absolute", left: 2.3, top: 1.9 }} />
      </View>
      <View style={{ position: "absolute", left: 18, top: 637, width: 339, height: 52, backgroundColor: "#FFFFFF", borderRadius: 13, borderWidth: 1, borderColor: "#EAF0F3" }} />
      <View style={{ position: "absolute", left: 28, top: 660, width: 7, height: 7, backgroundColor: "#F0A32B", borderRadius: 3.5 }} />
      <Text style={{ position: "absolute", left: 39, top: 656, width: 70, textAlign: "left", fontFamily: "PlusJakartaSans_600SemiBold", fontSize: 11, lineHeight: 14.3, color: "#F0A32B" }}>{"05:30 PM"}</Text>
      <View style={{ position: "absolute", left: 115, top: 646, width: 34, height: 34, backgroundColor: "#FDF3E4", borderRadius: 9 }} />
      <Text style={{ position: "absolute", left: 115, top: 655, width: 34, textAlign: "center", fontFamily: "PlusJakartaSans_800ExtraBold", fontSize: 12, lineHeight: 15.6, color: "#B77A18" }}>{"AT"}</Text>
      <Text style={{ position: "absolute", left: 156, top: 647, width: 159, textAlign: "left", fontFamily: "PlusJakartaSans_700Bold", fontSize: 13, lineHeight: 16.9, color: "#0F3244" }}>{"Anand Machine Tools"}</Text>
      <Text style={{ position: "absolute", left: 156, top: 665, width: 159, textAlign: "left", fontFamily: "PlusJakartaSans_400Regular", fontSize: 11, lineHeight: 14.3, color: "#6B8796" }}>{"Site visit confirmation"}</Text>
      <View style={{ position: "absolute", left: 324, top: 654, width: 18, height: 18 }} pointerEvents="box-none">{/* "row-ic-1" */}
        <SvgXml xml={SVG_15} width={11.4} height={15.2} style={{ position: "absolute", left: 3.3, top: 1.4 }} />
      </View>
      <View style={{ position: "absolute", left: 18, top: 696, width: 339, height: 52, backgroundColor: "#FFFFFF", borderRadius: 13, borderWidth: 1, borderColor: "#EAF0F3" }} />
      <View style={{ position: "absolute", left: 28, top: 720, width: 7, height: 7, backgroundColor: "#17A45E", borderRadius: 3.5 }} />
      <Text style={{ position: "absolute", left: 39, top: 716, width: 70, textAlign: "left", fontFamily: "PlusJakartaSans_600SemiBold", fontSize: 11, lineHeight: 14.3, color: "#17A45E" }}>{"Tomorrow"}</Text>
      <View style={{ position: "absolute", left: 115, top: 706, width: 34, height: 34, backgroundColor: "#E9F6EF", borderRadius: 9 }} />
      <Text style={{ position: "absolute", left: 115, top: 715, width: 34, textAlign: "center", fontFamily: "PlusJakartaSans_800ExtraBold", fontSize: 12, lineHeight: 15.6, color: "#0E7A4A" }}>{"KW"}</Text>
      <Text style={{ position: "absolute", left: 156, top: 707, width: 159, textAlign: "left", fontFamily: "PlusJakartaSans_700Bold", fontSize: 13, lineHeight: 16.9, color: "#0F3244" }}>{"Krishna Metal Works"}</Text>
      <Text style={{ position: "absolute", left: 156, top: 725, width: 159, textAlign: "left", fontFamily: "PlusJakartaSans_400Regular", fontSize: 11, lineHeight: 14.3, color: "#6B8796" }}>{"Follow up on payment"}</Text>
      <View style={{ position: "absolute", left: 324, top: 713, width: 18, height: 18 }} pointerEvents="box-none">{/* "row-ic-2" */}
        <SvgXml xml={SVG_16} width={13.8} height={13.8} style={{ position: "absolute", left: 2.3, top: 1.9 }} />
      </View>
      <View style={{ position: "absolute", left: 0, top: 807, width: 376, height: 52, backgroundColor: "#FFFFFF", borderBottomRightRadius: 34, borderBottomLeftRadius: 34, boxShadow: "0px -3px 14px 0px rgba(15,50,68,0.08)" }} />
      <View style={{ position: "absolute", left: 42, top: 816, width: 21, height: 21 }} pointerEvents="box-none">{/* "nav-ic-0" */}
        <SvgXml xml={SVG_17} width={17.9} height={16.4} style={{ position: "absolute", left: 1.6, top: 2.3 }} />
      </View>
      <Text style={{ position: "absolute", left: 11, top: 841, width: 83, textAlign: "center", fontFamily: "PlusJakartaSans_700Bold", fontSize: 10, lineHeight: 12.5, color: "#17A45E" }}>{"Home"}</Text>
      <View style={{ position: "absolute", left: 109, top: 816, width: 21, height: 21 }} pointerEvents="box-none">{/* "nav-ic-1" */}
        <SvgXml xml={SVG_18} width={16.6} height={16.6} style={{ position: "absolute", left: 2.2, top: 2.3 }} />
      </View>
      <Text style={{ position: "absolute", left: 78, top: 841, width: 83, textAlign: "center", fontFamily: "PlusJakartaSans_500Medium", fontSize: 10, lineHeight: 12.5, color: "#93A9B5" }}>{"Pipeline"}</Text>
      <View style={{ position: "absolute", left: 246, top: 816, width: 21, height: 21 }} pointerEvents="box-none">{/* "nav-ic-2" */}
        <SvgXml xml={SVG_19} width={18.4} height={14} style={{ position: "absolute", left: 0.9, top: 3.5 }} />
      </View>
      <Text style={{ position: "absolute", left: 215, top: 841, width: 83, textAlign: "center", fontFamily: "PlusJakartaSans_500Medium", fontSize: 10, lineHeight: 12.5, color: "#93A9B5" }}>{"Customers"}</Text>
      <View style={{ position: "absolute", left: 314, top: 816, width: 21, height: 21 }} pointerEvents="box-none">{/* "nav-ic-3" */}
        <View style={{ position: "absolute", left: 2.5, top: 8.7, width: 15.9, height: 3.7 }} pointerEvents="box-none">{/* "svg-g" */}
          <View style={{ position: "absolute", left: 0, top: 0, width: 3.7, height: 3.7, backgroundColor: "#93A9B5", borderRadius: 1.9 }} />
          <View style={{ position: "absolute", left: 6.2, top: 0, width: 3.7, height: 3.7, backgroundColor: "#93A9B5", borderRadius: 1.9 }} />
          <View style={{ position: "absolute", left: 12.3, top: 0, width: 3.7, height: 3.7, backgroundColor: "#93A9B5", borderRadius: 1.9 }} />
        </View>
      </View>
      <Text style={{ position: "absolute", left: 282, top: 841, width: 83, textAlign: "center", fontFamily: "PlusJakartaSans_500Medium", fontSize: 10, lineHeight: 12.5, color: "#93A9B5" }}>{"More"}</Text>
      <View style={{ position: "absolute", left: 161, top: 790, width: 53, height: 53, borderRadius: 26.5, overflow: "hidden", boxShadow: "0px 5px 14px 0px rgba(15,50,68,0.3)" }}>{/* "fab" */}
        <Svg style={StyleSheet.absoluteFill} width="100%" height="100%"><Defs><LinearGradient id="g02e4backtohome2" x1="0" y1="0" x2="1" y2="1"><Stop offset={0} stopColor="#1BA560" stopOpacity={1} /><Stop offset={1} stopColor="#0E7A4A" stopOpacity={1} /></LinearGradient></Defs><Rect width="100%" height="100%" fill="url(#g02e4backtohome2)" /></Svg>
      </View>
      <View style={{ position: "absolute", left: 176, top: 804, width: 25, height: 25 }} pointerEvents="box-none">{/* "fab-plus" */}
        <View style={{ position: "absolute", left: 5.2, top: 5.2, width: 14.6, height: 14.6 }} pointerEvents="box-none">{/* "svg-g" */}
          <SvgXml xml={SVG_20} width={3.6} height={18.2} style={{ position: "absolute", left: 5.5, top: -1.8 }} />
          <SvgXml xml={SVG_21} width={18.2} height={3.6} style={{ position: "absolute", left: -1.8, top: 5.5 }} />
        </View>
      </View>
      <Text style={{ position: "absolute", left: 22, top: 57, width: 170, textAlign: "left", fontFamily: "PlusJakartaSans_800ExtraBold", fontSize: 20, lineHeight: 26, letterSpacing: -0.3, color: "#17A45E" }}>{"G"}<Text style={{ color: "#0F3244" }}>{"reatSales"}</Text></Text>
      <Text style={{ position: "absolute", left: 23, top: 84, width: 170, textAlign: "left", fontFamily: "PlusJakartaSans_600SemiBold", fontSize: 10, lineHeight: 13, color: "#6B8796" }}>{"Field Sales CRM"}</Text>
      <View style={{ position: "absolute", left: 304, top: 62, width: 16, height: 16, backgroundColor: "#E5484D", borderRadius: 8, borderWidth: 1.5, borderColor: "#FFFFFF" }} />
      <Text style={{ position: "absolute", left: 304, top: 65, width: 16, textAlign: "center", fontFamily: "PlusJakartaSans_700Bold", fontSize: 9, lineHeight: 11.7, color: "#FFFFFF" }}>{"3"}</Text>
    </View>
  );
}
