/* GENERATED by tools/penpot-to-code/to-react-native.mjs from the Penpot
 * board "02E.1 Home Screen". Do not edit: regenerate with
 * `pnpm design:rn`. Its text is the board's sample copy — a design
 * reference, not a screen.
 */
import React from "react";
import { StyleSheet, View, Text, Image } from "react-native";
import Svg, { SvgXml, Defs, Rect, Stop, LinearGradient } from "react-native-svg";

export const size = { width: 376, height: 859 } as const;

const SVG_0 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"376\" height=\"109.7\" viewBox=\"356 8236.3 376 109.7\" fill=\"none\"><path d=\"M356.0,8295.375L405.439453125,8256.0L441.8685302734375,8281.3125L491.3079833984375,8236.3125L545.9515380859375,8278.5L597.9930419921875,8247.5625L647.4324951171875,8284.125L696.8719482421875,8253.1875L732.0,8278.5L732.0,8346.0L356.0,8346.0Z\" fill=\"#e6f1ec\"/></svg>";
const SVG_1 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"376\" height=\"75.9\" viewBox=\"356 8270.1 376 75.9\" fill=\"none\"><path d=\"M356.0,8315.0625L413.2457275390625,8281.3125L462.68505859375,8306.625L519.9307861328125,8270.0625L577.176513671875,8301.0L631.820068359375,8275.6875L683.861572265625,8306.625L732.0,8286.9375L732.0,8346.0L356.0,8346.0Z\" fill=\"#d8e8e1\"/></svg>";
const SVG_2 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"18.6\" height=\"5.4\" viewBox=\"661.9 8121.8 18.6 5.4\" fill=\"none\"><path d=\"M663.2884521484375,8125.85693359375C667.6153564453125,8122.28564453125,674.826904296875,8122.28564453125,679.15380859375,8125.85693359375\" fill=\"none\" stroke=\"#0f3244\" stroke-width=\"1.7\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_3 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"11.9\" height=\"4.4\" viewBox=\"665.3 8126.9 11.9 4.4\" fill=\"none\"><path d=\"M666.605712890625,8130.0C669.34619140625,8127.71435546875,673.09619140625,8127.71435546875,675.8365478515625,8130.0\" fill=\"none\" stroke=\"#0f3244\" stroke-width=\"1.7\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_4 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"16.1\" height=\"19.2\" viewBox=\"648.4 8168.9 16.1 19.2\" fill=\"none\"><path d=\"M656.5,8168.91650390625C655.6002197265625,8168.91650390625,654.870849609375,8169.64599609375,654.870849609375,8170.5458984375L654.870849609375,8171.12060546875C651.970458984375,8171.8798828125,649.9814453125,8174.54541015625,650.0792236328125,8177.54150390625L650.0792236328125,8181.56689453125L648.449951171875,8184.25L648.449951171875,8185.20849609375L664.550048828125,8185.20849609375L664.550048828125,8184.25L662.9207763671875,8181.56689453125L662.9207763671875,8177.54150390625C663.0185546875,8174.54541015625,661.029541015625,8171.8798828125,658.129150390625,8171.12060546875L658.129150390625,8170.5458984375C658.129150390625,8169.64599609375,657.3997802734375,8168.91650390625,656.5,8168.91650390625ZM656.5,8188.08349609375C657.8045654296875,8188.08740234375,658.891357421875,8187.083984375,658.99169921875,8185.783203125L654.00830078125,8185.783203125C654.108642578125,8187.083984375,655.1954345703125,8188.08740234375,656.5,8188.08349609375Z\" fill=\"#123e52\"/></svg>";
const SVG_5 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"12\" height=\"13.3\" viewBox=\"392 8303.3 12 13.3\" fill=\"none\"><path d=\"M394.6666259765625,8303.3330078125L394.6666259765625,8304.6669921875L393.6666259765625,8304.6669921875C392.7462158203125,8304.6669921875,392.0,8305.4130859375,392.0,8306.3330078125L392.0,8315.3330078125C392.0,8316.0693359375,392.596923828125,8316.6669921875,393.3333740234375,8316.6669921875L402.6666259765625,8316.6669921875C403.403076171875,8316.6669921875,404.0,8316.0693359375,404.0,8315.3330078125L404.0,8306.3330078125C404.0,8305.4130859375,403.2537841796875,8304.6669921875,402.3333740234375,8304.6669921875L401.3333740234375,8304.6669921875L401.3333740234375,8303.3330078125L400.0,8303.3330078125L400.0,8304.6669921875L396.0,8304.6669921875L396.0,8303.3330078125L394.6666259765625,8303.3330078125ZM402.6666259765625,8308.0L402.6666259765625,8315.3330078125L393.3333740234375,8315.3330078125L393.3333740234375,8308.0L402.6666259765625,8308.0Z\" fill=\"#5e7a88\"/></svg>";
const SVG_6 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"10.1\" height=\"13.5\" viewBox=\"623.9 8303.3 10.1 13.5\" fill=\"none\"><path d=\"M629.0,8303.2666015625C626.2017822265625,8303.2666015625,623.933349609375,8305.53515625,623.933349609375,8308.3330078125C623.933349609375,8312.1337890625,629.0,8316.7333984375,629.0,8316.7333984375C629.0,8316.7333984375,634.066650390625,8312.1337890625,634.066650390625,8308.3330078125C634.066650390625,8306.9892578125,633.5328369140625,8305.701171875,632.5826416015625,8304.7509765625C631.6324462890625,8303.80078125,630.34375,8303.2666015625,629.0,8303.2666015625ZM629.0,8310.1337890625C628.005859375,8310.1337890625,627.199951171875,8309.3271484375,627.199951171875,8308.3330078125C627.199951171875,8307.3388671875,628.005859375,8306.533203125,629.0,8306.533203125C629.994140625,8306.533203125,630.800048828125,8307.3388671875,630.800048828125,8308.3330078125C630.800048828125,8309.3271484375,629.994140625,8310.1337890625,629.0,8310.1337890625Z\" fill=\"#5e7a88\"/></svg>";
const SVG_7 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"7.2\" height=\"11.7\" viewBox=\"705.7 8361.2 7.2 11.7\" fill=\"none\"><path d=\"M707.0,8362.5L711.5,8367.0L707.0,8371.5\" fill=\"none\" stroke=\"#0e7a4a\" stroke-width=\"1.7\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_8 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"11.6\" height=\"15.8\" viewBox=\"406.1 8534.9 11.6 15.8\" fill=\"none\"><path d=\"M412.75,8542.974609375C414.972900390625,8542.974609375,416.7750244140625,8541.1728515625,416.7750244140625,8538.9501953125C416.7750244140625,8536.7265625,414.972900390625,8534.9248046875,412.75,8534.9248046875C410.527099609375,8534.9248046875,408.7249755859375,8536.7265625,408.7249755859375,8538.9501953125C408.7249755859375,8541.1728515625,410.527099609375,8542.974609375,412.75,8542.974609375ZM412.75,8544.6376953125C409.425048828125,8544.6376953125,406.0999755859375,8546.2998046875,406.0999755859375,8548.400390625L406.0999755859375,8550.6748046875L416.074951171875,8550.6748046875L416.074951171875,8548.5751953125C416.074951171875,8547.0,416.6875,8545.599609375,417.6500244140625,8544.900390625C416.0447998046875,8544.5244140625,414.3861083984375,8544.435546875,412.75,8544.6376953125Z\" fill=\"#17a45e\"/></svg>";
const SVG_9 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"6.9\" height=\"6.9\" viewBox=\"417.5 8544 6.9 6.9\" fill=\"none\"><path d=\"M420.0999755859375,8544.025390625L421.762451171875,8544.025390625L421.762451171875,8546.650390625L424.387451171875,8546.650390625L424.387451171875,8548.3125L421.762451171875,8548.3125L421.762451171875,8550.9375L420.0999755859375,8550.9375L420.0999755859375,8548.3125L417.4749755859375,8548.3125L417.4749755859375,8546.650390625L420.0999755859375,8546.650390625Z\" fill=\"#17a45e\"/></svg>";
const SVG_10 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"13.3\" height=\"17.7\" viewBox=\"492.9 8534.7 13.3 17.7\" fill=\"none\"><path d=\"M499.5,8534.662109375C495.8272705078125,8534.662109375,492.8499755859375,8537.6396484375,492.8499755859375,8541.3125C492.8499755859375,8546.2998046875,499.5,8552.337890625,499.5,8552.337890625C499.5,8552.337890625,506.1500244140625,8546.2998046875,506.1500244140625,8541.3125C506.1500244140625,8539.548828125,505.4493408203125,8537.857421875,504.2022705078125,8536.6103515625C502.9552001953125,8535.36328125,501.263671875,8534.662109375,499.5,8534.662109375ZM499.5,8543.6748046875C498.1951904296875,8543.6748046875,497.137451171875,8542.6171875,497.137451171875,8541.3125C497.137451171875,8540.0078125,498.1951904296875,8538.9501953125,499.5,8538.9501953125C500.8048095703125,8538.9501953125,501.862548828125,8540.0078125,501.862548828125,8541.3125C501.862548828125,8542.6171875,500.8048095703125,8543.6748046875,499.5,8543.6748046875Z\" fill=\"#2e7fc2\"/></svg>";
const SVG_11 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"16.4\" height=\"16.4\" viewBox=\"575.3 8535.3 16.4 16.4\" fill=\"none\"><path d=\"M575.2750244140625,8535.275390625L581.4000244140625,8535.275390625L581.4000244140625,8537.1123046875L577.112548828125,8537.1123046875L577.112548828125,8541.400390625L575.2750244140625,8541.400390625ZM585.5999755859375,8535.275390625L591.7249755859375,8535.275390625L591.7249755859375,8541.400390625L589.887451171875,8541.400390625L589.887451171875,8537.1123046875L585.5999755859375,8537.1123046875ZM575.2750244140625,8545.599609375L577.112548828125,8545.599609375L577.112548828125,8549.8876953125L581.4000244140625,8549.8876953125L581.4000244140625,8551.724609375L575.2750244140625,8551.724609375ZM589.887451171875,8545.599609375L591.7249755859375,8545.599609375L591.7249755859375,8551.724609375L585.5999755859375,8551.724609375L585.5999755859375,8549.8876953125L589.887451171875,8549.8876953125Z\" fill=\"#3b5ea8\"/></svg>";
const SVG_12 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"16.7\" height=\"18\" viewBox=\"660.1 8535.3 16.7 18\" fill=\"none\"><path d=\"M660.0999755859375,8535.275390625L663.074951171875,8535.275390625L663.7750244140625,8538.25L676.8125,8538.25L674.887451171875,8545.599609375L665.0875244140625,8545.599609375L664.737548828125,8547.1748046875L674.887451171875,8547.1748046875L674.887451171875,8549.0126953125L662.550048828125,8549.0126953125L665.0,8538.775390625L664.125,8537.1123046875L660.0999755859375,8537.1123046875ZM665.875,8549.974609375C664.956787109375,8549.974609375,664.2125244140625,8550.7197265625,664.2125244140625,8551.6376953125C664.2125244140625,8552.5556640625,664.956787109375,8553.2998046875,665.875,8553.2998046875C666.793212890625,8553.2998046875,667.5374755859375,8552.5556640625,667.5374755859375,8551.6376953125C667.5374755859375,8550.7197265625,666.793212890625,8549.974609375,665.875,8549.974609375ZM673.2249755859375,8549.974609375C672.306884765625,8549.974609375,671.5625,8550.7197265625,671.5625,8551.6376953125C671.5625,8552.5556640625,672.306884765625,8553.2998046875,673.2249755859375,8553.2998046875C674.1431884765625,8553.2998046875,674.887451171875,8552.5556640625,674.887451171875,8551.6376953125C674.887451171875,8550.7197265625,674.1431884765625,8549.974609375,673.2249755859375,8549.974609375Z\" fill=\"#17a45e\"/></svg>";
const SVG_13 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"7.2\" height=\"11.7\" viewBox=\"705.7 8650.2 7.2 11.7\" fill=\"none\"><path d=\"M707.0,8651.5L711.5,8656.0L707.0,8660.5\" fill=\"none\" stroke=\"#0e7a4a\" stroke-width=\"1.7\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_14 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"13.8\" height=\"13.8\" viewBox=\"682.3 8695.9 13.8 13.8\" fill=\"none\"><path d=\"M684.949951171875,8695.9501953125L682.25,8698.650390625C682.25,8705.099609375,686.9000244140625,8709.75,693.3499755859375,8709.75L696.050048828125,8707.0498046875L692.5250244140625,8704.724609375L690.7249755859375,8706.525390625C688.763916015625,8705.5703125,687.179443359375,8703.986328125,686.2249755859375,8702.025390625L688.0250244140625,8700.224609375L684.949951171875,8695.9501953125Z\" fill=\"#17a45e\"/></svg>";
const SVG_15 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"11.4\" height=\"15.2\" viewBox=\"683.3 8755.4 11.4 15.2\" fill=\"none\"><path d=\"M689.0,8755.4248046875C685.8519287109375,8755.4248046875,683.300048828125,8757.9765625,683.300048828125,8761.125C683.300048828125,8765.400390625,689.0,8770.5751953125,689.0,8770.5751953125C689.0,8770.5751953125,694.699951171875,8765.400390625,694.699951171875,8761.125C694.699951171875,8759.61328125,694.0994873046875,8758.1630859375,693.030517578125,8757.0947265625C691.9615478515625,8756.025390625,690.51171875,8755.4248046875,689.0,8755.4248046875ZM689.0,8763.150390625C687.881591796875,8763.150390625,686.9749755859375,8762.2431640625,686.9749755859375,8761.125C686.9749755859375,8760.0068359375,687.881591796875,8759.099609375,689.0,8759.099609375C690.118408203125,8759.099609375,691.0250244140625,8760.0068359375,691.0250244140625,8761.125C691.0250244140625,8762.2431640625,690.118408203125,8763.150390625,689.0,8763.150390625Z\" fill=\"#17a45e\"/></svg>";
const SVG_16 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"13.8\" height=\"13.8\" viewBox=\"682.3 8814.9 13.8 13.8\" fill=\"none\"><path d=\"M684.949951171875,8814.9501953125L682.25,8817.650390625C682.25,8824.099609375,686.9000244140625,8828.75,693.3499755859375,8828.75L696.050048828125,8826.0498046875L692.5250244140625,8823.724609375L690.7249755859375,8825.525390625C688.763916015625,8824.5703125,687.179443359375,8822.986328125,686.2249755859375,8821.025390625L688.0250244140625,8819.224609375L684.949951171875,8814.9501953125Z\" fill=\"#17a45e\"/></svg>";
const SVG_17 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"17.9\" height=\"16.4\" viewBox=\"399.6 8918.3 17.9 16.4\" fill=\"none\"><path d=\"M408.5,8918.275390625L399.574951171875,8925.7998046875L402.199951171875,8925.7998046875L402.199951171875,8934.724609375L407.449951171875,8934.724609375L407.449951171875,8929.125L409.550048828125,8929.125L409.550048828125,8934.724609375L414.800048828125,8934.724609375L414.800048828125,8925.7998046875L417.425048828125,8925.7998046875L408.5,8918.275390625Z\" fill=\"#17a45e\"/></svg>";
const SVG_18 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"16.6\" height=\"16.6\" viewBox=\"467.2 8918.3 16.6 16.6\" fill=\"none\"><path d=\"M467.1875,8918.275390625L483.8125,8918.275390625L483.8125,8920.2001953125L467.1875,8920.2001953125ZM468.675048828125,8921.4248046875L482.324951171875,8921.4248046875L482.324951171875,8929.650390625C482.324951171875,8930.4716796875,481.6590576171875,8931.1376953125,480.8375244140625,8931.1376953125L470.1624755859375,8931.1376953125C469.3409423828125,8931.1376953125,468.675048828125,8930.4716796875,468.675048828125,8929.650390625L468.675048828125,8921.4248046875ZM474.625,8932.099609375L476.375,8932.099609375L476.375,8934.900390625L474.625,8934.900390625Z\" fill=\"#93a9b5\"/></svg>";
const SVG_19 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"18.4\" height=\"14\" viewBox=\"602.9 8919.5 18.4 14\" fill=\"none\"><path d=\"M609.4375,8925.625C611.12890625,8925.625,612.5,8924.25390625,612.5,8922.5625C612.5,8920.87109375,611.12890625,8919.5,609.4375,8919.5C607.74609375,8919.5,606.375,8920.87109375,606.375,8922.5625C606.375,8924.25390625,607.74609375,8925.625,609.4375,8925.625ZM615.5625,8925.625C617.01220703125,8925.625,618.1875,8924.44921875,618.1875,8923.0C618.1875,8921.55078125,617.01220703125,8920.375,615.5625,8920.375C614.11279296875,8920.375,612.9375,8921.55078125,612.9375,8923.0C612.9375,8924.44921875,614.11279296875,8925.625,615.5625,8925.625ZM609.4375,8927.375C606.8125,8927.375,602.875,8928.775390625,602.875,8931.3125L602.875,8933.5L616.0,8933.5L616.0,8931.3125C616.0,8928.775390625,612.0625,8927.375,609.4375,8927.375ZM615.737548828125,8927.375C614.949951171875,8927.375,614.1624755859375,8927.462890625,613.4625244140625,8927.6376953125C614.6875,8928.599609375,615.125,8929.7373046875,615.125,8931.3125L615.125,8933.5L621.25,8933.5L621.25,8931.3125C621.25,8928.9501953125,618.0999755859375,8927.375,615.737548828125,8927.375Z\" fill=\"#93a9b5\"/></svg>";
const SVG_20 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"3.6\" height=\"18.2\" viewBox=\"542.7 8907.4 3.6 18.2\" fill=\"none\"><path d=\"M544.5,8909.2080078125L544.5,8923.7919921875\" fill=\"none\" stroke=\"#ffffff\" stroke-width=\"2.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_21 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"18.2\" height=\"3.6\" viewBox=\"535.4 8914.7 18.2 3.6\" fill=\"none\"><path d=\"M537.2083740234375,8916.5L551.7916259765625,8916.5\" fill=\"none\" stroke=\"#ffffff\" stroke-width=\"2.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";

export default function Penpot02e1HomeScreen() {
  return (
    <View style={{ width: 376, height: 859, backgroundColor: "#FFFFFF", borderRadius: 34, overflow: "hidden" }}>{/* "02E.1 Home Screen" */}
      <View style={{ position: "absolute", left: 0, top: 0, width: 376, height: 859, backgroundColor: "#F4F8FA", borderRadius: 34 }} />
      <View style={{ position: "absolute", left: 0, top: 111, width: 376, height: 135 }} pointerEvents="box-none">{/* "hdr-mountains" */}
        <SvgXml xml={SVG_0} width={376} height={109.7} style={{ position: "absolute", left: 0, top: 25.3 }} />
        <SvgXml xml={SVG_1} width={376} height={75.9} style={{ position: "absolute", left: 0, top: 59.1 }} />
      </View>
      <View style={{ position: "absolute", left: 0, top: 179, width: 376, height: 78, overflow: "hidden" }}>{/* "hdr-fade" */}
        <Svg style={StyleSheet.absoluteFill} width="100%" height="100%"><Defs><LinearGradient id="g02e1homescreen0" x1="0.5" y1="0" x2="0.5" y2="1"><Stop offset={0} stopColor="#F4F8FA" stopOpacity={0} /><Stop offset={1} stopColor="#F4F8FA" stopOpacity={1} /></LinearGradient></Defs><Rect width="100%" height="100%" fill="url(#g02e1homescreen0)" /></Svg>
      </View>
      <View style={{ position: "absolute", left: 0, top: 0, width: 376, height: 260, borderTopLeftRadius: 34, borderTopRightRadius: 34, overflow: "hidden" }}>{/* "hdr-wash" */}
        <Svg style={StyleSheet.absoluteFill} width="100%" height="100%"><Defs><LinearGradient id="g02e1homescreen1" x1="0.5" y1="0" x2="0.5" y2="1"><Stop offset={0} stopColor="#FFFFFF" stopOpacity={1} /><Stop offset={1} stopColor="#FFFFFF" stopOpacity={0} /></LinearGradient></Defs><Rect width="100%" height="100%" fill="url(#g02e1homescreen1)" /></Svg>
      </View>
      <Text style={{ position: "absolute", left: 24, top: 18, width: 78, textAlign: "left", fontFamily: "PlusJakartaSans_700Bold", fontSize: 14, lineHeight: 16.8, color: "#0F3244" }}>{"9:41"}</Text>
      <View style={{ position: "absolute", left: 277, top: 18, width: 75, height: 20 }} pointerEvents="box-none">{/* "status-icons" */}
        <View style={{ position: "absolute", left: 0, top: 12.9, width: 4.3, height: 7.1, backgroundColor: "#0F3244", borderRadius: 1 }} />
        <View style={{ position: "absolute", left: 6.5, top: 9.3, width: 4.3, height: 10.7, backgroundColor: "#0F3244", borderRadius: 1 }} />
        <View style={{ position: "absolute", left: 13, top: 5.7, width: 4.3, height: 14.3, backgroundColor: "#0F3244", borderRadius: 1 }} />
        <View style={{ position: "absolute", left: 19.5, top: 2.1, width: 4.3, height: 17.9, backgroundColor: "#0F3244", borderRadius: 1 }} />
        <SvgXml xml={SVG_2} width={18.6} height={5.4} style={{ position: "absolute", left: 28.9, top: 3.8 }} />
        <SvgXml xml={SVG_3} width={11.9} height={4.4} style={{ position: "absolute", left: 32.3, top: 8.9 }} />
        <View style={{ position: "absolute", left: 36.2, top: 14.6, width: 4, height: 4, backgroundColor: "#0F3244", borderRadius: 2 }} />
        <View style={{ position: "absolute", left: 53.4, top: 4.3, width: 18.8, height: 11.4, borderRadius: 2.2, borderWidth: 1.1, borderColor: "#0F3244", opacity: 0.9 }} />
        <View style={{ position: "absolute", left: 55.7, top: 6.6, width: 12.7, height: 6.9, backgroundColor: "#0F3244", borderRadius: 1.1 }} />
        <View style={{ position: "absolute", left: 72.8, top: 8, width: 2, height: 4, backgroundColor: "#0F3244", borderRadius: 0.7 }} />
      </View>
      <Text style={{ position: "absolute", left: 22, top: 118, width: 140, textAlign: "left", fontFamily: "PlusJakartaSans_400Regular", fontSize: 12.5, lineHeight: 16.3, color: "#6B8796" }}>{"Good Morning,"}</Text>
      <Text style={{ position: "absolute", left: 22, top: 134, width: 170, textAlign: "left", fontFamily: "PlusJakartaSans_800ExtraBold", fontSize: 22, lineHeight: 28.6, color: "#0F3244" }}>{"Megala 👋"}</Text>
      <View style={{ position: "absolute", left: 289, top: 67, width: 23, height: 23 }} pointerEvents="box-none">{/* "bell" */}
        <SvgXml xml={SVG_4} width={16.1} height={19.2} style={{ position: "absolute", left: 3.4, top: 1.9 }} />
      </View>
      <View style={{ position: "absolute", left: 328, top: 59, width: 39, height: 39, borderRadius: 19.5, overflow: "hidden" }}>{/* "avatar" */}
        <Image source={require("@/assets/penpot/megala-avatar.jpg")} style={{ position: "absolute", left: 0, top: 0, width: 39, height: 39 }} resizeMode="cover" />
      </View>
      <Text style={{ position: "absolute", left: 194, top: 120, width: 160, textAlign: "right", fontFamily: "PlusJakartaSans_400Regular", fontSize: 14, lineHeight: 20.3, color: "#5E7A88" }}>{"“More conversations."}</Text>
      <Text style={{ position: "absolute", left: 194, top: 141, width: 160, textAlign: "right", fontFamily: "PlusJakartaSans_400Regular", fontSize: 14, lineHeight: 20.3, color: "#5E7A88" }}>{"More opportunities.”"}</Text>
      <View style={{ position: "absolute", left: 22, top: 195, width: 159, height: 33, backgroundColor: "#FFFFFF", borderRadius: 10, borderWidth: 1, borderColor: "#E4EDF1" }} />
      <View style={{ position: "absolute", left: 34, top: 202, width: 16, height: 16 }} pointerEvents="box-none">{/* "pill-date-ic" */}
        <SvgXml xml={SVG_5} width={12} height={13.3} style={{ position: "absolute", left: 2, top: 1.3 }} />
        <View style={{ position: "absolute", left: 4.7, top: 7.6, width: 2, height: 2, backgroundColor: "#5E7A88", borderRadius: 0.7 }} />
        <View style={{ position: "absolute", left: 7.7, top: 7.6, width: 2, height: 2, backgroundColor: "#5E7A88", borderRadius: 0.7 }} />
        <View style={{ position: "absolute", left: 10.7, top: 7.6, width: 2, height: 2, backgroundColor: "#5E7A88", borderRadius: 0.7 }} />
      </View>
      <Text style={{ position: "absolute", left: 56, top: 204, width: 124, textAlign: "left", fontFamily: "PlusJakartaSans_600SemiBold", fontSize: 12, lineHeight: 15.6, color: "#123E52" }}>{"Sun, 14 Sep 2026"}</Text>
      <View style={{ position: "absolute", left: 254, top: 195, width: 100, height: 33, backgroundColor: "#FFFFFF", borderRadius: 10, borderWidth: 1, borderColor: "#E4EDF1" }} />
      <View style={{ position: "absolute", left: 265, top: 202, width: 16, height: 16 }} pointerEvents="box-none">{/* "pill-loc-ic" */}
        <SvgXml xml={SVG_6} width={10.1} height={13.5} style={{ position: "absolute", left: 2.9, top: 1.3 }} />
      </View>
      <Text style={{ position: "absolute", left: 286, top: 204, width: 65, textAlign: "left", fontFamily: "PlusJakartaSans_600SemiBold", fontSize: 12, lineHeight: 15.6, color: "#123E52" }}>{"Chennai"}</Text>
      <Text style={{ position: "absolute", left: 22, top: 257, width: 234, textAlign: "left", fontFamily: "PlusJakartaSans_800ExtraBold", fontSize: 16, lineHeight: 20.8, color: "#0F3244" }}>{"Today's Focus"}</Text>
      <Text style={{ position: "absolute", left: 234, top: 258, width: 109, textAlign: "right", fontFamily: "PlusJakartaSans_600SemiBold", fontSize: 12, lineHeight: 15.6, color: "#0E7A4A" }}>{"View All"}</Text>
      <View style={{ position: "absolute", left: 349, top: 261, width: 8, height: 12 }} pointerEvents="box-none">{/* "vac-Today's Focus" */}
        <SvgXml xml={SVG_7} width={7.2} height={11.7} style={{ position: "absolute", left: 0.7, top: 0.2 }} />
      </View>
      <View style={{ position: "absolute", left: 22, top: 288, width: 103, height: 73, backgroundColor: "#E9F6EF", borderRadius: 13 }} />
      <Text style={{ position: "absolute", left: 22, top: 300, width: 103, textAlign: "center", fontFamily: "PlusJakartaSans_800ExtraBold", fontSize: 26, lineHeight: 32.5, color: "#0F3244" }}>{"5"}</Text>
      <Text style={{ position: "absolute", left: 22, top: 335, width: 103, textAlign: "center", fontFamily: "PlusJakartaSans_500Medium", fontSize: 12, lineHeight: 15.6, color: "#6B8796" }}>{"Follow-ups"}</Text>
      <View style={{ position: "absolute", left: 135, top: 288, width: 103, height: 73, backgroundColor: "#E9F6EF", borderRadius: 13 }} />
      <Text style={{ position: "absolute", left: 135, top: 300, width: 103, textAlign: "center", fontFamily: "PlusJakartaSans_800ExtraBold", fontSize: 26, lineHeight: 32.5, color: "#0F3244" }}>{"3"}</Text>
      <Text style={{ position: "absolute", left: 135, top: 335, width: 103, textAlign: "center", fontFamily: "PlusJakartaSans_500Medium", fontSize: 12, lineHeight: 15.6, color: "#6B8796" }}>{"Site Visits"}</Text>
      <View style={{ position: "absolute", left: 249, top: 288, width: 103, height: 73, backgroundColor: "#EBF1F8", borderRadius: 13 }} />
      <Text style={{ position: "absolute", left: 249, top: 300, width: 103, textAlign: "center", fontFamily: "PlusJakartaSans_800ExtraBold", fontSize: 26, lineHeight: 32.5, color: "#0F3244" }}>{"2"}</Text>
      <Text style={{ position: "absolute", left: 249, top: 335, width: 103, textAlign: "center", fontFamily: "PlusJakartaSans_500Medium", fontSize: 12, lineHeight: 15.6, color: "#6B8796" }}>{"Proposals"}</Text>
      <Text style={{ position: "absolute", left: 22, top: 390, width: 234, textAlign: "left", fontFamily: "PlusJakartaSans_800ExtraBold", fontSize: 16, lineHeight: 20.8, color: "#0F3244" }}>{"Quick Actions"}</Text>
      <View style={{ position: "absolute", left: 37, top: 421, width: 44, height: 44, backgroundColor: "#EDF6F1", borderRadius: 14 }} />
      <View style={{ position: "absolute", left: 48, top: 433, width: 21, height: 21 }} pointerEvents="box-none">{/* "qa-ic-0" */}
        <SvgXml xml={SVG_8} width={11.6} height={15.8} style={{ position: "absolute", left: 2.1, top: 1.9 }} />
        <SvgXml xml={SVG_9} width={6.9} height={6.9} style={{ position: "absolute", left: 13.5, top: 11 }} />
      </View>
      <Text style={{ position: "absolute", left: 18, top: 472, width: 81, textAlign: "center", fontFamily: "PlusJakartaSans_500Medium", fontSize: 11, lineHeight: 14.3, color: "#123E52" }}>{"Add Lead"}</Text>
      <View style={{ position: "absolute", left: 121, top: 421, width: 44, height: 44, backgroundColor: "#EDF6F1", borderRadius: 14 }} />
      <View style={{ position: "absolute", left: 133, top: 433, width: 21, height: 21 }} pointerEvents="box-none">{/* "qa-ic-1" */}
        <SvgXml xml={SVG_10} width={13.3} height={17.7} style={{ position: "absolute", left: 3.9, top: 1.7 }} />
      </View>
      <Text style={{ position: "absolute", left: 103, top: 472, width: 81, textAlign: "center", fontFamily: "PlusJakartaSans_500Medium", fontSize: 11, lineHeight: 14.3, color: "#123E52" }}>{"Log Visit"}</Text>
      <View style={{ position: "absolute", left: 206, top: 421, width: 44, height: 44, backgroundColor: "#EDF6F1", borderRadius: 14 }} />
      <View style={{ position: "absolute", left: 217, top: 433, width: 21, height: 21 }} pointerEvents="box-none">{/* "qa-ic-2" */}
        <View style={{ position: "absolute", left: 2.3, top: 2.3, width: 16.4, height: 16.4 }} pointerEvents="box-none">{/* "svg-g" */}
          <SvgXml xml={SVG_11} width={16.4} height={16.4} style={{ position: "absolute", left: 0, top: 0 }} />
          <View style={{ position: "absolute", left: 3.5, top: 7.3, width: 9.4, height: 1.8, backgroundColor: "#3B5EA8", borderRadius: 1 }} />
        </View>
      </View>
      <Text style={{ position: "absolute", left: 187, top: 472, width: 81, textAlign: "center", fontFamily: "PlusJakartaSans_500Medium", fontSize: 11, lineHeight: 14.3, color: "#123E52" }}>{"Scan Bill"}</Text>
      <View style={{ position: "absolute", left: 290, top: 421, width: 44, height: 44, backgroundColor: "#EDF6F1", borderRadius: 14 }} />
      <View style={{ position: "absolute", left: 302, top: 433, width: 21, height: 21 }} pointerEvents="box-none">{/* "qa-ic-3" */}
        <SvgXml xml={SVG_12} width={16.7} height={18} style={{ position: "absolute", left: 2.1, top: 2.3 }} />
      </View>
      <Text style={{ position: "absolute", left: 272, top: 472, width: 81, textAlign: "center", fontFamily: "PlusJakartaSans_500Medium", fontSize: 11, lineHeight: 14.3, color: "#123E52" }}>{"New Order"}</Text>
      <Text style={{ position: "absolute", left: 22, top: 546, width: 234, textAlign: "left", fontFamily: "PlusJakartaSans_800ExtraBold", fontSize: 16, lineHeight: 20.8, color: "#0F3244" }}>{"Upcoming Follow-ups"}</Text>
      <Text style={{ position: "absolute", left: 234, top: 547, width: 109, textAlign: "right", fontFamily: "PlusJakartaSans_600SemiBold", fontSize: 12, lineHeight: 15.6, color: "#0E7A4A" }}>{"View All"}</Text>
      <View style={{ position: "absolute", left: 349, top: 550, width: 8, height: 12 }} pointerEvents="box-none">{/* "vac-Upcoming Follow-ups" */}
        <SvgXml xml={SVG_13} width={7.2} height={11.7} style={{ position: "absolute", left: 0.7, top: 0.2 }} />
      </View>
      <View style={{ position: "absolute", left: 18, top: 577, width: 339, height: 52, backgroundColor: "#FFFFFF", borderRadius: 13, borderWidth: 1, borderColor: "#EAF0F3" }} />
      <View style={{ position: "absolute", left: 28, top: 600, width: 7, height: 7, backgroundColor: "#E5484D", borderRadius: 3.5 }} />
      <Text style={{ position: "absolute", left: 39, top: 596, width: 70, textAlign: "left", fontFamily: "PlusJakartaSans_600SemiBold", fontSize: 11, lineHeight: 14.3, color: "#E5484D" }}>{"04:00 PM"}</Text>
      <View style={{ position: "absolute", left: 115, top: 586, width: 34, height: 34, backgroundColor: "#FBE9EA", borderRadius: 9 }} />
      <Text style={{ position: "absolute", left: 115, top: 595, width: 34, textAlign: "center", fontFamily: "PlusJakartaSans_800ExtraBold", fontSize: 12, lineHeight: 15.6, color: "#C7343A" }}>{"SC"}</Text>
      <Text style={{ position: "absolute", left: 156, top: 587, width: 159, textAlign: "left", fontFamily: "PlusJakartaSans_700Bold", fontSize: 13, lineHeight: 16.9, color: "#0F3244" }}>{"Southern Auto Works"}</Text>
      <Text style={{ position: "absolute", left: 156, top: 605, width: 159, textAlign: "left", fontFamily: "PlusJakartaSans_400Regular", fontSize: 11, lineHeight: 14.3, color: "#6B8796" }}>{"Call & discuss proposal"}</Text>
      <View style={{ position: "absolute", left: 324, top: 594, width: 18, height: 18 }} pointerEvents="box-none">{/* "row-ic-0" */}
        <SvgXml xml={SVG_14} width={13.8} height={13.8} style={{ position: "absolute", left: 2.3, top: 1.9 }} />
      </View>
      <View style={{ position: "absolute", left: 18, top: 637, width: 339, height: 52, backgroundColor: "#FFFFFF", borderRadius: 13, borderWidth: 1, borderColor: "#EAF0F3" }} />
      <View style={{ position: "absolute", left: 28, top: 660, width: 7, height: 7, backgroundColor: "#F0A32B", borderRadius: 3.5 }} />
      <Text style={{ position: "absolute", left: 39, top: 656, width: 70, textAlign: "left", fontFamily: "PlusJakartaSans_600SemiBold", fontSize: 11, lineHeight: 14.3, color: "#F0A32B" }}>{"05:30 PM"}</Text>
      <View style={{ position: "absolute", left: 115, top: 646, width: 34, height: 34, backgroundColor: "#FDF3E4", borderRadius: 9 }} />
      <Text style={{ position: "absolute", left: 115, top: 655, width: 34, textAlign: "center", fontFamily: "PlusJakartaSans_800ExtraBold", fontSize: 12, lineHeight: 15.6, color: "#B77A18" }}>{"AT"}</Text>
      <Text style={{ position: "absolute", left: 156, top: 647, width: 159, textAlign: "left", fontFamily: "PlusJakartaSans_700Bold", fontSize: 13, lineHeight: 16.9, color: "#0F3244" }}>{"Anand Machine Tools"}</Text>
      <Text style={{ position: "absolute", left: 156, top: 665, width: 159, textAlign: "left", fontFamily: "PlusJakartaSans_400Regular", fontSize: 11, lineHeight: 14.3, color: "#6B8796" }}>{"Site visit confirmation"}</Text>
      <View style={{ position: "absolute", left: 324, top: 654, width: 18, height: 18 }} pointerEvents="box-none">{/* "row-ic-1" */}
        <SvgXml xml={SVG_15} width={11.4} height={15.2} style={{ position: "absolute", left: 3.3, top: 1.4 }} />
      </View>
      <View style={{ position: "absolute", left: 18, top: 696, width: 339, height: 52, backgroundColor: "#FFFFFF", borderRadius: 13, borderWidth: 1, borderColor: "#EAF0F3" }} />
      <View style={{ position: "absolute", left: 28, top: 720, width: 7, height: 7, backgroundColor: "#17A45E", borderRadius: 3.5 }} />
      <Text style={{ position: "absolute", left: 39, top: 716, width: 70, textAlign: "left", fontFamily: "PlusJakartaSans_600SemiBold", fontSize: 11, lineHeight: 14.3, color: "#17A45E" }}>{"Tomorrow"}</Text>
      <View style={{ position: "absolute", left: 115, top: 706, width: 34, height: 34, backgroundColor: "#E9F6EF", borderRadius: 9 }} />
      <Text style={{ position: "absolute", left: 115, top: 715, width: 34, textAlign: "center", fontFamily: "PlusJakartaSans_800ExtraBold", fontSize: 12, lineHeight: 15.6, color: "#0E7A4A" }}>{"KW"}</Text>
      <Text style={{ position: "absolute", left: 156, top: 707, width: 159, textAlign: "left", fontFamily: "PlusJakartaSans_700Bold", fontSize: 13, lineHeight: 16.9, color: "#0F3244" }}>{"Krishna Metal Works"}</Text>
      <Text style={{ position: "absolute", left: 156, top: 725, width: 159, textAlign: "left", fontFamily: "PlusJakartaSans_400Regular", fontSize: 11, lineHeight: 14.3, color: "#6B8796" }}>{"Follow up on payment"}</Text>
      <View style={{ position: "absolute", left: 324, top: 713, width: 18, height: 18 }} pointerEvents="box-none">{/* "row-ic-2" */}
        <SvgXml xml={SVG_16} width={13.8} height={13.8} style={{ position: "absolute", left: 2.3, top: 1.9 }} />
      </View>
      <View style={{ position: "absolute", left: 0, top: 807, width: 376, height: 52, backgroundColor: "#FFFFFF", borderBottomRightRadius: 34, borderBottomLeftRadius: 34, boxShadow: "0px -3px 14px 0px rgba(15,50,68,0.08)" }} />
      <View style={{ position: "absolute", left: 42, top: 816, width: 21, height: 21 }} pointerEvents="box-none">{/* "nav-ic-0" */}
        <SvgXml xml={SVG_17} width={17.9} height={16.4} style={{ position: "absolute", left: 1.6, top: 2.3 }} />
      </View>
      <Text style={{ position: "absolute", left: 11, top: 841, width: 83, textAlign: "center", fontFamily: "PlusJakartaSans_700Bold", fontSize: 10, lineHeight: 12.5, color: "#17A45E" }}>{"Home"}</Text>
      <View style={{ position: "absolute", left: 109, top: 816, width: 21, height: 21 }} pointerEvents="box-none">{/* "nav-ic-1" */}
        <SvgXml xml={SVG_18} width={16.6} height={16.6} style={{ position: "absolute", left: 2.2, top: 2.3 }} />
      </View>
      <Text style={{ position: "absolute", left: 78, top: 841, width: 83, textAlign: "center", fontFamily: "PlusJakartaSans_500Medium", fontSize: 10, lineHeight: 12.5, color: "#93A9B5" }}>{"Pipeline"}</Text>
      <View style={{ position: "absolute", left: 246, top: 816, width: 21, height: 21 }} pointerEvents="box-none">{/* "nav-ic-2" */}
        <SvgXml xml={SVG_19} width={18.4} height={14} style={{ position: "absolute", left: 0.9, top: 3.5 }} />
      </View>
      <Text style={{ position: "absolute", left: 215, top: 841, width: 83, textAlign: "center", fontFamily: "PlusJakartaSans_500Medium", fontSize: 10, lineHeight: 12.5, color: "#93A9B5" }}>{"Customers"}</Text>
      <View style={{ position: "absolute", left: 314, top: 816, width: 21, height: 21 }} pointerEvents="box-none">{/* "nav-ic-3" */}
        <View style={{ position: "absolute", left: 2.5, top: 8.7, width: 15.9, height: 3.7 }} pointerEvents="box-none">{/* "svg-g" */}
          <View style={{ position: "absolute", left: 0, top: 0, width: 3.7, height: 3.7, backgroundColor: "#93A9B5", borderRadius: 1.9 }} />
          <View style={{ position: "absolute", left: 6.2, top: 0, width: 3.7, height: 3.7, backgroundColor: "#93A9B5", borderRadius: 1.9 }} />
          <View style={{ position: "absolute", left: 12.3, top: 0, width: 3.7, height: 3.7, backgroundColor: "#93A9B5", borderRadius: 1.9 }} />
        </View>
      </View>
      <Text style={{ position: "absolute", left: 282, top: 841, width: 83, textAlign: "center", fontFamily: "PlusJakartaSans_500Medium", fontSize: 10, lineHeight: 12.5, color: "#93A9B5" }}>{"More"}</Text>
      <View style={{ position: "absolute", left: 161, top: 790, width: 53, height: 53, borderRadius: 26.5, overflow: "hidden", boxShadow: "0px 5px 14px 0px rgba(15,50,68,0.3)" }}>{/* "fab" */}
        <Svg style={StyleSheet.absoluteFill} width="100%" height="100%"><Defs><LinearGradient id="g02e1homescreen2" x1="0" y1="0" x2="1" y2="1"><Stop offset={0} stopColor="#1BA560" stopOpacity={1} /><Stop offset={1} stopColor="#0E7A4A" stopOpacity={1} /></LinearGradient></Defs><Rect width="100%" height="100%" fill="url(#g02e1homescreen2)" /></Svg>
      </View>
      <View style={{ position: "absolute", left: 176, top: 804, width: 25, height: 25 }} pointerEvents="box-none">{/* "fab-plus" */}
        <View style={{ position: "absolute", left: 5.2, top: 5.2, width: 14.6, height: 14.6 }} pointerEvents="box-none">{/* "svg-g" */}
          <SvgXml xml={SVG_20} width={3.6} height={18.2} style={{ position: "absolute", left: 5.5, top: -1.8 }} />
          <SvgXml xml={SVG_21} width={18.2} height={3.6} style={{ position: "absolute", left: -1.8, top: 5.5 }} />
        </View>
      </View>
      <Text style={{ position: "absolute", left: 22, top: 57, width: 170, textAlign: "left", fontFamily: "PlusJakartaSans_800ExtraBold", fontSize: 20, lineHeight: 26, letterSpacing: -0.3, color: "#17A45E" }}>{"G"}<Text style={{ color: "#0F3244" }}>{"reatSales"}</Text></Text>
      <Text style={{ position: "absolute", left: 23, top: 84, width: 170, textAlign: "left", fontFamily: "PlusJakartaSans_600SemiBold", fontSize: 10, lineHeight: 13, color: "#6B8796" }}>{"Field Sales CRM"}</Text>
      <View style={{ position: "absolute", left: 304, top: 62, width: 16, height: 16, backgroundColor: "#E5484D", borderRadius: 8, borderWidth: 1.5, borderColor: "#FFFFFF" }} />
      <Text style={{ position: "absolute", left: 304, top: 65, width: 16, textAlign: "center", fontFamily: "PlusJakartaSans_700Bold", fontSize: 9, lineHeight: 11.7, color: "#FFFFFF" }}>{"3"}</Text>
    </View>
  );
}
