/* GENERATED by tools/penpot-to-code/to-react-native.mjs from the Penpot
 * board "03.2 All Stages". Do not edit: regenerate with
 * `pnpm design:rn`. Its text is the board's sample copy — a design
 * reference, not a screen.
 */
import React from "react";
import { StyleSheet, View, Text, Image } from "react-native";
import Svg, { SvgXml, Defs, Rect, Stop, LinearGradient } from "react-native-svg";

export const size = { width: 376, height: 859 } as const;

const SVG_0 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"16.2\" height=\"5.3\" viewBox=\"1069.4 9319.8 16.2 5.3\" fill=\"none\"><path d=\"M1071.0,9323.5C1074.8697509765625,9320.6650390625,1080.1302490234375,9320.6650390625,1084.0,9323.5\" fill=\"none\" stroke=\"#0f3244\" stroke-width=\"2.2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_1 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"10.2\" height=\"4.2\" viewBox=\"1072.4 9324.6 10.2 4.2\" fill=\"none\"><path d=\"M1074.0,9327.2001953125C1076.134033203125,9325.8359375,1078.865966796875,9325.8359375,1081.0,9327.2001953125\" fill=\"none\" stroke=\"#0f3244\" stroke-width=\"2.2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_2 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"9.4\" height=\"15.8\" viewBox=\"789.1 9349.1 9.4 15.8\" fill=\"none\"><path d=\"M797.0,9363.4169921875L790.5833129882812,9357.0L797.0,9350.5830078125\" fill=\"none\" stroke=\"#0f3244\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_3 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"15.8\" height=\"3\" viewBox=\"789.1 9355.5 15.8 3\" fill=\"none\"><path d=\"M803.4166870117188,9357.0L790.5833129882812,9357.0\" fill=\"none\" stroke=\"#0f3244\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" transform=\"translate(797 9357) matrix(1,0,0,0.916666666666643,-1.1368683772161603e-13,-0.000381944444458715) translate(-797 -9357)\"/></svg>";
const SVG_4 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"17.7\" height=\"19.5\" viewBox=\"1106.2 9348.2 17.7 19.5\" fill=\"none\"><path d=\"M1118.6666259765625,9349.6669921875L1120.5,9349.6669921875C1121.5125732421875,9349.6669921875,1122.3333740234375,9350.4873046875,1122.3333740234375,9351.5L1122.3333740234375,9364.3330078125C1122.3333740234375,9365.345703125,1121.5125732421875,9366.1669921875,1120.5,9366.1669921875L1109.5,9366.1669921875C1108.4874267578125,9366.1669921875,1107.6666259765625,9365.345703125,1107.6666259765625,9364.3330078125L1107.6666259765625,9351.5C1107.6666259765625,9350.4873046875,1108.4874267578125,9349.6669921875,1109.5,9349.6669921875L1111.3333740234375,9349.6669921875\" fill=\"none\" stroke=\"#17a45e\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_5 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"6.7\" height=\"3\" viewBox=\"1113.5 9354.6 6.7 3\" fill=\"none\"><path d=\"M1115.0,9356.0830078125L1118.6666259765625,9356.0830078125\" fill=\"none\" stroke=\"#17a45e\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" transform=\"translate(1116.8 9356.1) matrix(1,0,0,0.9166666666666288,-2.842170943040401e-14,-0.00038194444443506725) translate(-1116.8 -9356.1)\"/></svg>";
const SVG_6 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"6.7\" height=\"3\" viewBox=\"1113.5 9359.2 6.7 3\" fill=\"none\"><path d=\"M1115.0,9360.6669921875L1118.6666259765625,9360.6669921875\" fill=\"none\" stroke=\"#17a45e\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" transform=\"translate(1116.8 9360.7) matrix(1,0,0,0.9166666666668561,0,-0.0003819444443298181) translate(-1116.8 -9360.7)\"/></svg>";
const SVG_7 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"3\" height=\"3\" viewBox=\"1109.8 9354.6 3 3\" fill=\"none\"><path d=\"M1111.3333740234375,9356.0830078125L1111.342529296875,9356.0830078125\" fill=\"none\" stroke=\"#17a45e\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" transform=\"translate(1111.3 9356.1) matrix(0.9166876475015897,0,0,0.9166666666666572,-0.00038185701107007475,-0.0003819444399988381) translate(-1111.3 -9356.1)\"/></svg>";
const SVG_8 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"3\" height=\"3\" viewBox=\"1109.8 9359.2 3 3\" fill=\"none\"><path d=\"M1111.3333740234375,9360.6669921875L1111.342529296875,9360.6669921875\" fill=\"none\" stroke=\"#17a45e\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" transform=\"translate(1111.3 9360.7) matrix(0.9166876475016466,0,0,0.916666666666913,-0.0003818570119040743,-0.0003819444504307157) translate(-1111.3 -9360.7)\"/></svg>";
const SVG_9 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"6\" height=\"6\" viewBox=\"810.3 9403.3 6 6\" fill=\"none\"><path d=\"M814.875,9407.875L811.8291625976562,9404.8291015625\" fill=\"none\" stroke=\"#8aa3b0\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_10 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"8.8\" height=\"3\" viewBox=\"1096 9395.7 8.8 3\" fill=\"none\"><path d=\"M1103.3333740234375,9397.1669921875L1097.5,9397.1669921875\" fill=\"none\" stroke=\"#6b8796\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" transform=\"translate(1100.4 9397.2) matrix(0.9999999999999999,0,0,0.8333333333333712,8.881784197001252e-16,-0.0006944444439325181) translate(-1100.4 -9397.2)\"/></svg>";
const SVG_11 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"10.5\" height=\"3\" viewBox=\"1096 9407.3 10.5 3\" fill=\"none\"><path d=\"M1105.0,9408.8330078125L1097.5,9408.8330078125\" fill=\"none\" stroke=\"#6b8796\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" transform=\"translate(1101.3 9408.8) matrix(1,0,0,0.8333333333334849,0,-0.0006944444442922304) translate(-1101.3 -9408.8)\"/></svg>";
const SVG_12 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"3\" height=\"6.3\" viewBox=\"1105.2 9394 3 6.3\" fill=\"none\"><path d=\"M1106.6666259765625,9395.5L1106.6666259765625,9398.8330078125\" fill=\"none\" stroke=\"#6b8796\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" transform=\"translate(1106.7 9397.2) matrix(0.8333333333333144,0,0,1.0000000000000042,-0.0006944444444456632,2.7533531010703882e-14) translate(-1106.7 -9397.2)\"/></svg>";
const SVG_13 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"3\" height=\"6.3\" viewBox=\"1106.8 9405.7 3 6.3\" fill=\"none\"><path d=\"M1108.3333740234375,9407.1669921875L1108.3333740234375,9410.5\" fill=\"none\" stroke=\"#6b8796\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" transform=\"translate(1108.3 9408.8) matrix(0.8333333333334849,0,0,1.0000000000000044,-0.0006944444444518805,-3.68594044175552e-14) translate(-1108.3 -9408.8)\"/></svg>";
const SVG_14 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"10.5\" height=\"3\" viewBox=\"1103.5 9401.5 10.5 3\" fill=\"none\"><path d=\"M1112.5,9403.0L1105.0,9403.0\" fill=\"none\" stroke=\"#6b8796\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" transform=\"translate(1108.8 9403) matrix(1,0,0,0.8333333333333144,-5.684341886080802e-14,-0.0006944444445013964) translate(-1108.8 -9403)\"/></svg>";
const SVG_15 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"7.2\" height=\"3\" viewBox=\"1106.8 9407.3 7.2 3\" fill=\"none\"><path d=\"M1112.5,9408.8330078125L1108.3333740234375,9408.8330078125\" fill=\"none\" stroke=\"#6b8796\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" transform=\"translate(1110.4 9408.8) matrix(1.0000000000000002,0,0,0.8333333333334849,1.7141843500212417e-13,-0.0006944444442922304) translate(-1110.4 -9408.8)\"/></svg>";
const SVG_16 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"8.8\" height=\"3\" viewBox=\"1105.2 9395.7 8.8 3\" fill=\"none\"><path d=\"M1112.5,9397.1669921875L1106.6666259765625,9397.1669921875\" fill=\"none\" stroke=\"#6b8796\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" transform=\"translate(1109.6 9397.2) matrix(1,0,0,0.8333333333333712,0,-0.0006944444448420128) translate(-1109.6 -9397.2)\"/></svg>";
const SVG_17 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"3\" height=\"6.3\" viewBox=\"1100.2 9399.8 3 6.3\" fill=\"none\"><path d=\"M1101.6666259765625,9401.3330078125L1101.6666259765625,9404.6669921875\" fill=\"none\" stroke=\"#6b8796\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" transform=\"translate(1101.7 9403) matrix(0.8333333333334849,0,0,1.0000000000000355,-0.0006944444456120635,-4.4719783431901305e-13) translate(-1101.7 -9403)\"/></svg>";
const SVG_18 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"7.2\" height=\"3\" viewBox=\"1096 9401.5 7.2 3\" fill=\"none\"><path d=\"M1101.6666259765625,9403.0L1097.5,9403.0\" fill=\"none\" stroke=\"#6b8796\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" transform=\"translate(1099.6 9403) matrix(1,0,0,0.8333333333333144,-2.2737367544323206e-13,-0.000694444444444553) translate(-1099.6 -9403)\"/></svg>";
const SVG_19 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"14.7\" height=\"3\" viewBox=\"810.7 9471.5 14.7 3\" fill=\"none\"><path d=\"M812.1666870117188,9473.0L823.8333129882812,9473.0\" fill=\"none\" stroke=\"#2e76d6\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" transform=\"translate(818 9473) matrix(1,0,0,0.8333333333333144,0,-0.0006944444445013964) translate(-818 -9473)\"/></svg>";
const SVG_20 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"3\" height=\"14.7\" viewBox=\"816.5 9465.7 3 14.7\" fill=\"none\"><path d=\"M818.0,9467.1669921875L818.0,9478.8330078125\" fill=\"none\" stroke=\"#2e76d6\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" transform=\"translate(818 9473) matrix(0.8333333333333144,0,0,0.9999999999999969,-0.0006944444444227926,-7.283063041541027e-14) translate(-818 -9473)\"/></svg>";
const SVG_21 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"6.5\" height=\"10\" viewBox=\"1107.8 9468 6.5 10\" fill=\"none\"><path d=\"M1109.25,9476.5L1112.75,9473.0L1109.25,9469.5\" fill=\"none\" stroke=\"#8aa3b0\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_22 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"19.7\" height=\"19.7\" viewBox=\"808.2 9533.2 19.7 19.7\" fill=\"none\"><path d=\"M819.5266723632812,9546.806640625C819.8811645507812,9546.9697265625,820.3012084960938,9546.8642578125,820.5374755859375,9546.5537109375L820.8333129882812,9546.1669921875C821.1480712890625,9545.7470703125,821.64208984375,9545.5,822.1666870117188,9545.5L824.6666870117188,9545.5C825.587158203125,9545.5,826.3333129882812,9546.24609375,826.3333129882812,9547.1669921875L826.3333129882812,9549.6669921875C826.3333129882812,9550.5869140625,825.587158203125,9551.3330078125,824.6666870117188,9551.3330078125C816.3823852539062,9551.3330078125,809.6666870117188,9544.6171875,809.6666870117188,9536.3330078125C809.6666870117188,9535.4130859375,810.412841796875,9534.6669921875,811.3333129882812,9534.6669921875L813.8333129882812,9534.6669921875C814.7537841796875,9534.6669921875,815.5,9535.4130859375,815.5,9536.3330078125L815.5,9538.8330078125C815.5,9539.3583984375,815.2529907226562,9539.8515625,814.8333129882812,9540.1669921875L814.443359375,9540.458984375C814.1278686523438,9540.7001953125,814.0260620117188,9541.1298828125,814.2000122070312,9541.486328125C815.3389282226562,9543.7998046875,817.2120361328125,9545.6708984375,819.5266723632812,9546.806640625\" fill=\"none\" stroke=\"#0e7a4a\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_23 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"6.5\" height=\"10\" viewBox=\"1107.8 9538 6.5 10\" fill=\"none\"><path d=\"M1109.25,9546.5L1112.75,9543.0L1109.25,9539.5\" fill=\"none\" stroke=\"#8aa3b0\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_24 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"16.3\" height=\"19.7\" viewBox=\"809.8 9603.2 16.3 19.7\" fill=\"none\"><path d=\"M820.5,9604.6669921875L813.0,9604.6669921875C812.0795288085938,9604.6669921875,811.3333129882812,9605.4130859375,811.3333129882812,9606.3330078125L811.3333129882812,9619.6669921875C811.3333129882812,9620.5869140625,812.0795288085938,9621.3330078125,813.0,9621.3330078125L823.0,9621.3330078125C823.9204711914062,9621.3330078125,824.6666870117188,9620.5869140625,824.6666870117188,9619.6669921875L824.6666870117188,9608.8330078125L820.5,9604.6669921875\" fill=\"none\" stroke=\"#c97a09\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_25 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"8\" height=\"8\" viewBox=\"818.2 9603.2 8 8\" fill=\"none\"><path d=\"M819.6666870117188,9604.6669921875L819.6666870117188,9608.0C819.6666870117188,9608.9208984375,820.412841796875,9609.6669921875,821.3333129882812,9609.6669921875L824.6666870117188,9609.6669921875\" fill=\"none\" stroke=\"#c97a09\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_26 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"9.7\" height=\"3\" viewBox=\"813.2 9612.3 9.7 3\" fill=\"none\"><path d=\"M821.3333129882812,9613.8330078125L814.6666870117188,9613.8330078125\" fill=\"none\" stroke=\"#c97a09\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" transform=\"translate(818 9613.8) matrix(0.9999999999999999,0,0,0.8333333333333144,2.220446049250313e-16,-0.0006944444444634268) translate(-818 -9613.8)\"/></svg>";
const SVG_27 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"9.7\" height=\"3\" viewBox=\"813.2 9615.7 9.7 3\" fill=\"none\"><path d=\"M821.3333129882812,9617.1669921875L814.6666870117188,9617.1669921875\" fill=\"none\" stroke=\"#c97a09\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" transform=\"translate(818 9617.2) matrix(0.9999999999999999,0,0,0.8333333333334849,2.220446049250313e-16,-0.0006944444445386999) translate(-818 -9617.2)\"/></svg>";
const SVG_28 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"4.7\" height=\"3\" viewBox=\"813.2 9609 4.7 3\" fill=\"none\"><path d=\"M816.3333129882812,9610.5L814.6666870117188,9610.5\" fill=\"none\" stroke=\"#c97a09\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" transform=\"translate(815.5 9610.5) matrix(1,0,0,0.8333333333333144,-9.094947017729282e-13,-0.0006944444450414089) translate(-815.5 -9610.5)\"/></svg>";
const SVG_29 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"6.5\" height=\"10\" viewBox=\"1107.8 9608 6.5 10\" fill=\"none\"><path d=\"M1109.25,9616.5L1112.75,9613.0L1109.25,9609.5\" fill=\"none\" stroke=\"#8aa3b0\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_30 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"14.7\" height=\"8\" viewBox=\"808.2 9684 14.7 8\" fill=\"none\"><path d=\"M821.3333129882812,9690.5L821.3333129882812,9688.8330078125C821.3333129882812,9686.9921875,819.8409423828125,9685.5,818.0,9685.5L813.0,9685.5C811.1590576171875,9685.5,809.6666870117188,9686.9921875,809.6666870117188,9688.8330078125L809.6666870117188,9690.5\" fill=\"none\" stroke=\"#4b7c93\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_31 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"5.5\" height=\"7.9\" viewBox=\"822.3 9684.1 5.5 7.9\" fill=\"none\"><path d=\"M826.3333129882812,9690.5L826.3333129882812,9688.8330078125C826.3322143554688,9687.314453125,825.3041381835938,9685.98828125,823.8333129882812,9685.6083984375\" fill=\"none\" stroke=\"#4b7c93\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_32 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"5.5\" height=\"9.5\" viewBox=\"819.8 9674.1 5.5 9.5\" fill=\"none\"><path d=\"M821.3333129882812,9675.6083984375C822.8082885742188,9675.986328125,823.83984375,9677.3154296875,823.83984375,9678.837890625C823.83984375,9680.3603515625,822.8082885742188,9681.689453125,821.3333129882812,9682.06640625\" fill=\"none\" stroke=\"#4b7c93\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_33 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"6.5\" height=\"10\" viewBox=\"1107.8 9678 6.5 10\" fill=\"none\"><path d=\"M1109.25,9686.5L1112.75,9683.0L1109.25,9679.5\" fill=\"none\" stroke=\"#8aa3b0\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_34 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"6.3\" height=\"7.2\" viewBox=\"808.2 9744.8 6.3 7.2\" fill=\"none\"><path d=\"M813.0,9750.5L811.75,9750.5C810.5994262695312,9750.5,809.6666870117188,9749.5673828125,809.6666870117188,9748.4169921875C809.6666870117188,9747.265625,810.5994262695312,9746.3330078125,811.75,9746.3330078125L813.0,9746.3330078125\" fill=\"none\" stroke=\"#0e7a4a\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_35 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"6.3\" height=\"7.2\" viewBox=\"821.5 9744.8 6.3 7.2\" fill=\"none\"><path d=\"M823.0,9750.5L824.25,9750.5C825.4005737304688,9750.5,826.3333129882812,9749.5673828125,826.3333129882812,9748.4169921875C826.3333129882812,9747.265625,825.4005737304688,9746.3330078125,824.25,9746.3330078125L823.0,9746.3330078125\" fill=\"none\" stroke=\"#0e7a4a\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_36 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"16.3\" height=\"3\" viewBox=\"809.8 9759.8 16.3 3\" fill=\"none\"><path d=\"M811.3333129882812,9761.3330078125L824.6666870117188,9761.3330078125\" fill=\"none\" stroke=\"#0e7a4a\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" transform=\"translate(818 9761.3) matrix(0.9999999999999998,0,0,0.8333333333334849,-9.090506125630782e-13,-0.0006944444433827357) translate(-818 -9761.3)\"/></svg>";
const SVG_37 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"5.5\" height=\"9.1\" viewBox=\"812.3 9753.7 5.5 9.1\" fill=\"none\"><path d=\"M816.3333129882812,9755.216796875L816.3333129882812,9757.1669921875C816.3333129882812,9757.625,815.941650390625,9757.9833984375,815.5250244140625,9758.1748046875C814.5416870117188,9758.625,813.8333129882812,9759.8662109375,813.8333129882812,9761.3330078125\" fill=\"none\" stroke=\"#0e7a4a\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_38 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"5.5\" height=\"9.1\" viewBox=\"818.2 9753.7 5.5 9.1\" fill=\"none\"><path d=\"M819.6666870117188,9755.216796875L819.6666870117188,9757.1669921875C819.6666870117188,9757.625,820.058349609375,9757.9833984375,820.4749755859375,9758.1748046875C821.4583129882812,9758.625,822.1666870117188,9759.8662109375,822.1666870117188,9761.3330078125\" fill=\"none\" stroke=\"#0e7a4a\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_39 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"13\" height=\"13.8\" viewBox=\"811.5 9743.2 13 13.8\" fill=\"none\"><path d=\"M823.0,9744.6669921875L813.0,9744.6669921875L813.0,9750.5C813.0,9753.26171875,815.2385864257812,9755.5,818.0,9755.5C820.7614135742188,9755.5,823.0,9753.26171875,823.0,9750.5L823.0,9744.6669921875L823.0,9744.6669921875\" fill=\"none\" stroke=\"#0e7a4a\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_40 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"6.5\" height=\"10\" viewBox=\"1107.8 9748 6.5 10\" fill=\"none\"><path d=\"M1109.25,9756.5L1112.75,9753.0L1109.25,9749.5\" fill=\"none\" stroke=\"#8aa3b0\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_41 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"8\" height=\"8\" viewBox=\"814 9819 8 8\" fill=\"none\"><path d=\"M820.5,9820.5L815.5,9825.5\" fill=\"none\" stroke=\"#e5484d\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_42 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"8\" height=\"8\" viewBox=\"814 9819 8 8\" fill=\"none\"><path d=\"M815.5,9820.5L820.5,9825.5\" fill=\"none\" stroke=\"#e5484d\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_43 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"6.5\" height=\"10\" viewBox=\"1107.8 9818 6.5 10\" fill=\"none\"><path d=\"M1109.25,9826.5L1112.75,9823.0L1109.25,9819.5\" fill=\"none\" stroke=\"#8aa3b0\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_44 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"8.3\" height=\"10.9\" viewBox=\"816.4 10126 8.3 10.9\" fill=\"none\"><path d=\"M823.125,10135.375L823.125,10128.375C823.125,10127.8916015625,822.7332763671875,10127.5,822.25,10127.5L818.75,10127.5C818.2667236328125,10127.5,817.875,10127.8916015625,817.875,10128.375L817.875,10135.375\" fill=\"none\" stroke=\"#8aa3b0\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_45 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"18.8\" height=\"19.6\" viewBox=\"811.1 10117.3 18.8 19.6\" fill=\"none\"><path d=\"M812.625,10125.75C812.6248779296875,10125.234375,812.851806640625,10124.7451171875,813.245361328125,10124.4130859375L819.370361328125,10119.1640625C820.0225830078125,10118.6123046875,820.9774169921875,10118.6123046875,821.629638671875,10119.1640625L827.754638671875,10124.4130859375C828.148193359375,10124.7451171875,828.3751220703125,10125.234375,828.375,10125.75L828.375,10133.625C828.375,10134.591796875,827.5914916992188,10135.375,826.625,10135.375L814.375,10135.375C813.4085083007812,10135.375,812.625,10134.591796875,812.625,10133.625L812.625,10125.75\" fill=\"none\" stroke=\"#8aa3b0\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_46 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"15.3\" height=\"8.3\" viewBox=\"1014.3 10128.6 15.3 8.3\" fill=\"none\"><path d=\"M1028.0,10135.375L1028.0,10133.625C1028.0,10131.6923828125,1026.4329833984375,10130.125,1024.5,10130.125L1019.25,10130.125C1017.3170166015625,10130.125,1015.75,10131.6923828125,1015.75,10133.625L1015.75,10135.375\" fill=\"none\" stroke=\"#8aa3b0\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_47 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"5.6\" height=\"8.1\" viewBox=\"1029.1 10128.7 5.6 8.1\" fill=\"none\"><path d=\"M1033.25,10135.375L1033.25,10133.625C1033.248779296875,10132.0302734375,1032.16943359375,10130.6376953125,1030.625,10130.23828125\" fill=\"none\" stroke=\"#8aa3b0\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_48 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"5.6\" height=\"9.8\" viewBox=\"1026.5 10118.2 5.6 9.8\" fill=\"none\"><path d=\"M1028.0,10119.73828125C1029.5487060546875,10120.1357421875,1030.6318359375,10121.5302734375,1030.6318359375,10123.12890625C1030.6318359375,10124.7275390625,1029.5487060546875,10126.123046875,1028.0,10126.51953125\" fill=\"none\" stroke=\"#8aa3b0\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_49 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"18\" height=\"3.4\" viewBox=\"946.5 10114.8 18 3.4\" fill=\"none\"><path d=\"M948.2083129882812,10116.5L962.7916870117188,10116.5\" fill=\"none\" stroke=\"#ffffff\" stroke-width=\"2.4\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_50 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"3.4\" height=\"18\" viewBox=\"953.8 10107.5 3.4 18\" fill=\"none\"><path d=\"M955.5,10109.2080078125L955.5,10123.7919921875\" fill=\"none\" stroke=\"#ffffff\" stroke-width=\"2.4\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";

export default function Penpot032AllStages() {
  return (
    <View style={{ width: 376, height: 859, backgroundColor: "#F8FBFC", borderRadius: 34, overflow: "hidden" }}>{/* "03.2 All Stages" */}
      <Text style={{ position: "absolute", left: 24, top: 11, width: 78, textAlign: "left", fontFamily: "PlusJakartaSans_700Bold", fontSize: 14, lineHeight: 18.9, color: "#0F3244" }}>{"9:41"}</Text>
      <View style={{ position: "absolute", left: 277, top: 16, width: 75, height: 20 }} pointerEvents="box-none">{/* "status-icons" */}
        <View style={{ position: "absolute", left: 0, top: 12, width: 3.5, height: 5, backgroundColor: "#0F3244", borderRadius: 1 }} />
        <View style={{ position: "absolute", left: 5.5, top: 9, width: 3.5, height: 8, backgroundColor: "#0F3244", borderRadius: 1 }} />
        <View style={{ position: "absolute", left: 11, top: 5.5, width: 3.5, height: 11.5, backgroundColor: "#0F3244", borderRadius: 1 }} />
        <View style={{ position: "absolute", left: 16.5, top: 2, width: 3.5, height: 15, backgroundColor: "#0F3244", borderRadius: 1 }} />
        <SvgXml xml={SVG_0} width={16.2} height={5.3} style={{ position: "absolute", left: 24.4, top: 3.8 }} />
        <SvgXml xml={SVG_1} width={10.2} height={4.2} style={{ position: "absolute", left: 27.4, top: 8.6 }} />
        <View style={{ position: "absolute", left: 30.7, top: 13.4, width: 3.6, height: 3.6, backgroundColor: "#0F3244", borderRadius: 1.8 }} />
        <View style={{ position: "absolute", left: 47, top: 4.5, width: 24, height: 12, borderRadius: 3.5, borderWidth: 1.6, borderColor: "#0F3244" }} />
        <View style={{ position: "absolute", left: 49.5, top: 7, width: 17, height: 7, backgroundColor: "#0F3244", borderRadius: 2 }} />
        <View style={{ position: "absolute", left: 72, top: 8, width: 2.5, height: 5, backgroundColor: "#0F3244", borderRadius: 1.2 }} />
      </View>
      <View style={{ position: "absolute", left: 18, top: 46, width: 22, height: 22 }} pointerEvents="box-none">{/* "ic-arrow-left" */}
        <SvgXml xml={SVG_2} width={9.4} height={15.8} style={{ position: "absolute", left: 3.1, top: 3.1 }} />
        <SvgXml xml={SVG_3} width={15.8} height={3} style={{ position: "absolute", left: 3.1, top: 9.5 }} />
      </View>
      <Text style={{ position: "absolute", left: 60, top: 48, width: 256, textAlign: "center", fontFamily: "PlusJakartaSans_700Bold", fontSize: 16, lineHeight: 21.6, color: "#0F3244" }}>{"Pipeline"}</Text>
      <View style={{ position: "absolute", left: 336, top: 46, width: 22, height: 22 }} pointerEvents="box-none">{/* "ic-clipboard-list" */}
        <View style={{ position: "absolute", left: 7.3, top: 1.8, width: 7.3, height: 3.7, borderRadius: 1, borderWidth: 2, borderColor: "#17A45E" }} />
        <SvgXml xml={SVG_4} width={17.7} height={19.5} style={{ position: "absolute", left: 2.2, top: 2.2 }} />
        <SvgXml xml={SVG_5} width={6.7} height={3} style={{ position: "absolute", left: 9.5, top: 8.6 }} />
        <SvgXml xml={SVG_6} width={6.7} height={3} style={{ position: "absolute", left: 9.5, top: 13.2 }} />
        <SvgXml xml={SVG_7} width={3} height={3} style={{ position: "absolute", left: 5.8, top: 8.6 }} />
        <SvgXml xml={SVG_8} width={3} height={3} style={{ position: "absolute", left: 5.8, top: 13.2 }} />
      </View>
      <View style={{ position: "absolute", left: 18, top: 82, width: 288, height: 40, backgroundColor: "#EFF5F8", borderRadius: 12, borderWidth: 1, borderColor: "#E6EFF3" }} />
      <View style={{ position: "absolute", left: 32, top: 93, width: 17, height: 17 }} pointerEvents="box-none">{/* "ic-search" */}
        <View style={{ position: "absolute", left: 2.1, top: 2.1, width: 11.3, height: 11.3, borderRadius: 5.7, borderWidth: 2, borderColor: "#8AA3B0" }} />
        <SvgXml xml={SVG_9} width={6} height={6} style={{ position: "absolute", left: 10.3, top: 10.3 }} />
      </View>
      <Text style={{ position: "absolute", left: 58, top: 94, width: 236, textAlign: "left", fontFamily: "PlusJakartaSans_500Medium", fontSize: 12, lineHeight: 16.2, color: "#93A9B5" }}>{"Search opportunities..."}</Text>
      <View style={{ position: "absolute", left: 316, top: 82, width: 42, height: 40, backgroundColor: "#FFFFFF", borderRadius: 12, borderWidth: 1, borderColor: "#E6EFF3" }} />
      <View style={{ position: "absolute", left: 327, top: 93, width: 20, height: 20 }} pointerEvents="box-none">{/* "ic-sliders-horizontal" */}
        <SvgXml xml={SVG_10} width={8.8} height={3} style={{ position: "absolute", left: 1, top: 2.7 }} />
        <SvgXml xml={SVG_11} width={10.5} height={3} style={{ position: "absolute", left: 1, top: 14.3 }} />
        <SvgXml xml={SVG_12} width={3} height={6.3} style={{ position: "absolute", left: 10.2, top: 1 }} />
        <SvgXml xml={SVG_13} width={3} height={6.3} style={{ position: "absolute", left: 11.8, top: 12.7 }} />
        <SvgXml xml={SVG_14} width={10.5} height={3} style={{ position: "absolute", left: 8.5, top: 8.5 }} />
        <SvgXml xml={SVG_15} width={7.2} height={3} style={{ position: "absolute", left: 11.8, top: 14.3 }} />
        <SvgXml xml={SVG_16} width={8.8} height={3} style={{ position: "absolute", left: 10.2, top: 2.7 }} />
        <SvgXml xml={SVG_17} width={3} height={6.3} style={{ position: "absolute", left: 5.2, top: 6.8 }} />
        <SvgXml xml={SVG_18} width={7.2} height={3} style={{ position: "absolute", left: 1, top: 8.5 }} />
      </View>
      <View style={{ position: "absolute", left: 18, top: 142, width: 340, height: 62, backgroundColor: "#FFFFFF", borderRadius: 14, borderWidth: 1, borderColor: "#E6EFF3", boxShadow: "0px 2px 8px 0px rgba(15,50,68,0.05)" }} />
      <View style={{ position: "absolute", left: 30, top: 153, width: 40, height: 40, backgroundColor: "#EAF2FC", borderRadius: 12 }} />
      <View style={{ position: "absolute", left: 40, top: 163, width: 20, height: 20 }} pointerEvents="box-none">{/* "ic-plus" */}
        <SvgXml xml={SVG_19} width={14.7} height={3} style={{ position: "absolute", left: 2.7, top: 8.5 }} />
        <SvgXml xml={SVG_20} width={3} height={14.7} style={{ position: "absolute", left: 8.5, top: 2.7 }} />
      </View>
      <Text style={{ position: "absolute", left: 84, top: 155, width: 150, textAlign: "left", fontFamily: "PlusJakartaSans_700Bold", fontSize: 13, lineHeight: 17.6, color: "#0F3244" }}>{"New Lead"}</Text>
      <Text style={{ position: "absolute", left: 84, top: 173, width: 160, textAlign: "left", fontFamily: "PlusJakartaSans_500Medium", fontSize: 11, lineHeight: 14.9, color: "#6B8796" }}>{"6 opportunities"}</Text>
      <Text style={{ position: "absolute", left: 240, top: 163, width: 90, textAlign: "right", fontFamily: "PlusJakartaSans_800ExtraBold", fontSize: 13, lineHeight: 17.6, color: "#0F3244" }}>{"₹ 9.4L"}</Text>
      <View style={{ position: "absolute", left: 336, top: 166, width: 14, height: 14 }} pointerEvents="box-none">{/* "ic-chevron-right" */}
        <SvgXml xml={SVG_21} width={6.5} height={10} style={{ position: "absolute", left: 3.8, top: 2 }} />
      </View>
      <View style={{ position: "absolute", left: 18, top: 212, width: 340, height: 62, backgroundColor: "#FFFFFF", borderRadius: 14, borderWidth: 1, borderColor: "#E6EFF3", boxShadow: "0px 2px 8px 0px rgba(15,50,68,0.05)" }} />
      <View style={{ position: "absolute", left: 30, top: 223, width: 40, height: 40, backgroundColor: "#E8F6EE", borderRadius: 12 }} />
      <View style={{ position: "absolute", left: 40, top: 233, width: 20, height: 20 }} pointerEvents="box-none">{/* "ic-phone" */}
        <SvgXml xml={SVG_22} width={19.7} height={19.7} style={{ position: "absolute", left: 0.2, top: 0.2 }} />
      </View>
      <Text style={{ position: "absolute", left: 84, top: 225, width: 150, textAlign: "left", fontFamily: "PlusJakartaSans_700Bold", fontSize: 13, lineHeight: 17.6, color: "#0F3244" }}>{"Contacted"}</Text>
      <Text style={{ position: "absolute", left: 84, top: 243, width: 160, textAlign: "left", fontFamily: "PlusJakartaSans_500Medium", fontSize: 11, lineHeight: 14.9, color: "#6B8796" }}>{"5 opportunities"}</Text>
      <Text style={{ position: "absolute", left: 240, top: 233, width: 90, textAlign: "right", fontFamily: "PlusJakartaSans_800ExtraBold", fontSize: 13, lineHeight: 17.6, color: "#0F3244" }}>{"₹ 8.6L"}</Text>
      <View style={{ position: "absolute", left: 336, top: 236, width: 14, height: 14 }} pointerEvents="box-none">{/* "ic-chevron-right" */}
        <SvgXml xml={SVG_23} width={6.5} height={10} style={{ position: "absolute", left: 3.8, top: 2 }} />
      </View>
      <View style={{ position: "absolute", left: 18, top: 282, width: 340, height: 62, backgroundColor: "#FFFFFF", borderRadius: 14, borderWidth: 1, borderColor: "#E6EFF3", boxShadow: "0px 2px 8px 0px rgba(15,50,68,0.05)" }} />
      <View style={{ position: "absolute", left: 30, top: 293, width: 40, height: 40, backgroundColor: "#FDF0E0", borderRadius: 12 }} />
      <View style={{ position: "absolute", left: 40, top: 303, width: 20, height: 20 }} pointerEvents="box-none">{/* "ic-file-text" */}
        <SvgXml xml={SVG_24} width={16.3} height={19.7} style={{ position: "absolute", left: 1.8, top: 0.2 }} />
        <SvgXml xml={SVG_25} width={8} height={8} style={{ position: "absolute", left: 10.2, top: 0.2 }} />
        <SvgXml xml={SVG_26} width={9.7} height={3} style={{ position: "absolute", left: 5.2, top: 9.3 }} />
        <SvgXml xml={SVG_27} width={9.7} height={3} style={{ position: "absolute", left: 5.2, top: 12.7 }} />
        <SvgXml xml={SVG_28} width={4.7} height={3} style={{ position: "absolute", left: 5.2, top: 6 }} />
      </View>
      <Text style={{ position: "absolute", left: 84, top: 295, width: 150, textAlign: "left", fontFamily: "PlusJakartaSans_700Bold", fontSize: 13, lineHeight: 17.6, color: "#0F3244" }}>{"Proposal Sent"}</Text>
      <Text style={{ position: "absolute", left: 84, top: 313, width: 160, textAlign: "left", fontFamily: "PlusJakartaSans_500Medium", fontSize: 11, lineHeight: 14.9, color: "#6B8796" }}>{"4 opportunities"}</Text>
      <Text style={{ position: "absolute", left: 240, top: 303, width: 90, textAlign: "right", fontFamily: "PlusJakartaSans_800ExtraBold", fontSize: 13, lineHeight: 17.6, color: "#0F3244" }}>{"₹ 12.5L"}</Text>
      <View style={{ position: "absolute", left: 336, top: 306, width: 14, height: 14 }} pointerEvents="box-none">{/* "ic-chevron-right" */}
        <SvgXml xml={SVG_29} width={6.5} height={10} style={{ position: "absolute", left: 3.8, top: 2 }} />
      </View>
      <View style={{ position: "absolute", left: 18, top: 352, width: 340, height: 62, backgroundColor: "#FFFFFF", borderRadius: 14, borderWidth: 1, borderColor: "#E6EFF3", boxShadow: "0px 2px 8px 0px rgba(15,50,68,0.05)" }} />
      <View style={{ position: "absolute", left: 30, top: 363, width: 40, height: 40, backgroundColor: "#EAF2F7", borderRadius: 12 }} />
      <View style={{ position: "absolute", left: 40, top: 373, width: 20, height: 20 }} pointerEvents="box-none">{/* "ic-users" */}
        <SvgXml xml={SVG_30} width={14.7} height={8} style={{ position: "absolute", left: 0.2, top: 11 }} />
        <View style={{ position: "absolute", left: 4.2, top: 2.5, width: 6.7, height: 6.7, borderRadius: 3.4, borderWidth: 2, borderColor: "#4B7C93" }} />
        <SvgXml xml={SVG_31} width={5.5} height={7.9} style={{ position: "absolute", left: 14.3, top: 11.1 }} />
        <SvgXml xml={SVG_32} width={5.5} height={9.5} style={{ position: "absolute", left: 11.8, top: 1.1 }} />
      </View>
      <Text style={{ position: "absolute", left: 84, top: 365, width: 150, textAlign: "left", fontFamily: "PlusJakartaSans_700Bold", fontSize: 13, lineHeight: 17.6, color: "#0F3244" }}>{"Negotiation"}</Text>
      <Text style={{ position: "absolute", left: 84, top: 383, width: 160, textAlign: "left", fontFamily: "PlusJakartaSans_500Medium", fontSize: 11, lineHeight: 14.9, color: "#6B8796" }}>{"4 opportunities"}</Text>
      <Text style={{ position: "absolute", left: 240, top: 373, width: 90, textAlign: "right", fontFamily: "PlusJakartaSans_800ExtraBold", fontSize: 13, lineHeight: 17.6, color: "#0F3244" }}>{"₹ 10.2L"}</Text>
      <View style={{ position: "absolute", left: 336, top: 376, width: 14, height: 14 }} pointerEvents="box-none">{/* "ic-chevron-right" */}
        <SvgXml xml={SVG_33} width={6.5} height={10} style={{ position: "absolute", left: 3.8, top: 2 }} />
      </View>
      <View style={{ position: "absolute", left: 18, top: 422, width: 340, height: 62, backgroundColor: "#FFFFFF", borderRadius: 14, borderWidth: 1, borderColor: "#E6EFF3", boxShadow: "0px 2px 8px 0px rgba(15,50,68,0.05)" }} />
      <View style={{ position: "absolute", left: 30, top: 433, width: 40, height: 40, backgroundColor: "#E8F6EE", borderRadius: 12 }} />
      <View style={{ position: "absolute", left: 40, top: 443, width: 20, height: 20 }} pointerEvents="box-none">{/* "ic-trophy" */}
        <SvgXml xml={SVG_34} width={6.3} height={7.2} style={{ position: "absolute", left: 0.2, top: 1.8 }} />
        <SvgXml xml={SVG_35} width={6.3} height={7.2} style={{ position: "absolute", left: 13.5, top: 1.8 }} />
        <SvgXml xml={SVG_36} width={16.3} height={3} style={{ position: "absolute", left: 1.8, top: 16.8 }} />
        <SvgXml xml={SVG_37} width={5.5} height={9.1} style={{ position: "absolute", left: 4.3, top: 10.7 }} />
        <SvgXml xml={SVG_38} width={5.5} height={9.1} style={{ position: "absolute", left: 10.2, top: 10.7 }} />
        <SvgXml xml={SVG_39} width={13} height={13.8} style={{ position: "absolute", left: 3.5, top: 0.2 }} />
      </View>
      <Text style={{ position: "absolute", left: 84, top: 435, width: 150, textAlign: "left", fontFamily: "PlusJakartaSans_700Bold", fontSize: 13, lineHeight: 17.6, color: "#0F3244" }}>{"Closed Won"}</Text>
      <Text style={{ position: "absolute", left: 84, top: 453, width: 160, textAlign: "left", fontFamily: "PlusJakartaSans_500Medium", fontSize: 11, lineHeight: 14.9, color: "#6B8796" }}>{"3 opportunities"}</Text>
      <Text style={{ position: "absolute", left: 240, top: 443, width: 90, textAlign: "right", fontFamily: "PlusJakartaSans_800ExtraBold", fontSize: 13, lineHeight: 17.6, color: "#0F3244" }}>{"₹ 18.5L"}</Text>
      <View style={{ position: "absolute", left: 336, top: 446, width: 14, height: 14 }} pointerEvents="box-none">{/* "ic-chevron-right" */}
        <SvgXml xml={SVG_40} width={6.5} height={10} style={{ position: "absolute", left: 3.8, top: 2 }} />
      </View>
      <View style={{ position: "absolute", left: 18, top: 492, width: 340, height: 62, backgroundColor: "#FFFFFF", borderRadius: 14, borderWidth: 1, borderColor: "#E6EFF3", boxShadow: "0px 2px 8px 0px rgba(15,50,68,0.05)" }} />
      <View style={{ position: "absolute", left: 30, top: 503, width: 40, height: 40, backgroundColor: "#FDECEC", borderRadius: 12 }} />
      <View style={{ position: "absolute", left: 40, top: 513, width: 20, height: 20 }} pointerEvents="box-none">{/* "ic-circle-x" */}
        <View style={{ position: "absolute", left: 1.7, top: 1.7, width: 16.7, height: 16.7, borderRadius: 8.4, borderWidth: 2, borderColor: "#E5484D" }} />
        <SvgXml xml={SVG_41} width={8} height={8} style={{ position: "absolute", left: 6, top: 6 }} />
        <SvgXml xml={SVG_42} width={8} height={8} style={{ position: "absolute", left: 6, top: 6 }} />
      </View>
      <Text style={{ position: "absolute", left: 84, top: 505, width: 150, textAlign: "left", fontFamily: "PlusJakartaSans_700Bold", fontSize: 13, lineHeight: 17.6, color: "#0F3244" }}>{"Closed Lost"}</Text>
      <Text style={{ position: "absolute", left: 84, top: 523, width: 160, textAlign: "left", fontFamily: "PlusJakartaSans_500Medium", fontSize: 11, lineHeight: 14.9, color: "#6B8796" }}>{"2 opportunities"}</Text>
      <Text style={{ position: "absolute", left: 240, top: 513, width: 90, textAlign: "right", fontFamily: "PlusJakartaSans_800ExtraBold", fontSize: 13, lineHeight: 17.6, color: "#0F3244" }}>{"₹ 2.1L"}</Text>
      <View style={{ position: "absolute", left: 336, top: 516, width: 14, height: 14 }} pointerEvents="box-none">{/* "ic-chevron-right" */}
        <SvgXml xml={SVG_43} width={6.5} height={10} style={{ position: "absolute", left: 3.8, top: 2 }} />
      </View>
      <View style={{ position: "absolute", left: 0, top: 807, width: 376, height: 52, backgroundColor: "#FFFFFF", boxShadow: "0px -3px 14px 0px rgba(15,50,68,0.08)" }} />
      <View style={{ position: "absolute", left: 42, top: 817, width: 21, height: 21 }} pointerEvents="box-none">{/* "ic-house" */}
        <SvgXml xml={SVG_44} width={8.3} height={10.9} style={{ position: "absolute", left: 6.4, top: 9 }} />
        <SvgXml xml={SVG_45} width={18.8} height={19.6} style={{ position: "absolute", left: 1.1, top: 0.3 }} />
      </View>
      <Text style={{ position: "absolute", left: 11, top: 842, width: 83, textAlign: "center", fontFamily: "PlusJakartaSans_600SemiBold", fontSize: 10, lineHeight: 13.5, color: "#8AA3B0" }}>{"Home"}</Text>
      <View style={{ position: "absolute", left: 109, top: 817, width: 21, height: 21 }} pointerEvents="box-none">{/* "ic-layout-grid" */}
        <View style={{ position: "absolute", left: 2.6, top: 2.6, width: 6.1, height: 6.1, borderRadius: 1, borderWidth: 2, borderColor: "#17A45E" }} />
        <View style={{ position: "absolute", left: 12.3, top: 2.6, width: 6.1, height: 6.1, borderRadius: 1, borderWidth: 2, borderColor: "#17A45E" }} />
        <View style={{ position: "absolute", left: 12.3, top: 12.3, width: 6.1, height: 6.1, borderRadius: 1, borderWidth: 2, borderColor: "#17A45E" }} />
        <View style={{ position: "absolute", left: 2.6, top: 12.3, width: 6.1, height: 6.1, borderRadius: 1, borderWidth: 2, borderColor: "#17A45E" }} />
      </View>
      <Text style={{ position: "absolute", left: 78, top: 842, width: 83, textAlign: "center", fontFamily: "PlusJakartaSans_700Bold", fontSize: 10, lineHeight: 13.5, color: "#17A45E" }}>{"Pipeline"}</Text>
      <View style={{ position: "absolute", left: 246, top: 817, width: 21, height: 21 }} pointerEvents="box-none">{/* "ic-users" */}
        <SvgXml xml={SVG_46} width={15.3} height={8.3} style={{ position: "absolute", left: 0.3, top: 11.6 }} />
        <View style={{ position: "absolute", left: 4.4, top: 2.6, width: 7, height: 7, borderRadius: 3.5, borderWidth: 2, borderColor: "#8AA3B0" }} />
        <SvgXml xml={SVG_47} width={5.6} height={8.1} style={{ position: "absolute", left: 15.1, top: 11.7 }} />
        <SvgXml xml={SVG_48} width={5.6} height={9.8} style={{ position: "absolute", left: 12.5, top: 1.2 }} />
      </View>
      <Text style={{ position: "absolute", left: 215, top: 842, width: 83, textAlign: "center", fontFamily: "PlusJakartaSans_600SemiBold", fontSize: 10, lineHeight: 13.5, color: "#8AA3B0" }}>{"Customers"}</Text>
      <View style={{ position: "absolute", left: 313, top: 817, width: 21, height: 21 }} pointerEvents="box-none">{/* "ic-ellipsis" */}
        <View style={{ position: "absolute", left: 9.6, top: 9.6, width: 1.8, height: 1.8, borderRadius: 0.9, borderWidth: 2, borderColor: "#8AA3B0" }} />
        <View style={{ position: "absolute", left: 15.8, top: 9.6, width: 1.8, height: 1.8, borderRadius: 0.9, borderWidth: 2, borderColor: "#8AA3B0" }} />
        <View style={{ position: "absolute", left: 3.5, top: 9.6, width: 1.8, height: 1.8, borderRadius: 0.9, borderWidth: 2, borderColor: "#8AA3B0" }} />
      </View>
      <Text style={{ position: "absolute", left: 282, top: 842, width: 83, textAlign: "center", fontFamily: "PlusJakartaSans_600SemiBold", fontSize: 10, lineHeight: 13.5, color: "#8AA3B0" }}>{"More"}</Text>
      <View style={{ position: "absolute", left: 159, top: 788, width: 57, height: 57, backgroundColor: "#FFFFFF", borderRadius: 28.5 }} />
      <View style={{ position: "absolute", left: 161, top: 790, width: 53, height: 53, backgroundColor: "#17A45E", borderRadius: 26.5, boxShadow: "0px 4px 12px 0px rgba(14,122,74,0.2)" }} />
      <View style={{ position: "absolute", left: 175, top: 804, width: 25, height: 25 }} pointerEvents="box-none">{/* "ic-plus" */}
        <SvgXml xml={SVG_49} width={18} height={3.4} style={{ position: "absolute", left: 3.5, top: 10.8 }} />
        <SvgXml xml={SVG_50} width={3.4} height={18} style={{ position: "absolute", left: 10.8, top: 3.5 }} />
      </View>
      <View style={{ position: "absolute", left: 18, top: 576, width: 340, height: 158, backgroundColor: "#F1F9F5", borderRadius: 16, borderWidth: 1, borderColor: "#DCEFE4", overflow: "hidden" }}>{/* "promo" */}
        <View style={{ position: "absolute", left: 0, top: -22, width: 340, height: 227, overflow: "hidden" }}>{/* "promo-art" */}
          <Image source={require("@/assets/penpot/var0.jpg")} style={{ position: "absolute", left: 0, top: 0, width: 340, height: 227 }} resizeMode="cover" />
        </View>
        <View style={{ position: "absolute", left: 0, top: 0, width: 340, height: 158, overflow: "hidden" }}>{/* "promo-veil" */}
          <Svg style={StyleSheet.absoluteFill} width="100%" height="100%"><Defs><LinearGradient id="g032allstages0" x1="0" y1="0.4" x2="1" y2="0.8"><Stop offset={0} stopColor="#FFFFFF" stopOpacity={0.86} /><Stop offset={0.5} stopColor="#FFFFFF" stopOpacity={0.38} /><Stop offset={1} stopColor="#FFFFFF" stopOpacity={0} /></LinearGradient></Defs><Rect width="100%" height="100%" fill="url(#g032allstages0)" /></Svg>
        </View>
        <Text style={{ position: "absolute", left: 18, top: 24, width: 250, textAlign: "left", fontFamily: "PlusJakartaSans_700Bold", fontSize: 13, lineHeight: 17.6, color: "#0F3244" }}>{"Keep your pipeline moving."}</Text>
        <Text style={{ position: "absolute", left: 18, top: 45, width: 200, textAlign: "left", fontFamily: "PlusJakartaSans_500Medium", fontSize: 11, lineHeight: 14.9, color: "#3D5E6E" }}>{"Turn opportunities into"}</Text>
        <Text style={{ position: "absolute", left: 18, top: 60, width: 200, textAlign: "left", fontFamily: "PlusJakartaSans_500Medium", fontSize: 11, lineHeight: 14.9, color: "#3D5E6E" }}>{"long-term customers."}</Text>
      </View>
    </View>
  );
}
