/* GENERATED by tools/penpot-to-code/to-react-native.mjs from the Penpot
 * board "03.3 Opportunity Card". Do not edit: regenerate with
 * `pnpm design:rn`. Its text is the board's sample copy — a design
 * reference, not a screen.
 */
import React from "react";
import { View, Text } from "react-native";
import { SvgXml } from "react-native-svg";

export const size = { width: 376, height: 859 } as const;

const SVG_0 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"16.2\" height=\"5.3\" viewBox=\"1481.4 9319.8 16.2 5.3\" fill=\"none\"><path d=\"M1483.0,9323.5C1486.8697509765625,9320.6650390625,1492.1302490234375,9320.6650390625,1496.0,9323.5\" fill=\"none\" stroke=\"#0f3244\" stroke-width=\"2.2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_1 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"10.2\" height=\"4.2\" viewBox=\"1484.4 9324.6 10.2 4.2\" fill=\"none\"><path d=\"M1486.0,9327.2001953125C1488.134033203125,9325.8359375,1490.865966796875,9325.8359375,1493.0,9327.2001953125\" fill=\"none\" stroke=\"#0f3244\" stroke-width=\"2.2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_2 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"9.4\" height=\"15.8\" viewBox=\"1201.1 9349.1 9.4 15.8\" fill=\"none\"><path d=\"M1209.0,9363.4169921875L1202.5833740234375,9357.0L1209.0,9350.5830078125\" fill=\"none\" stroke=\"#0f3244\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_3 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"15.8\" height=\"3\" viewBox=\"1201.1 9355.5 15.8 3\" fill=\"none\"><path d=\"M1215.4166259765625,9357.0L1202.5833740234375,9357.0\" fill=\"none\" stroke=\"#0f3244\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" transform=\"translate(1209 9357) matrix(1,0,0,0.916666666666643,-1.1368683772161603e-13,-0.000381944444458715) translate(-1209 -9357)\"/></svg>";
const SVG_4 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"21.3\" height=\"20.4\" viewBox=\"1516.3 9347.3 21.3 20.4\" fill=\"none\"><path d=\"M1525.1666259765625,9364.3330078125C1525.16650390625,9364.6806640625,1525.36279296875,9364.998046875,1525.673583984375,9365.1533203125L1527.5069580078125,9366.0703125C1527.7911376953125,9366.212890625,1528.128662109375,9366.197265625,1528.3988037109375,9366.0302734375C1528.6690673828125,9365.86328125,1528.83349609375,9365.5673828125,1528.8333740234375,9365.25L1528.8333740234375,9358.8330078125C1528.83349609375,9358.37890625,1529.00244140625,9357.94140625,1529.3072509765625,9357.6044921875L1535.9283447265625,9350.28125C1536.1707763671875,9350.0126953125,1536.2325439453125,9349.6259765625,1536.0859375,9349.294921875C1535.9393310546875,9348.96484375,1535.61181640625,9348.7509765625,1535.25,9348.75L1518.75,9348.75C1518.3878173828125,9348.75,1518.0596923828125,9348.9638671875,1517.91259765625,9349.294921875C1517.765625,9349.625,1517.8271484375,9350.01171875,1518.06982421875,9350.28125L1524.6927490234375,9357.6044921875C1524.99755859375,9357.94140625,1525.16650390625,9358.37890625,1525.1666259765625,9358.8330078125L1525.1666259765625,9364.3330078125\" fill=\"none\" stroke=\"#17a45e\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_5 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"6\" height=\"6\" viewBox=\"1222.3 9403.3 6 6\" fill=\"none\"><path d=\"M1226.875,9407.875L1223.8292236328125,9404.8291015625\" fill=\"none\" stroke=\"#8aa3b0\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_6 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"8.8\" height=\"3\" viewBox=\"1508 9395.7 8.8 3\" fill=\"none\"><path d=\"M1515.3333740234375,9397.1669921875L1509.5,9397.1669921875\" fill=\"none\" stroke=\"#6b8796\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" transform=\"translate(1512.4 9397.2) matrix(0.9999999999999999,0,0,0.8333333333333712,8.881784197001252e-16,-0.0006944444439325181) translate(-1512.4 -9397.2)\"/></svg>";
const SVG_7 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"10.5\" height=\"3\" viewBox=\"1508 9407.3 10.5 3\" fill=\"none\"><path d=\"M1517.0,9408.8330078125L1509.5,9408.8330078125\" fill=\"none\" stroke=\"#6b8796\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" transform=\"translate(1513.3 9408.8) matrix(1,0,0,0.8333333333334849,0,-0.0006944444442922304) translate(-1513.3 -9408.8)\"/></svg>";
const SVG_8 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"3\" height=\"6.3\" viewBox=\"1517.2 9394 3 6.3\" fill=\"none\"><path d=\"M1518.6666259765625,9395.5L1518.6666259765625,9398.8330078125\" fill=\"none\" stroke=\"#6b8796\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" transform=\"translate(1518.7 9397.2) matrix(0.8333333333333144,0,0,1.0000000000000042,-0.0006944444444456632,2.7533531010703882e-14) translate(-1518.7 -9397.2)\"/></svg>";
const SVG_9 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"3\" height=\"6.3\" viewBox=\"1518.8 9405.7 3 6.3\" fill=\"none\"><path d=\"M1520.3333740234375,9407.1669921875L1520.3333740234375,9410.5\" fill=\"none\" stroke=\"#6b8796\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" transform=\"translate(1520.3 9408.8) matrix(0.8333333333334849,0,0,1.0000000000000044,-0.0006944444444518805,-3.68594044175552e-14) translate(-1520.3 -9408.8)\"/></svg>";
const SVG_10 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"10.5\" height=\"3\" viewBox=\"1515.5 9401.5 10.5 3\" fill=\"none\"><path d=\"M1524.5,9403.0L1517.0,9403.0\" fill=\"none\" stroke=\"#6b8796\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" transform=\"translate(1520.8 9403) matrix(1,0,0,0.8333333333333144,-5.684341886080802e-14,-0.0006944444445013964) translate(-1520.8 -9403)\"/></svg>";
const SVG_11 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"7.2\" height=\"3\" viewBox=\"1518.8 9407.3 7.2 3\" fill=\"none\"><path d=\"M1524.5,9408.8330078125L1520.3333740234375,9408.8330078125\" fill=\"none\" stroke=\"#6b8796\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" transform=\"translate(1522.4 9408.8) matrix(1.0000000000000002,0,0,0.8333333333334849,1.7141843500212417e-13,-0.0006944444442922304) translate(-1522.4 -9408.8)\"/></svg>";
const SVG_12 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"8.8\" height=\"3\" viewBox=\"1517.2 9395.7 8.8 3\" fill=\"none\"><path d=\"M1524.5,9397.1669921875L1518.6666259765625,9397.1669921875\" fill=\"none\" stroke=\"#6b8796\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" transform=\"translate(1521.6 9397.2) matrix(1,0,0,0.8333333333333712,0,-0.0006944444448420128) translate(-1521.6 -9397.2)\"/></svg>";
const SVG_13 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"3\" height=\"6.3\" viewBox=\"1512.2 9399.8 3 6.3\" fill=\"none\"><path d=\"M1513.6666259765625,9401.3330078125L1513.6666259765625,9404.6669921875\" fill=\"none\" stroke=\"#6b8796\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" transform=\"translate(1513.7 9403) matrix(0.8333333333334849,0,0,1.0000000000000355,-0.0006944444456120635,-4.4719783431901305e-13) translate(-1513.7 -9403)\"/></svg>";
const SVG_14 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"7.2\" height=\"3\" viewBox=\"1508 9401.5 7.2 3\" fill=\"none\"><path d=\"M1513.6666259765625,9403.0L1509.5,9403.0\" fill=\"none\" stroke=\"#6b8796\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" transform=\"translate(1511.6 9403) matrix(1,0,0,0.8333333333333144,-2.2737367544323206e-13,-0.000694444444444553) translate(-1511.6 -9403)\"/></svg>";
const SVG_15 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"10\" height=\"6.5\" viewBox=\"1518 9487.8 10 6.5\" fill=\"none\"><path d=\"M1519.5,9489.25L1523.0,9492.75L1526.5,9489.25\" fill=\"none\" stroke=\"#6b8796\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_16 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"6.5\" height=\"10\" viewBox=\"1517.8 9546 6.5 10\" fill=\"none\"><path d=\"M1519.25,9554.5L1522.75,9551.0L1519.25,9547.5\" fill=\"none\" stroke=\"#8aa3b0\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_17 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"3\" height=\"5\" viewBox=\"1410.5 9561.5 3 5\" fill=\"none\"><path d=\"M1412.0,9563.0L1412.0,9565.0\" fill=\"none\" stroke=\"#8aa3b0\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" transform=\"translate(1412 9564) matrix(0.5,0,0,1,-0.0012499999988913046,1.0231815394945443e-12) translate(-1412 -9564)\"/></svg>";
const SVG_18 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"3\" height=\"5\" viewBox=\"1414.5 9561.5 3 5\" fill=\"none\"><path d=\"M1416.0,9563.0L1416.0,9565.0\" fill=\"none\" stroke=\"#8aa3b0\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" transform=\"translate(1416 9564) matrix(0.5000000000001137,0,0,1,-0.001250000000809992,-1.7053025658242404e-12) translate(-1416 -9564)\"/></svg>";
const SVG_19 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"12\" height=\"3\" viewBox=\"1408 9565.5 12 3\" fill=\"none\"><path d=\"M1409.5,9567.0L1418.5,9567.0\" fill=\"none\" stroke=\"#8aa3b0\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" transform=\"translate(1414 9567) matrix(0.9999999999999999,0,0,0.5,9.103828801926284e-13,-0.0012499999999997513) translate(-1414 -9567)\"/></svg>";
const SVG_20 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"6.5\" height=\"10\" viewBox=\"1517.8 9628 6.5 10\" fill=\"none\"><path d=\"M1519.25,9636.5L1522.75,9633.0L1519.25,9629.5\" fill=\"none\" stroke=\"#8aa3b0\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_21 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"3\" height=\"5\" viewBox=\"1410.5 9643.5 3 5\" fill=\"none\"><path d=\"M1412.0,9645.0L1412.0,9647.0\" fill=\"none\" stroke=\"#8aa3b0\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" transform=\"translate(1412 9646) matrix(0.5,0,0,1,-0.0012499999988913046,1.0231815394945443e-12) translate(-1412 -9646)\"/></svg>";
const SVG_22 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"3\" height=\"5\" viewBox=\"1414.5 9643.5 3 5\" fill=\"none\"><path d=\"M1416.0,9645.0L1416.0,9647.0\" fill=\"none\" stroke=\"#8aa3b0\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" transform=\"translate(1416 9646) matrix(0.5000000000001137,0,0,1,-0.001250000000809992,-1.7053025658242404e-12) translate(-1416 -9646)\"/></svg>";
const SVG_23 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"12\" height=\"3\" viewBox=\"1408 9647.5 12 3\" fill=\"none\"><path d=\"M1409.5,9649.0L1418.5,9649.0\" fill=\"none\" stroke=\"#8aa3b0\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" transform=\"translate(1414 9649) matrix(0.9999999999999999,0,0,0.5,9.103828801926284e-13,-0.0012499999999997513) translate(-1414 -9649)\"/></svg>";
const SVG_24 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"6.5\" height=\"10\" viewBox=\"1517.8 9710 6.5 10\" fill=\"none\"><path d=\"M1519.25,9718.5L1522.75,9715.0L1519.25,9711.5\" fill=\"none\" stroke=\"#8aa3b0\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_25 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"3\" height=\"5\" viewBox=\"1410.5 9725.5 3 5\" fill=\"none\"><path d=\"M1412.0,9727.0L1412.0,9729.0\" fill=\"none\" stroke=\"#8aa3b0\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" transform=\"translate(1412 9728) matrix(0.5,0,0,1,-0.0012499999988913046,1.0231815394945443e-12) translate(-1412 -9728)\"/></svg>";
const SVG_26 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"3\" height=\"5\" viewBox=\"1414.5 9725.5 3 5\" fill=\"none\"><path d=\"M1416.0,9727.0L1416.0,9729.0\" fill=\"none\" stroke=\"#8aa3b0\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" transform=\"translate(1416 9728) matrix(0.5000000000001137,0,0,1,-0.001250000000809992,-1.7053025658242404e-12) translate(-1416 -9728)\"/></svg>";
const SVG_27 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"12\" height=\"3\" viewBox=\"1408 9729.5 12 3\" fill=\"none\"><path d=\"M1409.5,9731.0L1418.5,9731.0\" fill=\"none\" stroke=\"#8aa3b0\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" transform=\"translate(1414 9731) matrix(0.9999999999999999,0,0,0.5,9.103828801926284e-13,-0.0012499999999997513) translate(-1414 -9731)\"/></svg>";
const SVG_28 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"6.5\" height=\"10\" viewBox=\"1517.8 9792 6.5 10\" fill=\"none\"><path d=\"M1519.25,9800.5L1522.75,9797.0L1519.25,9793.5\" fill=\"none\" stroke=\"#8aa3b0\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_29 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"3\" height=\"5\" viewBox=\"1410.5 9807.5 3 5\" fill=\"none\"><path d=\"M1412.0,9809.0L1412.0,9811.0\" fill=\"none\" stroke=\"#8aa3b0\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" transform=\"translate(1412 9810) matrix(0.5,0,0,1,-0.0012499999988913046,1.0231815394945443e-12) translate(-1412 -9810)\"/></svg>";
const SVG_30 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"3\" height=\"5\" viewBox=\"1414.5 9807.5 3 5\" fill=\"none\"><path d=\"M1416.0,9809.0L1416.0,9811.0\" fill=\"none\" stroke=\"#8aa3b0\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" transform=\"translate(1416 9810) matrix(0.5000000000001137,0,0,1,-0.001250000000809992,-1.7053025658242404e-12) translate(-1416 -9810)\"/></svg>";
const SVG_31 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"12\" height=\"3\" viewBox=\"1408 9811.5 12 3\" fill=\"none\"><path d=\"M1409.5,9813.0L1418.5,9813.0\" fill=\"none\" stroke=\"#8aa3b0\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" transform=\"translate(1414 9813) matrix(0.9999999999999999,0,0,0.5,9.103828801926284e-13,-0.0012499999999997513) translate(-1414 -9813)\"/></svg>";
const SVG_32 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"6.5\" height=\"10\" viewBox=\"1517.8 9874 6.5 10\" fill=\"none\"><path d=\"M1519.25,9882.5L1522.75,9879.0L1519.25,9875.5\" fill=\"none\" stroke=\"#8aa3b0\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_33 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"3\" height=\"5\" viewBox=\"1410.5 9889.5 3 5\" fill=\"none\"><path d=\"M1412.0,9891.0L1412.0,9893.0\" fill=\"none\" stroke=\"#8aa3b0\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" transform=\"translate(1412 9892) matrix(0.5,0,0,1,-0.0012499999988913046,1.0231815394945443e-12) translate(-1412 -9892)\"/></svg>";
const SVG_34 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"3\" height=\"5\" viewBox=\"1414.5 9889.5 3 5\" fill=\"none\"><path d=\"M1416.0,9891.0L1416.0,9893.0\" fill=\"none\" stroke=\"#8aa3b0\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" transform=\"translate(1416 9892) matrix(0.5000000000001137,0,0,1,-0.001250000000809992,-1.7053025658242404e-12) translate(-1416 -9892)\"/></svg>";
const SVG_35 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"12\" height=\"3\" viewBox=\"1408 9893.5 12 3\" fill=\"none\"><path d=\"M1409.5,9895.0L1418.5,9895.0\" fill=\"none\" stroke=\"#8aa3b0\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" transform=\"translate(1414 9895) matrix(0.9999999999999999,0,0,0.5,9.103828801926284e-13,-0.0012499999999997513) translate(-1414 -9895)\"/></svg>";
const SVG_36 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"6.5\" height=\"10\" viewBox=\"1517.8 9956 6.5 10\" fill=\"none\"><path d=\"M1519.25,9964.5L1522.75,9961.0L1519.25,9957.5\" fill=\"none\" stroke=\"#8aa3b0\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_37 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"3\" height=\"5\" viewBox=\"1410.5 9971.5 3 5\" fill=\"none\"><path d=\"M1412.0,9973.0L1412.0,9975.0\" fill=\"none\" stroke=\"#8aa3b0\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" transform=\"translate(1412 9974) matrix(0.5,0,0,1,-0.0012499999988913046,1.0231815394945443e-12) translate(-1412 -9974)\"/></svg>";
const SVG_38 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"3\" height=\"5\" viewBox=\"1414.5 9971.5 3 5\" fill=\"none\"><path d=\"M1416.0,9973.0L1416.0,9975.0\" fill=\"none\" stroke=\"#8aa3b0\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" transform=\"translate(1416 9974) matrix(0.5000000000001137,0,0,1,-0.001250000000809992,-1.7053025658242404e-12) translate(-1416 -9974)\"/></svg>";
const SVG_39 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"12\" height=\"3\" viewBox=\"1408 9975.5 12 3\" fill=\"none\"><path d=\"M1409.5,9977.0L1418.5,9977.0\" fill=\"none\" stroke=\"#8aa3b0\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" transform=\"translate(1414 9977) matrix(0.9999999999999999,0,0,0.5,9.103828801926284e-13,-0.0012499999999997513) translate(-1414 -9977)\"/></svg>";
const SVG_40 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"8.3\" height=\"10.9\" viewBox=\"1228.4 10126 8.3 10.9\" fill=\"none\"><path d=\"M1235.125,10135.375L1235.125,10128.375C1235.125,10127.8916015625,1234.7332763671875,10127.5,1234.25,10127.5L1230.75,10127.5C1230.2667236328125,10127.5,1229.875,10127.8916015625,1229.875,10128.375L1229.875,10135.375\" fill=\"none\" stroke=\"#8aa3b0\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_41 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"18.8\" height=\"19.6\" viewBox=\"1223.1 10117.3 18.8 19.6\" fill=\"none\"><path d=\"M1224.625,10125.75C1224.6248779296875,10125.234375,1224.851806640625,10124.7451171875,1225.245361328125,10124.4130859375L1231.370361328125,10119.1640625C1232.0225830078125,10118.6123046875,1232.9774169921875,10118.6123046875,1233.629638671875,10119.1640625L1239.754638671875,10124.4130859375C1240.148193359375,10124.7451171875,1240.3751220703125,10125.234375,1240.375,10125.75L1240.375,10133.625C1240.375,10134.591796875,1239.591552734375,10135.375,1238.625,10135.375L1226.375,10135.375C1225.408447265625,10135.375,1224.625,10134.591796875,1224.625,10133.625L1224.625,10125.75\" fill=\"none\" stroke=\"#8aa3b0\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_42 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"15.3\" height=\"8.3\" viewBox=\"1426.3 10128.6 15.3 8.3\" fill=\"none\"><path d=\"M1440.0,10135.375L1440.0,10133.625C1440.0,10131.6923828125,1438.4329833984375,10130.125,1436.5,10130.125L1431.25,10130.125C1429.3170166015625,10130.125,1427.75,10131.6923828125,1427.75,10133.625L1427.75,10135.375\" fill=\"none\" stroke=\"#8aa3b0\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_43 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"5.6\" height=\"8.1\" viewBox=\"1441.1 10128.7 5.6 8.1\" fill=\"none\"><path d=\"M1445.25,10135.375L1445.25,10133.625C1445.248779296875,10132.0302734375,1444.16943359375,10130.6376953125,1442.625,10130.23828125\" fill=\"none\" stroke=\"#8aa3b0\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_44 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"5.6\" height=\"9.8\" viewBox=\"1438.5 10118.2 5.6 9.8\" fill=\"none\"><path d=\"M1440.0,10119.73828125C1441.5487060546875,10120.1357421875,1442.6318359375,10121.5302734375,1442.6318359375,10123.12890625C1442.6318359375,10124.7275390625,1441.5487060546875,10126.123046875,1440.0,10126.51953125\" fill=\"none\" stroke=\"#8aa3b0\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_45 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"18\" height=\"3.4\" viewBox=\"1358.5 10114.8 18 3.4\" fill=\"none\"><path d=\"M1360.2083740234375,10116.5L1374.7916259765625,10116.5\" fill=\"none\" stroke=\"#ffffff\" stroke-width=\"2.4\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_46 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"3.4\" height=\"18\" viewBox=\"1365.8 10107.5 3.4 18\" fill=\"none\"><path d=\"M1367.5,10109.2080078125L1367.5,10123.7919921875\" fill=\"none\" stroke=\"#ffffff\" stroke-width=\"2.4\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";

export default function Penpot033OpportunityCard() {
  return (
    <View style={{ width: 376, height: 859, backgroundColor: "#F8FBFC", borderRadius: 34, overflow: "hidden" }}>{/* "03.3 Opportunity Card" */}
      <Text style={{ position: "absolute", left: 24, top: 11, width: 78, textAlign: "left", fontFamily: "PlusJakartaSans_700Bold", fontSize: 14, lineHeight: 18.9, color: "#0F3244" }}>{"9:41"}</Text>
      <View style={{ position: "absolute", left: 277, top: 16, width: 75, height: 20 }} pointerEvents="box-none">{/* "status-icons" */}
        <View style={{ position: "absolute", left: 0, top: 12, width: 3.5, height: 5, backgroundColor: "#0F3244", borderRadius: 1 }} />
        <View style={{ position: "absolute", left: 5.5, top: 9, width: 3.5, height: 8, backgroundColor: "#0F3244", borderRadius: 1 }} />
        <View style={{ position: "absolute", left: 11, top: 5.5, width: 3.5, height: 11.5, backgroundColor: "#0F3244", borderRadius: 1 }} />
        <View style={{ position: "absolute", left: 16.5, top: 2, width: 3.5, height: 15, backgroundColor: "#0F3244", borderRadius: 1 }} />
        <SvgXml xml={SVG_0} width={16.2} height={5.3} style={{ position: "absolute", left: 24.4, top: 3.8 }} />
        <SvgXml xml={SVG_1} width={10.2} height={4.2} style={{ position: "absolute", left: 27.4, top: 8.6 }} />
        <View style={{ position: "absolute", left: 30.7, top: 13.4, width: 3.6, height: 3.6, backgroundColor: "#0F3244", borderRadius: 1.8 }} />
        <View style={{ position: "absolute", left: 47, top: 4.5, width: 24, height: 12, borderRadius: 3.5, borderWidth: 1.6, borderColor: "#0F3244" }} />
        <View style={{ position: "absolute", left: 49.5, top: 7, width: 17, height: 7, backgroundColor: "#0F3244", borderRadius: 2 }} />
        <View style={{ position: "absolute", left: 72, top: 8, width: 2.5, height: 5, backgroundColor: "#0F3244", borderRadius: 1.2 }} />
      </View>
      <View style={{ position: "absolute", left: 18, top: 46, width: 22, height: 22 }} pointerEvents="box-none">{/* "ic-arrow-left" */}
        <SvgXml xml={SVG_2} width={9.4} height={15.8} style={{ position: "absolute", left: 3.1, top: 3.1 }} />
        <SvgXml xml={SVG_3} width={15.8} height={3} style={{ position: "absolute", left: 3.1, top: 9.5 }} />
      </View>
      <Text style={{ position: "absolute", left: 60, top: 48, width: 256, textAlign: "center", fontFamily: "PlusJakartaSans_700Bold", fontSize: 16, lineHeight: 21.6, color: "#0F3244" }}>{"Pipeline"}</Text>
      <View style={{ position: "absolute", left: 336, top: 46, width: 22, height: 22 }} pointerEvents="box-none">{/* "ic-funnel" */}
        <SvgXml xml={SVG_4} width={21.3} height={20.4} style={{ position: "absolute", left: 0.3, top: 1.3 }} />
      </View>
      <View style={{ position: "absolute", left: 18, top: 82, width: 288, height: 40, backgroundColor: "#EFF5F8", borderRadius: 12, borderWidth: 1, borderColor: "#E6EFF3" }} />
      <View style={{ position: "absolute", left: 32, top: 93, width: 17, height: 17 }} pointerEvents="box-none">{/* "ic-search" */}
        <View style={{ position: "absolute", left: 2.1, top: 2.1, width: 11.3, height: 11.3, borderRadius: 5.7, borderWidth: 2, borderColor: "#8AA3B0" }} />
        <SvgXml xml={SVG_5} width={6} height={6} style={{ position: "absolute", left: 10.3, top: 10.3 }} />
      </View>
      <Text style={{ position: "absolute", left: 58, top: 94, width: 236, textAlign: "left", fontFamily: "PlusJakartaSans_500Medium", fontSize: 12, lineHeight: 16.2, color: "#93A9B5" }}>{"Search opportunities..."}</Text>
      <View style={{ position: "absolute", left: 316, top: 82, width: 42, height: 40, backgroundColor: "#FFFFFF", borderRadius: 12, borderWidth: 1, borderColor: "#E6EFF3" }} />
      <View style={{ position: "absolute", left: 327, top: 93, width: 20, height: 20 }} pointerEvents="box-none">{/* "ic-sliders-horizontal" */}
        <SvgXml xml={SVG_6} width={8.8} height={3} style={{ position: "absolute", left: 1, top: 2.7 }} />
        <SvgXml xml={SVG_7} width={10.5} height={3} style={{ position: "absolute", left: 1, top: 14.3 }} />
        <SvgXml xml={SVG_8} width={3} height={6.3} style={{ position: "absolute", left: 10.2, top: 1 }} />
        <SvgXml xml={SVG_9} width={3} height={6.3} style={{ position: "absolute", left: 11.8, top: 12.7 }} />
        <SvgXml xml={SVG_10} width={10.5} height={3} style={{ position: "absolute", left: 8.5, top: 8.5 }} />
        <SvgXml xml={SVG_11} width={7.2} height={3} style={{ position: "absolute", left: 11.8, top: 14.3 }} />
        <SvgXml xml={SVG_12} width={8.8} height={3} style={{ position: "absolute", left: 10.2, top: 2.7 }} />
        <SvgXml xml={SVG_13} width={3} height={6.3} style={{ position: "absolute", left: 5.2, top: 6.8 }} />
        <SvgXml xml={SVG_14} width={7.2} height={3} style={{ position: "absolute", left: 1, top: 8.5 }} />
      </View>
      <View style={{ position: "absolute", left: 18, top: 138, width: 123, height: 28, backgroundColor: "#17A45E", borderRadius: 14, boxShadow: "0px 4px 12px 0px rgba(14,122,74,0.2)" }} />
      <Text style={{ position: "absolute", left: 18, top: 145, width: 123, textAlign: "center", fontFamily: "PlusJakartaSans_700Bold", fontSize: 10, lineHeight: 13.5, color: "#FFFFFF" }}>{"High Probability"}</Text>
      <View style={{ position: "absolute", left: 151, top: 138, width: 86, height: 28, backgroundColor: "#FFFFFF", borderRadius: 14, borderWidth: 1, borderColor: "#E6EFF3" }} />
      <Text style={{ position: "absolute", left: 151, top: 145, width: 86, textAlign: "center", fontFamily: "PlusJakartaSans_700Bold", fontSize: 10, lineHeight: 13.5, color: "#0F3244" }}>{"This Month"}</Text>
      <View style={{ position: "absolute", left: 247, top: 138, width: 74, height: 28, backgroundColor: "#FFFFFF", borderRadius: 14, borderWidth: 1, borderColor: "#E6EFF3" }} />
      <Text style={{ position: "absolute", left: 247, top: 145, width: 74, textAlign: "center", fontFamily: "PlusJakartaSans_700Bold", fontSize: 10, lineHeight: 13.5, color: "#0F3244" }}>{"My Deals"}</Text>
      <Text style={{ position: "absolute", left: 18, top: 182, width: 180, textAlign: "left", fontFamily: "PlusJakartaSans_700Bold", fontSize: 13, lineHeight: 17.6, color: "#0F3244" }}>{"10 Opportunities"}</Text>
      <Text style={{ position: "absolute", left: 180, top: 184, width: 150, textAlign: "right", fontFamily: "PlusJakartaSans_600SemiBold", fontSize: 11, lineHeight: 14.9, color: "#6B8796" }}>{"Sort: Expected Close"}</Text>
      <View style={{ position: "absolute", left: 336, top: 184, width: 14, height: 14 }} pointerEvents="box-none">{/* "ic-chevron-down" */}
        <SvgXml xml={SVG_15} width={10} height={6.5} style={{ position: "absolute", left: 2, top: 3.8 }} />
      </View>
      <View style={{ position: "absolute", left: 18, top: 214, width: 340, height: 74, backgroundColor: "#FFFFFF", borderRadius: 14, borderWidth: 1, borderColor: "#E6EFF3", boxShadow: "0px 2px 8px 0px rgba(15,50,68,0.05)" }} />
      <View style={{ position: "absolute", left: 30, top: 223, width: 34, height: 34, backgroundColor: "#E8F6EE", borderRadius: 17 }} />
      <Text style={{ position: "absolute", left: 30, top: 232.4, width: 34, textAlign: "center", fontFamily: "PlusJakartaSans_800ExtraBold", fontSize: 11, lineHeight: 14.9, letterSpacing: 0.2, color: "#0E7A4A" }}>{"TM"}</Text>
      <Text style={{ position: "absolute", left: 74, top: 223, width: 156, textAlign: "left", fontFamily: "PlusJakartaSans_700Bold", fontSize: 13, lineHeight: 17.6, color: "#0F3244" }}>{"TrendMart"}</Text>
      <Text style={{ position: "absolute", left: 236, top: 223, width: 104, textAlign: "right", fontFamily: "PlusJakartaSans_800ExtraBold", fontSize: 13, lineHeight: 17.6, color: "#0F3244" }}>{"₹ 5.0L"}</Text>
      <Text style={{ position: "absolute", left: 74, top: 240, width: 170, textAlign: "left", fontFamily: "PlusJakartaSans_500Medium", fontSize: 11, lineHeight: 14.9, color: "#6B8796" }}>{"New Outlet Expansion"}</Text>
      <View style={{ position: "absolute", left: 334, top: 244, width: 14, height: 14 }} pointerEvents="box-none">{/* "ic-chevron-right" */}
        <SvgXml xml={SVG_16} width={6.5} height={10} style={{ position: "absolute", left: 3.8, top: 2 }} />
      </View>
      <View style={{ position: "absolute", left: 74, top: 260, width: 93, height: 19, backgroundColor: "#FDF0E0", borderRadius: 9.5 }} />
      <Text style={{ position: "absolute", left: 84, top: 263, width: 78, textAlign: "left", fontFamily: "PlusJakartaSans_700Bold", fontSize: 9.5, lineHeight: 12.8, color: "#C97A09" }}>{"Proposal Sent"}</Text>
      <Text style={{ position: "absolute", left: 175, top: 262, width: 32, textAlign: "left", fontFamily: "PlusJakartaSans_800ExtraBold", fontSize: 10, lineHeight: 13.5, color: "#0F3244" }}>{"80%"}</Text>
      <View style={{ position: "absolute", left: 228, top: 262, width: 12, height: 12 }} pointerEvents="box-none">{/* "ic-calendar" */}
        <SvgXml xml={SVG_17} width={3} height={5} style={{ position: "absolute", left: 2.5, top: -0.5 }} />
        <SvgXml xml={SVG_18} width={3} height={5} style={{ position: "absolute", left: 6.5, top: -0.5 }} />
        <View style={{ position: "absolute", left: 1.5, top: 2, width: 9, height: 9, borderRadius: 2, borderWidth: 2, borderColor: "#8AA3B0" }} />
        <SvgXml xml={SVG_19} width={12} height={3} style={{ position: "absolute", left: 0, top: 3.5 }} />
      </View>
      <Text style={{ position: "absolute", left: 244, top: 261, width: 90, textAlign: "left", fontFamily: "PlusJakartaSans_500Medium", fontSize: 10, lineHeight: 13.5, color: "#6B8796" }}>{"20 Sep 2026"}</Text>
      <View style={{ position: "absolute", left: 18, top: 296, width: 340, height: 74, backgroundColor: "#FFFFFF", borderRadius: 14, borderWidth: 1, borderColor: "#E6EFF3", boxShadow: "0px 2px 8px 0px rgba(15,50,68,0.05)" }} />
      <View style={{ position: "absolute", left: 30, top: 305, width: 34, height: 34, backgroundColor: "#E8F6EE", borderRadius: 17 }} />
      <Text style={{ position: "absolute", left: 30, top: 314.4, width: 34, textAlign: "center", fontFamily: "PlusJakartaSans_800ExtraBold", fontSize: 11, lineHeight: 14.9, letterSpacing: 0.2, color: "#0E7A4A" }}>{"MR"}</Text>
      <Text style={{ position: "absolute", left: 74, top: 305, width: 156, textAlign: "left", fontFamily: "PlusJakartaSans_700Bold", fontSize: 13, lineHeight: 17.6, color: "#0F3244" }}>{"Metro Retail"}</Text>
      <Text style={{ position: "absolute", left: 236, top: 305, width: 104, textAlign: "right", fontFamily: "PlusJakartaSans_800ExtraBold", fontSize: 13, lineHeight: 17.6, color: "#0F3244" }}>{"₹ 12.5L"}</Text>
      <Text style={{ position: "absolute", left: 74, top: 322, width: 170, textAlign: "left", fontFamily: "PlusJakartaSans_500Medium", fontSize: 11, lineHeight: 14.9, color: "#6B8796" }}>{"Annual Supply Contract"}</Text>
      <View style={{ position: "absolute", left: 334, top: 326, width: 14, height: 14 }} pointerEvents="box-none">{/* "ic-chevron-right" */}
        <SvgXml xml={SVG_20} width={6.5} height={10} style={{ position: "absolute", left: 3.8, top: 2 }} />
      </View>
      <View style={{ position: "absolute", left: 74, top: 342, width: 82, height: 19, backgroundColor: "#EAF2F7", borderRadius: 9.5 }} />
      <Text style={{ position: "absolute", left: 84, top: 345, width: 67, textAlign: "left", fontFamily: "PlusJakartaSans_700Bold", fontSize: 9.5, lineHeight: 12.8, color: "#4B7C93" }}>{"Negotiation"}</Text>
      <Text style={{ position: "absolute", left: 164, top: 344, width: 32, textAlign: "left", fontFamily: "PlusJakartaSans_800ExtraBold", fontSize: 10, lineHeight: 13.5, color: "#0F3244" }}>{"70%"}</Text>
      <View style={{ position: "absolute", left: 228, top: 344, width: 12, height: 12 }} pointerEvents="box-none">{/* "ic-calendar" */}
        <SvgXml xml={SVG_21} width={3} height={5} style={{ position: "absolute", left: 2.5, top: -0.5 }} />
        <SvgXml xml={SVG_22} width={3} height={5} style={{ position: "absolute", left: 6.5, top: -0.5 }} />
        <View style={{ position: "absolute", left: 1.5, top: 2, width: 9, height: 9, borderRadius: 2, borderWidth: 2, borderColor: "#8AA3B0" }} />
        <SvgXml xml={SVG_23} width={12} height={3} style={{ position: "absolute", left: 0, top: 3.5 }} />
      </View>
      <Text style={{ position: "absolute", left: 244, top: 343, width: 90, textAlign: "left", fontFamily: "PlusJakartaSans_500Medium", fontSize: 10, lineHeight: 13.5, color: "#6B8796" }}>{"25 Sep 2026"}</Text>
      <View style={{ position: "absolute", left: 18, top: 378, width: 340, height: 74, backgroundColor: "#FFFFFF", borderRadius: 14, borderWidth: 1, borderColor: "#E6EFF3", boxShadow: "0px 2px 8px 0px rgba(15,50,68,0.05)" }} />
      <View style={{ position: "absolute", left: 30, top: 387, width: 34, height: 34, backgroundColor: "#E8F6EE", borderRadius: 17 }} />
      <Text style={{ position: "absolute", left: 30, top: 396.4, width: 34, textAlign: "center", fontFamily: "PlusJakartaSans_800ExtraBold", fontSize: 11, lineHeight: 14.9, letterSpacing: 0.2, color: "#0E7A4A" }}>{"UC"}</Text>
      <Text style={{ position: "absolute", left: 74, top: 387, width: 156, textAlign: "left", fontFamily: "PlusJakartaSans_700Bold", fontSize: 13, lineHeight: 17.6, color: "#0F3244" }}>{"Urban Creations"}</Text>
      <Text style={{ position: "absolute", left: 236, top: 387, width: 104, textAlign: "right", fontFamily: "PlusJakartaSans_800ExtraBold", fontSize: 13, lineHeight: 17.6, color: "#0F3244" }}>{"₹ 4.8L"}</Text>
      <Text style={{ position: "absolute", left: 74, top: 404, width: 170, textAlign: "left", fontFamily: "PlusJakartaSans_500Medium", fontSize: 11, lineHeight: 14.9, color: "#6B8796" }}>{"Product Upgrade"}</Text>
      <View style={{ position: "absolute", left: 334, top: 408, width: 14, height: 14 }} pointerEvents="box-none">{/* "ic-chevron-right" */}
        <SvgXml xml={SVG_24} width={6.5} height={10} style={{ position: "absolute", left: 3.8, top: 2 }} />
      </View>
      <View style={{ position: "absolute", left: 74, top: 424, width: 93, height: 19, backgroundColor: "#FDF0E0", borderRadius: 9.5 }} />
      <Text style={{ position: "absolute", left: 84, top: 427, width: 78, textAlign: "left", fontFamily: "PlusJakartaSans_700Bold", fontSize: 9.5, lineHeight: 12.8, color: "#C97A09" }}>{"Proposal Sent"}</Text>
      <Text style={{ position: "absolute", left: 175, top: 426, width: 32, textAlign: "left", fontFamily: "PlusJakartaSans_800ExtraBold", fontSize: 10, lineHeight: 13.5, color: "#0F3244" }}>{"75%"}</Text>
      <View style={{ position: "absolute", left: 228, top: 426, width: 12, height: 12 }} pointerEvents="box-none">{/* "ic-calendar" */}
        <SvgXml xml={SVG_25} width={3} height={5} style={{ position: "absolute", left: 2.5, top: -0.5 }} />
        <SvgXml xml={SVG_26} width={3} height={5} style={{ position: "absolute", left: 6.5, top: -0.5 }} />
        <View style={{ position: "absolute", left: 1.5, top: 2, width: 9, height: 9, borderRadius: 2, borderWidth: 2, borderColor: "#8AA3B0" }} />
        <SvgXml xml={SVG_27} width={12} height={3} style={{ position: "absolute", left: 0, top: 3.5 }} />
      </View>
      <Text style={{ position: "absolute", left: 244, top: 425, width: 90, textAlign: "left", fontFamily: "PlusJakartaSans_500Medium", fontSize: 10, lineHeight: 13.5, color: "#6B8796" }}>{"18 Sep 2026"}</Text>
      <View style={{ position: "absolute", left: 18, top: 460, width: 340, height: 74, backgroundColor: "#FFFFFF", borderRadius: 14, borderWidth: 1, borderColor: "#E6EFF3", boxShadow: "0px 2px 8px 0px rgba(15,50,68,0.05)" }} />
      <View style={{ position: "absolute", left: 30, top: 469, width: 34, height: 34, backgroundColor: "#E8F6EE", borderRadius: 17 }} />
      <Text style={{ position: "absolute", left: 30, top: 478.4, width: 34, textAlign: "center", fontFamily: "PlusJakartaSans_800ExtraBold", fontSize: 11, lineHeight: 14.9, letterSpacing: 0.2, color: "#0E7A4A" }}>{"GT"}</Text>
      <Text style={{ position: "absolute", left: 74, top: 469, width: 156, textAlign: "left", fontFamily: "PlusJakartaSans_700Bold", fontSize: 13, lineHeight: 17.6, color: "#0F3244" }}>{"Greenfield Traders"}</Text>
      <Text style={{ position: "absolute", left: 236, top: 469, width: 104, textAlign: "right", fontFamily: "PlusJakartaSans_800ExtraBold", fontSize: 13, lineHeight: 17.6, color: "#0F3244" }}>{"₹ 3.6L"}</Text>
      <Text style={{ position: "absolute", left: 74, top: 486, width: 170, textAlign: "left", fontFamily: "PlusJakartaSans_500Medium", fontSize: 11, lineHeight: 14.9, color: "#6B8796" }}>{"New Product Line"}</Text>
      <View style={{ position: "absolute", left: 334, top: 490, width: 14, height: 14 }} pointerEvents="box-none">{/* "ic-chevron-right" */}
        <SvgXml xml={SVG_28} width={6.5} height={10} style={{ position: "absolute", left: 3.8, top: 2 }} />
      </View>
      <View style={{ position: "absolute", left: 74, top: 506, width: 104, height: 19, backgroundColor: "#FDECEC", borderRadius: 9.5 }} />
      <Text style={{ position: "absolute", left: 84, top: 509, width: 89, textAlign: "left", fontFamily: "PlusJakartaSans_700Bold", fontSize: 9.5, lineHeight: 12.8, color: "#E5484D" }}>{"Needs Follow-up"}</Text>
      <Text style={{ position: "absolute", left: 186, top: 508, width: 32, textAlign: "left", fontFamily: "PlusJakartaSans_800ExtraBold", fontSize: 10, lineHeight: 13.5, color: "#0F3244" }}>{"60%"}</Text>
      <View style={{ position: "absolute", left: 228, top: 508, width: 12, height: 12 }} pointerEvents="box-none">{/* "ic-calendar" */}
        <SvgXml xml={SVG_29} width={3} height={5} style={{ position: "absolute", left: 2.5, top: -0.5 }} />
        <SvgXml xml={SVG_30} width={3} height={5} style={{ position: "absolute", left: 6.5, top: -0.5 }} />
        <View style={{ position: "absolute", left: 1.5, top: 2, width: 9, height: 9, borderRadius: 2, borderWidth: 2, borderColor: "#8AA3B0" }} />
        <SvgXml xml={SVG_31} width={12} height={3} style={{ position: "absolute", left: 0, top: 3.5 }} />
      </View>
      <Text style={{ position: "absolute", left: 244, top: 507, width: 90, textAlign: "left", fontFamily: "PlusJakartaSans_500Medium", fontSize: 10, lineHeight: 13.5, color: "#6B8796" }}>{"22 Sep 2026"}</Text>
      <View style={{ position: "absolute", left: 18, top: 542, width: 340, height: 74, backgroundColor: "#FFFFFF", borderRadius: 14, borderWidth: 1, borderColor: "#E6EFF3", boxShadow: "0px 2px 8px 0px rgba(15,50,68,0.05)" }} />
      <View style={{ position: "absolute", left: 30, top: 551, width: 34, height: 34, backgroundColor: "#E8F6EE", borderRadius: 17 }} />
      <Text style={{ position: "absolute", left: 30, top: 560.4, width: 34, textAlign: "center", fontFamily: "PlusJakartaSans_800ExtraBold", fontSize: 11, lineHeight: 14.9, letterSpacing: 0.2, color: "#0E7A4A" }}>{"CY"}</Text>
      <Text style={{ position: "absolute", left: 74, top: 551, width: 156, textAlign: "left", fontFamily: "PlusJakartaSans_700Bold", fontSize: 13, lineHeight: 17.6, color: "#0F3244" }}>{"City Super Market"}</Text>
      <Text style={{ position: "absolute", left: 236, top: 551, width: 104, textAlign: "right", fontFamily: "PlusJakartaSans_800ExtraBold", fontSize: 13, lineHeight: 17.6, color: "#0F3244" }}>{"₹ 1.9L"}</Text>
      <Text style={{ position: "absolute", left: 74, top: 568, width: 170, textAlign: "left", fontFamily: "PlusJakartaSans_500Medium", fontSize: 11, lineHeight: 14.9, color: "#6B8796" }}>{"Product Sampling"}</Text>
      <View style={{ position: "absolute", left: 334, top: 572, width: 14, height: 14 }} pointerEvents="box-none">{/* "ic-chevron-right" */}
        <SvgXml xml={SVG_32} width={6.5} height={10} style={{ position: "absolute", left: 3.8, top: 2 }} />
      </View>
      <View style={{ position: "absolute", left: 74, top: 588, width: 93, height: 19, backgroundColor: "#FDF0E0", borderRadius: 9.5 }} />
      <Text style={{ position: "absolute", left: 84, top: 591, width: 78, textAlign: "left", fontFamily: "PlusJakartaSans_700Bold", fontSize: 9.5, lineHeight: 12.8, color: "#C97A09" }}>{"Proposal Sent"}</Text>
      <Text style={{ position: "absolute", left: 175, top: 590, width: 32, textAlign: "left", fontFamily: "PlusJakartaSans_800ExtraBold", fontSize: 10, lineHeight: 13.5, color: "#0F3244" }}>{"80%"}</Text>
      <View style={{ position: "absolute", left: 228, top: 590, width: 12, height: 12 }} pointerEvents="box-none">{/* "ic-calendar" */}
        <SvgXml xml={SVG_33} width={3} height={5} style={{ position: "absolute", left: 2.5, top: -0.5 }} />
        <SvgXml xml={SVG_34} width={3} height={5} style={{ position: "absolute", left: 6.5, top: -0.5 }} />
        <View style={{ position: "absolute", left: 1.5, top: 2, width: 9, height: 9, borderRadius: 2, borderWidth: 2, borderColor: "#8AA3B0" }} />
        <SvgXml xml={SVG_35} width={12} height={3} style={{ position: "absolute", left: 0, top: 3.5 }} />
      </View>
      <Text style={{ position: "absolute", left: 244, top: 589, width: 90, textAlign: "left", fontFamily: "PlusJakartaSans_500Medium", fontSize: 10, lineHeight: 13.5, color: "#6B8796" }}>{"05 Oct 2026"}</Text>
      <View style={{ position: "absolute", left: 18, top: 624, width: 340, height: 74, backgroundColor: "#FFFFFF", borderRadius: 14, borderWidth: 1, borderColor: "#E6EFF3", boxShadow: "0px 2px 8px 0px rgba(15,50,68,0.05)" }} />
      <View style={{ position: "absolute", left: 30, top: 633, width: 34, height: 34, backgroundColor: "#E8F6EE", borderRadius: 17 }} />
      <Text style={{ position: "absolute", left: 30, top: 642.4, width: 34, textAlign: "center", fontFamily: "PlusJakartaSans_800ExtraBold", fontSize: 11, lineHeight: 14.9, letterSpacing: 0.2, color: "#0E7A4A" }}>{"VE"}</Text>
      <Text style={{ position: "absolute", left: 74, top: 633, width: 156, textAlign: "left", fontFamily: "PlusJakartaSans_700Bold", fontSize: 13, lineHeight: 17.6, color: "#0F3244" }}>{"Value Fresh"}</Text>
      <Text style={{ position: "absolute", left: 236, top: 633, width: 104, textAlign: "right", fontFamily: "PlusJakartaSans_800ExtraBold", fontSize: 13, lineHeight: 17.6, color: "#0F3244" }}>{"₹ 2.4L"}</Text>
      <Text style={{ position: "absolute", left: 74, top: 650, width: 170, textAlign: "left", fontFamily: "PlusJakartaSans_500Medium", fontSize: 11, lineHeight: 14.9, color: "#6B8796" }}>{"Regional Expansion"}</Text>
      <View style={{ position: "absolute", left: 334, top: 654, width: 14, height: 14 }} pointerEvents="box-none">{/* "ic-chevron-right" */}
        <SvgXml xml={SVG_36} width={6.5} height={10} style={{ position: "absolute", left: 3.8, top: 2 }} />
      </View>
      <View style={{ position: "absolute", left: 74, top: 670, width: 82, height: 19, backgroundColor: "#EAF2F7", borderRadius: 9.5 }} />
      <Text style={{ position: "absolute", left: 84, top: 673, width: 67, textAlign: "left", fontFamily: "PlusJakartaSans_700Bold", fontSize: 9.5, lineHeight: 12.8, color: "#4B7C93" }}>{"Negotiation"}</Text>
      <Text style={{ position: "absolute", left: 164, top: 672, width: 32, textAlign: "left", fontFamily: "PlusJakartaSans_800ExtraBold", fontSize: 10, lineHeight: 13.5, color: "#0F3244" }}>{"70%"}</Text>
      <View style={{ position: "absolute", left: 228, top: 672, width: 12, height: 12 }} pointerEvents="box-none">{/* "ic-calendar" */}
        <SvgXml xml={SVG_37} width={3} height={5} style={{ position: "absolute", left: 2.5, top: -0.5 }} />
        <SvgXml xml={SVG_38} width={3} height={5} style={{ position: "absolute", left: 6.5, top: -0.5 }} />
        <View style={{ position: "absolute", left: 1.5, top: 2, width: 9, height: 9, borderRadius: 2, borderWidth: 2, borderColor: "#8AA3B0" }} />
        <SvgXml xml={SVG_39} width={12} height={3} style={{ position: "absolute", left: 0, top: 3.5 }} />
      </View>
      <Text style={{ position: "absolute", left: 244, top: 671, width: 90, textAlign: "left", fontFamily: "PlusJakartaSans_500Medium", fontSize: 10, lineHeight: 13.5, color: "#6B8796" }}>{"12 Oct 2026"}</Text>
      <View style={{ position: "absolute", left: 0, top: 807, width: 376, height: 52, backgroundColor: "#FFFFFF", boxShadow: "0px -3px 14px 0px rgba(15,50,68,0.08)" }} />
      <View style={{ position: "absolute", left: 42, top: 817, width: 21, height: 21 }} pointerEvents="box-none">{/* "ic-house" */}
        <SvgXml xml={SVG_40} width={8.3} height={10.9} style={{ position: "absolute", left: 6.4, top: 9 }} />
        <SvgXml xml={SVG_41} width={18.8} height={19.6} style={{ position: "absolute", left: 1.1, top: 0.3 }} />
      </View>
      <Text style={{ position: "absolute", left: 11, top: 842, width: 83, textAlign: "center", fontFamily: "PlusJakartaSans_600SemiBold", fontSize: 10, lineHeight: 13.5, color: "#8AA3B0" }}>{"Home"}</Text>
      <View style={{ position: "absolute", left: 109, top: 817, width: 21, height: 21 }} pointerEvents="box-none">{/* "ic-layout-grid" */}
        <View style={{ position: "absolute", left: 2.6, top: 2.6, width: 6.1, height: 6.1, borderRadius: 1, borderWidth: 2, borderColor: "#17A45E" }} />
        <View style={{ position: "absolute", left: 12.3, top: 2.6, width: 6.1, height: 6.1, borderRadius: 1, borderWidth: 2, borderColor: "#17A45E" }} />
        <View style={{ position: "absolute", left: 12.3, top: 12.3, width: 6.1, height: 6.1, borderRadius: 1, borderWidth: 2, borderColor: "#17A45E" }} />
        <View style={{ position: "absolute", left: 2.6, top: 12.3, width: 6.1, height: 6.1, borderRadius: 1, borderWidth: 2, borderColor: "#17A45E" }} />
      </View>
      <Text style={{ position: "absolute", left: 78, top: 842, width: 83, textAlign: "center", fontFamily: "PlusJakartaSans_700Bold", fontSize: 10, lineHeight: 13.5, color: "#17A45E" }}>{"Pipeline"}</Text>
      <View style={{ position: "absolute", left: 246, top: 817, width: 21, height: 21 }} pointerEvents="box-none">{/* "ic-users" */}
        <SvgXml xml={SVG_42} width={15.3} height={8.3} style={{ position: "absolute", left: 0.3, top: 11.6 }} />
        <View style={{ position: "absolute", left: 4.4, top: 2.6, width: 7, height: 7, borderRadius: 3.5, borderWidth: 2, borderColor: "#8AA3B0" }} />
        <SvgXml xml={SVG_43} width={5.6} height={8.1} style={{ position: "absolute", left: 15.1, top: 11.7 }} />
        <SvgXml xml={SVG_44} width={5.6} height={9.8} style={{ position: "absolute", left: 12.5, top: 1.2 }} />
      </View>
      <Text style={{ position: "absolute", left: 215, top: 842, width: 83, textAlign: "center", fontFamily: "PlusJakartaSans_600SemiBold", fontSize: 10, lineHeight: 13.5, color: "#8AA3B0" }}>{"Customers"}</Text>
      <View style={{ position: "absolute", left: 313, top: 817, width: 21, height: 21 }} pointerEvents="box-none">{/* "ic-ellipsis" */}
        <View style={{ position: "absolute", left: 9.6, top: 9.6, width: 1.8, height: 1.8, borderRadius: 0.9, borderWidth: 2, borderColor: "#8AA3B0" }} />
        <View style={{ position: "absolute", left: 15.8, top: 9.6, width: 1.8, height: 1.8, borderRadius: 0.9, borderWidth: 2, borderColor: "#8AA3B0" }} />
        <View style={{ position: "absolute", left: 3.5, top: 9.6, width: 1.8, height: 1.8, borderRadius: 0.9, borderWidth: 2, borderColor: "#8AA3B0" }} />
      </View>
      <Text style={{ position: "absolute", left: 282, top: 842, width: 83, textAlign: "center", fontFamily: "PlusJakartaSans_600SemiBold", fontSize: 10, lineHeight: 13.5, color: "#8AA3B0" }}>{"More"}</Text>
      <View style={{ position: "absolute", left: 159, top: 788, width: 57, height: 57, backgroundColor: "#FFFFFF", borderRadius: 28.5 }} />
      <View style={{ position: "absolute", left: 161, top: 790, width: 53, height: 53, backgroundColor: "#17A45E", borderRadius: 26.5, boxShadow: "0px 4px 12px 0px rgba(14,122,74,0.2)" }} />
      <View style={{ position: "absolute", left: 175, top: 804, width: 25, height: 25 }} pointerEvents="box-none">{/* "ic-plus" */}
        <SvgXml xml={SVG_45} width={18} height={3.4} style={{ position: "absolute", left: 3.5, top: 10.8 }} />
        <SvgXml xml={SVG_46} width={3.4} height={18} style={{ position: "absolute", left: 10.8, top: 3.5 }} />
      </View>
    </View>
  );
}
