/* GENERATED by tools/penpot-to-code/to-react-native.mjs from the Penpot
 * board "03A.1 Pipeline List". Do not edit: regenerate with
 * `pnpm design:rn`. Its text is the board's sample copy — a design
 * reference, not a screen.
 */
import React from "react";
import { View, Text } from "react-native";
import { SvgXml } from "react-native-svg";

export const size = { width: 376, height: 859 } as const;

const SVG_0 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"16.2\" height=\"5.3\" viewBox=\"657.4 10519.8 16.2 5.3\" fill=\"none\"><path d=\"M659.0,10523.5C662.8698120117188,10520.6650390625,668.1301879882812,10520.6650390625,672.0,10523.5\" fill=\"none\" stroke=\"#0f3244\" stroke-width=\"2.2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_1 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"10.2\" height=\"4.2\" viewBox=\"660.4 10524.6 10.2 4.2\" fill=\"none\"><path d=\"M662.0,10527.2001953125C664.1340942382812,10525.8359375,666.8659057617188,10525.8359375,669.0,10527.2001953125\" fill=\"none\" stroke=\"#0f3244\" stroke-width=\"2.2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_2 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"9.4\" height=\"15.8\" viewBox=\"377.1 10549.1 9.4 15.8\" fill=\"none\"><path d=\"M385.0,10563.4169921875L378.5833435058594,10557.0L385.0,10550.5830078125\" fill=\"none\" stroke=\"#0f3244\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_3 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"15.8\" height=\"3\" viewBox=\"377.1 10555.5 15.8 3\" fill=\"none\"><path d=\"M391.4166564941406,10557.0L378.5833435058594,10557.0\" fill=\"none\" stroke=\"#0f3244\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" transform=\"translate(385 10557) matrix(1,0,0,0.916666666666643,-1.1368683772161603e-13,-0.000381944444458715) translate(-385 -10557)\"/></svg>";
const SVG_4 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"21.3\" height=\"20.4\" viewBox=\"692.3 10547.3 21.3 20.4\" fill=\"none\"><path d=\"M701.1666870117188,10564.3330078125C701.16650390625,10564.6806640625,701.36279296875,10564.998046875,701.673583984375,10565.1533203125L703.5068969726562,10566.0703125C703.7911376953125,10566.212890625,704.128662109375,10566.197265625,704.3988647460938,10566.0302734375C704.6690673828125,10565.86328125,704.83349609375,10565.5673828125,704.8333129882812,10565.25L704.8333129882812,10558.8330078125C704.8335571289062,10558.37890625,705.00244140625,10557.94140625,705.3072509765625,10557.6044921875L711.9283447265625,10550.28125C712.1707763671875,10550.0126953125,712.2324829101562,10549.6259765625,712.0859375,10549.294921875C711.9393310546875,10548.96484375,711.61181640625,10548.7509765625,711.25,10548.75L694.75,10548.75C694.3878173828125,10548.75,694.0596923828125,10548.9638671875,693.91259765625,10549.294921875C693.7655639648438,10549.625,693.8271484375,10550.01171875,694.06982421875,10550.28125L700.6927490234375,10557.6044921875C700.99755859375,10557.94140625,701.1664428710938,10558.37890625,701.1666870117188,10558.8330078125L701.1666870117188,10564.3330078125\" fill=\"none\" stroke=\"#17a45e\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_5 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"3\" height=\"3\" viewBox=\"400.4 10596.6 3 3\" fill=\"none\"><path d=\"M401.875,10598.125L401.8812561035156,10598.125\" fill=\"none\" stroke=\"#ffffff\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" transform=\"translate(401.9 10598.1) matrix(0.625,0,0,0.625,-0.0011718753346947608,-0.0011718752937674992) translate(-401.9 -10598.1)\"/></svg>";
const SVG_6 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"3\" height=\"3\" viewBox=\"400.4 10601 3 3\" fill=\"none\"><path d=\"M401.875,10602.5L401.8812561035156,10602.5\" fill=\"none\" stroke=\"#ffffff\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" transform=\"translate(401.9 10602.5) matrix(0.625,0,0,0.625,-0.0011718753383327396,-0.0011718751502938218) translate(-401.9 -10602.5)\"/></svg>";
const SVG_7 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"3\" height=\"3\" viewBox=\"400.4 10605.4 3 3\" fill=\"none\"><path d=\"M401.875,10606.875L401.8812561035156,10606.875\" fill=\"none\" stroke=\"#ffffff\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" transform=\"translate(401.9 10606.9) matrix(0.625,0,0,0.6250000000001101,-0.0011718749991196376,-0.0011718749999786032) translate(-401.9 -10606.9)\"/></svg>";
const SVG_8 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"11.1\" height=\"3\" viewBox=\"403.5 10596.6 11.1 3\" fill=\"none\"><path d=\"M405.0,10598.125L413.125,10598.125\" fill=\"none\" stroke=\"#ffffff\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" transform=\"translate(409.1 10598.1) matrix(1,0,0,0.6249999999998863,9.094947017729282e-13,-0.0011718749999012346) translate(-409.1 -10598.1)\"/></svg>";
const SVG_9 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"11.1\" height=\"3\" viewBox=\"403.5 10601 11.1 3\" fill=\"none\"><path d=\"M405.0,10602.5L413.125,10602.5\" fill=\"none\" stroke=\"#ffffff\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" transform=\"translate(409.1 10602.5) matrix(1,0,0,0.625,0,-0.001171875000227196) translate(-409.1 -10602.5)\"/></svg>";
const SVG_10 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"11.1\" height=\"3\" viewBox=\"403.5 10605.4 11.1 3\" fill=\"none\"><path d=\"M405.0,10606.875L413.125,10606.875\" fill=\"none\" stroke=\"#ffffff\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" transform=\"translate(409.1 10606.9) matrix(0.9999999999999999,0,0,0.6250000000001421,-1.3766765505351941e-14,-0.0011718749999998224) translate(-409.1 -10606.9)\"/></svg>";
const SVG_11 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"6\" height=\"6\" viewBox=\"398.3 10657.3 6 6\" fill=\"none\"><path d=\"M402.875,10661.875L399.82916259765625,10658.8291015625\" fill=\"none\" stroke=\"#8aa3b0\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_12 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"8.8\" height=\"3\" viewBox=\"684 10649.7 8.8 3\" fill=\"none\"><path d=\"M691.3333129882812,10651.1669921875L685.5,10651.1669921875\" fill=\"none\" stroke=\"#6b8796\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" transform=\"translate(688.4 10651.2) matrix(0.9999999999999999,0,0,0.8333333333333712,8.881784197001252e-16,-0.0006944444439325181) translate(-688.4 -10651.2)\"/></svg>";
const SVG_13 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"10.5\" height=\"3\" viewBox=\"684 10661.3 10.5 3\" fill=\"none\"><path d=\"M693.0,10662.8330078125L685.5,10662.8330078125\" fill=\"none\" stroke=\"#6b8796\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" transform=\"translate(689.3 10662.8) matrix(1,0,0,0.8333333333334849,0,-0.0006944444442922304) translate(-689.3 -10662.8)\"/></svg>";
const SVG_14 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"3\" height=\"6.3\" viewBox=\"693.2 10648 3 6.3\" fill=\"none\"><path d=\"M694.6666870117188,10649.5L694.6666870117188,10652.8330078125\" fill=\"none\" stroke=\"#6b8796\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" transform=\"translate(694.7 10651.2) matrix(0.8333333333333144,0,0,1.0000000000000042,-0.0006944444444456632,2.7533531010703882e-14) translate(-694.7 -10651.2)\"/></svg>";
const SVG_15 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"3\" height=\"6.3\" viewBox=\"694.8 10659.7 3 6.3\" fill=\"none\"><path d=\"M696.3333129882812,10661.1669921875L696.3333129882812,10664.5\" fill=\"none\" stroke=\"#6b8796\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" transform=\"translate(696.3 10662.8) matrix(0.8333333333334849,0,0,1.0000000000000044,-0.0006944444444518805,-3.68594044175552e-14) translate(-696.3 -10662.8)\"/></svg>";
const SVG_16 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"10.5\" height=\"3\" viewBox=\"691.5 10655.5 10.5 3\" fill=\"none\"><path d=\"M700.5,10657.0L693.0,10657.0\" fill=\"none\" stroke=\"#6b8796\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" transform=\"translate(696.8 10657) matrix(1,0,0,0.8333333333333144,-5.684341886080802e-14,-0.0006944444445013964) translate(-696.8 -10657)\"/></svg>";
const SVG_17 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"7.2\" height=\"3\" viewBox=\"694.8 10661.3 7.2 3\" fill=\"none\"><path d=\"M700.5,10662.8330078125L696.3333129882812,10662.8330078125\" fill=\"none\" stroke=\"#6b8796\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" transform=\"translate(698.4 10662.8) matrix(1.0000000000000002,0,0,0.8333333333334849,1.7141843500212417e-13,-0.0006944444442922304) translate(-698.4 -10662.8)\"/></svg>";
const SVG_18 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"8.8\" height=\"3\" viewBox=\"693.2 10649.7 8.8 3\" fill=\"none\"><path d=\"M700.5,10651.1669921875L694.6666870117188,10651.1669921875\" fill=\"none\" stroke=\"#6b8796\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" transform=\"translate(697.6 10651.2) matrix(1,0,0,0.8333333333333712,0,-0.0006944444448420128) translate(-697.6 -10651.2)\"/></svg>";
const SVG_19 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"3\" height=\"6.3\" viewBox=\"688.2 10653.8 3 6.3\" fill=\"none\"><path d=\"M689.6666870117188,10655.3330078125L689.6666870117188,10658.6669921875\" fill=\"none\" stroke=\"#6b8796\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" transform=\"translate(689.7 10657) matrix(0.8333333333334849,0,0,1.0000000000000355,-0.0006944444456120635,-4.4719783431901305e-13) translate(-689.7 -10657)\"/></svg>";
const SVG_20 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"7.2\" height=\"3\" viewBox=\"684 10655.5 7.2 3\" fill=\"none\"><path d=\"M689.6666870117188,10657.0L685.5,10657.0\" fill=\"none\" stroke=\"#6b8796\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" transform=\"translate(687.6 10657) matrix(1,0,0,0.8333333333333144,-2.2737367544323206e-13,-0.000694444444444553) translate(-687.6 -10657)\"/></svg>";
const SVG_21 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"8.3\" height=\"3\" viewBox=\"686.8 10699.3 8.3 3\" fill=\"none\"><path d=\"M693.5,10700.75L688.25,10700.75\" fill=\"none\" stroke=\"#6b8796\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" transform=\"translate(690.9 10700.8) matrix(0.9999999999999999,0,0,0.7500000000001137,8.881784197001252e-16,-0.0009375000000284572) translate(-690.9 -10700.8)\"/></svg>";
const SVG_22 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"9.8\" height=\"3\" viewBox=\"686.8 10709.8 9.8 3\" fill=\"none\"><path d=\"M695.0,10711.25L688.25,10711.25\" fill=\"none\" stroke=\"#6b8796\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" transform=\"translate(691.6 10711.3) matrix(1,0,0,0.7500000000001137,0,-0.0009375000000850786) translate(-691.6 -10711.3)\"/></svg>";
const SVG_23 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"3\" height=\"6\" viewBox=\"695 10697.8 3 6\" fill=\"none\"><path d=\"M696.5,10699.25L696.5,10702.25\" fill=\"none\" stroke=\"#6b8796\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" transform=\"translate(696.5 10700.8) matrix(0.7499999999999716,0,0,0.9999999999999925,-0.0009374999998952305,6.661338147750939e-13) translate(-696.5 -10700.8)\"/></svg>";
const SVG_24 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"3\" height=\"6\" viewBox=\"696.5 10708.3 3 6\" fill=\"none\"><path d=\"M698.0,10709.75L698.0,10712.75\" fill=\"none\" stroke=\"#6b8796\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" transform=\"translate(698 10711.3) matrix(0.7500000000001172,0,0,1.0000000000000002,-0.0009374999999997068,4.440892098500626e-16) translate(-698 -10711.3)\"/></svg>";
const SVG_25 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"9.8\" height=\"3\" viewBox=\"693.5 10704.5 9.8 3\" fill=\"none\"><path d=\"M701.75,10706.0L695.0,10706.0\" fill=\"none\" stroke=\"#6b8796\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" transform=\"translate(698.4 10706) matrix(1,0,0,0.7499999999999432,-2.2737367544323206e-13,-0.0009374999999431921) translate(-698.4 -10706)\"/></svg>";
const SVG_26 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"6.8\" height=\"3\" viewBox=\"696.5 10709.8 6.8 3\" fill=\"none\"><path d=\"M701.75,10711.25L698.0,10711.25\" fill=\"none\" stroke=\"#6b8796\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" transform=\"translate(699.9 10711.3) matrix(1,0,0,0.7500000000001137,0,-0.0009375000000282352) translate(-699.9 -10711.3)\"/></svg>";
const SVG_27 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"8.3\" height=\"3\" viewBox=\"695 10699.3 8.3 3\" fill=\"none\"><path d=\"M701.75,10700.75L696.5,10700.75\" fill=\"none\" stroke=\"#6b8796\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" transform=\"translate(699.1 10700.8) matrix(0.9999999999999999,0,0,0.7500000000001137,2.2715163083830703e-13,-0.0009375000000284572) translate(-699.1 -10700.8)\"/></svg>";
const SVG_28 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"3\" height=\"6\" viewBox=\"690.5 10703 3 6\" fill=\"none\"><path d=\"M692.0,10704.5L692.0,10707.5\" fill=\"none\" stroke=\"#6b8796\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" transform=\"translate(692 10706) matrix(0.75,0,0,0.9999999999999407,-0.0009374999992894928,3.552713678800501e-13) translate(-692 -10706)\"/></svg>";
const SVG_29 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"6.8\" height=\"3\" viewBox=\"686.8 10704.5 6.8 3\" fill=\"none\"><path d=\"M692.0,10706.0L688.25,10706.0\" fill=\"none\" stroke=\"#6b8796\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" transform=\"translate(690.1 10706) matrix(1,0,0,0.7499999999999432,-4.547473508864641e-13,-0.0009374999997158184) translate(-690.1 -10706)\"/></svg>";
const SVG_30 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"6.5\" height=\"10\" viewBox=\"693.8 10772 6.5 10\" fill=\"none\"><path d=\"M695.25,10780.5L698.75,10777.0L695.25,10773.5\" fill=\"none\" stroke=\"#8aa3b0\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_31 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"3\" height=\"5\" viewBox=\"544.5 10788.5 3 5\" fill=\"none\"><path d=\"M546.0,10790.0L546.0,10792.0\" fill=\"none\" stroke=\"#8aa3b0\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" transform=\"translate(546 10791) matrix(0.5,0,0,1,-0.0012499999988913046,1.0231815394945443e-12) translate(-546 -10791)\"/></svg>";
const SVG_32 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"3\" height=\"5\" viewBox=\"548.5 10788.5 3 5\" fill=\"none\"><path d=\"M550.0,10790.0L550.0,10792.0\" fill=\"none\" stroke=\"#8aa3b0\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" transform=\"translate(550 10791) matrix(0.5000000000001137,0,0,1,-0.001250000000809992,-1.7053025658242404e-12) translate(-550 -10791)\"/></svg>";
const SVG_33 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"12\" height=\"3\" viewBox=\"542 10792.5 12 3\" fill=\"none\"><path d=\"M543.5,10794.0L552.5,10794.0\" fill=\"none\" stroke=\"#8aa3b0\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" transform=\"translate(548 10794) matrix(0.9999999999999999,0,0,0.5,9.103828801926284e-13,-0.0012499999999997513) translate(-548 -10794)\"/></svg>";
const SVG_34 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"4\" height=\"6\" viewBox=\"640.5 10792 4 6\" fill=\"none\"><path d=\"M642.0,10793.5L642.0,10795.5L643.0,10796.5\" fill=\"none\" stroke=\"#e5484d\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_35 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"4.5\" height=\"4.5\" viewBox=\"635.5 10789 4.5 4.5\" fill=\"none\"><path d=\"M638.5,10790.5L637.0,10792.0\" fill=\"none\" stroke=\"#e5484d\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_36 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"4.5\" height=\"4.5\" viewBox=\"644 10789 4.5 4.5\" fill=\"none\"><path d=\"M647.0,10792.0L645.5,10790.5\" fill=\"none\" stroke=\"#e5484d\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_37 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"4.2\" height=\"4.1\" viewBox=\"636.5 10796.9 4.2 4.1\" fill=\"none\"><path d=\"M639.1900024414062,10798.349609375L638.0,10799.5\" fill=\"none\" stroke=\"#e5484d\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_38 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"4.2\" height=\"4.2\" viewBox=\"643.3 10796.8 4.2 4.2\" fill=\"none\"><path d=\"M644.8200073242188,10798.3349609375L646.0,10799.5\" fill=\"none\" stroke=\"#e5484d\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_39 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"6.5\" height=\"10\" viewBox=\"693.8 10856 6.5 10\" fill=\"none\"><path d=\"M695.25,10864.5L698.75,10861.0L695.25,10857.5\" fill=\"none\" stroke=\"#8aa3b0\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_40 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"3\" height=\"5\" viewBox=\"544.5 10872.5 3 5\" fill=\"none\"><path d=\"M546.0,10874.0L546.0,10876.0\" fill=\"none\" stroke=\"#8aa3b0\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" transform=\"translate(546 10875) matrix(0.5,0,0,1,-0.0012499999988913046,1.0231815394945443e-12) translate(-546 -10875)\"/></svg>";
const SVG_41 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"3\" height=\"5\" viewBox=\"548.5 10872.5 3 5\" fill=\"none\"><path d=\"M550.0,10874.0L550.0,10876.0\" fill=\"none\" stroke=\"#8aa3b0\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" transform=\"translate(550 10875) matrix(0.5000000000001137,0,0,1,-0.001250000000809992,-1.7053025658242404e-12) translate(-550 -10875)\"/></svg>";
const SVG_42 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"12\" height=\"3\" viewBox=\"542 10876.5 12 3\" fill=\"none\"><path d=\"M543.5,10878.0L552.5,10878.0\" fill=\"none\" stroke=\"#8aa3b0\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" transform=\"translate(548 10878) matrix(0.9999999999999999,0,0,0.5,9.103828801926284e-13,-0.0012499999999997513) translate(-548 -10878)\"/></svg>";
const SVG_43 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"4\" height=\"6\" viewBox=\"640.5 10876 4 6\" fill=\"none\"><path d=\"M642.0,10877.5L642.0,10879.5L643.0,10880.5\" fill=\"none\" stroke=\"#e5484d\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_44 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"4.5\" height=\"4.5\" viewBox=\"635.5 10873 4.5 4.5\" fill=\"none\"><path d=\"M638.5,10874.5L637.0,10876.0\" fill=\"none\" stroke=\"#e5484d\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_45 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"4.5\" height=\"4.5\" viewBox=\"644 10873 4.5 4.5\" fill=\"none\"><path d=\"M647.0,10876.0L645.5,10874.5\" fill=\"none\" stroke=\"#e5484d\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_46 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"4.2\" height=\"4.1\" viewBox=\"636.5 10880.9 4.2 4.1\" fill=\"none\"><path d=\"M639.1900024414062,10882.349609375L638.0,10883.5\" fill=\"none\" stroke=\"#e5484d\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_47 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"4.2\" height=\"4.2\" viewBox=\"643.3 10880.8 4.2 4.2\" fill=\"none\"><path d=\"M644.8200073242188,10882.3349609375L646.0,10883.5\" fill=\"none\" stroke=\"#e5484d\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_48 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"6.5\" height=\"10\" viewBox=\"693.8 10940 6.5 10\" fill=\"none\"><path d=\"M695.25,10948.5L698.75,10945.0L695.25,10941.5\" fill=\"none\" stroke=\"#8aa3b0\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_49 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"3\" height=\"5\" viewBox=\"544.5 10956.5 3 5\" fill=\"none\"><path d=\"M546.0,10958.0L546.0,10960.0\" fill=\"none\" stroke=\"#8aa3b0\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" transform=\"translate(546 10959) matrix(0.5,0,0,1,-0.0012499999988913046,1.0231815394945443e-12) translate(-546 -10959)\"/></svg>";
const SVG_50 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"3\" height=\"5\" viewBox=\"548.5 10956.5 3 5\" fill=\"none\"><path d=\"M550.0,10958.0L550.0,10960.0\" fill=\"none\" stroke=\"#8aa3b0\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" transform=\"translate(550 10959) matrix(0.5000000000001137,0,0,1,-0.001250000000809992,-1.7053025658242404e-12) translate(-550 -10959)\"/></svg>";
const SVG_51 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"12\" height=\"3\" viewBox=\"542 10960.5 12 3\" fill=\"none\"><path d=\"M543.5,10962.0L552.5,10962.0\" fill=\"none\" stroke=\"#8aa3b0\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" transform=\"translate(548 10962) matrix(0.9999999999999999,0,0,0.5,9.103828801926284e-13,-0.0012499999999997513) translate(-548 -10962)\"/></svg>";
const SVG_52 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"4\" height=\"6\" viewBox=\"640.5 10960 4 6\" fill=\"none\"><path d=\"M642.0,10961.5L642.0,10963.5L643.0,10964.5\" fill=\"none\" stroke=\"#e5484d\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_53 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"4.5\" height=\"4.5\" viewBox=\"635.5 10957 4.5 4.5\" fill=\"none\"><path d=\"M638.5,10958.5L637.0,10960.0\" fill=\"none\" stroke=\"#e5484d\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_54 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"4.5\" height=\"4.5\" viewBox=\"644 10957 4.5 4.5\" fill=\"none\"><path d=\"M647.0,10960.0L645.5,10958.5\" fill=\"none\" stroke=\"#e5484d\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_55 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"4.2\" height=\"4.1\" viewBox=\"636.5 10964.9 4.2 4.1\" fill=\"none\"><path d=\"M639.1900024414062,10966.349609375L638.0,10967.5\" fill=\"none\" stroke=\"#e5484d\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_56 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"4.2\" height=\"4.2\" viewBox=\"643.3 10964.8 4.2 4.2\" fill=\"none\"><path d=\"M644.8200073242188,10966.3349609375L646.0,10967.5\" fill=\"none\" stroke=\"#e5484d\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_57 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"6.5\" height=\"10\" viewBox=\"693.8 11024 6.5 10\" fill=\"none\"><path d=\"M695.25,11032.5L698.75,11029.0L695.25,11025.5\" fill=\"none\" stroke=\"#8aa3b0\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_58 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"3\" height=\"5\" viewBox=\"544.5 11040.5 3 5\" fill=\"none\"><path d=\"M546.0,11042.0L546.0,11044.0\" fill=\"none\" stroke=\"#8aa3b0\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" transform=\"translate(546 11043) matrix(0.5,0,0,1,-0.0012499999988913046,1.0231815394945443e-12) translate(-546 -11043)\"/></svg>";
const SVG_59 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"3\" height=\"5\" viewBox=\"548.5 11040.5 3 5\" fill=\"none\"><path d=\"M550.0,11042.0L550.0,11044.0\" fill=\"none\" stroke=\"#8aa3b0\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" transform=\"translate(550 11043) matrix(0.5000000000001137,0,0,1,-0.001250000000809992,-1.7053025658242404e-12) translate(-550 -11043)\"/></svg>";
const SVG_60 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"12\" height=\"3\" viewBox=\"542 11044.5 12 3\" fill=\"none\"><path d=\"M543.5,11046.0L552.5,11046.0\" fill=\"none\" stroke=\"#8aa3b0\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" transform=\"translate(548 11046) matrix(0.9999999999999999,0,0,0.5,9.103828801926284e-13,-0.0012499999999997513) translate(-548 -11046)\"/></svg>";
const SVG_61 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"4\" height=\"6\" viewBox=\"640.5 11044 4 6\" fill=\"none\"><path d=\"M642.0,11045.5L642.0,11047.5L643.0,11048.5\" fill=\"none\" stroke=\"#e5484d\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_62 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"4.5\" height=\"4.5\" viewBox=\"635.5 11041 4.5 4.5\" fill=\"none\"><path d=\"M638.5,11042.5L637.0,11044.0\" fill=\"none\" stroke=\"#e5484d\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_63 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"4.5\" height=\"4.5\" viewBox=\"644 11041 4.5 4.5\" fill=\"none\"><path d=\"M647.0,11044.0L645.5,11042.5\" fill=\"none\" stroke=\"#e5484d\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_64 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"4.2\" height=\"4.1\" viewBox=\"636.5 11048.9 4.2 4.1\" fill=\"none\"><path d=\"M639.1900024414062,11050.349609375L638.0,11051.5\" fill=\"none\" stroke=\"#e5484d\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_65 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"4.2\" height=\"4.2\" viewBox=\"643.3 11048.8 4.2 4.2\" fill=\"none\"><path d=\"M644.8200073242188,11050.3349609375L646.0,11051.5\" fill=\"none\" stroke=\"#e5484d\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_66 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"6.5\" height=\"10\" viewBox=\"693.8 11108 6.5 10\" fill=\"none\"><path d=\"M695.25,11116.5L698.75,11113.0L695.25,11109.5\" fill=\"none\" stroke=\"#8aa3b0\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_67 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"3\" height=\"5\" viewBox=\"544.5 11124.5 3 5\" fill=\"none\"><path d=\"M546.0,11126.0L546.0,11128.0\" fill=\"none\" stroke=\"#8aa3b0\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" transform=\"translate(546 11127) matrix(0.5,0,0,1,-0.0012499999988913046,1.0231815394945443e-12) translate(-546 -11127)\"/></svg>";
const SVG_68 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"3\" height=\"5\" viewBox=\"548.5 11124.5 3 5\" fill=\"none\"><path d=\"M550.0,11126.0L550.0,11128.0\" fill=\"none\" stroke=\"#8aa3b0\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" transform=\"translate(550 11127) matrix(0.5000000000001137,0,0,1,-0.001250000000809992,-1.7053025658242404e-12) translate(-550 -11127)\"/></svg>";
const SVG_69 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"12\" height=\"3\" viewBox=\"542 11128.5 12 3\" fill=\"none\"><path d=\"M543.5,11130.0L552.5,11130.0\" fill=\"none\" stroke=\"#8aa3b0\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" transform=\"translate(548 11130) matrix(0.9999999999999999,0,0,0.5,9.103828801926284e-13,-0.0012499999999997513) translate(-548 -11130)\"/></svg>";
const SVG_70 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"4\" height=\"6\" viewBox=\"640.5 11128 4 6\" fill=\"none\"><path d=\"M642.0,11129.5L642.0,11131.5L643.0,11132.5\" fill=\"none\" stroke=\"#e5484d\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_71 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"4.5\" height=\"4.5\" viewBox=\"635.5 11125 4.5 4.5\" fill=\"none\"><path d=\"M638.5,11126.5L637.0,11128.0\" fill=\"none\" stroke=\"#e5484d\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_72 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"4.5\" height=\"4.5\" viewBox=\"644 11125 4.5 4.5\" fill=\"none\"><path d=\"M647.0,11128.0L645.5,11126.5\" fill=\"none\" stroke=\"#e5484d\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_73 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"4.2\" height=\"4.1\" viewBox=\"636.5 11132.9 4.2 4.1\" fill=\"none\"><path d=\"M639.1900024414062,11134.349609375L638.0,11135.5\" fill=\"none\" stroke=\"#e5484d\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_74 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"4.2\" height=\"4.2\" viewBox=\"643.3 11132.8 4.2 4.2\" fill=\"none\"><path d=\"M644.8200073242188,11134.3349609375L646.0,11135.5\" fill=\"none\" stroke=\"#e5484d\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_75 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"6.5\" height=\"10\" viewBox=\"693.8 11192 6.5 10\" fill=\"none\"><path d=\"M695.25,11200.5L698.75,11197.0L695.25,11193.5\" fill=\"none\" stroke=\"#8aa3b0\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_76 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"3\" height=\"5\" viewBox=\"544.5 11208.5 3 5\" fill=\"none\"><path d=\"M546.0,11210.0L546.0,11212.0\" fill=\"none\" stroke=\"#8aa3b0\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" transform=\"translate(546 11211) matrix(0.5,0,0,1,-0.0012499999988913046,1.0231815394945443e-12) translate(-546 -11211)\"/></svg>";
const SVG_77 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"3\" height=\"5\" viewBox=\"548.5 11208.5 3 5\" fill=\"none\"><path d=\"M550.0,11210.0L550.0,11212.0\" fill=\"none\" stroke=\"#8aa3b0\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" transform=\"translate(550 11211) matrix(0.5000000000001137,0,0,1,-0.001250000000809992,-1.7053025658242404e-12) translate(-550 -11211)\"/></svg>";
const SVG_78 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"12\" height=\"3\" viewBox=\"542 11212.5 12 3\" fill=\"none\"><path d=\"M543.5,11214.0L552.5,11214.0\" fill=\"none\" stroke=\"#8aa3b0\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" transform=\"translate(548 11214) matrix(0.9999999999999999,0,0,0.5,9.103828801926284e-13,-0.0012499999999997513) translate(-548 -11214)\"/></svg>";
const SVG_79 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"4\" height=\"6\" viewBox=\"640.5 11212 4 6\" fill=\"none\"><path d=\"M642.0,11213.5L642.0,11215.5L643.0,11216.5\" fill=\"none\" stroke=\"#e5484d\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_80 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"4.5\" height=\"4.5\" viewBox=\"635.5 11209 4.5 4.5\" fill=\"none\"><path d=\"M638.5,11210.5L637.0,11212.0\" fill=\"none\" stroke=\"#e5484d\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_81 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"4.5\" height=\"4.5\" viewBox=\"644 11209 4.5 4.5\" fill=\"none\"><path d=\"M647.0,11212.0L645.5,11210.5\" fill=\"none\" stroke=\"#e5484d\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_82 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"4.2\" height=\"4.1\" viewBox=\"636.5 11216.9 4.2 4.1\" fill=\"none\"><path d=\"M639.1900024414062,11218.349609375L638.0,11219.5\" fill=\"none\" stroke=\"#e5484d\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_83 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"4.2\" height=\"4.2\" viewBox=\"643.3 11216.8 4.2 4.2\" fill=\"none\"><path d=\"M644.8200073242188,11218.3349609375L646.0,11219.5\" fill=\"none\" stroke=\"#e5484d\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_84 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"8.3\" height=\"10.9\" viewBox=\"404.4 11326 8.3 10.9\" fill=\"none\"><path d=\"M411.125,11335.375L411.125,11328.375C411.125,11327.8916015625,410.7332458496094,11327.5,410.25,11327.5L406.75,11327.5C406.2667541503906,11327.5,405.875,11327.8916015625,405.875,11328.375L405.875,11335.375\" fill=\"none\" stroke=\"#8aa3b0\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_85 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"18.8\" height=\"19.6\" viewBox=\"399.1 11317.3 18.8 19.6\" fill=\"none\"><path d=\"M400.625,11325.75C400.6248779296875,11325.234375,400.8518371582031,11324.7451171875,401.245361328125,11324.4130859375L407.370361328125,11319.1640625C408.0225830078125,11318.6123046875,408.9774169921875,11318.6123046875,409.629638671875,11319.1640625L415.754638671875,11324.4130859375C416.1481628417969,11324.7451171875,416.3751220703125,11325.234375,416.375,11325.75L416.375,11333.625C416.375,11334.591796875,415.59149169921875,11335.375,414.625,11335.375L402.375,11335.375C401.40850830078125,11335.375,400.625,11334.591796875,400.625,11333.625L400.625,11325.75\" fill=\"none\" stroke=\"#8aa3b0\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_86 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"15.3\" height=\"8.3\" viewBox=\"602.3 11328.6 15.3 8.3\" fill=\"none\"><path d=\"M616.0,11335.375L616.0,11333.625C616.0,11331.6923828125,614.4329833984375,11330.125,612.5,11330.125L607.25,11330.125C605.3170166015625,11330.125,603.75,11331.6923828125,603.75,11333.625L603.75,11335.375\" fill=\"none\" stroke=\"#8aa3b0\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_87 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"5.6\" height=\"8.1\" viewBox=\"617.1 11328.7 5.6 8.1\" fill=\"none\"><path d=\"M621.25,11335.375L621.25,11333.625C621.248779296875,11332.0302734375,620.1693725585938,11330.6376953125,618.625,11330.23828125\" fill=\"none\" stroke=\"#8aa3b0\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_88 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"5.6\" height=\"9.8\" viewBox=\"614.5 11318.2 5.6 9.8\" fill=\"none\"><path d=\"M616.0,11319.73828125C617.5486450195312,11320.1357421875,618.6318359375,11321.5302734375,618.6318359375,11323.12890625C618.6318359375,11324.7275390625,617.5486450195312,11326.123046875,616.0,11326.51953125\" fill=\"none\" stroke=\"#8aa3b0\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_89 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"18\" height=\"3.4\" viewBox=\"534.5 11314.8 18 3.4\" fill=\"none\"><path d=\"M536.2083129882812,11316.5L550.7916870117188,11316.5\" fill=\"none\" stroke=\"#ffffff\" stroke-width=\"2.4\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_90 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"3.4\" height=\"18\" viewBox=\"541.8 11307.5 3.4 18\" fill=\"none\"><path d=\"M543.5,11309.2080078125L543.5,11323.7919921875\" fill=\"none\" stroke=\"#ffffff\" stroke-width=\"2.4\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";

export default function Penpot03a1PipelineList() {
  return (
    <View style={{ width: 376, height: 859, backgroundColor: "#F8FBFC", borderRadius: 34, overflow: "hidden" }}>{/* "03A.1 Pipeline List" */}
      <Text style={{ position: "absolute", left: 24, top: 11, width: 78, textAlign: "left", fontFamily: "PlusJakartaSans_700Bold", fontSize: 14, lineHeight: 18.9, color: "#0F3244" }}>{"9:41"}</Text>
      <View style={{ position: "absolute", left: 277, top: 16, width: 75, height: 20 }} pointerEvents="box-none">{/* "status-icons" */}
        <View style={{ position: "absolute", left: 0, top: 12, width: 3.5, height: 5, backgroundColor: "#0F3244", borderRadius: 1 }} />
        <View style={{ position: "absolute", left: 5.5, top: 9, width: 3.5, height: 8, backgroundColor: "#0F3244", borderRadius: 1 }} />
        <View style={{ position: "absolute", left: 11, top: 5.5, width: 3.5, height: 11.5, backgroundColor: "#0F3244", borderRadius: 1 }} />
        <View style={{ position: "absolute", left: 16.5, top: 2, width: 3.5, height: 15, backgroundColor: "#0F3244", borderRadius: 1 }} />
        <SvgXml xml={SVG_0} width={16.2} height={5.3} style={{ position: "absolute", left: 24.4, top: 3.8 }} />
        <SvgXml xml={SVG_1} width={10.2} height={4.2} style={{ position: "absolute", left: 27.4, top: 8.6 }} />
        <View style={{ position: "absolute", left: 30.7, top: 13.4, width: 3.6, height: 3.6, backgroundColor: "#0F3244", borderRadius: 1.8 }} />
        <View style={{ position: "absolute", left: 47, top: 4.5, width: 24, height: 12, borderRadius: 3.5, borderWidth: 1.6, borderColor: "#0F3244" }} />
        <View style={{ position: "absolute", left: 49.5, top: 7, width: 17, height: 7, backgroundColor: "#0F3244", borderRadius: 2 }} />
        <View style={{ position: "absolute", left: 72, top: 8, width: 2.5, height: 5, backgroundColor: "#0F3244", borderRadius: 1.2 }} />
      </View>
      <View style={{ position: "absolute", left: 18, top: 46, width: 22, height: 22 }} pointerEvents="box-none">{/* "ic-arrow-left" */}
        <SvgXml xml={SVG_2} width={9.4} height={15.8} style={{ position: "absolute", left: 3.1, top: 3.1 }} />
        <SvgXml xml={SVG_3} width={15.8} height={3} style={{ position: "absolute", left: 3.1, top: 9.5 }} />
      </View>
      <Text style={{ position: "absolute", left: 60, top: 48, width: 256, textAlign: "center", fontFamily: "PlusJakartaSans_700Bold", fontSize: 16, lineHeight: 21.6, color: "#0F3244" }}>{"Pipeline"}</Text>
      <View style={{ position: "absolute", left: 336, top: 46, width: 22, height: 22 }} pointerEvents="box-none">{/* "ic-funnel" */}
        <SvgXml xml={SVG_4} width={21.3} height={20.4} style={{ position: "absolute", left: 0.3, top: 1.3 }} />
      </View>
      <View style={{ position: "absolute", left: 18, top: 82, width: 340, height: 40, backgroundColor: "#EFF5F8", borderRadius: 12, borderWidth: 1, borderColor: "#E6EFF3" }} />
      <View style={{ position: "absolute", left: 20, top: 84, width: 168, height: 36, backgroundColor: "#17A45E", borderRadius: 10, boxShadow: "0px 4px 12px 0px rgba(14,122,74,0.2)" }} />
      <View style={{ position: "absolute", left: 44, top: 95, width: 15, height: 15 }} pointerEvents="box-none">{/* "ic-list" */}
        <SvgXml xml={SVG_5} width={3} height={3} style={{ position: "absolute", left: 0.4, top: 1.6 }} />
        <SvgXml xml={SVG_6} width={3} height={3} style={{ position: "absolute", left: 0.4, top: 6 }} />
        <SvgXml xml={SVG_7} width={3} height={3} style={{ position: "absolute", left: 0.4, top: 10.4 }} />
        <SvgXml xml={SVG_8} width={11.1} height={3} style={{ position: "absolute", left: 3.5, top: 1.6 }} />
        <SvgXml xml={SVG_9} width={11.1} height={3} style={{ position: "absolute", left: 3.5, top: 6 }} />
        <SvgXml xml={SVG_10} width={11.1} height={3} style={{ position: "absolute", left: 3.5, top: 10.4 }} />
      </View>
      <Text style={{ position: "absolute", left: 64, top: 95, width: 110, textAlign: "left", fontFamily: "PlusJakartaSans_700Bold", fontSize: 12, lineHeight: 16.2, color: "#FFFFFF" }}>{"List View"}</Text>
      <Text style={{ position: "absolute", left: 190, top: 95, width: 166, textAlign: "center", fontFamily: "PlusJakartaSans_600SemiBold", fontSize: 12, lineHeight: 16.2, color: "#6B8796" }}>{"My Pipeline"}</Text>
      <View style={{ position: "absolute", left: 18, top: 136, width: 288, height: 40, backgroundColor: "#EFF5F8", borderRadius: 12, borderWidth: 1, borderColor: "#E6EFF3" }} />
      <View style={{ position: "absolute", left: 32, top: 147, width: 17, height: 17 }} pointerEvents="box-none">{/* "ic-search" */}
        <View style={{ position: "absolute", left: 2.1, top: 2.1, width: 11.3, height: 11.3, borderRadius: 5.7, borderWidth: 2, borderColor: "#8AA3B0" }} />
        <SvgXml xml={SVG_11} width={6} height={6} style={{ position: "absolute", left: 10.3, top: 10.3 }} />
      </View>
      <Text style={{ position: "absolute", left: 58, top: 148, width: 236, textAlign: "left", fontFamily: "PlusJakartaSans_500Medium", fontSize: 12, lineHeight: 16.2, color: "#93A9B5" }}>{"Search opportunities or customers..."}</Text>
      <View style={{ position: "absolute", left: 316, top: 136, width: 42, height: 40, backgroundColor: "#FFFFFF", borderRadius: 12, borderWidth: 1, borderColor: "#E6EFF3" }} />
      <View style={{ position: "absolute", left: 327, top: 147, width: 20, height: 20 }} pointerEvents="box-none">{/* "ic-sliders-horizontal" */}
        <SvgXml xml={SVG_12} width={8.8} height={3} style={{ position: "absolute", left: 1, top: 2.7 }} />
        <SvgXml xml={SVG_13} width={10.5} height={3} style={{ position: "absolute", left: 1, top: 14.3 }} />
        <SvgXml xml={SVG_14} width={3} height={6.3} style={{ position: "absolute", left: 10.2, top: 1 }} />
        <SvgXml xml={SVG_15} width={3} height={6.3} style={{ position: "absolute", left: 11.8, top: 12.7 }} />
        <SvgXml xml={SVG_16} width={10.5} height={3} style={{ position: "absolute", left: 8.5, top: 8.5 }} />
        <SvgXml xml={SVG_17} width={7.2} height={3} style={{ position: "absolute", left: 11.8, top: 14.3 }} />
        <SvgXml xml={SVG_18} width={8.8} height={3} style={{ position: "absolute", left: 10.2, top: 2.7 }} />
        <SvgXml xml={SVG_19} width={3} height={6.3} style={{ position: "absolute", left: 5.2, top: 6.8 }} />
        <SvgXml xml={SVG_20} width={7.2} height={3} style={{ position: "absolute", left: 1, top: 8.5 }} />
      </View>
      <View style={{ position: "absolute", left: 18, top: 190, width: 59, height: 28, backgroundColor: "#17A45E", borderRadius: 14, boxShadow: "0px 4px 12px 0px rgba(14,122,74,0.2)" }} />
      <Text style={{ position: "absolute", left: 29, top: 197, width: 23, textAlign: "left", fontFamily: "PlusJakartaSans_700Bold", fontSize: 10, lineHeight: 13.5, color: "#FFFFFF" }}>{"All"}</Text>
      <Text style={{ position: "absolute", left: 54, top: 197, width: 16, textAlign: "left", fontFamily: "PlusJakartaSans_800ExtraBold", fontSize: 10, lineHeight: 13.5, color: "#FFFFFF" }}>{"24"}</Text>
      <View style={{ position: "absolute", left: 85, top: 190, width: 65, height: 28, backgroundColor: "#FFFFFF", borderRadius: 14, borderWidth: 1, borderColor: "#E6EFF3" }} />
      <Text style={{ position: "absolute", left: 96, top: 197, width: 29, textAlign: "left", fontFamily: "PlusJakartaSans_700Bold", fontSize: 10, lineHeight: 13.5, color: "#0F3244" }}>{"Open"}</Text>
      <Text style={{ position: "absolute", left: 127, top: 197, width: 16, textAlign: "left", fontFamily: "PlusJakartaSans_800ExtraBold", fontSize: 10, lineHeight: 13.5, color: "#17A45E" }}>{"18"}</Text>
      <View style={{ position: "absolute", left: 158, top: 190, width: 84, height: 28, backgroundColor: "#FFFFFF", borderRadius: 14, borderWidth: 1, borderColor: "#E6EFF3" }} />
      <Text style={{ position: "absolute", left: 169, top: 197, width: 54, textAlign: "left", fontFamily: "PlusJakartaSans_700Bold", fontSize: 10, lineHeight: 13.5, color: "#0F3244" }}>{"My Deals"}</Text>
      <Text style={{ position: "absolute", left: 225, top: 197, width: 10, textAlign: "left", fontFamily: "PlusJakartaSans_800ExtraBold", fontSize: 10, lineHeight: 13.5, color: "#17A45E" }}>{"6"}</Text>
      <View style={{ position: "absolute", left: 320, top: 190, width: 38, height: 28, backgroundColor: "#FFFFFF", borderRadius: 14, borderWidth: 1, borderColor: "#E6EFF3" }} />
      <View style={{ position: "absolute", left: 330, top: 197, width: 18, height: 18 }} pointerEvents="box-none">{/* "ic-sliders-horizontal" */}
        <SvgXml xml={SVG_21} width={8.3} height={3} style={{ position: "absolute", left: 0.8, top: 2.3 }} />
        <SvgXml xml={SVG_22} width={9.8} height={3} style={{ position: "absolute", left: 0.8, top: 12.8 }} />
        <SvgXml xml={SVG_23} width={3} height={6} style={{ position: "absolute", left: 9, top: 0.8 }} />
        <SvgXml xml={SVG_24} width={3} height={6} style={{ position: "absolute", left: 10.5, top: 11.3 }} />
        <SvgXml xml={SVG_25} width={9.8} height={3} style={{ position: "absolute", left: 7.5, top: 7.5 }} />
        <SvgXml xml={SVG_26} width={6.8} height={3} style={{ position: "absolute", left: 10.5, top: 12.8 }} />
        <SvgXml xml={SVG_27} width={8.3} height={3} style={{ position: "absolute", left: 9, top: 2.3 }} />
        <SvgXml xml={SVG_28} width={3} height={6} style={{ position: "absolute", left: 4.5, top: 6 }} />
        <SvgXml xml={SVG_29} width={6.8} height={3} style={{ position: "absolute", left: 0.8, top: 7.5 }} />
      </View>
      <View style={{ position: "absolute", left: 18, top: 238, width: 340, height: 78, backgroundColor: "#FFFFFF", borderRadius: 14, borderWidth: 1, borderColor: "#E6EFF3", boxShadow: "0px 2px 8px 0px rgba(15,50,68,0.05)" }} />
      <View style={{ position: "absolute", left: 30, top: 248, width: 36, height: 36, backgroundColor: "#E8F6EE", borderRadius: 18 }} />
      <Text style={{ position: "absolute", left: 30, top: 258, width: 36, textAlign: "center", fontFamily: "PlusJakartaSans_800ExtraBold", fontSize: 12, lineHeight: 16.2, letterSpacing: 0.2, color: "#0E7A4A" }}>{"TM"}</Text>
      <Text style={{ position: "absolute", left: 76, top: 248, width: 156, textAlign: "left", fontFamily: "PlusJakartaSans_700Bold", fontSize: 13, lineHeight: 17.6, color: "#0F3244" }}>{"New Outlet Expansion"}</Text>
      <Text style={{ position: "absolute", left: 236, top: 248, width: 100, textAlign: "right", fontFamily: "PlusJakartaSans_800ExtraBold", fontSize: 13, lineHeight: 17.6, color: "#0F3244" }}>{"₹ 5.0L"}</Text>
      <Text style={{ position: "absolute", left: 76, top: 266, width: 156, textAlign: "left", fontFamily: "PlusJakartaSans_500Medium", fontSize: 11, lineHeight: 14.9, color: "#6B8796" }}>{"TrendMart"}</Text>
      <Text style={{ position: "absolute", left: 236, top: 267, width: 100, textAlign: "right", fontFamily: "PlusJakartaSans_700Bold", fontSize: 11, lineHeight: 14.9, color: "#0E7A4A" }}>{"80%"}</Text>
      <View style={{ position: "absolute", left: 334, top: 270, width: 14, height: 14 }} pointerEvents="box-none">{/* "ic-chevron-right" */}
        <SvgXml xml={SVG_30} width={6.5} height={10} style={{ position: "absolute", left: 3.8, top: 2 }} />
      </View>
      <View style={{ position: "absolute", left: 76, top: 286, width: 93, height: 20, backgroundColor: "#FDF0E0", borderRadius: 10 }} />
      <Text style={{ position: "absolute", left: 86, top: 289.5, width: 78, textAlign: "left", fontFamily: "PlusJakartaSans_700Bold", fontSize: 9.5, lineHeight: 12.8, color: "#C97A09" }}>{"Proposal Sent"}</Text>
      <View style={{ position: "absolute", left: 186, top: 289, width: 12, height: 12 }} pointerEvents="box-none">{/* "ic-calendar" */}
        <SvgXml xml={SVG_31} width={3} height={5} style={{ position: "absolute", left: 2.5, top: -0.5 }} />
        <SvgXml xml={SVG_32} width={3} height={5} style={{ position: "absolute", left: 6.5, top: -0.5 }} />
        <View style={{ position: "absolute", left: 1.5, top: 2, width: 9, height: 9, borderRadius: 2, borderWidth: 2, borderColor: "#8AA3B0" }} />
        <SvgXml xml={SVG_33} width={12} height={3} style={{ position: "absolute", left: 0, top: 3.5 }} />
      </View>
      <Text style={{ position: "absolute", left: 202, top: 288, width: 70, textAlign: "left", fontFamily: "PlusJakartaSans_500Medium", fontSize: 9.5, lineHeight: 12.8, color: "#6B8796" }}>{"20 Sep 2026"}</Text>
      <View style={{ position: "absolute", left: 280, top: 289, width: 12, height: 12 }} pointerEvents="box-none">{/* "ic-alarm-clock" */}
        <View style={{ position: "absolute", left: 2, top: 2.5, width: 8, height: 8, borderRadius: 4, borderWidth: 2, borderColor: "#E5484D" }} />
        <SvgXml xml={SVG_34} width={4} height={6} style={{ position: "absolute", left: 4.5, top: 3 }} />
        <SvgXml xml={SVG_35} width={4.5} height={4.5} style={{ position: "absolute", left: -0.5, top: 0 }} />
        <SvgXml xml={SVG_36} width={4.5} height={4.5} style={{ position: "absolute", left: 8, top: 0 }} />
        <SvgXml xml={SVG_37} width={4.2} height={4.1} style={{ position: "absolute", left: 0.5, top: 7.9 }} />
        <SvgXml xml={SVG_38} width={4.2} height={4.2} style={{ position: "absolute", left: 7.3, top: 7.8 }} />
      </View>
      <Text style={{ position: "absolute", left: 296, top: 288, width: 52, textAlign: "left", fontFamily: "PlusJakartaSans_700Bold", fontSize: 9.5, lineHeight: 12.8, color: "#E5484D" }}>{"18 Sep"}</Text>
      <View style={{ position: "absolute", left: 18, top: 322, width: 340, height: 78, backgroundColor: "#FFFFFF", borderRadius: 14, borderWidth: 1, borderColor: "#E6EFF3", boxShadow: "0px 2px 8px 0px rgba(15,50,68,0.05)" }} />
      <View style={{ position: "absolute", left: 30, top: 332, width: 36, height: 36, backgroundColor: "#E8F6EE", borderRadius: 18 }} />
      <Text style={{ position: "absolute", left: 30, top: 342, width: 36, textAlign: "center", fontFamily: "PlusJakartaSans_800ExtraBold", fontSize: 12, lineHeight: 16.2, letterSpacing: 0.2, color: "#0E7A4A" }}>{"MR"}</Text>
      <Text style={{ position: "absolute", left: 76, top: 332, width: 156, textAlign: "left", fontFamily: "PlusJakartaSans_700Bold", fontSize: 13, lineHeight: 17.6, color: "#0F3244" }}>{"Annual Supply Contract"}</Text>
      <Text style={{ position: "absolute", left: 236, top: 332, width: 100, textAlign: "right", fontFamily: "PlusJakartaSans_800ExtraBold", fontSize: 13, lineHeight: 17.6, color: "#0F3244" }}>{"₹ 12.5L"}</Text>
      <Text style={{ position: "absolute", left: 76, top: 350, width: 156, textAlign: "left", fontFamily: "PlusJakartaSans_500Medium", fontSize: 11, lineHeight: 14.9, color: "#6B8796" }}>{"Metro Retail"}</Text>
      <Text style={{ position: "absolute", left: 236, top: 351, width: 100, textAlign: "right", fontFamily: "PlusJakartaSans_700Bold", fontSize: 11, lineHeight: 14.9, color: "#0E7A4A" }}>{"70%"}</Text>
      <View style={{ position: "absolute", left: 334, top: 354, width: 14, height: 14 }} pointerEvents="box-none">{/* "ic-chevron-right" */}
        <SvgXml xml={SVG_39} width={6.5} height={10} style={{ position: "absolute", left: 3.8, top: 2 }} />
      </View>
      <View style={{ position: "absolute", left: 76, top: 370, width: 82, height: 20, backgroundColor: "#EAF2F7", borderRadius: 10 }} />
      <Text style={{ position: "absolute", left: 86, top: 373.5, width: 67, textAlign: "left", fontFamily: "PlusJakartaSans_700Bold", fontSize: 9.5, lineHeight: 12.8, color: "#4B7C93" }}>{"Negotiation"}</Text>
      <View style={{ position: "absolute", left: 186, top: 373, width: 12, height: 12 }} pointerEvents="box-none">{/* "ic-calendar" */}
        <SvgXml xml={SVG_40} width={3} height={5} style={{ position: "absolute", left: 2.5, top: -0.5 }} />
        <SvgXml xml={SVG_41} width={3} height={5} style={{ position: "absolute", left: 6.5, top: -0.5 }} />
        <View style={{ position: "absolute", left: 1.5, top: 2, width: 9, height: 9, borderRadius: 2, borderWidth: 2, borderColor: "#8AA3B0" }} />
        <SvgXml xml={SVG_42} width={12} height={3} style={{ position: "absolute", left: 0, top: 3.5 }} />
      </View>
      <Text style={{ position: "absolute", left: 202, top: 372, width: 70, textAlign: "left", fontFamily: "PlusJakartaSans_500Medium", fontSize: 9.5, lineHeight: 12.8, color: "#6B8796" }}>{"25 Sep 2026"}</Text>
      <View style={{ position: "absolute", left: 280, top: 373, width: 12, height: 12 }} pointerEvents="box-none">{/* "ic-alarm-clock" */}
        <View style={{ position: "absolute", left: 2, top: 2.5, width: 8, height: 8, borderRadius: 4, borderWidth: 2, borderColor: "#E5484D" }} />
        <SvgXml xml={SVG_43} width={4} height={6} style={{ position: "absolute", left: 4.5, top: 3 }} />
        <SvgXml xml={SVG_44} width={4.5} height={4.5} style={{ position: "absolute", left: -0.5, top: 0 }} />
        <SvgXml xml={SVG_45} width={4.5} height={4.5} style={{ position: "absolute", left: 8, top: 0 }} />
        <SvgXml xml={SVG_46} width={4.2} height={4.1} style={{ position: "absolute", left: 0.5, top: 7.9 }} />
        <SvgXml xml={SVG_47} width={4.2} height={4.2} style={{ position: "absolute", left: 7.3, top: 7.8 }} />
      </View>
      <Text style={{ position: "absolute", left: 296, top: 372, width: 52, textAlign: "left", fontFamily: "PlusJakartaSans_700Bold", fontSize: 9.5, lineHeight: 12.8, color: "#E5484D" }}>{"22 Sep"}</Text>
      <View style={{ position: "absolute", left: 18, top: 406, width: 340, height: 78, backgroundColor: "#FFFFFF", borderRadius: 14, borderWidth: 1, borderColor: "#E6EFF3", boxShadow: "0px 2px 8px 0px rgba(15,50,68,0.05)" }} />
      <View style={{ position: "absolute", left: 30, top: 416, width: 36, height: 36, backgroundColor: "#E8F6EE", borderRadius: 18 }} />
      <Text style={{ position: "absolute", left: 30, top: 426, width: 36, textAlign: "center", fontFamily: "PlusJakartaSans_800ExtraBold", fontSize: 12, lineHeight: 16.2, letterSpacing: 0.2, color: "#0E7A4A" }}>{"UC"}</Text>
      <Text style={{ position: "absolute", left: 76, top: 416, width: 156, textAlign: "left", fontFamily: "PlusJakartaSans_700Bold", fontSize: 13, lineHeight: 17.6, color: "#0F3244" }}>{"Product Upgrade"}</Text>
      <Text style={{ position: "absolute", left: 236, top: 416, width: 100, textAlign: "right", fontFamily: "PlusJakartaSans_800ExtraBold", fontSize: 13, lineHeight: 17.6, color: "#0F3244" }}>{"₹ 4.8L"}</Text>
      <Text style={{ position: "absolute", left: 76, top: 434, width: 156, textAlign: "left", fontFamily: "PlusJakartaSans_500Medium", fontSize: 11, lineHeight: 14.9, color: "#6B8796" }}>{"Urban Creations"}</Text>
      <Text style={{ position: "absolute", left: 236, top: 435, width: 100, textAlign: "right", fontFamily: "PlusJakartaSans_700Bold", fontSize: 11, lineHeight: 14.9, color: "#0E7A4A" }}>{"75%"}</Text>
      <View style={{ position: "absolute", left: 334, top: 438, width: 14, height: 14 }} pointerEvents="box-none">{/* "ic-chevron-right" */}
        <SvgXml xml={SVG_48} width={6.5} height={10} style={{ position: "absolute", left: 3.8, top: 2 }} />
      </View>
      <View style={{ position: "absolute", left: 76, top: 454, width: 93, height: 20, backgroundColor: "#FDF0E0", borderRadius: 10 }} />
      <Text style={{ position: "absolute", left: 86, top: 457.5, width: 78, textAlign: "left", fontFamily: "PlusJakartaSans_700Bold", fontSize: 9.5, lineHeight: 12.8, color: "#C97A09" }}>{"Proposal Sent"}</Text>
      <View style={{ position: "absolute", left: 186, top: 457, width: 12, height: 12 }} pointerEvents="box-none">{/* "ic-calendar" */}
        <SvgXml xml={SVG_49} width={3} height={5} style={{ position: "absolute", left: 2.5, top: -0.5 }} />
        <SvgXml xml={SVG_50} width={3} height={5} style={{ position: "absolute", left: 6.5, top: -0.5 }} />
        <View style={{ position: "absolute", left: 1.5, top: 2, width: 9, height: 9, borderRadius: 2, borderWidth: 2, borderColor: "#8AA3B0" }} />
        <SvgXml xml={SVG_51} width={12} height={3} style={{ position: "absolute", left: 0, top: 3.5 }} />
      </View>
      <Text style={{ position: "absolute", left: 202, top: 456, width: 70, textAlign: "left", fontFamily: "PlusJakartaSans_500Medium", fontSize: 9.5, lineHeight: 12.8, color: "#6B8796" }}>{"18 Sep 2026"}</Text>
      <View style={{ position: "absolute", left: 280, top: 457, width: 12, height: 12 }} pointerEvents="box-none">{/* "ic-alarm-clock" */}
        <View style={{ position: "absolute", left: 2, top: 2.5, width: 8, height: 8, borderRadius: 4, borderWidth: 2, borderColor: "#E5484D" }} />
        <SvgXml xml={SVG_52} width={4} height={6} style={{ position: "absolute", left: 4.5, top: 3 }} />
        <SvgXml xml={SVG_53} width={4.5} height={4.5} style={{ position: "absolute", left: -0.5, top: 0 }} />
        <SvgXml xml={SVG_54} width={4.5} height={4.5} style={{ position: "absolute", left: 8, top: 0 }} />
        <SvgXml xml={SVG_55} width={4.2} height={4.1} style={{ position: "absolute", left: 0.5, top: 7.9 }} />
        <SvgXml xml={SVG_56} width={4.2} height={4.2} style={{ position: "absolute", left: 7.3, top: 7.8 }} />
      </View>
      <Text style={{ position: "absolute", left: 296, top: 456, width: 52, textAlign: "left", fontFamily: "PlusJakartaSans_700Bold", fontSize: 9.5, lineHeight: 12.8, color: "#E5484D" }}>{"17 Sep"}</Text>
      <View style={{ position: "absolute", left: 18, top: 490, width: 340, height: 78, backgroundColor: "#FFFFFF", borderRadius: 14, borderWidth: 1, borderColor: "#E6EFF3", boxShadow: "0px 2px 8px 0px rgba(15,50,68,0.05)" }} />
      <View style={{ position: "absolute", left: 30, top: 500, width: 36, height: 36, backgroundColor: "#E8F6EE", borderRadius: 18 }} />
      <Text style={{ position: "absolute", left: 30, top: 510, width: 36, textAlign: "center", fontFamily: "PlusJakartaSans_800ExtraBold", fontSize: 12, lineHeight: 16.2, letterSpacing: 0.2, color: "#0E7A4A" }}>{"GT"}</Text>
      <Text style={{ position: "absolute", left: 76, top: 500, width: 156, textAlign: "left", fontFamily: "PlusJakartaSans_700Bold", fontSize: 13, lineHeight: 17.6, color: "#0F3244" }}>{"New Product Line"}</Text>
      <Text style={{ position: "absolute", left: 236, top: 500, width: 100, textAlign: "right", fontFamily: "PlusJakartaSans_800ExtraBold", fontSize: 13, lineHeight: 17.6, color: "#0F3244" }}>{"₹ 3.6L"}</Text>
      <Text style={{ position: "absolute", left: 76, top: 518, width: 156, textAlign: "left", fontFamily: "PlusJakartaSans_500Medium", fontSize: 11, lineHeight: 14.9, color: "#6B8796" }}>{"Greenfield Traders"}</Text>
      <Text style={{ position: "absolute", left: 236, top: 519, width: 100, textAlign: "right", fontFamily: "PlusJakartaSans_700Bold", fontSize: 11, lineHeight: 14.9, color: "#0E7A4A" }}>{"60%"}</Text>
      <View style={{ position: "absolute", left: 334, top: 522, width: 14, height: 14 }} pointerEvents="box-none">{/* "ic-chevron-right" */}
        <SvgXml xml={SVG_57} width={6.5} height={10} style={{ position: "absolute", left: 3.8, top: 2 }} />
      </View>
      <View style={{ position: "absolute", left: 76, top: 538, width: 104, height: 20, backgroundColor: "#FDECEC", borderRadius: 10 }} />
      <Text style={{ position: "absolute", left: 86, top: 541.5, width: 89, textAlign: "left", fontFamily: "PlusJakartaSans_700Bold", fontSize: 9.5, lineHeight: 12.8, color: "#E5484D" }}>{"Needs Follow-up"}</Text>
      <View style={{ position: "absolute", left: 186, top: 541, width: 12, height: 12 }} pointerEvents="box-none">{/* "ic-calendar" */}
        <SvgXml xml={SVG_58} width={3} height={5} style={{ position: "absolute", left: 2.5, top: -0.5 }} />
        <SvgXml xml={SVG_59} width={3} height={5} style={{ position: "absolute", left: 6.5, top: -0.5 }} />
        <View style={{ position: "absolute", left: 1.5, top: 2, width: 9, height: 9, borderRadius: 2, borderWidth: 2, borderColor: "#8AA3B0" }} />
        <SvgXml xml={SVG_60} width={12} height={3} style={{ position: "absolute", left: 0, top: 3.5 }} />
      </View>
      <Text style={{ position: "absolute", left: 202, top: 540, width: 70, textAlign: "left", fontFamily: "PlusJakartaSans_500Medium", fontSize: 9.5, lineHeight: 12.8, color: "#6B8796" }}>{"22 Sep 2026"}</Text>
      <View style={{ position: "absolute", left: 280, top: 541, width: 12, height: 12 }} pointerEvents="box-none">{/* "ic-alarm-clock" */}
        <View style={{ position: "absolute", left: 2, top: 2.5, width: 8, height: 8, borderRadius: 4, borderWidth: 2, borderColor: "#E5484D" }} />
        <SvgXml xml={SVG_61} width={4} height={6} style={{ position: "absolute", left: 4.5, top: 3 }} />
        <SvgXml xml={SVG_62} width={4.5} height={4.5} style={{ position: "absolute", left: -0.5, top: 0 }} />
        <SvgXml xml={SVG_63} width={4.5} height={4.5} style={{ position: "absolute", left: 8, top: 0 }} />
        <SvgXml xml={SVG_64} width={4.2} height={4.1} style={{ position: "absolute", left: 0.5, top: 7.9 }} />
        <SvgXml xml={SVG_65} width={4.2} height={4.2} style={{ position: "absolute", left: 7.3, top: 7.8 }} />
      </View>
      <Text style={{ position: "absolute", left: 296, top: 540, width: 52, textAlign: "left", fontFamily: "PlusJakartaSans_700Bold", fontSize: 9.5, lineHeight: 12.8, color: "#E5484D" }}>{"22 Sep"}</Text>
      <View style={{ position: "absolute", left: 18, top: 574, width: 340, height: 78, backgroundColor: "#FFFFFF", borderRadius: 14, borderWidth: 1, borderColor: "#E6EFF3", boxShadow: "0px 2px 8px 0px rgba(15,50,68,0.05)" }} />
      <View style={{ position: "absolute", left: 30, top: 584, width: 36, height: 36, backgroundColor: "#E8F6EE", borderRadius: 18 }} />
      <Text style={{ position: "absolute", left: 30, top: 594, width: 36, textAlign: "center", fontFamily: "PlusJakartaSans_800ExtraBold", fontSize: 12, lineHeight: 16.2, letterSpacing: 0.2, color: "#0E7A4A" }}>{"LM"}</Text>
      <Text style={{ position: "absolute", left: 76, top: 584, width: 156, textAlign: "left", fontFamily: "PlusJakartaSans_700Bold", fontSize: 13, lineHeight: 17.6, color: "#0F3244" }}>{"Store Expansion"}</Text>
      <Text style={{ position: "absolute", left: 236, top: 584, width: 100, textAlign: "right", fontFamily: "PlusJakartaSans_800ExtraBold", fontSize: 13, lineHeight: 17.6, color: "#0F3244" }}>{"₹ 2.8L"}</Text>
      <Text style={{ position: "absolute", left: 76, top: 602, width: 156, textAlign: "left", fontFamily: "PlusJakartaSans_500Medium", fontSize: 11, lineHeight: 14.9, color: "#6B8796" }}>{"Laxmi Mart"}</Text>
      <Text style={{ position: "absolute", left: 236, top: 603, width: 100, textAlign: "right", fontFamily: "PlusJakartaSans_700Bold", fontSize: 11, lineHeight: 14.9, color: "#0E7A4A" }}>{"50%"}</Text>
      <View style={{ position: "absolute", left: 334, top: 606, width: 14, height: 14 }} pointerEvents="box-none">{/* "ic-chevron-right" */}
        <SvgXml xml={SVG_66} width={6.5} height={10} style={{ position: "absolute", left: 3.8, top: 2 }} />
      </View>
      <View style={{ position: "absolute", left: 76, top: 622, width: 70, height: 20, backgroundColor: "#E8F6EE", borderRadius: 10 }} />
      <Text style={{ position: "absolute", left: 86, top: 625.5, width: 55, textAlign: "left", fontFamily: "PlusJakartaSans_700Bold", fontSize: 9.5, lineHeight: 12.8, color: "#0E7A4A" }}>{"Discovery"}</Text>
      <View style={{ position: "absolute", left: 186, top: 625, width: 12, height: 12 }} pointerEvents="box-none">{/* "ic-calendar" */}
        <SvgXml xml={SVG_67} width={3} height={5} style={{ position: "absolute", left: 2.5, top: -0.5 }} />
        <SvgXml xml={SVG_68} width={3} height={5} style={{ position: "absolute", left: 6.5, top: -0.5 }} />
        <View style={{ position: "absolute", left: 1.5, top: 2, width: 9, height: 9, borderRadius: 2, borderWidth: 2, borderColor: "#8AA3B0" }} />
        <SvgXml xml={SVG_69} width={12} height={3} style={{ position: "absolute", left: 0, top: 3.5 }} />
      </View>
      <Text style={{ position: "absolute", left: 202, top: 624, width: 70, textAlign: "left", fontFamily: "PlusJakartaSans_500Medium", fontSize: 9.5, lineHeight: 12.8, color: "#6B8796" }}>{"30 Sep 2026"}</Text>
      <View style={{ position: "absolute", left: 280, top: 625, width: 12, height: 12 }} pointerEvents="box-none">{/* "ic-alarm-clock" */}
        <View style={{ position: "absolute", left: 2, top: 2.5, width: 8, height: 8, borderRadius: 4, borderWidth: 2, borderColor: "#E5484D" }} />
        <SvgXml xml={SVG_70} width={4} height={6} style={{ position: "absolute", left: 4.5, top: 3 }} />
        <SvgXml xml={SVG_71} width={4.5} height={4.5} style={{ position: "absolute", left: -0.5, top: 0 }} />
        <SvgXml xml={SVG_72} width={4.5} height={4.5} style={{ position: "absolute", left: 8, top: 0 }} />
        <SvgXml xml={SVG_73} width={4.2} height={4.1} style={{ position: "absolute", left: 0.5, top: 7.9 }} />
        <SvgXml xml={SVG_74} width={4.2} height={4.2} style={{ position: "absolute", left: 7.3, top: 7.8 }} />
      </View>
      <Text style={{ position: "absolute", left: 296, top: 624, width: 52, textAlign: "left", fontFamily: "PlusJakartaSans_700Bold", fontSize: 9.5, lineHeight: 12.8, color: "#E5484D" }}>{"25 Sep"}</Text>
      <View style={{ position: "absolute", left: 18, top: 658, width: 340, height: 78, backgroundColor: "#FFFFFF", borderRadius: 14, borderWidth: 1, borderColor: "#E6EFF3", boxShadow: "0px 2px 8px 0px rgba(15,50,68,0.05)" }} />
      <View style={{ position: "absolute", left: 30, top: 668, width: 36, height: 36, backgroundColor: "#E8F6EE", borderRadius: 18 }} />
      <Text style={{ position: "absolute", left: 30, top: 678, width: 36, textAlign: "center", fontFamily: "PlusJakartaSans_800ExtraBold", fontSize: 12, lineHeight: 16.2, letterSpacing: 0.2, color: "#0E7A4A" }}>{"CY"}</Text>
      <Text style={{ position: "absolute", left: 76, top: 668, width: 156, textAlign: "left", fontFamily: "PlusJakartaSans_700Bold", fontSize: 13, lineHeight: 17.6, color: "#0F3244" }}>{"Product Sampling"}</Text>
      <Text style={{ position: "absolute", left: 236, top: 668, width: 100, textAlign: "right", fontFamily: "PlusJakartaSans_800ExtraBold", fontSize: 13, lineHeight: 17.6, color: "#0F3244" }}>{"₹ 1.9L"}</Text>
      <Text style={{ position: "absolute", left: 76, top: 686, width: 156, textAlign: "left", fontFamily: "PlusJakartaSans_500Medium", fontSize: 11, lineHeight: 14.9, color: "#6B8796" }}>{"City Super Market"}</Text>
      <Text style={{ position: "absolute", left: 236, top: 687, width: 100, textAlign: "right", fontFamily: "PlusJakartaSans_700Bold", fontSize: 11, lineHeight: 14.9, color: "#0E7A4A" }}>{"50%"}</Text>
      <View style={{ position: "absolute", left: 334, top: 690, width: 14, height: 14 }} pointerEvents="box-none">{/* "ic-chevron-right" */}
        <SvgXml xml={SVG_75} width={6.5} height={10} style={{ position: "absolute", left: 3.8, top: 2 }} />
      </View>
      <View style={{ position: "absolute", left: 76, top: 706, width: 93, height: 20, backgroundColor: "#FDF0E0", borderRadius: 10 }} />
      <Text style={{ position: "absolute", left: 86, top: 709.5, width: 78, textAlign: "left", fontFamily: "PlusJakartaSans_700Bold", fontSize: 9.5, lineHeight: 12.8, color: "#C97A09" }}>{"Proposal Sent"}</Text>
      <View style={{ position: "absolute", left: 186, top: 709, width: 12, height: 12 }} pointerEvents="box-none">{/* "ic-calendar" */}
        <SvgXml xml={SVG_76} width={3} height={5} style={{ position: "absolute", left: 2.5, top: -0.5 }} />
        <SvgXml xml={SVG_77} width={3} height={5} style={{ position: "absolute", left: 6.5, top: -0.5 }} />
        <View style={{ position: "absolute", left: 1.5, top: 2, width: 9, height: 9, borderRadius: 2, borderWidth: 2, borderColor: "#8AA3B0" }} />
        <SvgXml xml={SVG_78} width={12} height={3} style={{ position: "absolute", left: 0, top: 3.5 }} />
      </View>
      <Text style={{ position: "absolute", left: 202, top: 708, width: 70, textAlign: "left", fontFamily: "PlusJakartaSans_500Medium", fontSize: 9.5, lineHeight: 12.8, color: "#6B8796" }}>{"05 Oct 2026"}</Text>
      <View style={{ position: "absolute", left: 280, top: 709, width: 12, height: 12 }} pointerEvents="box-none">{/* "ic-alarm-clock" */}
        <View style={{ position: "absolute", left: 2, top: 2.5, width: 8, height: 8, borderRadius: 4, borderWidth: 2, borderColor: "#E5484D" }} />
        <SvgXml xml={SVG_79} width={4} height={6} style={{ position: "absolute", left: 4.5, top: 3 }} />
        <SvgXml xml={SVG_80} width={4.5} height={4.5} style={{ position: "absolute", left: -0.5, top: 0 }} />
        <SvgXml xml={SVG_81} width={4.5} height={4.5} style={{ position: "absolute", left: 8, top: 0 }} />
        <SvgXml xml={SVG_82} width={4.2} height={4.1} style={{ position: "absolute", left: 0.5, top: 7.9 }} />
        <SvgXml xml={SVG_83} width={4.2} height={4.2} style={{ position: "absolute", left: 7.3, top: 7.8 }} />
      </View>
      <Text style={{ position: "absolute", left: 296, top: 708, width: 52, textAlign: "left", fontFamily: "PlusJakartaSans_700Bold", fontSize: 9.5, lineHeight: 12.8, color: "#E5484D" }}>{"02 Oct"}</Text>
      <View style={{ position: "absolute", left: 0, top: 807, width: 376, height: 52, backgroundColor: "#FFFFFF", boxShadow: "0px -3px 14px 0px rgba(15,50,68,0.08)" }} />
      <View style={{ position: "absolute", left: 42, top: 817, width: 21, height: 21 }} pointerEvents="box-none">{/* "ic-house" */}
        <SvgXml xml={SVG_84} width={8.3} height={10.9} style={{ position: "absolute", left: 6.4, top: 9 }} />
        <SvgXml xml={SVG_85} width={18.8} height={19.6} style={{ position: "absolute", left: 1.1, top: 0.3 }} />
      </View>
      <Text style={{ position: "absolute", left: 11, top: 842, width: 83, textAlign: "center", fontFamily: "PlusJakartaSans_600SemiBold", fontSize: 10, lineHeight: 13.5, color: "#8AA3B0" }}>{"Home"}</Text>
      <View style={{ position: "absolute", left: 109, top: 817, width: 21, height: 21 }} pointerEvents="box-none">{/* "ic-layout-grid" */}
        <View style={{ position: "absolute", left: 2.6, top: 2.6, width: 6.1, height: 6.1, borderRadius: 1, borderWidth: 2, borderColor: "#17A45E" }} />
        <View style={{ position: "absolute", left: 12.3, top: 2.6, width: 6.1, height: 6.1, borderRadius: 1, borderWidth: 2, borderColor: "#17A45E" }} />
        <View style={{ position: "absolute", left: 12.3, top: 12.3, width: 6.1, height: 6.1, borderRadius: 1, borderWidth: 2, borderColor: "#17A45E" }} />
        <View style={{ position: "absolute", left: 2.6, top: 12.3, width: 6.1, height: 6.1, borderRadius: 1, borderWidth: 2, borderColor: "#17A45E" }} />
      </View>
      <Text style={{ position: "absolute", left: 78, top: 842, width: 83, textAlign: "center", fontFamily: "PlusJakartaSans_700Bold", fontSize: 10, lineHeight: 13.5, color: "#17A45E" }}>{"Pipeline"}</Text>
      <View style={{ position: "absolute", left: 246, top: 817, width: 21, height: 21 }} pointerEvents="box-none">{/* "ic-users" */}
        <SvgXml xml={SVG_86} width={15.3} height={8.3} style={{ position: "absolute", left: 0.3, top: 11.6 }} />
        <View style={{ position: "absolute", left: 4.4, top: 2.6, width: 7, height: 7, borderRadius: 3.5, borderWidth: 2, borderColor: "#8AA3B0" }} />
        <SvgXml xml={SVG_87} width={5.6} height={8.1} style={{ position: "absolute", left: 15.1, top: 11.7 }} />
        <SvgXml xml={SVG_88} width={5.6} height={9.8} style={{ position: "absolute", left: 12.5, top: 1.2 }} />
      </View>
      <Text style={{ position: "absolute", left: 215, top: 842, width: 83, textAlign: "center", fontFamily: "PlusJakartaSans_600SemiBold", fontSize: 10, lineHeight: 13.5, color: "#8AA3B0" }}>{"Customers"}</Text>
      <View style={{ position: "absolute", left: 313, top: 817, width: 21, height: 21 }} pointerEvents="box-none">{/* "ic-ellipsis" */}
        <View style={{ position: "absolute", left: 9.6, top: 9.6, width: 1.8, height: 1.8, borderRadius: 0.9, borderWidth: 2, borderColor: "#8AA3B0" }} />
        <View style={{ position: "absolute", left: 15.8, top: 9.6, width: 1.8, height: 1.8, borderRadius: 0.9, borderWidth: 2, borderColor: "#8AA3B0" }} />
        <View style={{ position: "absolute", left: 3.5, top: 9.6, width: 1.8, height: 1.8, borderRadius: 0.9, borderWidth: 2, borderColor: "#8AA3B0" }} />
      </View>
      <Text style={{ position: "absolute", left: 282, top: 842, width: 83, textAlign: "center", fontFamily: "PlusJakartaSans_600SemiBold", fontSize: 10, lineHeight: 13.5, color: "#8AA3B0" }}>{"More"}</Text>
      <View style={{ position: "absolute", left: 159, top: 788, width: 57, height: 57, backgroundColor: "#FFFFFF", borderRadius: 28.5 }} />
      <View style={{ position: "absolute", left: 161, top: 790, width: 53, height: 53, backgroundColor: "#17A45E", borderRadius: 26.5, boxShadow: "0px 4px 12px 0px rgba(14,122,74,0.2)" }} />
      <View style={{ position: "absolute", left: 175, top: 804, width: 25, height: 25 }} pointerEvents="box-none">{/* "ic-plus" */}
        <SvgXml xml={SVG_89} width={18} height={3.4} style={{ position: "absolute", left: 3.5, top: 10.8 }} />
        <SvgXml xml={SVG_90} width={3.4} height={18} style={{ position: "absolute", left: 10.8, top: 3.5 }} />
      </View>
    </View>
  );
}
