/* GENERATED by tools/penpot-to-code/to-react-native.mjs from the Penpot
 * board "05 — Corner Radius". Do not edit: regenerate with
 * `pnpm design:rn`. Its text is the board's sample copy — a design
 * reference, not a screen.
 */
import React from "react";
import { View, Text } from "react-native";

export const size = { width: 880, height: 340 } as const;



export default function Penpot05CornerRadius() {
  return (
    <View style={{ width: 880, height: 340, backgroundColor: "#FFFFFF", borderRadius: 16, borderWidth: 1, borderColor: "#E2E8F0", overflow: "hidden", boxShadow: "0px 1px 4px 0px rgba(0,0,0,0.2)" }}>{/* "05 — Corner Radius" */}
      <Text style={{ position: "absolute", left: 32, top: 14, width: 60, textAlign: "left", fontFamily: "PlusJakartaSans_800ExtraBold", fontSize: 10, lineHeight: 13.5, letterSpacing: 0.6, color: "#17A45E" }}>{"05"}</Text>
      <Text style={{ position: "absolute", left: 32, top: 30, width: 420, textAlign: "left", fontFamily: "PlusJakartaSans_700Bold", fontSize: 16, lineHeight: 21.6, color: "#0F3244" }}>{"Corner Radius"}</Text>
      <Text style={{ position: "absolute", left: 32, top: 54, width: 760, textAlign: "left", fontFamily: "PlusJakartaSans_500Medium", fontSize: 11, lineHeight: 14.9, color: "#6B8796" }}>{"Cards 12–14 · pills and chips fully rounded · phone frame 26 · icon tiles 8–10"}</Text>
      <View style={{ position: "absolute", left: 32, top: 78, width: 816, height: 1, backgroundColor: "#EEF4F7" }} />
      <View style={{ position: "absolute", left: 42, top: 104, width: 96, height: 86, backgroundColor: "#F1F9F5", borderRadius: 8, borderWidth: 1.5, borderColor: "#CFE7DA" }} />
      <Text style={{ position: "absolute", left: 42, top: 200, width: 96, textAlign: "center", fontFamily: "PlusJakartaSans_800ExtraBold", fontSize: 12, lineHeight: 16.2, color: "#0F3244" }}>{"8"}</Text>
      <Text style={{ position: "absolute", left: 42, top: 216, width: 96, textAlign: "center", fontFamily: "PlusJakartaSans_500Medium", fontSize: 9, lineHeight: 12.2, color: "#8AA3B0" }}>{"Icon tile"}</Text>
      <View style={{ position: "absolute", left: 158, top: 104, width: 96, height: 86, backgroundColor: "#F1F9F5", borderRadius: 10, borderWidth: 1.5, borderColor: "#CFE7DA" }} />
      <Text style={{ position: "absolute", left: 158, top: 200, width: 96, textAlign: "center", fontFamily: "PlusJakartaSans_800ExtraBold", fontSize: 12, lineHeight: 16.2, color: "#0F3244" }}>{"10"}</Text>
      <Text style={{ position: "absolute", left: 158, top: 216, width: 96, textAlign: "center", fontFamily: "PlusJakartaSans_500Medium", fontSize: 9, lineHeight: 12.2, color: "#8AA3B0" }}>{"Input, small card"}</Text>
      <View style={{ position: "absolute", left: 274, top: 104, width: 96, height: 86, backgroundColor: "#F1F9F5", borderRadius: 12, borderWidth: 1.5, borderColor: "#CFE7DA" }} />
      <Text style={{ position: "absolute", left: 274, top: 200, width: 96, textAlign: "center", fontFamily: "PlusJakartaSans_800ExtraBold", fontSize: 12, lineHeight: 16.2, color: "#0F3244" }}>{"12"}</Text>
      <Text style={{ position: "absolute", left: 274, top: 216, width: 96, textAlign: "center", fontFamily: "PlusJakartaSans_500Medium", fontSize: 9, lineHeight: 12.2, color: "#8AA3B0" }}>{"Card"}</Text>
      <View style={{ position: "absolute", left: 390, top: 104, width: 96, height: 86, backgroundColor: "#F1F9F5", borderRadius: 14, borderWidth: 1.5, borderColor: "#CFE7DA" }} />
      <Text style={{ position: "absolute", left: 390, top: 200, width: 96, textAlign: "center", fontFamily: "PlusJakartaSans_800ExtraBold", fontSize: 12, lineHeight: 16.2, color: "#0F3244" }}>{"14"}</Text>
      <Text style={{ position: "absolute", left: 390, top: 216, width: 96, textAlign: "center", fontFamily: "PlusJakartaSans_500Medium", fontSize: 9, lineHeight: 12.2, color: "#8AA3B0" }}>{"List card"}</Text>
      <View style={{ position: "absolute", left: 506, top: 104, width: 96, height: 86, backgroundColor: "#F1F9F5", borderRadius: 16, borderWidth: 1.5, borderColor: "#CFE7DA" }} />
      <Text style={{ position: "absolute", left: 506, top: 200, width: 96, textAlign: "center", fontFamily: "PlusJakartaSans_800ExtraBold", fontSize: 12, lineHeight: 16.2, color: "#0F3244" }}>{"16"}</Text>
      <Text style={{ position: "absolute", left: 506, top: 216, width: 96, textAlign: "center", fontFamily: "PlusJakartaSans_500Medium", fontSize: 9, lineHeight: 12.2, color: "#8AA3B0" }}>{"Hero card"}</Text>
      <View style={{ position: "absolute", left: 622, top: 104, width: 96, height: 86, backgroundColor: "#F1F9F5", borderRadius: 26, borderWidth: 1.5, borderColor: "#CFE7DA" }} />
      <Text style={{ position: "absolute", left: 622, top: 200, width: 96, textAlign: "center", fontFamily: "PlusJakartaSans_800ExtraBold", fontSize: 12, lineHeight: 16.2, color: "#0F3244" }}>{"26"}</Text>
      <Text style={{ position: "absolute", left: 622, top: 216, width: 96, textAlign: "center", fontFamily: "PlusJakartaSans_500Medium", fontSize: 9, lineHeight: 12.2, color: "#8AA3B0" }}>{"Phone frame"}</Text>
      <View style={{ position: "absolute", left: 738, top: 104, width: 96, height: 86, backgroundColor: "#F1F9F5", borderRadius: 43, borderWidth: 1.5, borderColor: "#CFE7DA" }} />
      <Text style={{ position: "absolute", left: 738, top: 200, width: 96, textAlign: "center", fontFamily: "PlusJakartaSans_800ExtraBold", fontSize: 12, lineHeight: 16.2, color: "#0F3244" }}>{"full"}</Text>
      <Text style={{ position: "absolute", left: 738, top: 216, width: 96, textAlign: "center", fontFamily: "PlusJakartaSans_500Medium", fontSize: 9, lineHeight: 12.2, color: "#8AA3B0" }}>{"Pill / chip"}</Text>
    </View>
  );
}
