/* GENERATED by tools/penpot-to-code/to-react-native.mjs from the Penpot
 * board "09 — Inputs & Form Controls". Do not edit: regenerate with
 * `pnpm design:rn`. Its text is the board's sample copy — a design
 * reference, not a screen.
 */
import React from "react";
import { View, Text } from "react-native";
import { SvgXml } from "react-native-svg";

export const size = { width: 880, height: 780 } as const;

const SVG_0 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"6.2\" height=\"6.2\" viewBox=\"1027 1909 6.2 6.2\" fill=\"none\"><path d=\"M1031.75,1913.75L1028.5250244140625,1910.5250244140625\" fill=\"none\" stroke=\"#8aa3b0\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_1 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"12\" height=\"7.5\" viewBox=\"1517 1903.3 12 7.5\" fill=\"none\"><path d=\"M1518.5,1904.75L1523.0,1909.25L1527.5,1904.75\" fill=\"none\" stroke=\"#6b8796\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_2 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"12\" height=\"7.5\" viewBox=\"1077 2003.3 12 7.5\" fill=\"none\"><path d=\"M1078.5,2004.75L1083.0,2009.25L1087.5,2004.75\" fill=\"none\" stroke=\"#6b8796\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_3 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"12\" height=\"7.5\" viewBox=\"1237 2003.3 12 7.5\" fill=\"none\"><path d=\"M1238.5,2004.75L1243.0,2009.25L1247.5,2004.75\" fill=\"none\" stroke=\"#6b8796\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_4 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"12\" height=\"7.5\" viewBox=\"1357 2003.3 12 7.5\" fill=\"none\"><path d=\"M1358.5,2004.75L1363.0,2009.25L1367.5,2004.75\" fill=\"none\" stroke=\"#6b8796\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_5 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"12\" height=\"9.5\" viewBox=\"1005 2157 12 9.5\" fill=\"none\"><path d=\"M1015.0,2159.0L1009.5,2164.5L1007.0,2162.0\" fill=\"none\" stroke=\"#ffffff\" stroke-width=\"3\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_6 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"13.7\" height=\"3.2\" viewBox=\"1611.2 2163.4 13.7 3.2\" fill=\"none\"><path d=\"M1612.75,2165.0L1623.25,2165.0\" fill=\"none\" stroke=\"#6b8796\" stroke-width=\"2.2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" transform=\"translate(1618 2165) matrix(1,0,0,0.5833333333333712,-9.094947017729282e-13,-0.0012152777781189172) translate(-1618 -2165)\"/></svg>";
const SVG_7 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"13.7\" height=\"3.2\" viewBox=\"1715.2 2163.4 13.7 3.2\" fill=\"none\"><path d=\"M1716.75,2165.0L1727.25,2165.0\" fill=\"none\" stroke=\"#0e7a4a\" stroke-width=\"2.2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" transform=\"translate(1722 2165) matrix(1,0,0,0.5833333333333712,-9.094947017729282e-13,-0.0012152777781189172) translate(-1722 -2165)\"/></svg>";
const SVG_8 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"3.2\" height=\"11.4\" viewBox=\"1720.4 2159.3 3.2 11.4\" fill=\"none\"><path d=\"M1722.0,2160.916748046875L1722.0,2169.083251953125\" fill=\"none\" stroke=\"#0e7a4a\" stroke-width=\"2.2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" transform=\"translate(1722 2165) matrix(0.75,0,0,1.0000000000000182,-0.0009374999999307576,-1.6964207816272392e-13) translate(-1722 -2165)\"/></svg>";

export default function Penpot09InputsFormControls() {
  return (
    <View style={{ width: 880, height: 780, backgroundColor: "#FFFFFF", borderRadius: 16, borderWidth: 1, borderColor: "#E2E8F0", overflow: "hidden", boxShadow: "0px 1px 4px 0px rgba(0,0,0,0.2)" }}>{/* "09 — Inputs & Form Controls" */}
      <Text style={{ position: "absolute", left: 32, top: 14, width: 60, textAlign: "left", fontFamily: "PlusJakartaSans_800ExtraBold", fontSize: 10, lineHeight: 13.5, letterSpacing: 0.6, color: "#17A45E" }}>{"09"}</Text>
      <Text style={{ position: "absolute", left: 32, top: 30, width: 420, textAlign: "left", fontFamily: "PlusJakartaSans_700Bold", fontSize: 16, lineHeight: 21.6, color: "#0F3244" }}>{"Inputs & Form Controls"}</Text>
      <Text style={{ position: "absolute", left: 32, top: 54, width: 790, textAlign: "left", fontFamily: "PlusJakartaSans_500Medium", fontSize: 11, lineHeight: 14.9, color: "#6B8796" }}>{"Field 44 tall · radius 10 · label 10/700 above · value 13/500 · helper 10/500 below · dates are day / month / year selects"}</Text>
      <View style={{ position: "absolute", left: 32, top: 78, width: 816, height: 1, backgroundColor: "#EEF4F7" }} />
      <Text style={{ position: "absolute", left: 42, top: 96, width: 400, textAlign: "left", fontFamily: "PlusJakartaSans_800ExtraBold", fontSize: 10, lineHeight: 13.5, letterSpacing: 0.8, color: "#6B8796" }}>{"Text field · states"}</Text>
      <Text style={{ position: "absolute", left: 42, top: 116, width: 190, textAlign: "left", fontFamily: "PlusJakartaSans_700Bold", fontSize: 10, lineHeight: 13.5, letterSpacing: 0.3, color: "#6B8796" }}>{"Customer Name"}</Text>
      <View style={{ position: "absolute", left: 42, top: 132, width: 190, height: 44, backgroundColor: "#FFFFFF", borderRadius: 10, borderWidth: 1, borderColor: "#E6EFF3" }} />
      <Text style={{ position: "absolute", left: 55, top: 146, width: 164, textAlign: "left", fontFamily: "PlusJakartaSans_500Medium", fontSize: 13, lineHeight: 17.6, color: "#93A9B5" }}>{"Enter customer name"}</Text>
      <Text style={{ position: "absolute", left: 42, top: 196, width: 190, textAlign: "center", fontFamily: "PlusJakartaSans_700Bold", fontSize: 9, lineHeight: 12.2, color: "#93A9B5" }}>{"Default"}</Text>
      <Text style={{ position: "absolute", left: 242, top: 116, width: 190, textAlign: "left", fontFamily: "PlusJakartaSans_700Bold", fontSize: 10, lineHeight: 13.5, letterSpacing: 0.3, color: "#6B8796" }}>{"Customer Name"}</Text>
      <View style={{ position: "absolute", left: 242, top: 132, width: 190, height: 44, backgroundColor: "#FFFFFF", borderRadius: 10, borderWidth: 1.6, borderColor: "#17A45E" }} />
      <Text style={{ position: "absolute", left: 255, top: 146, width: 164, textAlign: "left", fontFamily: "PlusJakartaSans_600SemiBold", fontSize: 13, lineHeight: 17.6, color: "#0F3244" }}>{"TrendMart"}</Text>
      <View style={{ position: "absolute", left: 318, top: 145, width: 2, height: 17, backgroundColor: "#17A45E" }} />
      <Text style={{ position: "absolute", left: 242, top: 196, width: 190, textAlign: "center", fontFamily: "PlusJakartaSans_700Bold", fontSize: 9, lineHeight: 12.2, color: "#93A9B5" }}>{"Focused"}</Text>
      <Text style={{ position: "absolute", left: 442, top: 116, width: 190, textAlign: "left", fontFamily: "PlusJakartaSans_700Bold", fontSize: 10, lineHeight: 13.5, letterSpacing: 0.3, color: "#6B8796" }}>{"Customer Name"}</Text>
      <View style={{ position: "absolute", left: 442, top: 132, width: 190, height: 44, backgroundColor: "#FFFFFF", borderRadius: 10, borderWidth: 1, borderColor: "#E6EFF3" }} />
      <Text style={{ position: "absolute", left: 455, top: 146, width: 164, textAlign: "left", fontFamily: "PlusJakartaSans_600SemiBold", fontSize: 13, lineHeight: 17.6, color: "#0F3244" }}>{"Greenfield Traders"}</Text>
      <Text style={{ position: "absolute", left: 442, top: 196, width: 190, textAlign: "center", fontFamily: "PlusJakartaSans_700Bold", fontSize: 9, lineHeight: 12.2, color: "#93A9B5" }}>{"Filled"}</Text>
      <Text style={{ position: "absolute", left: 642, top: 116, width: 190, textAlign: "left", fontFamily: "PlusJakartaSans_700Bold", fontSize: 10, lineHeight: 13.5, letterSpacing: 0.3, color: "#6B8796" }}>{"Mobile"}</Text>
      <View style={{ position: "absolute", left: 642, top: 132, width: 190, height: 44, backgroundColor: "#FFFFFF", borderRadius: 10, borderWidth: 1.4, borderColor: "#E5484D" }} />
      <Text style={{ position: "absolute", left: 655, top: 146, width: 164, textAlign: "left", fontFamily: "PlusJakartaSans_500Medium", fontSize: 13, lineHeight: 17.6, color: "#0F3244" }}>{"98765"}</Text>
      <Text style={{ position: "absolute", left: 642, top: 180, width: 190, textAlign: "left", fontFamily: "PlusJakartaSans_500Medium", fontSize: 9, lineHeight: 12.2, color: "#E5484D" }}>{"Enter a valid mobile number"}</Text>
      <Text style={{ position: "absolute", left: 642, top: 196, width: 190, textAlign: "center", fontFamily: "PlusJakartaSans_700Bold", fontSize: 9, lineHeight: 12.2, color: "#93A9B5" }}>{"Error"}</Text>
      <Text style={{ position: "absolute", left: 42, top: 232, width: 400, textAlign: "left", fontFamily: "PlusJakartaSans_800ExtraBold", fontSize: 10, lineHeight: 13.5, letterSpacing: 0.8, color: "#6B8796" }}>{"Search · select · amount"}</Text>
      <View style={{ position: "absolute", left: 42, top: 252, width: 280, height: 44, backgroundColor: "#EFF5F8", borderRadius: 10, borderWidth: 1, borderColor: "#E6EFF3" }} />
      <View style={{ position: "absolute", left: 56, top: 265, width: 18, height: 18 }} pointerEvents="box-none">{/* "f-ic" */}
        <View style={{ position: "absolute", left: 2.3, top: 2.3, width: 12, height: 12, borderRadius: 6, borderWidth: 2, borderColor: "#8AA3B0" }} />
        <SvgXml xml={SVG_0} width={6.2} height={6.2} style={{ position: "absolute", left: 11, top: 11 }} />
      </View>
      <Text style={{ position: "absolute", left: 82, top: 266, width: 200, textAlign: "left", fontFamily: "PlusJakartaSans_500Medium", fontSize: 13, lineHeight: 17.6, color: "#93A9B5" }}>{"Search customers or invoice..."}</Text>
      <Text style={{ position: "absolute", left: 42, top: 302, width: 280, textAlign: "left", fontFamily: "PlusJakartaSans_500Medium", fontSize: 9, lineHeight: 12.2, color: "#8AA3B0" }}>{"Search"}</Text>
      <View style={{ position: "absolute", left: 342, top: 252, width: 240, height: 44, backgroundColor: "#FFFFFF", borderRadius: 10, borderWidth: 1, borderColor: "#E6EFF3" }} />
      <Text style={{ position: "absolute", left: 355, top: 266, width: 180, textAlign: "left", fontFamily: "PlusJakartaSans_600SemiBold", fontSize: 13, lineHeight: 17.6, color: "#0F3244" }}>{"Proposal Sent"}</Text>
      <View style={{ position: "absolute", left: 554, top: 265, width: 18, height: 18 }} pointerEvents="box-none">{/* "f-ic" */}
        <SvgXml xml={SVG_1} width={12} height={7.5} style={{ position: "absolute", left: 3, top: 5.3 }} />
      </View>
      <Text style={{ position: "absolute", left: 342, top: 302, width: 240, textAlign: "left", fontFamily: "PlusJakartaSans_500Medium", fontSize: 9, lineHeight: 12.2, color: "#8AA3B0" }}>{"Select"}</Text>
      <View style={{ position: "absolute", left: 602, top: 252, width: 200, height: 44, backgroundColor: "#FFFFFF", borderRadius: 10, borderWidth: 1, borderColor: "#E6EFF3" }} />
      <Text style={{ position: "absolute", left: 615, top: 266, width: 20, textAlign: "left", fontFamily: "PlusJakartaSans_700Bold", fontSize: 13, lineHeight: 17.6, color: "#6B8796" }}>{"₹"}</Text>
      <View style={{ position: "absolute", left: 636, top: 262, width: 1, height: 24, backgroundColor: "#E6EFF3" }} />
      <Text style={{ position: "absolute", left: 648, top: 266, width: 140, textAlign: "left", fontFamily: "PlusJakartaSans_700Bold", fontSize: 13, lineHeight: 17.6, color: "#0F3244" }}>{"5,00,000"}</Text>
      <Text style={{ position: "absolute", left: 602, top: 302, width: 200, textAlign: "left", fontFamily: "PlusJakartaSans_500Medium", fontSize: 9, lineHeight: 12.2, color: "#8AA3B0" }}>{"Amount"}</Text>
      <Text style={{ position: "absolute", left: 42, top: 332, width: 400, textAlign: "left", fontFamily: "PlusJakartaSans_800ExtraBold", fontSize: 10, lineHeight: 13.5, letterSpacing: 0.8, color: "#6B8796" }}>{"Date · day / month / year selects, never a bare native date input"}</Text>
      <View style={{ position: "absolute", left: 42, top: 352, width: 100, height: 44, backgroundColor: "#FFFFFF", borderRadius: 10, borderWidth: 1, borderColor: "#E6EFF3" }} />
      <Text style={{ position: "absolute", left: 55, top: 366, width: 60, textAlign: "left", fontFamily: "PlusJakartaSans_600SemiBold", fontSize: 13, lineHeight: 17.6, color: "#0F3244" }}>{"14"}</Text>
      <View style={{ position: "absolute", left: 114, top: 365, width: 18, height: 18 }} pointerEvents="box-none">{/* "f-ic" */}
        <SvgXml xml={SVG_2} width={12} height={7.5} style={{ position: "absolute", left: 3, top: 5.3 }} />
      </View>
      <Text style={{ position: "absolute", left: 42, top: 402, width: 100, textAlign: "left", fontFamily: "PlusJakartaSans_500Medium", fontSize: 9, lineHeight: 12.2, color: "#8AA3B0" }}>{"Day"}</Text>
      <View style={{ position: "absolute", left: 152, top: 352, width: 150, height: 44, backgroundColor: "#FFFFFF", borderRadius: 10, borderWidth: 1, borderColor: "#E6EFF3" }} />
      <Text style={{ position: "absolute", left: 165, top: 366, width: 110, textAlign: "left", fontFamily: "PlusJakartaSans_600SemiBold", fontSize: 13, lineHeight: 17.6, color: "#0F3244" }}>{"September"}</Text>
      <View style={{ position: "absolute", left: 274, top: 365, width: 18, height: 18 }} pointerEvents="box-none">{/* "f-ic" */}
        <SvgXml xml={SVG_3} width={12} height={7.5} style={{ position: "absolute", left: 3, top: 5.3 }} />
      </View>
      <Text style={{ position: "absolute", left: 152, top: 402, width: 150, textAlign: "left", fontFamily: "PlusJakartaSans_500Medium", fontSize: 9, lineHeight: 12.2, color: "#8AA3B0" }}>{"Month"}</Text>
      <View style={{ position: "absolute", left: 312, top: 352, width: 110, height: 44, backgroundColor: "#FFFFFF", borderRadius: 10, borderWidth: 1, borderColor: "#E6EFF3" }} />
      <Text style={{ position: "absolute", left: 325, top: 366, width: 70, textAlign: "left", fontFamily: "PlusJakartaSans_600SemiBold", fontSize: 13, lineHeight: 17.6, color: "#0F3244" }}>{"2026"}</Text>
      <View style={{ position: "absolute", left: 394, top: 365, width: 18, height: 18 }} pointerEvents="box-none">{/* "f-ic" */}
        <SvgXml xml={SVG_4} width={12} height={7.5} style={{ position: "absolute", left: 3, top: 5.3 }} />
      </View>
      <Text style={{ position: "absolute", left: 312, top: 402, width: 110, textAlign: "left", fontFamily: "PlusJakartaSans_500Medium", fontSize: 9, lineHeight: 12.2, color: "#8AA3B0" }}>{"Year"}</Text>
      <View style={{ position: "absolute", left: 442, top: 352, width: 380, height: 92, backgroundColor: "#FFFFFF", borderRadius: 10, borderWidth: 1, borderColor: "#E6EFF3" }} />
      <Text style={{ position: "absolute", left: 455, top: 364, width: 350, textAlign: "left", fontFamily: "PlusJakartaSans_500Medium", fontSize: 13, lineHeight: 19.5, color: "#0F3244" }}>{"Client is interested in opening 2 new outlets. Waiting for final confirmation after proposal."}</Text>
      <Text style={{ position: "absolute", left: 442, top: 450, width: 380, textAlign: "left", fontFamily: "PlusJakartaSans_500Medium", fontSize: 9, lineHeight: 12.2, color: "#8AA3B0" }}>{"Textarea · min 92"}</Text>
      <Text style={{ position: "absolute", left: 42, top: 496, width: 400, textAlign: "left", fontFamily: "PlusJakartaSans_800ExtraBold", fontSize: 10, lineHeight: 13.5, letterSpacing: 0.8, color: "#6B8796" }}>{"Selection controls"}</Text>
      <View style={{ position: "absolute", left: 42, top: 520, width: 18, height: 18, backgroundColor: "#17A45E", borderRadius: 5 }} />
      <View style={{ position: "absolute", left: 45, top: 523, width: 12, height: 12 }} pointerEvents="box-none">{/* "cb-ic" */}
        <SvgXml xml={SVG_5} width={12} height={9.5} style={{ position: "absolute", left: 0, top: 1 }} />
      </View>
      <Text style={{ position: "absolute", left: 68, top: 521, width: 150, textAlign: "left", fontFamily: "PlusJakartaSans_700Bold", fontSize: 12, lineHeight: 16.2, color: "#0F3244" }}>{"High (70% - 100%)"}</Text>
      <View style={{ position: "absolute", left: 42, top: 550, width: 18, height: 18, backgroundColor: "#FFFFFF", borderRadius: 5, borderWidth: 1.4, borderColor: "#C9D9E1" }} />
      <Text style={{ position: "absolute", left: 68, top: 551, width: 150, textAlign: "left", fontFamily: "PlusJakartaSans_500Medium", fontSize: 12, lineHeight: 16.2, color: "#0F3244" }}>{"Medium (40% - 69%)"}</Text>
      <Text style={{ position: "absolute", left: 42, top: 578, width: 180, textAlign: "left", fontFamily: "PlusJakartaSans_500Medium", fontSize: 9, lineHeight: 12.2, color: "#8AA3B0" }}>{"Checkbox"}</Text>
      <View style={{ position: "absolute", left: 250, top: 520, width: 18, height: 18, backgroundColor: "#FFFFFF", borderRadius: 9, borderWidth: 2, borderColor: "#17A45E" }} />
      <View style={{ position: "absolute", left: 255, top: 525, width: 8, height: 8, backgroundColor: "#17A45E", borderRadius: 4 }} />
      <Text style={{ position: "absolute", left: 276, top: 521, width: 130, textAlign: "left", fontFamily: "PlusJakartaSans_700Bold", fontSize: 12, lineHeight: 16.2, color: "#0F3244" }}>{"This Month"}</Text>
      <View style={{ position: "absolute", left: 250, top: 550, width: 18, height: 18, backgroundColor: "#FFFFFF", borderRadius: 9, borderWidth: 1.6, borderColor: "#C9D9E1" }} />
      <Text style={{ position: "absolute", left: 276, top: 551, width: 130, textAlign: "left", fontFamily: "PlusJakartaSans_500Medium", fontSize: 12, lineHeight: 16.2, color: "#0F3244" }}>{"Last Month"}</Text>
      <Text style={{ position: "absolute", left: 250, top: 578, width: 150, textAlign: "left", fontFamily: "PlusJakartaSans_500Medium", fontSize: 9, lineHeight: 12.2, color: "#8AA3B0" }}>{"Radio"}</Text>
      <View style={{ position: "absolute", left: 430, top: 519, width: 40, height: 22, backgroundColor: "#17A45E", borderRadius: 11 }} />
      <View style={{ position: "absolute", left: 451, top: 521, width: 18, height: 18, backgroundColor: "#FFFFFF", borderRadius: 9, boxShadow: "0px 2px 8px 0px rgba(15,50,68,0.05)" }} />
      <Text style={{ position: "absolute", left: 480, top: 521, width: 120, textAlign: "left", fontFamily: "PlusJakartaSans_700Bold", fontSize: 12, lineHeight: 16.2, color: "#0F3244" }}>{"Remember me"}</Text>
      <View style={{ position: "absolute", left: 430, top: 549, width: 40, height: 22, backgroundColor: "#D9E4EA", borderRadius: 11 }} />
      <View style={{ position: "absolute", left: 431, top: 551, width: 18, height: 18, backgroundColor: "#FFFFFF", borderRadius: 9, boxShadow: "0px 2px 8px 0px rgba(15,50,68,0.05)" }} />
      <Text style={{ position: "absolute", left: 480, top: 551, width: 120, textAlign: "left", fontFamily: "PlusJakartaSans_500Medium", fontSize: 12, lineHeight: 16.2, color: "#0F3244" }}>{"Offline mode"}</Text>
      <Text style={{ position: "absolute", left: 430, top: 578, width: 150, textAlign: "left", fontFamily: "PlusJakartaSans_500Medium", fontSize: 9, lineHeight: 12.2, color: "#8AA3B0" }}>{"Toggle"}</Text>
      <View style={{ position: "absolute", left: 640, top: 516, width: 36, height: 32, backgroundColor: "#FFFFFF", borderRadius: 9, borderWidth: 1, borderColor: "#E6EFF3" }} />
      <View style={{ position: "absolute", left: 649, top: 525, width: 18, height: 14 }} pointerEvents="box-none">{/* "st-ic" */}
        <SvgXml xml={SVG_6} width={13.7} height={3.2} style={{ position: "absolute", left: 2.2, top: 5.4 }} />
      </View>
      <View style={{ position: "absolute", left: 682, top: 516, width: 56, height: 32, backgroundColor: "#FFFFFF", borderRadius: 9, borderWidth: 1, borderColor: "#E6EFF3" }} />
      <Text style={{ position: "absolute", left: 682, top: 523, width: 56, textAlign: "center", fontFamily: "PlusJakartaSans_700Bold", fontSize: 13, lineHeight: 17.6, color: "#0F3244" }}>{"12"}</Text>
      <View style={{ position: "absolute", left: 744, top: 516, width: 36, height: 32, backgroundColor: "#E8F6EE", borderRadius: 9, borderWidth: 1, borderColor: "#D6EDE0" }} />
      <View style={{ position: "absolute", left: 753, top: 525, width: 18, height: 14 }} pointerEvents="box-none">{/* "st-ic" */}
        <SvgXml xml={SVG_7} width={13.7} height={3.2} style={{ position: "absolute", left: 2.2, top: 5.4 }} />
        <SvgXml xml={SVG_8} width={3.2} height={11.4} style={{ position: "absolute", left: 7.4, top: 1.3 }} />
      </View>
      <Text style={{ position: "absolute", left: 640, top: 578, width: 140, textAlign: "left", fontFamily: "PlusJakartaSans_500Medium", fontSize: 9, lineHeight: 12.2, color: "#8AA3B0" }}>{"Stepper · quantity"}</Text>
      <Text style={{ position: "absolute", left: 42, top: 620, width: 400, textAlign: "left", fontFamily: "PlusJakartaSans_800ExtraBold", fontSize: 10, lineHeight: 13.5, letterSpacing: 0.8, color: "#6B8796" }}>{"Helper text"}</Text>
      <Text style={{ position: "absolute", left: 42, top: 644, width: 200, textAlign: "left", fontFamily: "PlusJakartaSans_500Medium", fontSize: 10, lineHeight: 13.5, color: "#6B8796" }}>{"Shown under the field in muted 10/500"}</Text>
      <Text style={{ position: "absolute", left: 42, top: 662, width: 200, textAlign: "left", fontFamily: "PlusJakartaSans_500Medium", fontSize: 9, lineHeight: 12.2, color: "#8AA3B0" }}>{"Helper"}</Text>
      <Text style={{ position: "absolute", left: 252, top: 644, width: 200, textAlign: "left", fontFamily: "PlusJakartaSans_500Medium", fontSize: 10, lineHeight: 13.5, color: "#E5484D" }}>{"Enter a valid mobile number"}</Text>
      <Text style={{ position: "absolute", left: 252, top: 662, width: 200, textAlign: "left", fontFamily: "PlusJakartaSans_500Medium", fontSize: 9, lineHeight: 12.2, color: "#8AA3B0" }}>{"Error"}</Text>
      <Text style={{ position: "absolute", left: 462, top: 644, width: 200, textAlign: "left", fontFamily: "PlusJakartaSans_500Medium", fontSize: 10, lineHeight: 13.5, color: "#0E7A4A" }}>{"Customer saved"}</Text>
      <Text style={{ position: "absolute", left: 462, top: 662, width: 200, textAlign: "left", fontFamily: "PlusJakartaSans_500Medium", fontSize: 9, lineHeight: 12.2, color: "#8AA3B0" }}>{"Success"}</Text>
      <Text style={{ position: "absolute", left: 672, top: 644, width: 200, textAlign: "left", fontFamily: "PlusJakartaSans_500Medium", fontSize: 10, lineHeight: 13.5, color: "#8AA3B0" }}>{"148 / 200"}</Text>
      <Text style={{ position: "absolute", left: 672, top: 662, width: 200, textAlign: "left", fontFamily: "PlusJakartaSans_500Medium", fontSize: 9, lineHeight: 12.2, color: "#8AA3B0" }}>{"Counter"}</Text>
    </View>
  );
}
