/* GENERATED by tools/penpot-to-code/to-react-native.mjs from the Penpot
 * board "Screen 01 Splash". Do not edit: regenerate with
 * `pnpm design:rn`. Its text is the board's sample copy — a design
 * reference, not a screen.
 */
import React from "react";
import { StyleSheet, View, Text, Image } from "react-native";
import Svg, { SvgXml, Defs, Rect, Stop, LinearGradient } from "react-native-svg";

export const size = { width: 376, height: 859 } as const;

const SVG_0 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"18.6\" height=\"5.4\" viewBox=\"2883.9 361.8 18.6 5.4\" fill=\"none\"><path d=\"M2885.28857421875,365.8571472167969C2889.615478515625,362.28570556640625,2896.826904296875,362.28570556640625,2901.15380859375,365.8571472167969\" fill=\"none\" stroke=\"#ffffff\" stroke-width=\"1.7\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_1 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"11.9\" height=\"4.4\" viewBox=\"2887.3 366.9 11.9 4.4\" fill=\"none\"><path d=\"M2888.605712890625,370.0C2891.34619140625,367.7142639160156,2895.09619140625,367.7142639160156,2897.836669921875,370.0\" fill=\"none\" stroke=\"#ffffff\" stroke-width=\"1.7\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";
const SVG_2 = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"152.6\" height=\"19.2\" viewBox=\"2642.7 707.6 152.6 19.2\" fill=\"none\"><path d=\"M2644.89990234375,722.611083984375C2682.60009765625,729.0,2747.60009765625,718.7777709960938,2793.10009765625,709.8333129882812\" fill=\"none\" stroke=\"#2fcb7c\" stroke-width=\"3.4\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>";

export default function PenpotScreen01Splash() {
  return (
    <View style={{ width: 376, height: 859, backgroundColor: "#FFFFFF", borderRadius: 34, overflow: "hidden", boxShadow: "0px 10px 28px 0px rgba(15,50,68,0.14)" }}>{/* "Screen 01 Splash" */}
      <View style={{ position: "absolute", left: 0, top: 0, width: 376, height: 666, borderTopLeftRadius: 34, borderTopRightRadius: 34, overflow: "hidden" }}>{/* "splash-photo" */}
        <Image source={require("@/assets/penpot/splash-bg.jpg")} style={{ position: "absolute", left: 0, top: 0, width: 376, height: 666 }} resizeMode="cover" />
      </View>
      <View style={{ position: "absolute", left: 0, top: 0, width: 376, height: 260, borderTopLeftRadius: 34, borderTopRightRadius: 34, overflow: "hidden" }}>{/* "scrim-top" */}
        <Svg style={StyleSheet.absoluteFill} width="100%" height="100%"><Defs><LinearGradient id="gscreen01splash0" x1="0.5" y1="0" x2="0.5" y2="1"><Stop offset={0} stopColor="#06202C" stopOpacity={0.55} /><Stop offset={1} stopColor="#06202C" stopOpacity={0} /></LinearGradient></Defs><Rect width="100%" height="100%" fill="url(#gscreen01splash0)" /></Svg>
      </View>
      <View style={{ position: "absolute", left: 0, top: 379, width: 376, height: 286, overflow: "hidden" }}>{/* "scrim-bot" */}
        <Svg style={StyleSheet.absoluteFill} width="100%" height="100%"><Defs><LinearGradient id="gscreen01splash1" x1="0.5" y1="0" x2="0.5" y2="1"><Stop offset={0} stopColor="#06202C" stopOpacity={0} /><Stop offset={1} stopColor="#06202C" stopOpacity={0.5} /></LinearGradient></Defs><Rect width="100%" height="100%" fill="url(#gscreen01splash1)" /></Svg>
      </View>
      <Text style={{ position: "absolute", left: 24, top: 18, width: 78, textAlign: "left", fontFamily: "PlusJakartaSans_700Bold", fontSize: 14, lineHeight: 16.8, color: "#FFFFFF" }}>{"9:41"}</Text>
      <View style={{ position: "absolute", left: 277, top: 18, width: 75, height: 20 }} pointerEvents="box-none">{/* "status-icons" */}
        <View style={{ position: "absolute", left: 0, top: 12.9, width: 4.3, height: 7.1, backgroundColor: "#FFFFFF", borderRadius: 1 }} />
        <View style={{ position: "absolute", left: 6.5, top: 9.3, width: 4.3, height: 10.7, backgroundColor: "#FFFFFF", borderRadius: 1 }} />
        <View style={{ position: "absolute", left: 13, top: 5.7, width: 4.3, height: 14.3, backgroundColor: "#FFFFFF", borderRadius: 1 }} />
        <View style={{ position: "absolute", left: 19.5, top: 2.1, width: 4.3, height: 17.9, backgroundColor: "#FFFFFF", borderRadius: 1 }} />
        <SvgXml xml={SVG_0} width={18.6} height={5.4} style={{ position: "absolute", left: 28.9, top: 3.8 }} />
        <SvgXml xml={SVG_1} width={11.9} height={4.4} style={{ position: "absolute", left: 32.3, top: 8.9 }} />
        <View style={{ position: "absolute", left: 36.2, top: 14.6, width: 4, height: 4, backgroundColor: "#FFFFFF", borderRadius: 2 }} />
        <View style={{ position: "absolute", left: 53.4, top: 4.3, width: 18.8, height: 11.4, borderRadius: 2.2, borderWidth: 1.1, borderColor: "#FFFFFF", opacity: 0.9 }} />
        <View style={{ position: "absolute", left: 55.7, top: 6.6, width: 12.7, height: 6.9, backgroundColor: "#FFFFFF", borderRadius: 1.1 }} />
        <View style={{ position: "absolute", left: 72.8, top: 8, width: 2, height: 4, backgroundColor: "#FFFFFF", borderRadius: 0.7 }} />
      </View>
      <Text style={{ position: "absolute", left: 0, top: 62, width: 376, textAlign: "center", fontFamily: "PlusJakartaSans_800ExtraBold", fontSize: 42, lineHeight: 48.3, color: "#2FCB7C" }}>{"G"}</Text>
      <Text style={{ position: "absolute", left: 0, top: 135, width: 376, textAlign: "center", fontFamily: "PlusJakartaSans_800ExtraBold", fontSize: 27, lineHeight: 32.4, color: "#FFFFFF" }}>{"GreatSales"}</Text>
      <Text style={{ position: "absolute", left: 0, top: 170, width: 376, textAlign: "center", fontFamily: "PlusJakartaSans_500Medium", fontSize: 13, lineHeight: 15.6, letterSpacing: 1.3, color: "rgba(255,255,255,0.88)" }}>{"Field Sales CRM"}</Text>
      <Text style={{ position: "absolute", left: 39, top: 197, width: 260, textAlign: "left", fontFamily: "Caveat_400Regular", fontSize: 39, lineHeight: 41, color: "#FFFFFF" }}>{"Every"}</Text>
      <Text style={{ position: "absolute", left: 63, top: 239, width: 260, textAlign: "left", fontFamily: "Caveat_400Regular", fontSize: 39, lineHeight: 41, color: "#FFFFFF" }}>{"visit"}</Text>
      <Text style={{ position: "absolute", left: 47, top: 278, width: 260, textAlign: "left", fontFamily: "Caveat_400Regular", fontSize: 39, lineHeight: 41, color: "#FFFFFF" }}>{"builds"}</Text>
      <Text style={{ position: "absolute", left: 68, top: 317, width: 260, textAlign: "left", fontFamily: "Caveat_400Regular", fontSize: 39, lineHeight: 41, color: "#FFFFFF" }}>{"tomorrow"}</Text>
      <View style={{ position: "absolute", left: 63, top: 366, width: 156, height: 23 }} pointerEvents="box-none">{/* "hw-swoosh" */}
        <SvgXml xml={SVG_2} width={152.6} height={19.2} style={{ position: "absolute", left: 1.7, top: 1.6 }} />
      </View>
      <View style={{ position: "absolute", left: 0, top: 639, width: 376, height: 220, backgroundColor: "#FFFFFF", borderTopLeftRadius: 31, borderTopRightRadius: 31, borderBottomRightRadius: 34, borderBottomLeftRadius: 34 }} />
      <Text style={{ position: "absolute", left: 0, top: 655, width: 376, textAlign: "center", fontFamily: "PlusJakartaSans_800ExtraBold", fontSize: 25, lineHeight: 31.3, color: "#0F3244" }}>{"Sell Smarter."}</Text>
      <Text style={{ position: "absolute", left: 0, top: 686, width: 376, textAlign: "center", fontFamily: "PlusJakartaSans_800ExtraBold", fontSize: 25, lineHeight: 31.3, color: "#0F3244" }}>{"Go Further."}</Text>
      <Text style={{ position: "absolute", left: 0, top: 724, width: 376, textAlign: "center", fontFamily: "PlusJakartaSans_500Medium", fontSize: 15, lineHeight: 19.5, color: "#6B8796" }}>{"Track · Engage · Grow"}</Text>
      <View style={{ position: "absolute", left: 29, top: 761, width: 319, height: 49, borderRadius: 13, overflow: "hidden", boxShadow: "0px 4px 12px 0px rgba(15,50,68,0.22)" }}>{/* "cta" */}
        <Svg style={StyleSheet.absoluteFill} width="100%" height="100%"><Defs><LinearGradient id="gscreen01splash2" x1="0" y1="0.5" x2="1" y2="0.5"><Stop offset={0} stopColor="#0E7A4A" stopOpacity={1} /><Stop offset={1} stopColor="#1BA560" stopOpacity={1} /></LinearGradient></Defs><Rect width="100%" height="100%" fill="url(#gscreen01splash2)" /></Svg>
      </View>
      <Text style={{ position: "absolute", left: 29, top: 776, width: 319, textAlign: "center", fontFamily: "PlusJakartaSans_700Bold", fontSize: 18, lineHeight: 23.4, color: "#FFFFFF" }}>{"Get Started   →"}</Text>
      <Text style={{ position: "absolute", left: 0, top: 834, width: 376, textAlign: "center", fontFamily: "PlusJakartaSans_400Regular", fontSize: 13, lineHeight: 16.9, color: "#8AA3B0" }}>{"Trusted by 10,000+ field sales teams"}</Text>
    </View>
  );
}
