import { Injectable, Logger, OnModuleInit } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import {
  DeleteObjectCommand,
  GetObjectCommand,
  PutObjectCommand,
  S3Client,
} from '@aws-sdk/client-s3';
import { mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import { dirname, join, resolve, sep } from 'node:path';

/**
 * Where uploaded files actually live.
 *
 * Two drivers behind one interface, chosen by STORAGE_DRIVER. "local" writes
 * under a directory and exists so a developer machine needs no bucket and no
 * credentials; "s3" is production, which `env.ts` insists on, because a file on
 * one container's disk is invisible to every other instance and gone at the
 * next deploy — a broken file feature that looks fine on one box.
 *
 * The KEY is opaque to callers and always carries the tenant as its first
 * segment. That is not authorization — the database row is what proves a file
 * belongs to a workspace — but it means a bucket listing is legible, a lifecycle
 * rule can be written per tenant, and a mistake shows up as a wrong prefix
 * rather than as a flat pile of cuids.
 */
export interface StoredObject {
  body: Buffer;
  contentType: string | null;
}

@Injectable()
export class StorageService implements OnModuleInit {
  private readonly logger = new Logger(StorageService.name);
  private s3?: S3Client;

  constructor(private readonly config: ConfigService) {}

  private get driver(): 'local' | 's3' {
    return this.config.get<'local' | 's3'>('STORAGE_DRIVER') ?? 'local';
  }

  private get bucket(): string {
    return this.config.getOrThrow<string>('S3_BUCKET');
  }

  private get localRoot(): string {
    return resolve(
      process.cwd(),
      this.config.get<string>('STORAGE_LOCAL_DIR') ?? '.storage',
    );
  }

  onModuleInit(): void {
    if (this.driver === 's3') {
      this.s3 = new S3Client({
        region: this.config.getOrThrow<string>('S3_REGION'),
        // Only set for a local stand-in (MinIO, LocalStack). Unset in
        // production, where the SDK resolves the real endpoint from the region.
        ...(this.config.get<string>('S3_ENDPOINT')
          ? {
              endpoint: this.config.get<string>('S3_ENDPOINT'),
              forcePathStyle: true,
            }
          : {}),
      });
      this.logger.log(`Attachments in S3 bucket "${this.bucket}"`);
    } else {
      this.logger.warn(
        `Attachments on local disk (${this.localRoot}). Development only — ` +
          'files are not shared between instances and do not survive a deploy.',
      );
    }
  }

  /**
   * Resolve a key to a path under the storage root, refusing to escape it.
   *
   * Keys are generated by this application and never come from a request, so
   * this should be unreachable — which is exactly why it is checked: an
   * unreachable traversal is one refactor away from being reachable, and by
   * then it reads and writes anywhere the process can.
   */
  private pathFor(key: string): string {
    const full = resolve(this.localRoot, key);
    if (full !== this.localRoot && !full.startsWith(this.localRoot + sep)) {
      throw new Error(`Refusing a storage key outside the root: ${key}`);
    }
    return full;
  }

  async put(key: string, body: Buffer, contentType: string): Promise<void> {
    if (this.driver === 's3') {
      await this.s3!.send(
        new PutObjectCommand({
          Bucket: this.bucket,
          Key: key,
          Body: body,
          ContentType: contentType,
          // Attachments are business documents. Even in a private bucket,
          // encryption at rest is the default a reviewer will look for.
          ServerSideEncryption: 'AES256',
        }),
      );
      return;
    }
    const path = this.pathFor(key);
    await mkdir(dirname(path), { recursive: true });
    await writeFile(path, body);
    await writeFile(`${path}.type`, contentType, 'utf8');
  }

  async get(key: string): Promise<StoredObject> {
    if (this.driver === 's3') {
      const res = await this.s3!.send(
        new GetObjectCommand({ Bucket: this.bucket, Key: key }),
      );
      const body = Buffer.from(await res.Body!.transformToByteArray());
      return { body, contentType: res.ContentType ?? null };
    }
    const path = this.pathFor(key);
    const body = await readFile(path);
    const contentType = await readFile(`${path}.type`, 'utf8').catch(
      () => null,
    );
    return { body, contentType };
  }

  /**
   * Remove an object. Missing is success.
   *
   * The database row is deleted in the same operation, and a delete that fails
   * because the file was already gone would leave the row behind — pointing at
   * nothing, and listed to the user as a file they cannot download.
   */
  async remove(key: string): Promise<void> {
    if (this.driver === 's3') {
      await this.s3!.send(
        new DeleteObjectCommand({ Bucket: this.bucket, Key: key }),
      );
      return;
    }
    const path = this.pathFor(key);
    await rm(path, { force: true });
    await rm(`${path}.type`, { force: true });
  }

  /** `<tenant>/<entity>/<entityId>/<id>-<safe file name>`. */
  keyFor(
    tenantId: string,
    entityType: string,
    entityId: string,
    id: string,
    fileName: string,
  ): string {
    const safe = fileName.replace(/[^A-Za-z0-9._-]+/g, '_').slice(-80);
    return join(tenantId, entityType, entityId, `${id}-${safe}`).replace(
      /\\/g,
      '/',
    );
  }
}
